### ISSUE TITLE
rbenv: command not found on linux

### ISSUE THREAD

**Issue by xavierleonardo** [TheOdinProject/theodinproject#1001]
I had an error rbenv command not found following the steps from [this guide](https://www.theodinproject.com/courses/web-development-101/lessons/installing-ruby?ref=lnav). Especifically in this command: `mkdir -p "$(rbenv root)"/plugins`.

So i assumed that it was wrong installed and followed this steps:

> `cd ~`
> `rm -rf .rbenv/`
> `git clone git://github.com/sstephenson/rbenv.git .rbenv`
> `echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bashrc`
> `echo 'eval "$(rbenv init -)"' >> ~/.bashrc`
> `git clone git://github.com/sstephenson/ruby-build.git ~/.rbenv/plugins/ruby-build`
> `source ~/.bashrc`

from [this issue](https://github.com/rbenv/rbenv/issues/976) in [rbenv repo](https://github.com/rbenv).

So I've got `rbenv` from another repo and this fixed my problem. Maybe we'll have to update the course ruby install guide for linux.

I'm using `lubuntu 18.10`.

**Comment by I3uckwheat** [comment]
@xavierleonardo Did you close and re-open your terminal after `echo`ing the commands to your `.bashrc`?

**Comment by xavierleonardo** [comment]
> @xavierleonardo Did you close and re-open your terminal after `echo`ing the commands to your `.bashrc`?

Yes, @I3uckwheat. But I only got it working after follow that steps.

**Comment by I3uckwheat** [comment]
@xavierleonardo Those are basically the steps we use.

**Comment by I3uckwheat** [comment]
Maybe exiting and re-opening the terminal didn't reload the .bashrc somehow. Depending how things are sourced.

We'll keep an eye on this issue, however, it's likely that it was a typo somewhere.

**Comment by xavierleonardo** [comment]
> Maybe exiting and re-opening the terminal didn't reload the .bashrc somehow. Depending how things are sourced.
> 
> We'll keep an eye on this issue, however, it's likely that it was a typo somewhere when following the directions.

I didn't fully understand all the configuration matters about terminal, mas I've also had sourced `.bashrc` before searching for another way to achieve this.

Maybe that's not a typo, but something that had changed from the time you wrote and now. Or maybe something specifically about my OS and terminal config. I just thought it was a good idea let you all know.

**Comment by KevinMulhern** [comment]
Our [discord](https://discordapp.com/channels/505093832157691914/505093832157691916) or [forum](https://forum.theodinproject.com/) is the more appropriate place for this type of support.

Closing due to it not being related to this repo.
