### ISSUE TITLE
Adding a "previous lesson" button

### ISSUE THREAD

**Issue by sampsonmao** [TheOdinProject/theodinproject#1002]
I think it would be really helpful to have a button to go back a lesson, rather than having view course. I find myself opening the assignment page and needing to reference something in the previous lesson but have to go through many pages and scrolling before finding the one I need to reference.

**Comment by MoonKingArthur** [comment]
While I wouldn't really care too much to have a previous lesson button, I will admit that I often peek ahead at the next lesson to see what's to come, only to go back to the lesson I'm working on

**Comment by DoviMaj** [comment]
i feel a previous lesson would be very helpful too
