### ISSUE TITLE
Make clickable dropdowns more enticing to click

### ISSUE THREAD

**Issue by I3uckwheat** [TheOdinProject/theodinproject#1004]
![image](https://user-images.githubusercontent.com/4411701/57104791-e4506100-6cee-11e9-924f-451559bf7cb6.png)

**Comment by rubynho** [comment]
I think one way of doing it is to change those triangles by something like `^` closed and `v` opened. Just an idea.

**Comment by saydus** [comment]
I also think that the font-size should be smaller (to be consistent with the text), color could pale on hover, and possible small indentation.

**Comment by I3uckwheat** [comment]
@rubynho Currently the arrows do point downwards when opened. 

@saydus Changing the font to be smaller may be more confusing as it makes it less obvious they are different. 

I think changing the color slightly on hover is a good idea though. Additionally, some more content earlier on in the gearing up portions could explain what these are and how to use them.

**Comment by ZachBaird** [comment]
It doesn't look like somebody has committed code to this issue as of yet, so I'll add the hover CSS and link a pull request for now.

**Comment by I3uckwheat** [comment]
@ZachBaird Thanks!
