### ISSUE TITLE
Auto-Next on Lesson Completion click

### ISSUE THREAD

**Issue by tarnalcock** [TheOdinProject/theodinproject#1010]
It seems pointless to have to click both "Complete" and then "Next Lesson" each time one completes a lesson. It makes sense to go to the next lesson without completing if one is simply browsing the lessons, but when completing a lesson - I  feel it would be logical, and more "responsive", to move on to the next lesson automatically.

**Comment by KevinMulhern** [comment]
We can test definitley test this out, I think we'll have to add a previous button as well, just incase the user didn't want to be taken to the next lesson just yet.

**Comment by rubynho** [comment]
I don't think the previous button is really necessary, the buttons says `Next Lesson`, I think it's auto descriptive that the user will be moved to where it's saying. Just like [CodeCademy](https://www.codecademy.com/) does at the end of the lessons:

![image](https://user-images.githubusercontent.com/24780712/66048860-ad31e600-e500-11e9-94d5-83092cfed59c.png)

**Comment by I3uckwheat** [comment]
In the codecademy screenshot, there is a "back" button. People would get frustrated if they clicked and were taken to the next lesson and had to figure out what lesson they were just on.

**Comment by I3uckwheat** [comment]
I agree a "go-back" button could be useful, but auto moving to the next lesson could be confusing to some people.

**Comment by DoviMaj** [comment]
What about 4 buttons? complete, complete-next, back and next buttons? Or a user setting that can chose auto next on complete?

**Comment by I3uckwheat** [comment]
@DoviMaj A setting seems like a very low reward for the amount of work that would need to be put in for it.

Redundancy isn't the name of the game either. Seems silly to have buttons that do the same things.
