### ISSUE TITLE
View Curriculum points to wrong page

### ISSUE THREAD

**Issue by I3uckwheat** [TheOdinProject/theodinproject#1015]
Currently points to https://www.theodinproject.com/courses , where it should point to https://www.theodinproject.com/tracks

When adding the tracks feature, the courses page shows ALL the courses without a definite path the student should take, this can be confusing to people unsure

**Comment by wadie** [comment]
Why ?

**Comment by KevinMulhern** [comment]
@wadie we recently changed to a tracks model for the curriculum.

**Comment by mindovermiles262** [comment]
I think this has been taken care of. closing
