### ISSUE TITLE
Add Badge for New Node Course

### ISSUE THREAD

**Issue by KevinMulhern** [TheOdinProject/theodinproject#1016]
We recently added a new Node course to the curriculum. However it does not have a badge yet. 

@adachiu has generously created a node badge we can use. It can be found [here](https://www.dropbox.com/sh/3y7iwe8zrq4o568/AABpRQFpVlwH1PqCbqt8hviVa?dl=0)

**Comment by jakedallinson** [comment]
@KevinMulhern I can take this

**Comment by CouchofTomato** [comment]
@jakedallinson Go ahead mate.

**Comment by jakedallinson** [comment]
Unable to complete this issue. Can someone else take over?

**Comment by mindovermiles262** [comment]
Closing with https://github.com/TheOdinProject/theodinproject/pull/1039
