### ISSUE TITLE
Issue with the badge of the new Node Course

### ISSUE THREAD

**Issue by mvedataydin** [TheOdinProject/theodinproject#1029]
If you login to TOP, you can see that there is still a placeholder instead of new badge of Node Course. After logging out from website, badge of  Node Course is coming back.

![Screen Shot 2019-10-07 at 09 33 34](https://user-images.githubusercontent.com/44524609/66289502-8f3ff900-e8e5-11e9-99ca-637d7f03241f.png)

**Comment by tfantina** [comment]
I'm opening a PR for this.

**Comment by mindovermiles262** [comment]
It should show the NodeJS Badge, and then % complete when the mouse hovers
