### ISSUE TITLE
Courses displayed twice in User dashboard

### ISSUE THREAD

**Issue by leosoaivan** [TheOdinProject/theodinproject#1034]
See https://github.com/TheOdinProject/curriculum/issues/12636.

Are there duplicates in the DB? The user dashboard views all look ok to me on the Rails side of things.

**Comment by arku** [comment]
@leosoaivan Ah, I ran `rails db:seed` earlier which seems to have caused this issue. I was under the assumption that the seed would always `create_or_update` resources.

Let me fix it.

**Comment by leosoaivan** [comment]
👍 get those Hacktoberfest PRs in!

**Comment by arku** [comment]
@leosoaivan hahaha.

The issue should be fixed now. Can you please confirm and close the issue?

Thanks!

**Comment by arku** [comment]
@leosoaivan I created https://github.com/TheOdinProject/theodinproject/issues/1035 to fix the seeding script. Feel free to add more information to the issue.

**Comment by leosoaivan** [comment]
Confirmed, and closed!
