### ISSUE TITLE
Duplicate `TrackCourse`s are created when seeding the database

### ISSUE THREAD

**Issue by arku** [TheOdinProject/theodinproject#1035]
When we run `rails db:seed` mutiple times, it looks like duplicate `TrackCourse`s are getting created.

Please see #1034 for more context.

**Comment by CouchofTomato** [comment]
Thanks to @catalindrg this issue seems to be resolved.

**Comment by mindovermiles262** [comment]
Do we need to go in and manually delete duplicates?

**Comment by CouchofTomato** [comment]
@mindovermiles262

Yes. If you can handle it then great otherwise I’ll look when I’m home. It’s the courses linked to tracks 2 and 3 as far as I can tell

**Comment by arku** [comment]
@mindovermiles262 The duplicates should be gone now.
