### ISSUE TITLE
Different versions of Ruby in instructions and in the code provided

### ISSUE THREAD

**Issue by BosEriko** [TheOdinProject/theodinproject#1044]
On the page [Installing Ruby](https://www.theodinproject.com/lessons/installing-ruby), Step 3.3: Install Ruby of the MacOS instructions says it recommends 2.6.4 but all the code provided is for 2.6.5. Is this intentional?

**Comment by dvik1950** [comment]
The instructions will usually install the latest stable version, sometimes the results in the curriculum aren't updated to the latest version. You can make a PR to change the version to the latest in the curriculum :)

**Comment by BosEriko** [comment]
It seems like it has been updated. 😃 
https://github.com/TheOdinProject/curriculum/commit/c1f6def2dc96684f4a9fea557bf011cfae7b935a

**Comment by dvik1950** [comment]
I guess you can close the issue then :)
