### ISSUE TITLE
Username length validation fails without JavaScript

### ISSUE THREAD

**Issue by hasithsen** [TheOdinProject/theodinproject#1056]
Minimum username length is not validated if JavaScript is disabled in browser when signing up with email.

**Comment by scottrobel** [comment]
This is because the validations on the client-side don't match the validations on the server-side.

**Comment by scottrobel** [comment]
@KevinMulhern I think my PR Fixed this issue

**Comment by KevinMulhern** [comment]
Thanks again @hasithsen
