### ISSUE TITLE
Content not getting displayed in Chrome browser

### ISSUE THREAD

**Issue by vimalkurup** [TheOdinProject/theodinproject#107]
The content of the page is not properly getting displayed in Chrome Browser regardless of logged in or not. The content gets displayed for a fraction of second and hides. The version of the browser is '38.0.2125.122'. AdBlocker is disabled. When inspected with dev tools, I can seen that a 'display: none' is added to the div with class 'row' inside the div with class 'container'. <div class="row" style="display: none;">
With dev tools doing a refresh shows that the 'style="display: none;"' is added dynamically after the page is loaded.
![odin](https://cloud.githubusercontent.com/assets/1284919/5055292/3aec606a-6c2f-11e4-8fee-a84918d9fc53.png)

**Comment by KevinMulhern** [comment]
This seems like it was a bit of a one off issue due to no one else reporting it, due to this I think this issue should be closed.

**Comment by Amit-Naudiyal** [comment]
I am also getting this issue and as reported earlier by @vimalkurup, it works in incognito window.

**Comment by bobrecio** [comment]
The same thing just happened to me in Chrome.
Thanks to @Amit-Naudiyal I was able to resolve it.
Recently, I installed the chrome extension called "Markdown Viewer". It was set to work on all pages. I changed the setting so that it only works when I click the extension and GitHub renders fine, now.

**Comment by rizblie** [comment]
I had the same problem with e.g. https://github.com/Dash-Industry-Forum/dash.js/blob/development/README.md

I also had the Markdown viewer installed, and changing the setting as described by @bobrecio fixed it. Thanks!

**Comment by Di-Maas** [comment]
@Amit-Naudiyal  - Many thanks! Long lasting issue is resolved)
