### ISSUE TITLE
As a student, I would like to have a link to the github page the lesson is reading from

### ISSUE THREAD

**Issue by I3uckwheat** [TheOdinProject/theodinproject#1095]
This will make it a lot easier for people to find the lesson and make PRs to. It can be a bit difficult for students to find the github repo in the first place, let alone find the lesson as the title of the page can be different from the name of the file. Automatically generating links to the specific page could be super helpful.

**Comment by KevinMulhern** [comment]
Nice suggestion @I3uckwheat. We used to have something like this before, and it was very useful.

A link with the github icon right below the content on the page seems like the best place to put it. Do you have any thoughts on where we should put it on the page?

**Comment by I3uckwheat** [comment]
@KevinMulhern One place it could live is here: 

![image](https://user-images.githubusercontent.com/4411701/79674178-64d4cf80-8195-11ea-810f-f1758e95752a.png)


People that find a typo or something may scroll to the bottom looking for contact information to let us know and happen across it. 

Otherwise somewhere in the header could be nice.

**Comment by KevinMulhern** [comment]
I like that location 👍 thanks @I3uckwheat

**Comment by KevinMulhern** [comment]
For whoever picks this up, we have the url for the lesson on github stored for each lesson in the db so it should just be a matter of adding a rails link_to with that attribute of the lesson as the url.
