### ISSUE TITLE
Make tiles on main page hyperlinks.

### ISSUE THREAD

**Issue by AndruMace** [TheOdinProject/theodinproject#1100]
As seen in the image, there are tiles on the main page that have section/subject titles on them. It would be really convenient and user friendly to make them hyperlinks to their corresponding sections. They already give the appearance of being such and I clicked on them multiple times before realizing that they aren't indeed interactive. 

<img width="325" alt="hyperlinksugg" src="https://user-images.githubusercontent.com/44399849/79639646-51256b00-818d-11ea-84a5-8db20c96b923.PNG">

**Comment by Kshubhranshu** [comment]
i will do it.

**Comment by codyloyd** [comment]
alright @Kshubhranshu have fun!

**Comment by bcoffin9** [comment]
Going through the git workflow lesson on the Ruby course, so I'll also give it a shot!
