### ISSUE TITLE
Project submissions updates

### ISSUE THREAD

**Issue by arku** [TheOdinProject/theodinproject#1118]
TODOs:

- [ ] The feature uses Gitter as the communication medium for reporting issues with submissions.  Now that we are using Discord, we should replace the Gitter client with [Discord](https://github.com/discordrb/discordrb)
- [ ] Refactor

**Comment by KevinMulhern** [comment]
Hey @arku, check your DM's on discord please. We need to talk about this one 😃

**Comment by KevinMulhern** [comment]
Hey @arku, I'm going to close this since we are going a different direction with this as discussed today.
