### ISSUE TITLE
Fix Discord chat floating icon tracker

### ISSUE THREAD

**Issue by arku** [TheOdinProject/theodinproject#1124]
**Note**: This issue is reserved for first-time contributors. Comment on the issue if you're interested in working on this.

### Description

https://github.com/TheOdinProject/theodinproject/blob/a04787982124a218847b6e97a820b21124f33560/app/javascript/src/js/analytics.js#L53-L55

The code above is supposed to track clicks on the floating chat button at the bottom right (See image).

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/7039523/80245975-48231680-8631-11ea-9670-e8029e27473a.png">

The issue is that the chat link does not have the `chat-floating-btn` class.

<img width="1328" alt="image" src="https://user-images.githubusercontent.com/7039523/80246171-99330a80-8631-11ea-905e-bcc892569bb6.png">

### How to fix it?

 Add the `chat-floating-btn` class to the link. That's it!

The template that needs an update:

https://github.com/TheOdinProject/theodinproject/blob/a04787982124a218847b6e97a820b21124f33560/app/views/shared/_sidecar.html.erb#L3

If you haven't worked with ERB templates, no worries! Here's a snippet of a link with a class attribute.

https://github.com/TheOdinProject/theodinproject/blob/a04787982124a218847b6e97a820b21124f33560/app/views/shared/_footer.html.erb#L15

### Getting Started

Please refer to the [contributing guide](https://github.com/TheOdinProject/theodinproject/wiki/Contributing-Guide) to set up the app locally. Once you get it running locally, follow these steps:

1. Update [the code](https://github.com/TheOdinProject/theodinproject/blob/a04787982124a218847b6e97a820b21124f33560/app/views/shared/_sidecar.html.erb#L3) to include the class
2. Commit and push your changes to your fork
3. Open a PR :tada:

If you get stuck and need any help, come chat with us on [Discord](https://discordapp.com/channels/505093832157691914/540903304046182425)!

**Comment by logancderrick** [comment]
I'll take it.

**Comment by devmohy** [comment]
I cab work on this

**Comment by arku** [comment]
@logancderrick Awesome, thanks! Just assigned it to you.

**Comment by arku** [comment]
@devmohy Sorry, this has already been picked up. But no worries!

How about working on another issue to track link clicks on the floating Forum icon? Let me know if you're interested.

**Comment by eduardoramosdev** [comment]
Firat time contributor here. Interested! Please forgive if I commit mistakes in advance

**Comment by devmohy** [comment]
Oh, that makes sense let me try it out

**Comment by logancderrick** [comment]
> @devmohy Sorry, this has already been picked up. But no worries!
> 
> How about working on another issue to track link clicks on the floating Forum icon? Let me know if you're interested.

Give it to someone else I am having a hell of a time getting ruby to work right on my VM. I'll try to catch another one when I get all this sorted out.

**Comment by arku** [comment]
No problem @logancderrick. Thanks for the update.

**Comment by I3uckwheat** [comment]
@devmohy Are you still interested in this issue?

**Comment by violetguos** [comment]
Hi, if it's not too late, I can have a look.

**Comment by devmohy** [comment]
Yes am interested

**Comment by I3uckwheat** [comment]
@devmohy Alright, I will assign this to you! Please keep us updated with your progress.

**Comment by Ochuba** [comment]
i can do this

**Comment by I3uckwheat** [comment]
@Ochuba, @devmohy has already been assigned this. If he hasn't made progress, or checked in by tomorrow i'll assign this to you.

@devmohy Have you made any progress on this?

**Comment by devmohy** [comment]
I will submit today
