### ISSUE TITLE
FAQ Dropdowns not dropping down on click

### ISSUE THREAD

**Issue by ZachBaird** [TheOdinProject/theodinproject#1154]
URL: [FAQ]( https://www.theodinproject.com/faq?ref=homehav)

Clicking on the FAQs doesn't open them on Google Chrome and Chromium Edge. Unsure if this issue extends to Firefox or Safari but I assume it probably does.

**Comment by mKawi** [comment]
Can confirm, getting the error on Firefox too. It's a TypeError that's being logged in the console when an accordion is clicked.

Uncaught TypeError: Cannot convert object to primitive value
at RegExp.test ()
at HTMLDivElement. (bootstrap.js:1498)
at Function.each (core.js:209)
at e.fn.init.each (core.js:49)
at e.fn.init.e._jQueryInterface [as collapse] (bootstrap.js:1492)
at HTMLDivElement. (bootstrap.js:1552)
at Function.each (core.js:209)
at e.fn.init.each (core.js:49)
at HTMLAnchorElement. (bootstrap.js:1547)
at HTMLDocument.dispatch (event.js:328)

It seems to be an issue with bootstrap and jQuery versioning: [https://github.com/twbs/bootstrap/issues/30553](https://github.com/twbs/bootstrap/issues/30553)

**Comment by ZachBaird** [comment]
@mKawi Thanks for sharing the console error, I forgot to do so.

From researching it, it looks like it might be due to the jQuery version that's used on the site : https://stackoverflow.com/questions/61177140/uncaught-typeerror-cannot-convert-object-to-primitive-valuezone-evergreen-js1
I'm trying to confirm what version TOP uses.

**Comment by ZachBaird** [comment]
@KevinMulhern I have a local branch with the fix in package.json I can PR if you want to assign this to me.
