### ISSUE TITLE
Duplicate material in JavaScript Track.

### ISSUE THREAD

**Issue by Rey810** [TheOdinProject/theodinproject#1175]
In the JavaScript track, there is a [JavaScript and Rails](https://www.theodinproject.com/courses/javascript#javascript-and-rails) module as well as a [JavaScript and the Backend](https://www.theodinproject.com/courses/javascript#javascript-and-the-backend) module which appears to house exactly the same content. Looks like you guys may have just forgotten to remove "JavaScript and Rails" when you added "JavaScript and the Backend". Buuuut I'm not sure.

**Comment by KevinMulhern** [comment]
Thanks for reporting @Rey810, this has been resolved.
