### ISSUE TITLE
Faq Item "What Technologies does the Odin Project Teach?" Need Updated

### ISSUE THREAD

**Issue by KevinMulhern** [TheOdinProject/theodinproject#1192]
### Description
[Link To Faq Page](https://www.theodinproject.com/faq)

The information in this item is a bit outdated since we now offer three different tracks through the curriculum with Frontend, Full Stack with Rails and Full Stack with Node. 

We also have updated the Javascript course and no longer teach Jquery or Backbone so we should remove any mentions of those in this item as well.

### Acceptance Criteria
1. Explain the different routes the users can take through the curriculum with tracks in this faq item.
2. Remove any mention of Jquery and Backbone in this faq item.

**Comment by bycdiaz** [comment]
@KevinMulhern I'm thinking it might make sense to even change the phrasing of the question as well.

I think it is important for learners to understand that this is a self-paced and, more importantly, self-directed learning experience. I've seen instances where learners felt dissatisfied with the way content was "taught," with some learners expecting a sort of teacher/student dynamic. And even when the teacher/student dynamic wasn't explicitly expected, I've often seen learners express frustration when the content is delivered in a way that works for them. While it isn't extremely common, I think removing the idea that we are teaching here will help new learners frame their expectations about us (curriculum maintainers/chat moderators) and their role as self-directed learners. Typically, learners that expect to be taught will be frustrated when the first resource doesn't deliver. When the expectation of self-directed learning is established early on, a learner will be more willing to seek out a different resource when the one provided doesn't "click" for them. 

Perhaps we can change the question to:

"Which technologies can I learn with The Odin Project?"

I also noticed that there are a few references to teaching in the answer. Perhaps whoever takes this on can make adjustments there as well?

**Comment by KevinMulhern** [comment]
Great point @bycdiaz, I definitely agree with all that.

**Comment by tldalton1622** [comment]
What's the timeline for something like this?

**Comment by KevinMulhern** [comment]
Theres no rush with it @tldalton1622 😃

**Comment by peterchou3788** [comment]
Mind if I take on this issue?

**Comment by CouchofTomato** [comment]
@peterchou3788 It doesn't look like anyone else has so feel free.

**Comment by CouchofTomato** [comment]
@tldalton1622 Or are you working on this?

**Comment by peterchou3788** [comment]
I will prepare the tools needed for the Odin Project in the meantime so I can practice forking.

**Comment by peterchou3788** [comment]
I have submitted a pull request just now on a updated faq.
