### ISSUE TITLE
Webpacker can't find application.css

### ISSUE THREAD

**Issue by coolbrg** [TheOdinProject/theodinproject#1200]
First of all nice project 👍 Kudos to creator and maintainers 😄 

I was going through the [`Running the TOP locally`](https://github.com/TheOdinProject/theodinproject/wiki/Running-The-Odin-Project-Locally) and able to complete all steps by God's grace in the first attempt. Some glitches in setting up Postgresql but it was my system issue.

However, when starting my own server `rails s` and hitting `https://localhost:3000`, I hit by the following errors:

```
...
  Rendered shared/_head.html.erb (Duration: 2053.1ms | Allocations: 77312)
Completed 500 Internal Server Error in 3923ms (ActiveRecord: 26.8ms | Allocations: 717387)

ActionView::Template::Error - Webpacker can't find application.css in /Users/coolbrg/me/osproj/theodinproject/public/packs/manifest.json. Possible causes:
1. You want to set webpacker.yml value of compile to true for your environment
   unless you are using the `webpack -w` or the webpack-dev-server.
2. webpack has not yet re-run to reflect updates.
3. You have misconfigured Webpacker's config/webpacker.yml file.
4. Your webpack configuration is not creating a manifest.
Your manifest contains:
{
}
:
  app/views/shared/_head.html.erb:38:in `view template'
  app/views/layouts/application.html.erb:3

...
``` 

And, found that `yarn install` step is missing from this doc. Probably, missed updating this doc after [`Rails 6.0.3` update](https://github.com/TheOdinProject/theodinproject/commit/b19b11fbed0e025d0043786657699e45c767ad1d)

Thanks

**Comment by coolbrg** [comment]
Although, I have updated the [Wiki](https://github.com/TheOdinProject/theodinproject/wiki/Running-The-Odin-Project-Locally#install-javascript-modules-npn-packages-required-by-webpacker) this issue is for reporting purpose.

Feel free to close it.

**Comment by KevinMulhern** [comment]
Thanks for reporting @coolbrg, and thanks for making that change on the wiki 💪 

Hopefully that resolves that issue.

**Comment by coolbrg** [comment]
> Hopefully that resolves that issue.

Yes :)
