### ISSUE TITLE
There should be a way to resume from last lesson.

### ISSUE THREAD

**Issue by jonmast** [TheOdinProject/theodinproject#121]
When I visit the homepage I have to navigate to the courses page then click the course I'm currently doing and then click on the lesson. It would be convenient to have some sort of resume progress link on the homepage so I could just go directly there. Could potentially store the last visited lesson in a cookie or maybe use the successor to the last completed lesson.

**Comment by KevinMulhern** [comment]
Late reply to your suggestion @jonmast, but I really like this idea. I will add it to our Trello board.
