### ISSUE TITLE
Doubling of title on Frameworks page

### ISSUE THREAD

**Issue by AJMcDee** [TheOdinProject/theodinproject#1230]
https://www.theodinproject.com/courses/javascript/lessons/introduction-to-frameworks-javascript

"What is a framework" title has been entered twice.

**Comment by adam-goodrich** [comment]
I can fix this one

**Comment by CouchofTomato** [comment]
All yours @adam-goodrich

**Comment by adam-goodrich** [comment]
Sorry I could not figure it out, I thought it was easier than it is I guess

**Comment by Ramanjs** [comment]
Hi! I want to work on this issue @CouchofTomato
