### ISSUE TITLE
Git Basics Issues

### ISSUE THREAD

**Issue by themagicbean** [TheOdinProject/theodinproject#1241]
I was using the basic Git course to review and noticed two minor things:

1.  [Setting Up Git](https://www.theodinproject.com/courses/web-development-101/lessons/setting-up-git):  There is a somewhat common issue where people cannot use SSH due to inability to use Port 22.  [Github tutorial](https://docs.github.com/en/github/using-git/which-remote-url-should-i-use#cloning-with-https-urls-recommended); [forum topics](https://forum.theodinproject.com/search?q=port%2022).  It might be better to give students the link to this page, and the option of (1) using HTTPS or (2) give the [link to step by step instruction to use SSH over HTTPS](https://docs.github.com/en/github/authenticating-to-github/using-ssh-over-the-https-port).

2.  [Project: Practicing Git Basics](https://www.theodinproject.com/courses/web-development-101/lessons/practicing-git-basics):  Git's init repo page somewhat encourages you to init the repo with a README, although admittedly the box is not checked by default.  Some foolish people (self included) might just click the box to be sure they can immediately clone the repo, and then find there is already a README, kind of sidelining the first subproject of creating it.  It might be good to add a note "don't check the create a README box, we will do that soon enough" or something like that.

**Comment by I3uckwheat** [comment]
1. I have not seen anybody complain about port 22, I however have seen people that have had issues connecting to github at all, http or not. Usually on public internet connections, outside the US. We will continue to monitor that. We don't want to add more to the directions in this case as people will get confused. It often happens that people will use the http link and then complain about having to use their password. 

Then we have to send them back to the directions to get them setup. If someone has issues with port 22, it will be obvious very quickly when they come for help. I think the people that will have issues with port 22 are going to be FAR less than those that will get confused and be upset they have to type in their password every time. 

2. Reading and following directions is an extremely valuable skill, and one that is learned by making mistakes. This is a pretty easy one to make and solve on your own. I don't think this has been an issue reported often in the chat either. It almost always comes down to people not following directions.

**Comment by I3uckwheat** [comment]
Please keep one topic per issue as well.

**Comment by KevinMulhern** [comment]
Hey @themagicbean, thanks for opening this. Can you open this issue on the [curriculum repo](https://github.com/TheOdinProject/curriculum) instead please? that repo is better suited to issues about content on the site.
