### ISSUE TITLE
Node.js not showing up in my dashboard though enrolled

### ISSUE THREAD

**Issue by themagicbean** [TheOdinProject/theodinproject#1247]
I'm primarily at TOP to do back-end because FCC was having problems there.  So I am enrolled in the nodejs.course.  I also enrolled in the Ruby on Rails fullstack track because I wanted to review Git and learn Ruby/Rails.  

My dashboard never shows the Node course, only the Ruby-related courses I am in, despite having completed some of the Node material.  I have to search Google or TOP to find the Node course.  Very frustrating.  Would be better if the dashboard kept track of (a) all courses or (b) all courses I am in.

**Comment by CouchofTomato** [comment]
Thanks @themagicbean 

We only set up for users to take one track as that is what usually happens. I'll feed this back though

**Comment by CouchofTomato** [comment]
On review, we don't feel multiple tracks is beneficial to beginners learning to code and can confuse, especially as both tracks share many of the lessons between them so this isn't a change we can support.

You can go to https://www.theodinproject.com/tracks at any time to see the lessons of other tracks. I would recommend you to take one track in full before looking at any other.

Thanks for the feedback.
