### ISSUE TITLE
Postgresql Installation RoR

### ISSUE THREAD

**Issue by TildaDares** [TheOdinProject/theodinproject#1252]
The Deployment lesson in the RoR course mentions setting up Postgresql for Heroku but there is no guide on how to install it. I recommend using Postgresql as the default database right from the Installing Rails lesson and providing a guide alongside.

**Comment by marvingay** [comment]
This issue should be posted in our [curriculum repository](https://github.com/TheOdinProject/curriculum) . Please provide as much detail as possible, including but not limited to the lesson(s) where the problem exists, the lesson(s) that reference Postgres. Thank you!
