### ISSUE TITLE
Move Ruby Course's "Methods" lesson to its appropriate sequential place.

### ISSUE THREAD

**Issue by marvingay** [TheOdinProject/theodinproject#1259]
In reference to https://github.com/TheOdinProject/curriculum/issues/19544

The "Methods" lesson of the Ruby course is currently in the incorrect place. It belongs before the "Basic Enumerable Methods" lesson.

The person who takes ownership of this issue will need to:
- [ ] Edit the [Ruby course's seeds file](https://github.com/TheOdinProject/theodinproject/blob/master/db/seeds/02_ruby_course_seeds.rb) to place the "Methods" lesson in the appropriate spot.

**Comment by Mohammed-Sibahi** [comment]
Hi. I'll take care of it.

**Comment by marvingay** [comment]
@Mohammed-Sibahi  Thanks! If you have questions do not hesitate to ask.
