### ISSUE TITLE
Submission Issues in PROJECT: BUILDING YOUR PERSONAL WEBSITE

### ISSUE THREAD

**Issue by jessicaawhy** [TheOdinProject/theodinproject#1267]
Everything from Hammad Ahmed to Krzysztof Sordyl is duplicated twice.
Link [https://www.theodinproject.com/courses/getting-hired/lessons/building-your-personal-website](url)
<img width="617" alt="Screen Shot 2020-08-11 at 12 24 37 AM" src="https://user-images.githubusercontent.com/66457042/89869405-29597900-db69-11ea-8de0-1be7d55f97d9.png">

**Comment by merrcury** [comment]
Created Pull Request Against it @ https://github.com/TheOdinProject/curriculum/pull/20164

**Comment by marvingay** [comment]
@jessicaawhy Hello. Thank you for pointing that out. In the future, issues concerning the content of the lessons should be in our https://github.com/TheOdinProject/curriculum repository.
