### ISSUE TITLE
Twitter button doesn't include the link or hashtag

### ISSUE THREAD

**Issue by eriktrautman** [TheOdinProject/theodinproject#128]
Clicking the "Tweet" button at the bottom of lessons currently auto-populates the tweet with a really lame description and doesn't include the link to the lesson!.  Ideally, pull together a more interesting blurb (including @theodinproject and/or a useful hashtag like #learntocode ) and definitely include the link to the lesson.  Just be sure to leave room (e.g. 20 chars) at the end so people can retweet.

**Comment by KevinMulhern** [comment]
This has been done :smile:
