### ISSUE TITLE
Discus Widget not displaying comments when navigating via the bubble bar

### ISSUE THREAD

**Issue by Cgipson06** [TheOdinProject/theodinproject#131]
I noticed that the Discus comments associated with the lessons are not displayed when navigating by the bubble nav bar, (  .lc-progress-wrapper  ).  If I look back at the previous lesson by clicking the bubble nav bar, , and return to the original page by clicking the nav bar again, all comments will be gone.  I found the comment will load again by navigating from the main nav page, or altering the url to remove the referer link.
http://www.theodinproject.com/ruby-programming/ruby-on-the-web?ref=lc-pb
to
http://www.theodinproject.com/ruby-programming/ruby-on-the-web?

Thanks so much for the site!

**Comment by KevinMulhern** [comment]
disqus has now been removed, thanks for opening this.
