### ISSUE TITLE
How seeds.rb is generated from curriculum repo?

### ISSUE THREAD

**Issue by avinassh** [TheOdinProject/theodinproject#135]
I am just trying to understand how this whole thing works. if I understand correctly, the main data exists in curriculum repo and using that `seeds.rb` is generated. And this will be used to load the initial data.

but...how this `seeds.rb` is generated and gets updated as curriculum gets updated?

**Comment by chaudhary27** [comment]
this may be helpful --> http://www.colinrubbert.com/blog/2015/9/4/seeding-the-lightning
