### ISSUE TITLE
Lesson completion button removes clickable link from progress badge

### ISSUE THREAD

**Issue by clormor** [TheOdinProject/theodinproject#1364]
Tested on Safari (14.0 (15610.1.28.1.9, 15610)) and Chrome (85.0.4183.121) on the [Advanced Concepts](https://www.theodinproject.com/courses/javascript/lessons/advanced-concepts) lesson page amongst others. I think this is a cross-browser issue affecting most/all lesson pages.

When a lesson page first loads, the course progress badge at the top is clickable, and navigates you back to the course's curriculum.

However after pressing the button to mark a lesson complete/incomplete, the badge at the top is no longer clickable.

The following gif shows the bug in action:

![progress-badge-error](https://user-images.githubusercontent.com/3955231/94436422-52bf7a00-0194-11eb-9f36-1bb35c2fbf46.gif)

**Comment by clormor** [comment]
It looks like when the page loads, the badge is contained inside an anchor element with class `course-card-header__link`. After the button is pressed, the badge is retained but the parent anchor link no longer exists.

**Comment by clormor** [comment]
Possibly cause by / related to https://github.com/TheOdinProject/theodinproject/pull/1286?

**Comment by clormor** [comment]
After some debugging, it appears the issue is something to do with the scoping/availability of `course` inside [_banner.html.erb](https://github.com/TheOdinProject/theodinproject/blob/master/app/views/courses/course/_banner.html.erb). When the page is first loaded, the `banner_badge` div holds a reference to the course. However after pressing the lesson completion button, the same div has no reference to course.

For example, adding `<h1><%= course.title %></h1>` anywhere inside this div (e.g. between lines 2-6) renders the course title on page load, but the heading goes missing after pressing the lesson completion button.

Interestingly, if you add the same line outside of the `banner__badge` div then the course title is rendered as expected.

This code snippet hopefully illustrates what I mean:

~~~ruby
<div class="banner">

  <h1><%= 
    # This will always render the course title, even after pressing the lesson completion button
    course.title %>
  </h1>

  <div class='banner__badge'>
    <h1><%= 
      # This will render the course title on page load, but not after pressing the lesson completion button
      course.title %>
    </h1>
    ...
  </div>
  
  ...
</div>
~~~

I don't know enough about Ruby/Rails to figure out the best way to fix this.

**Comment by KevinMulhern** [comment]
Thanks for the detailed report @clormor 😄 

I've just opened [this PR](https://github.com/TheOdinProject/theodinproject/pull/1367/files) to fix it.

**Comment by clormor** [comment]
Great! I was hoping I could fumble around and fix this myself (managed to get TOP running locally) but since I know nothing about Ruby/Rails I realised it probably needed someone else to fix this.

**Comment by KevinMulhern** [comment]
Sorry @clormor, I should have asked if you wanted to take this on first. Thanks again for reporting.
