### ISSUE TITLE
(minor issue) Firefox's 'reader view' misses entire sections on bootcamp site https://www.theodinproject.com/

### ISSUE THREAD

**Issue by redLocomotive** [TheOdinProject/theodinproject#1392]
I initially posted this a as bug on firefox, and got this response: "I thought I'd add additional information. It seems to me, that it's not shown in reader mode, because a JavaScript event handler (i.e. Bootstrap's Scrollspy) is attached to the div of the Introduction section. If I remove the class from the element, it works as it should."

Eg. https://www.theodinproject.com/courses/web-development-101/lessons/how-this-course-will-work
With reader view, entire introduction is missing. 

https://support.mozilla.org/en-US/questions/1293452

I don't know if that's an issue worth fixing, or if it's an issue at all.

**Comment by KevinMulhern** [comment]
We use Scrollspy for the navigation menu at the side of the lesson content, it needs that class to be able to scroll the user to the appropriate heading when they click one of the navigation items.

I'll leave this open for now incase anyone know's of a work around. But from previous experience with reader view's there might not be much we can do about this unfortunately.
