### ISSUE TITLE
Link is Down

### ISSUE THREAD

**Issue by mattshaffer11** [TheOdinProject/theodinproject#140]
The first extra credit link is down on this [page](http://www.theodinproject.com/web-development-101/ruby-on-rails).

Thanks!

**Comment by jhgilbert** [comment]
I'm not set up to contribute, but here's the correct link for anyone who's ready to go: https://www.railstutorial.org/book/toy_app

**Comment by KevinMulhern** [comment]
This has been fixed, thanks guys

**Comment by mattshaffer11** [comment]
:+1: thanks man.
