### ISSUE TITLE
Fix: Responsive Issues with Submissions Modals

### ISSUE THREAD

**Issue by KevinMulhern** [TheOdinProject/theodinproject#1408]
### Problem
The Edit submissions modal is too small for medium screen widths, causing the make submission public label to overflow.

### Steps to recreate
1. Visit the google home page project and upload a submission.
2. Open the edit modal and reduce the screen width to around 1300px.
3. 💥  the make submission public label is overflowing the modal container.

### Acceptance Criteria
1. Visit the google home page project and upload a submission.
2. Open the edit modal and reduce the screen width to around 1300px.
3. The make submission public label should not overflow the container.

### Additional Information
The modal could just be made bigger at medium screen sizes to solve the problem for now. We need to have a good look into our responsive system in the near future.

**Comment by AJMcDee** [comment]
I'd be happy to look at this one as well if needed :)

**Comment by ZachBaird** [comment]
@AJMcDee Sure thing! Just let us know if you'll take it and we'll assign it to you 😃

**Comment by AJMcDee** [comment]
@ZachBaird Yes please!

**Comment by DoviMaj** [comment]
i can take this

**Comment by KevinMulhern** [comment]
Thanks @DoviMaj 💪
