### ISSUE TITLE
Fix: Content overflowing out of the body when on tablet mode

### ISSUE THREAD

**Issue by smcommits** [TheOdinProject/theodinproject#1411]
**Problem**

When on tablet mode or visiting the website from a tablet, the content (navbar) is overflowing out of the flow. It is disturbing the proper alignment of the page. It happens only on the chrome browser.

[Screenshot](https://imgur.com/a/VHsYYM1)

**To replicate the issue**

Use google chrome to visit the website using a tablet or visit the website using google chrome on a desktop and switch to ipad mode using developer tools. 

**Source of the problem**
The problem is occuring due to the padding set on navbar. When you disable the padding, the problem is fixed.

**Comment by AJMcDee** [comment]
I'd be happy to fix this as it seems relatively simple via the stylesheet.

**Comment by smcommits** [comment]
@AJMcDee 

Hey! You can absolutely go ahead and try to fix that and create a pull request. 

Although, I will have to look deeper into the problem as **we cannot straight away remove the padding** because the padding centering the navbar on large screens. A quick fix would be to remove the padding just on the media query used for medium screen sizes. 

Good Luck!

**Comment by AJMcDee** [comment]
@smcommits I will have a look and try to ensure it's only applicable to the medium screens, that's no problem :)

**Comment by AJMcDee** [comment]
@ZachBaird I'm having some trouble with this and the other issue, because I've actually never worked in Ruby before. These are both stylesheet fixes and I've found the stylesheets, so that's not a problem, but I have NO idea how to actually check my changes (e.g. see a preview of the site locally). Is there a specific build/run command similar to npm that I should be using?

**Comment by KevinMulhern** [comment]
@AJMcDee we have a guide for that https://github.com/TheOdinProject/theodinproject/wiki/Running-The-Odin-Project-Locally

**Comment by DoviMaj** [comment]
how is this going @AJMcDee ? 

adding this to https://github.com/TheOdinProject/theodinproject/edit/master/app/assets/stylesheets/components/navbar.scss
should solve it.

```
@media (min-width: 768px){
    .navbar{
        padding: 0px 30px 0px 30px
    }
}


@media (min-width:1440px ){
    .navbar{
        padding: 0.5rem 1rem;
    }
}
```

should i go ahead and do it?

**Comment by DoviMaj** [comment]
how is this going @AJMcDee ? 

adding this to https://github.com/TheOdinProject/theodinproject/edit/master/app/assets/stylesheets/components/navbar.scss
should solve it.

```
@media (min-width: 768px){
    .navbar{
        padding: 0px 30px 0px 30px
    }
}


@media (min-width:1440px ){
    .navbar{
       padding: 0 168px;
    }
}


```

should i go ahead and do it?

**Comment by DoviMaj** [comment]
took the liberty.. https://github.com/TheOdinProject/theodinproject/pull/1439

hope its ok

![Peek 2020-10-23 04-20](https://user-images.githubusercontent.com/36450233/96946346-c67d4a00-14e8-11eb-82cd-910eb80ec808.gif)

**Comment by smcommits** [comment]
@DoviMaj Hey! Yeah that should be it but The Odin Project seems to use some sort of framework. So, it will be better to add the same condition using a HTML class. I will try and dig into it tomorrow. What do you say?

**Comment by ZachBaird** [comment]
Hey @DoviMaj , we really appreciate you creating a pull request for this task and contributing to The Odin Project!

That being said, you helping has actually created an opportunity to talk about task management and courtesy when it comes to open-source development. While Anna hasn't provided an update yet on her progress with this work, this task and another are nevertheless assigned to her. Despite this particular example being a fairly simple code change, your contribution has created a situation where whatever effort she has spent on this has been wasted. This can be a frustrating experience for whomever was working the task, and so its generally best to seek work that hasn't been assigned or to tackle issues that may not be on the board yet.

This can happen in the professional environment too: two people work a task simultaneously and dev effort & time becomes inefficient, so please don't take this as me admonishing you for helping us out!

@AJMcDee if you're fine with it, I can assign this task to @DoviMaj  and @KevinMulhern can review/approve them while you shift to the other one you have.

**Comment by DoviMaj** [comment]
Oh. I see thanks for explaining and sorry Anna. Newbie here. @ZachBaird maybe add that to the contribution guide? or maybe not if it's the first time this happens

**Comment by KevinMulhern** [comment]
@DoviMaj it's the first item on our contributing guide

> Find an issue tagged with "help wanted" to work on. Please comment on the issue to let others know you are working on it.

The implication being that if someone has commented on it to claim it they are working on it.

**Comment by AJMcDee** [comment]
@KevinMulhern @ZachBaird Thank you for saying something, as I probably wouldn't have kicked up a fuss myself but was definitely disappointed when I saw that someone else had worked onit. As it so happens I've actually been sick and so it's turned out for the best that the task was taken over, and I should probably relinquish the other one as well. Thank you for your support, though, and I will keep an eye out for some others that I can work on in future once this bout of bad health passes me by.

**Comment by KevinMulhern** [comment]
Thanks for letting us know @AJMcDee, hope you feel better soon.
