### ISSUE TITLE
Forgotten Password errors

### ISSUE THREAD

**Issue by eriktrautman** [TheOdinProject/theodinproject#142]
Several emails recently like: "I forgot my password and when I attempt to recover it, it keeps saying something went wrong."  Seems to have happened after the `bundle update` on the repo's gems, so something there is probably the issue.  Tests don't seem to be covering it since the suite was all green on the relaunch.

**Comment by herminiotorres** [comment]
@eriktrautman I suggest you can recreate the steps you tried and generated this error?
with images or step by step or some other way?

**Comment by KevinMulhern** [comment]
@herminiotorres we got this issue from someone emailing in. Erik is just letting us know that we are getting these issues reported here.

**Comment by muzfuz** [comment]
Have we been able to replicate this?

**Comment by KevinMulhern** [comment]
It should have been flagged in new relic as an error, but I haven't been able to find any.

**Comment by eriktrautman** [comment]
No emails like that in a long time so it may have worked out during intervening commits.  Never replicated it.
