### ISSUE TITLE
Learning paths buttons overflow nav

### ISSUE THREAD

**Issue by DoviMaj** [TheOdinProject/theodinproject#1421]
On mobile, https://www.theodinproject.com/paths resume and switch buttons overflow the top navigation bar. 

Screenshots:
![Screenshot_2020-10-19-17-51-00-552_com android chrome](https://user-images.githubusercontent.com/36450233/96472946-bab82c00-1239-11eb-88a9-dc3e7f330253.jpg)
![Screenshot_2020-10-19-17-51-30-750_com android chrome](https://user-images.githubusercontent.com/36450233/96472947-bc81ef80-1239-11eb-95f3-aacfbb3fae8b.jpg)

**Comment by DoviMaj** [comment]
i think i resolved it by removing .card-main_buton z-index here: 

https://github.com/TheOdinProject/theodinproject/pull/1422

**Comment by ZachBaird** [comment]
@DoviMaj Thanks for catching this! Can you share a screenshot of what it looks like with the change?

**Comment by DoviMaj** [comment]
a gif

![chrome-capture (2)](https://user-images.githubusercontent.com/36450233/96495188-2c9b7000-1250-11eb-99c4-c92f691e45b4.gif)

a screenshot

![chrome-capture](https://user-images.githubusercontent.com/36450233/96495270-4b9a0200-1250-11eb-9116-d5bf62441492.jpg)

my only concert is that this class is being used somewhere else but i coudnt find anywere.

**Comment by ZachBaird** [comment]
@DoviMaj You can actually do a search in Visual Studio Code if that's the editor you're using. It should be a magnifying glass icon or you can press CTRL + Shift + F to bring it up and search that class. It'll give you any instances where that code shows up.

I'd search for `.card-main_button` and `card-main_button` (was it one or 2 T's? in "buton")

**Comment by DoviMaj** [comment]
`.card-main__button` with two T's. 

Just checked, didnt find any other instances of this class.
