### ISSUE TITLE
Linux installation guide no longer includes Ruby installation information

### ISSUE THREAD

**Issue by AJMcDee** [TheOdinProject/theodinproject#1431]
This page: https://github.com/TheOdinProject/theodinproject/wiki/Linux-Installation-Guide

It indicates that Ruby/Rails installation is assumed based on the installation guide from TOP, but that guide no longer includes Ruby/Rails. I am trying to install everything needed for some fixes and am cobbling my way through, but a step-by-step similar to the rest of that page would be advisable for future fixes.

**Comment by AJMcDee** [comment]
I just saw that the guide still exists but is now located here: https://www.theodinproject.com/courses/ruby-programming/lessons/installing-ruby-ruby-programming

It would be a good first issue for someone if they could change the link in the installation guide to go to that page instead.

**Comment by I3uckwheat** [comment]
The wiki has some nuances that aren't beginner friendly to PR, I have fixed this. Thank you for reporting!
