### ISSUE TITLE
drop "learnlayout.com" link with expired domain from "Foundations/HTML & CSS Basics/Additional Resources"

### ISSUE THREAD

**Issue by PatrickMayoMoran** [TheOdinProject/theodinproject#1458]
Link is dead; sorry I couldn't contribute with a pull request, still figuring out how things work on my computer

**Comment by leosoaivan** [comment]
@PatrickMayoMoran could you open up this issue at [https://github.com/TheOdinProject/curriculum](https://github.com/TheOdinProject/curriculum)? And provide a link to the lesson page, for quick navigation.

This particular repository is for the website itself, not the content.

**Comment by PatrickMayoMoran** [comment]
Will do!
Patrick Moran
