### ISSUE TITLE
Looking to Contribute

### ISSUE THREAD

**Issue by jk47** [TheOdinProject/theodinproject#147]
Can I get added to the slack channel?

**Comment by KevinMulhern** [comment]
Hey @jk47, did you register on this page? https://slackin-theodinproject.herokuapp.com/

**Comment by KevinMulhern** [comment]
I can add you manually if that isn't working, so just let me know :)

**Comment by jk47** [comment]
That worked. Thanks! Maybe I missed it somewhere else, but do you think adding your link above to [this](http://www.theodinproject.com/contributing) page would be easier for people to join the slack channel?

**Comment by KevinMulhern** [comment]
Good idea, I will get it added.
