### ISSUE TITLE
Investigate if Splash Screens are Still Needed

### ISSUE THREAD

**Issue by muzfuz** [TheOdinProject/theodinproject#148]
This looks like it was removed in 2013.

https://github.com/TheOdinProject/theodinproject/commits/upgrade_to_ruby_2.3/spec/models/splash_email_spec.rb

**Comment by KevinMulhern** [comment]
Looks like we can remove what's left of it, gets my vote.

**Comment by KevinMulhern** [comment]
Was this removed @muzfuz?
