### ISSUE TITLE
Flip Async and React section in seeds file.

### ISSUE THREAD

**Issue by I3uckwheat** [TheOdinProject/theodinproject#1480]
![image](https://user-images.githubusercontent.com/4411701/98856710-d36bca00-2412-11eb-8e52-7870baaf6e31.png)
These two sections should be flipped so we're not making mental jumps between learning vanilla JS and a framework. In the future, this could mean we need to add an API project to the React stuff as well.

**Comment by twalton83** [comment]
I’ll go ahead and handle this.
