### ISSUE TITLE
Unable to close "Thanks for updating your solution" popup on dashboard when you update a solution (chrome)

### ISSUE THREAD

**Issue by BoxenOfDonuts** [TheOdinProject/theodinproject#1489]
On the main dashboard if you update a solution, you are unable to close the popup.

appears to be working in Firefox (version 80.1)

Keys, and clicks tried:
- Clicking close
- Clicking the 'x'
- Spacebar / Escape / Backspace

Browser: Chrome 86

The 'click' event listener is tied to  `class="button button--primary"`
following link to the minified js leads to an empty function `function sd() {}`

![image](https://user-images.githubusercontent.com/7082618/99158266-a0396d00-2696-11eb-8367-e382f1eb99d8.png)

**Comment by BoxenOfDonuts** [comment]
Appears the issue only happens when you actually update the code / live preview. Just clicking Edit then Update allows you to close the popup. Reported non-issue with Firefox is incorrect as I didn't update the repo url when testing.

Steps to reproduce: 

1. Go to hompage
2. Click 'Edit Solution'
3. Update the Repository URL
4. Click 'Update' to update the submission

**Comment by ZachBaird** [comment]
Hey @BoxenOfDonuts can you retest? I'm trying to reproduce this on the live site on Firefox and Chrome and I'm just not getting the behavior. I'll ask for some other folks to test as well.

There's been a lot of code changes to the site the past week, so it's very plausible this bug got fixed along the way 👀

**Comment by I3uckwheat** [comment]
I am unable to replicate.

**Comment by BoxenOfDonuts** [comment]
I can only reproduce it when updating my Google Homepage submission, my other submissions appear to work fine. Tried Firefox and Chrome.

**Comment by I3uckwheat** [comment]
@BoxenOfDonuts I am also unable to reproduce on the google home page

**Comment by ZachBaird** [comment]
Reproduced in Firefox on the Google project **only**. No console errors.

**Comment by ZachBaird** [comment]
@BoxenOfDonuts Fix is out and the issue is resolved for me. Can you do some testing and see if your results line up with mine?

**Comment by BoxenOfDonuts** [comment]
@ZachBaird Looks good to me! Updated the Google Project in Firefox and Chrome without issue.
