### ISSUE TITLE
[Tests - JS/React] Add unit tests for edit-form.js

### ISSUE THREAD

**Issue by leosoaivan** [TheOdinProject/theodinproject#1504]
### Background:
The recent addition of the project submissions feature introduces React components to The Odin Project's website. In order to maintain a level of confidence on the feature's implementation, we would like to add tests, starting with unit tests.

For this issue, add unit tests for `component/edit-form.js`.

### Suggestions:
1. Navigate to the TOP website, identify the component in need of testing.
2. Using `react-testing-library`, write tests to address the side effects of changing props/state. Don't test props/state themselves. For more information, Google "white-box testing".

### Acceptance Criteria:
1. Running `yarn run test` does not break the current testing suite.

**Comment by DoviMaj** [comment]
i can give it a try

**Comment by samuelmckean** [comment]
I would love to give this a try if it's still available.

**Comment by Northrain-cmd** [comment]
I am working on it.  Any good repos I can look at in terms of React forms testing? I'm still not sure what exactly should I test

**Comment by I3uckwheat** [comment]
Make sure you guys comment on the issues, ask before you start working on things.

Because this is a learner's course, sometimes people take things and take a while to finish, please don't take that work from them.

**Comment by I3uckwheat** [comment]
This isn't a assigned to @DoviMaj as he commented first.

**Comment by DoviMaj** [comment]
*is

**Comment by Northrain-cmd** [comment]
Ok, no problem, I just figured it wasn't officially assigned so I could try it too. If somebody gets stuck I'll be ready to help

**Comment by I3uckwheat** [comment]
@Northrain-cmd 
I understand, it's tough to keep up with everything when we're as busy as we are :)
