### ISSUE TITLE
[Tests - JS/React] Add unit tests for modal.js

### ISSUE THREAD

**Issue by leosoaivan** [TheOdinProject/theodinproject#1507]
### Background:
The recent addition of the project submissions feature introduces React components to The Odin Project's website. In order to maintain a level of confidence on the feature's implementation, we would like to add tests, starting with unit tests.

For this issue, add unit tests for `component/modal.js`.

### Suggestions:
1. Navigate to the TOP website, identify the component in need of testing.
2. Using `react-testing-library`, write tests to address the side effects of changing props/state. Don't test props/state themselves. For more information, Google "white-box testing".

### Acceptance Criteria:
1. Running `yarn run test` does not break the current testing suite.

**Comment by aayushmau5** [comment]
Hey, i wanna take this one.

**Comment by leosoaivan** [comment]
Resolved by https://github.com/TheOdinProject/theodinproject/pull/1549.
