### ISSUE TITLE
 [Tests - JS/React] Add unit tests for submission.js

### ISSUE THREAD

**Issue by leosoaivan** [TheOdinProject/theodinproject#1509]
### Background:
The recent addition of the project submissions feature introduces React components to The Odin Project's website. In order to maintain a level of confidence on the feature's implementation, we would like to add tests, starting with unit tests.

For this issue, add unit tests for `component/submission.js`.

### Suggestions:
1. Navigate to the TOP website, identify the component in need of testing.
2. Using `react-testing-library`, write tests to address the side effects of changing props/state. Don't test props/state themselves. For more information, Google "white-box testing".

### Acceptance Criteria:
1. Running `yarn run test` does not break the current testing suite.

**Comment by OmarMoataz** [comment]
Hi, I'd like to take this if that's okay.

**Comment by marvingay** [comment]
@OmarMoataz  You're welcome to. If you have any questions or concerns, don't hesitate to leave a comment here. I'll go ahead and assign it to you.

**Comment by marvingay** [comment]
@OmarMoataz  Did we happen to give this a try?

**Comment by OmarMoataz** [comment]
I can work on it this weekend. Sorry for the delay, been a bit busy.
