### ISSUE TITLE
What do you think changing the figaro by dotenv?

### ISSUE THREAD

**Issue by herminiotorres** [TheOdinProject/theodinproject#151]
We have a `env` sample file with the keys to test all in development and test environment.

About it, could be able to have environment variables for development and testing for services. So if everyone who can contribute not need to create these variables of the services, e.g. `disqus`, `github`, `sendgrid`...

**Comment by muzfuz** [comment]
Honestly I don't feel like theres a huge difference between these two, so I'm not sure it justifies the time spent for everyone to change this.

Also, we need every developer to create their own `disqus` and `github` tokens - we don't have a generalised setup for this.  So either way, you are still storing your own ENV vars.

**Comment by herminiotorres** [comment]
Well, if you had a generic data, could reduce the complexity of someone help, because maybe not everyone knows how to create these keys

**Comment by herminiotorres** [comment]
What do you think?

**Comment by muzfuz** [comment]
I don't think it's worth the effort personally.  It requires changing not just the gem config but also figuring out a new way of talking to GitHub OAuth - and I'm not actually sure that there's a secure way of doing that if we abstract all this stuff out.  So I would not go in this direction right now.

If you really care about the issue though, then please go ahead and start a new branch with this feature implemented, and I'm happy to take another look.
