### ISSUE TITLE
 [Tests - JS/React] Add unit tests for submissions-list.js

### ISSUE THREAD

**Issue by leosoaivan** [TheOdinProject/theodinproject#1510]
### Background:
The recent addition of the project submissions feature introduces React components to The Odin Project's website. In order to maintain a level of confidence on the feature's implementation, we would like to add tests, starting with unit tests.

For this issue, add unit tests for `component/submissions-list.js`.

### Suggestions:
1. Navigate to the TOP website, identify the component in need of testing.
2. Using `react-testing-library`, write tests to address the side effects of changing props/state. Don't test props/state themselves. For more information, Google "white-box testing".

### Acceptance Criteria:
1. Running `yarn run test` does not break the current testing suite.

**Comment by brooksquil** [comment]
I'd love to give this a try.

**Comment by marvingay** [comment]
@brooksquil You're welcome to. If you have any questions or concerns, don't hesitate to leave a comment here. I'll go ahead and assign it to you.

**Comment by marvingay** [comment]
@brooksquil Did we happen to give this a try?

**Comment by brooksquil** [comment]
I haven't worked on this yet, but if no one is clamoring to do it I still
would like to

**Comment by fortypercenttitanium** [comment]
Seeing as this hasn't been done yet, I'd like to offer to take it over.

**Comment by CouchofTomato** [comment]
@brooksquil 

Hey Brooke, can you let us know if you're still wanting to take this one on please?

**Comment by brooksquil** [comment]
Of course sorry

**Comment by CouchofTomato** [comment]
@brooksquil Thanks for coming back so quickly. We need to close this one within the next two weeks.

Is this something you can do or should we hand it over to someone else?

**Comment by CEOehis** [comment]
Hi @CouchofTomato I'd like to take this up if @brooksquil is no longer available to based on the deadline.

**Comment by brooksquil** [comment]
So sorry please have someone take this over.

**Comment by I3uckwheat** [comment]
@CEOehis Hey, we'll give this to @fortypercenttitanium if he wants it because he asked first :)

@fortypercenttitanium, you still want this?

**Comment by fortypercenttitanium** [comment]
@I3uckwheat Yes I can get it done within a few days.

**Comment by I3uckwheat** [comment]
@fortypercenttitanium Great, this is assigned to you :)
