### ISSUE TITLE
Add link back to project page in project submission pages

### ISSUE THREAD

**Issue by jessicaawhy** [TheOdinProject/theodinproject#1519]
**Issue:**
I think the submissions pages for each projects is great so far but sometimes I find myself a few pages in and want to go back to the project description page more easily than hitting back a few times or navigating there again. It'd be useful if we were to add a button to link back to the project page.

**For example:** 
https://www.theodinproject.com/lessons/library/project_submissions?page=5

Say I'm on page 5 after hitting next a few times, it'd be nice to have a more direct link back to the project page of the library project. Maybe turn the `Javascript: (Library)` part of the page into a button.

**Comment by I3uckwheat** [comment]
Ahhh, this is a great idea! We really just need a link at the top that says `Go back to lesson`

**Comment by KevinMulhern** [comment]
Making the lesson name under the solutions header a link might be a better approach, but I'm not 100% sure 🤔

**Comment by I3uckwheat** [comment]
@KevinMulhern Can we consult @adachiu ?

**Comment by DoviMaj** [comment]
Guys, i think https://github.com/TheOdinProject/theodinproject/issues/1558 would solve this

**Comment by I3uckwheat** [comment]
I have closed #1558, it is not a solution to this, but an issue.

**Comment by I3uckwheat** [comment]
Waiting for @adachiu's response on this.
