### ISSUE TITLE
Small Readme changes

### ISSUE THREAD

**Issue by superspike7** [TheOdinProject/theodinproject#1532]
## remove "Jquery" and add "Node" and "React" to the "We Teach:" list

![image](https://user-images.githubusercontent.com/65844337/100291342-7b0efd80-2fb8-11eb-8d7d-c7af95c82e77.png)

**Comment by I3uckwheat** [comment]
Nice, great catch!

**Comment by berubenic** [comment]
I can fix this tonight!

**Comment by erdemyigitoglu** [comment]
If it is still available I can make the change.

**Comment by KevinMulhern** [comment]
This has been resolved
