### ISSUE TITLE
Solutions formatting issue with long usernames

### ISSUE THREAD

**Issue by BoxenOfDonuts** [TheOdinProject/theodinproject#1536]
When a username is longer than 18 characters and the width of the broswer is between 770px and 1000px, the formatting for the submission items breaks. 

Steps to reproduce:

1. Open - https://www.theodinproject.com/courses/javascript/lessons/tic-tac-toe-javascript
2. Scroll down to solutions
3. Shrink width to range above 770 - 1000 px

![image](https://user-images.githubusercontent.com/7082618/100526231-84e95a00-318c-11eb-92b4-9d1cd5de994a.png)

**Comment by tmannazy** [comment]
I will love to fix it. How do I go about that?

**Comment by I3uckwheat** [comment]
@tmannazy You will have to edit the CSS on the site to fix. You should have some basic knowledge of getting things running. Contributing guide is here: https://github.com/TheOdinProject/theodinproject/wiki/Contributing-Guide

**Comment by GiZmoFalcon** [comment]
I tried to solve this issue quickly on devtools and here is my solution if that helps:
For this to work, the username needs to be put inside a `<span>` tag inside the `<div class="submissions__submission-title">` element.
```css
.submissions__submission-title {
    font-weight: 600;
    font-size: 1.25rem;
    max-width: 18ch;
    overflow: hidden;
    span {
    display: inline-block;
    }
    span:hover{
    animation: marquee 15s linear alternate infinite;
   }
}

@keyframes marquee {
  0% { transform: translate(0, 0); }
  100% { transform: translate(-100%, 0); }
}

**Comment by shoebham** [comment]
adding`white-space:nowrap` seems to work
```
.submissions__item {
    white-space: nowrap;
    border-top: solid 1px rgba(0,0,0,0.1);
    display: flex;
    justify-content: space-between;
    align-items: center;
    padding: 1em 0;
}
```

**Comment by DoviMaj** [comment]
is this solved?

**Comment by I3uckwheat** [comment]
Yes

**Comment by GiZmoFalcon** [comment]
![image](https://user-images.githubusercontent.com/16624267/101500054-f5b22280-3993-11eb-9af7-eb52bfb824d8.png)
I think the issue still exists or the resolution gave rise to another issue. The hearts don't align now if the names are too large.

@I3uckwheat

**Comment by DoviMaj** [comment]
https://github.com/TheOdinProject/theodinproject/pull/1562

**Comment by BoxenOfDonuts** [comment]
@DoviMaj I think there is an issue from the previous solution where the `max-width` property isn't tied to a breakpoint. It applies with the full width as well.

#1562

![image](https://user-images.githubusercontent.com/7082618/101505012-7b54b480-3939-11eb-8897-1343f382a841.png)

**Comment by DoviMaj** [comment]
yes @BoxenOfDonuts. which width is this screenshot on?

**Comment by BoxenOfDonuts** [comment]
@DoviMaj 1920px,

**Comment by DoviMaj** [comment]
ok @BoxenOfDonuts i updated this PR https://github.com/TheOdinProject/theodinproject/pull/1563 to solve that also
