### ISSUE TITLE
Styling: Reducing the H1 size on mobiles.

### ISSUE THREAD

**Issue by eriktrautman** [TheOdinProject/theodinproject#154]
This came via the form on the bottom of the site.  Think it's a problem?  We've had some complaints before about the mobile-unfriendliness of our navbar and headers.
***************
New feedback suggestion for The Odin Project! 

User < not logged in > was on /home and said: 

pls, fix the size of "div .headline h1" for mobiles using css3. media screen (max width 768px) { font-size:18px }

**Comment by C-Whitlock** [comment]
What are the thoughts on converting over to em over px? That should fix the sizing issue and increase mobile friendliness.

**Comment by KevinMulhern** [comment]
Hey @C-Whitlock, we will be ensuring everything is mobile friendly in our impending re-design 😄
