### ISSUE TITLE
Solutions dashboard view with long titles breaks CSS

### ISSUE THREAD

**Issue by fortypercenttitanium** [TheOdinProject/theodinproject#1550]
When a project has a long name, the buttons to the right on the dashboard view break.

![image](https://user-images.githubusercontent.com/61510135/100662802-636ea680-3323-11eb-9c68-9d91614017c9.png)

**Comment by KevinMulhern** [comment]
Hi @fortypercenttitanium, thanks for reporting. This is a duplicate of https://github.com/TheOdinProject/theodinproject/issues/1536

**Comment by fortypercenttitanium** [comment]
Sorry about that - I thought it was different because it was the dashboard view.

**Comment by KevinMulhern** [comment]
ahh I see. The same react component is used for both views. Fixing it one should sort out the other 🤞
