### ISSUE TITLE
add navigation through submissions to project page

### ISSUE THREAD

**Issue by DoviMaj** [TheOdinProject/theodinproject#1558]
Its not very nice to have to go into a diferent page to view all of the project submittions so...

i propose that instead of:
(_screenshot from project page_)
![Screenshot_2020-12-02 Project Battleship The Odin Project(1)](https://user-images.githubusercontent.com/36450233/100914129-51376880-34db-11eb-9092-3b42f289687a.png)

we have the full list of submitions show only 10 most recent submittions and have a navigation to other submittions from whitin the project page, not needing to go to other page to view more submissions. like this:
(_screenshot from full list of submittions page_)
![Screenshot_2020-12-02 Shopping Cart The Odin Project](https://user-images.githubusercontent.com/36450233/100914155-5a283a00-34db-11eb-9c41-026a0bba9932.png)
and view old submissions can be on bottom or right side for easier navigation.

**Comment by I3uckwheat** [comment]
This is intended, with the voting system we have coming new submissions will be shown alongside the most voted submissions. We can't move this page into that same component because the order will not line up.

**Comment by DoviMaj** [comment]
oh well. if we cant we cant.

**Comment by I3uckwheat** [comment]
@DoviMaj This *could* be implemented, but it defeats the purpose of having new submissions alongside top rated submissions.

We want to make sure we have good examples, while also allowing for new people a chance to get more exposure on their projects.

**Comment by DoviMaj** [comment]
makes sense @I3uckwheat. but i dont see how would two columns of solutions fit into the page, but i guess u guys have something in mind already...

**Comment by I3uckwheat** [comment]
@DoviMaj It wouldn't be two columns. They would be mixed within the results.

**Comment by DoviMaj** [comment]
and view all submitions page would be by newest?

**Comment by I3uckwheat** [comment]
Possibly, we have no comment on this and we have been working through plans.

**Comment by DoviMaj** [comment]
im trying to understand why would it not line up whithin the same component

**Comment by DoviMaj** [comment]
> Possibly, we have no comment on this and we have been working through plans.

ah. what about having a sort by likes or newest option?

**Comment by I3uckwheat** [comment]
If you have old items mixed with new, you're going to break the sorting if you try to go to a "next page". This causes unnecessary load on the DB as well as adding load to the site to sort and filter the results. 

Keeping it simple is important so we don't spend way too much time on this small thing and we can bring better content to everyone. Feel free to make a PR fo this.

**Comment by DoviMaj** [comment]
_you're going to break the sorting if you try to go to a "next page"_
cant sort the DB by random and then load them into the pages in order?

make a PR u mean an issue? cause i dont have the skills to implement that yet.

Also if a sorting button gets implemented then this issue could stay open for implementation and solves the other issue i mentioned too.

**Comment by I3uckwheat** [comment]
It's unnecessary overhead

By PR I mean,  make changes to the code and request they get added to the codebase. If you do not have the skills yet, you can gain them and do that then.

**Comment by DoviMaj** [comment]
maybe when i finish Node and then i'l need to learn Rails to do that
