### ISSUE TITLE
Change Course Titles in In Foundations

### ISSUE THREAD

**Issue by CatQueenCodes** [TheOdinProject/theodinproject#1560]
A few lesson titles in Foundations were sort of misleading and would be better changed to: 

The first chunk of lessons called **The Basics** would be better named **Introduction**

and the lesson **Gearing Up** would be better named **Motivation and Mindset**. 

This was discussed in discord.

**Comment by GiacomoGitHub** [comment]
@CatQueenCodes I’d like to help! It’s my first time, could you tell me what’s the procedure (or point me to the documentation)?

**Comment by CatQueenCodes** [comment]
@GiacomoGitHub  The seed files (https://github.com/TheOdinProject/theodinproject/blob/master/db/seeds/01_foundations_seeds.rb) need to be updated with the proper names!

**Comment by CatQueenCodes** [comment]
Additionally: The folder name 'the_basics'  in the curriculum repo will need to be updated and so will the md file name for the gearing up lesson there as well!  https://github.com/TheOdinProject/curriculum/tree/master/foundations

**Comment by GiacomoGitHub** [comment]
@CatQueenCodes I'm on it! 👍🏻

**Comment by GiacomoGitHub** [comment]
@CatQueenCodes done! 

It took me longer than I thought and it was a bit of a challenge. Is it always like this the first time? 😅

I hope everything I did is correct. Let me know if you need anything else or if I made a mistake, I'll fix it.

**Comment by derahn** [comment]
Hello @CatQueenCodes I'd also love to be of help....I'd view all of the links you shared and see what I can do..hope I'm not too late

**Comment by CatQueenCodes** [comment]
@derahn This issue is resolved and closed! Feel free to check the open issues or create your own issue or pull request if you can think of anything you'd like to add or change in the curriculum. :)

**Comment by derahn** [comment]
@CatQueenCodes thanks.. I'd pay attention

**Comment by ThorOnTheRocks** [comment]
Would love to contribute on that

**Comment by twalton83** [comment]
@ThorOnTheRocks As stated above, this issue is resolved.
