### ISSUE TITLE
Shareable link for MD preview feature

### ISSUE THREAD

**Issue by I3uckwheat** [TheOdinProject/theodinproject#1576]
We have a brand new feature to help debug MD issues! 
---> https://www.theodinproject.com/lessons/preview <---

It's missing one thing that would be very nice to have however, and that would be a way to share what is in the body of that form with others in a way that's easy to replicate. Because markdown may not be the same across all platforms, and a simple copy/paste can be error prone across platforms, a link generator that could encode the content into a base64 format and append it to a query parameter for sharing. When another user clicks this link, it could apply the text that was stored in the base64 query parameter to the body of the form which gives us a very easy and clean way to share markdown fixes and concepts.

Acceptance criteria:
- [x] Add a button that allows you to generate a link from the text in the form
- [x] Keep all code on the frontend, this does not need to hit the DB or store anything
- [x] Load text from query parameter when page is loaded
- [x] Unit tests for all added code

**Comment by twalton83** [comment]
I'm interested in this project.

**Comment by I3uckwheat** [comment]
@twalton83 Good luck, homeslice!
