### ISSUE TITLE
PWA Title

### ISSUE THREAD

**Issue by gogvale** [TheOdinProject/theodinproject#1596]
Could you please implement the website's title?

Here's how it looks after installing:

![image](https://user-images.githubusercontent.com/23729423/102673316-4296b580-4159-11eb-8239-2ed755fd3c43.png)
![image](https://user-images.githubusercontent.com/23729423/102673339-5cd09380-4159-11eb-87f0-757c0261e656.png)

**Comment by BoxenOfDonuts** [comment]
I can grab this. 

Name: The Odin Project
Short Name: TOP?

The short name will probably turn into "The Odin Proj..." on mobile if its not reduced, but I'm not really in love with it being TOP either.

**Comment by BoxenOfDonuts** [comment]
This should be resolved with PR 1637

https://github.com/TheOdinProject/theodinproject/pull/1637

**Comment by gogvale** [comment]
> This should be resolved with PR 1637
> 
> #1637

It's working, thank you!!

Closing the issue
