### ISSUE TITLE
Devise should not require email confirmation for Omniauth users

### ISSUE THREAD

**Issue by cdouglass** [TheOdinProject/theodinproject#160]
Current behavior: After a certain amount of time, users who created their accounts through GitHub are blocked from logging in, with a message "You have to confirm your account before continuing."
Screenshot:
![image](https://cloud.githubusercontent.com/assets/8453868/14657385/77a2a6b4-0642-11e6-831f-c4d62c956caf.png)

Desired behavior: Omniauth should be sufficient confirmation by itself, so these users should never be required to confirm their email addresses separately.

I think I can fix sometime this week.

**Comment by eriktrautman** [comment]
Github doesn't guarantee emails will be present if users log in with it so we do need to make sure we have a guaranteed email for each user.

**Comment by cdouglass** [comment]
It does seem to be a usability problem since we've been getting complaints about this (or at least I think this is what they're referring to). Maybe the email requesting confirmation needs to be clearer somehow, or we could reconsider the need for a guaranteed email.

**Comment by KevinMulhern** [comment]
After spending a bit more time looking into this, the screen shot above is normal behaviour. We really need to talk to someone who can't log in with github to find out what they are doing and what's happening when they try to login. 

I am going to close this issue for now.

**Comment by klimpaparazzi** [comment]
I had the same issue. After clicking on the link and submitting my email I used, I got a notice that the email doesn't exist. I had to go back to my mail box and search for the original email when I signed up with the TOP, and confirm that link. Then it worked like a charm and I was able to log into TOP with the github account.
