### ISSUE TITLE
Displaying wrong image when hovering over JavaScript section

### ISSUE THREAD

**Issue by sher-s7** [TheOdinProject/theodinproject#1616]
![odin](https://user-images.githubusercontent.com/37381007/103500719-e949aa00-4e19-11eb-9c83-cd9d5dae26ff.gif)

When the JavaScript section is hovered over, it displays an off-center Odin logo which I'm guessing shouldn't be there.
You can see when I hover over the HTML & CSS section, it displays it's image fine.

**Comment by twalton83** [comment]
Thank you for pointing this out, this is being addressed here #1613
