### ISSUE TITLE
Content is being fetched even when there has been no changes to it.

### ISSUE THREAD

**Issue by TopOneOfTopOne** [TheOdinProject/theodinproject#165]
The rake tasks in `lib/curriculum.rake` will pull content from https://github.com/TheOdinProject/curriculum even when the content does not change. 

You can test this simply by running two consecutive `rake curriculum:update_content` logically the second call should not update any content because the content has not changed.

I am sure this bug is simple but I am too dumb to figure this out XD

**Comment by KevinMulhern** [comment]
I've been testing this, it does it in development for some reason but not in production. I've confirmed that the content being imported is the same as the content already on the lesson.
