### ISSUE TITLE
Showing a non existent user blows up website

### ISSUE THREAD

**Issue by TopOneOfTopOne** [TheOdinProject/theodinproject#166]
If you call something like this `GET /users/show/12321313` i.e. non existent user id. You will get this error in production server `We're sorry, but something went wrong.` Clearly there is an issue. 

Upon further investigation it comes down to `redirect_to :back` in users controller. There is no referrer url i.e. `request.env["HTTP_REFERER"]` returns nil so the above line of code raises an exception. To solve this we could use `session["previous_url"]` or we could catch the exception and just return them to root url. I think the former is better. 

Finally as I go over the code should I just keep one issue open and keep adding to that one or just make seperate ones as I have done here?

**Comment by KevinMulhern** [comment]
I agree with your proposed solution @TopOneOfTopOne. Yeah make separate issues for each individual bug. That will allow us to tackle them  separately.
