### ISSUE TITLE
Auto-resizing of student project submissions overflow is off. 

### ISSUE THREAD

**Issue by CatQueenCodes** [TheOdinProject/theodinproject#1666]
![Screen Shot 2021-01-20 at 2 20 08 PM](https://user-images.githubusercontent.com/59713017/105224180-d974da00-5b2a-11eb-8452-635e9c451cce.png)

It seems to happen when I have it around half screen window size, if I keep making the screen smaller eventually it does wrap around. It only happens with the person who submitted it's line since it has more content than the other lines. 

Not a major issue, just something I noticed

**Comment by aayushmau5** [comment]
@CatQueenCodes I would like to work on this issue.

**Comment by aayushmau5** [comment]
![demo](https://user-images.githubusercontent.com/54525741/105341964-bcf9a000-5c05-11eb-8d96-e8808a41bcde.png)

Is this better?

**Comment by CatQueenCodes** [comment]
We think it looks a bit odd having it as the only item needing 2lines/ having the eye on a seperate line. Would it be possible to try and have it so the buttons+icon shrink to fit

**Comment by aayushmau5** [comment]
Working on it.

**Comment by aayushmau5** [comment]
Here are some of the things i tried:

After setting the font size to 15px.
![first](https://user-images.githubusercontent.com/54525741/105385568-83428c80-5c39-11eb-9684-586793ea261a.png)
After adding `work-break`
![second](https://user-images.githubusercontent.com/54525741/105385575-850c5000-5c39-11eb-8d4b-2ab6b4606bc3.png)

**Comment by rankoliang** [comment]
![image](https://user-images.githubusercontent.com/37024941/105418112-9853f700-5c0a-11eb-842c-33d3ce11fef3.png)

Here's a solution I came up with. Also added color to the borders to emphasize that it's your own submission. I'm not sure how it would look when it comes to the project submissions in the dashboard though.

**Comment by DoviMaj** [comment]
`*, *::before, *::after {
    box-sizing: border-box; 
 }` from bootstrap is causing this. how to fix it? no idea

**Comment by DoviMaj** [comment]
Can someone assign this to me? @aayushmau5 let me take it

**Comment by DoviMaj** [comment]
May be closed
