### ISSUE TITLE
Whitespace issues when signed out

### ISSUE THREAD

**Issue by rankoliang** [TheOdinProject/theodinproject#1667]
![image](https://user-images.githubusercontent.com/37024941/105564546-b3009b80-5cf0-11eb-93df-31a55e8dd9b3.png)
![image](https://user-images.githubusercontent.com/37024941/105564561-bd229a00-5cf0-11eb-917f-b1faf1c7a065.png)

I found two whitespace issues on these modals when you are signed out. One of them occurs when you try to create a project and the other occurs when you attempt to flag a project on a page with project submissions.

The offending files are here.
https://github.com/TheOdinProject/theodinproject/blob/master/app/javascript/components/project-submissions/components/create-form.jsx
https://github.com/TheOdinProject/theodinproject/blob/master/app/javascript/components/project-submissions/components/flag-form.jsx

All that would need to be done is to add a space (`{' '}`) after the word Please and the sign in link for both of the files.

**Comment by akoenig1** [comment]
I think I have what it takes to handle this one if its still open
