### ISSUE TITLE
? Erroneous email confirm link ?

### ISSUE THREAD

**Issue by eriktrautman** [TheOdinProject/theodinproject#169]
From email noon PT 5/31/16:
---

Hello,

I came across a problem when trying to confirm my email from the welcome email. It directs me to the correct link but times out with the error notification in the subject line. I had to add "www." to get it working.
---

**Comment by KevinMulhern** [comment]
That's an odd one, theres nothing in new relic and we haven't heard of any errors like this before. It's possible it's a one off but we should investigate none the less. 

**Action to be taken**
Try and recreate this error in development

**Comment by KevinMulhern** [comment]
We can't replicate this in development and it hasn't been reported since so I think it's safe to close this.
