### ISSUE TITLE
Update Slug when The a Resources Title is Changed

### ISSUE THREAD

**Issue by KevinMulhern** [TheOdinProject/theodinproject#1710]
### Description
We use a resources title to generate its slug (url path). But when we update the title on a lesson, section, course or paths title it does not also update the slug for that resource

### Steps to reproduce
1. Update a lesson title in the rails console
2. View that lesson in the browser
3. 💥  the path in the lesson url is not updated to use the new title.
4. Repeat for sections, courses and paths

### Expected 
1. Update a lesson title in the rails console
2. View that lesson in the browser
3. The path in the lesson url has been updated to use the new title.
4. Repeat for sections, courses and paths

### Additional Details
We use friendly_id to generate slugs automatically: https://github.com/norman/friendly_id

This might be as simple as adding the `should_generate_new_friendly_id?` hook method to each of the models that use friendly_id

https://norman.github.io/friendly_id/FriendlyId/Slugged.html#should_generate_new_friendly_id%3F-instance_method

**Comment by akoenig1** [comment]
Hey I'd love to take a pass at this one if there are no other takers!

**Comment by KevinMulhern** [comment]
It's all yours @akoenig1
