### ISSUE TITLE
Update FAQs

### ISSUE THREAD

**Issue by CouchofTomato** [TheOdinProject/theodinproject#1755]
The FAQs need to be updated to reflect recent changes to our courses.

The section on which technologies we use still mentions we enrol students in the rails track. This is no longer relevant since we enrol everyone into foundations. It also still references a front end path that no longer exists

We also need to remove the why ruby on rails question and answer as we no longer only offer that as an option.

**Comment by programmurr** [comment]
Hey, I can have a go at this if that's alright. Haven't contributed yet so it's a good one to get started with.

**Comment by ZachBaird** [comment]
@programmurr Go for it! I'll assign to you.

**Comment by programmurr** [comment]
Hey, I'm following the [Run TOP Locally](https://github.com/TheOdinProject/theodinproject/wiki/Running-The-Odin-Project-Locally) instructions and just ran the rspec tests, and there's one test failing which I attached in a screenshot. Is it safe to go ahead with seeding the DB or does this need resolved?
Everything installed fine with no errors, as far as I can tell. I have rspec installed using `sudo apt install ruby-rspec-core`.

![image](https://user-images.githubusercontent.com/64764695/114247301-4c505d00-9984-11eb-8a7d-4b66da56b264.png)

**Comment by ZachBaird** [comment]
@programmurr That's fine for now, this failing test cropped up in my code too but doesn't seem to be impacting everyone. Just make sure this is the only failing test when you're ready to push changes (assuming your code-change causes some tests to fail).

**Comment by KevinMulhern** [comment]
Thanks for reporting @programmurr, we need to add installing Redis to the setup instructions by the looks of it 😅
