### ISSUE TITLE
Trouble changing email address

### ISSUE THREAD

**Issue by eriktrautman** [TheOdinProject/theodinproject#176]
Problem via email with changing email address.  The error he mentions is a standard `we're sorry but something went wrong`.  Hopefully there is enough here to try and reproduce the issue!

It sounds like this occurs when someone:
1. Signs up using Github
2. Changes their email on Github (may or may not be relevant)
3. Attempts to change their email on Odin using the account page on our site.
4. Receives a 500 error that something went wrong.  Can still log in using Github though (for now).

This has not been attempted for reproduction yet, I'm just filing the issue.  Original email below.  Can provide redacted info if necessary and appropriate.

---

My question is I sign in with GitHub and I changed my address on GitHub, but the address change doesn’t appear in my TOP user info.  I am going to be shutting down the old email address ([redacted]) so I am changing any online profiles with this address.

When I try updating my user info on TOP it doesn’t change.  When I attempt to change I get the below error message.

It’s not a huge deal because I am able to log in with GitHub.  If nothing else I thought you’d like to know about the error.

BTW - this is my second run at sharpening up my coding skills and TOP is great!  Thank you!  I am tracking 1,000 hours of coding education online while I am working full-time and saving up money for a bootcamp and The Odin Project is making it easy to stay on track.

Regards,
[redacted]

---

**Comment by KevinMulhern** [comment]
We first need to reproduce in development, with all of the issues being reported lately about the auth system it would be a good idea to have a proper look at refactoring and fixing any bugs with it.
