### ISSUE TITLE
Error message when successfully logging with GitHub

### ISSUE THREAD

**Issue by elios11** [TheOdinProject/theodinproject#1778]
There's an error message that appears when you log-in to TOP with GitHub, apparently it logs normally, so it's just a message and not an error.
![image](https://user-images.githubusercontent.com/5899944/111513568-b41dda00-872f-11eb-8ff4-ccef6dd51361.png)

**Comment by CouchofTomato** [comment]
Thanks. This sometimes happens and logging in again solves it. It's a third party auth system so not much we can do.

**Comment by KevinMulhern** [comment]
Looks like this was caused by users logging in with https://theodinproject.com The Github Oauth callback url was expecting https://theodinproject.com

I've updated the callback url, it should work as expected now.
