### ISSUE TITLE
Upgrade to Rails 5

### ISSUE THREAD

**Issue by KevinMulhern** [TheOdinProject/theodinproject#179]
With Rails 5 being officially released we should upgrade, thankfully we are already running Rails 4.2 and Ruby 2.3 so the upgrade process should be relatively straight forward.

http://edgeguides.rubyonrails.org/upgrading_ruby_on_rails.html#upgrading-from-rails-4-2-to-rails-5-0

**Notes**
Because rails 5 supports left outer joins out of the box we should change the `by_latest_completion` method on the user model.

**Comment by jhack32** [comment]
#287
