### ISSUE TITLE
Update discord invite link

### ISSUE THREAD

**Issue by CatQueenCodes** [TheOdinProject/theodinproject#1815]
Currently our Discord community invite link lands users on the #rules channel. Due to the recent change to use Discord's membership screening feature (where users are exposed to the rules before agreeing to join), it's more sensible to have them land on the #faq channel upon joining. The new invite code (which can be appended  to the base discord invite link already there) is: fbFCkYabZB

Update the link in this file: https://github.com/TheOdinProject/theodinproject/blob/53b7245b45f3af3235c88f826134b9b012b8832e/README.md

https://github.com/TheOdinProject/theodinproject/blob/e1ef7d777fc95069434731291fdd1a51a0abae3a/spec/helpers/application_helper_spec.rb

https://github.com/TheOdinProject/theodinproject/blob/5c03fea31d8f1c1817529549c6ffd081ad39525f/app/helpers/application_helper.rb 
Make sure you link your pull request to this issue (over on the right side ----->)

**Comment by fernie-cpu** [comment]
All I have to do is change the link? I can do that

**Comment by CatQueenCodes** [comment]
@fernie-cpu you are assigned!
