### ISSUE TITLE
Homepage's NodeJS course link not working

### ISSUE THREAD

**Issue by U-C-S** [TheOdinProject/theodinproject#1820]
link: https://www.theodinproject.com/courses/nodejs
On opening the above link, it's showing: Looks like you're lost, Odinite! (Error page)

But the other link that's accessed from 'All Paths/Full Stack JavaScript' is working normally
Working link: https://www.theodinproject.com/paths/full-stack-javascript/courses/nodejs

**Comment by U-C-S** [comment]
https://github.com/TheOdinProject/theodinproject/blob/05f7857f0d1f19c37aa024bfe1d6c60d19c6a370/config/routes/old_route_redirects.rb#L22

Is this the root cause? 
Changing the redirect to **/paths/full-stack-javascript/courses/nodejs** might be the fix here

**Comment by ZachBaird** [comment]
@U-C-S I'll give it a go locally, stay tuned!

**Comment by U-C-S** [comment]
Thanks. Just my first-steps in open-source contributions

I might have tested it myself locally, but I have no idea about setting up environment for Ruby.
