### ISSUE TITLE
"Didn't receive instructions or need them again?" doesnot work

### ISSUE THREAD

**Issue by nextLane** [TheOdinProject/theodinproject#183]
I signed in using my Github account however my account was not confirmed, so I selected "Didn't receive instructions or need them again?", entered my email ID with which I have my github account but I did not get any email regarding confirmation.

**Comment by KevinMulhern** [comment]
Hi @nextLane, thanks for bring this to our attention. There have been a lot of errors reported about github login recently. It is something we are working on fixing at the moment. In the meantime you can use the traditional login method. Sorry for any inconvenience.

**Comment by KevinMulhern** [comment]
We've had a few others reporting this same issue since this issues has been raised. In each case the email was in Junk. 

I'm going to close this for now, but we will be improving the user features on the site in our next refactor cycle.
