### ISSUE TITLE
Chore: Bump React Hook Form

### ISSUE THREAD

**Issue by KevinMulhern** [TheOdinProject/theodinproject#1848]
### Description
We use react hook form for the project submission forms on lessons. There have been some pretty major breaking changes to the react hook form resolvers package which is making this difficult to bump.

### Acceptance Criteria
The app is using the latest version of React Hook Form.

**Comment by rankoliang** [comment]
Hey, I can help out with this issue.

**Comment by ZachBaird** [comment]
@rankoliang Go for it! Are you ok with this task being assigned to you?

**Comment by rankoliang** [comment]
Yup! I'll get started on it shortly.
