### ISSUE TITLE
Fix: Broken Path Courses Url Should Redirect to Path Page

### ISSUE THREAD

**Issue by KevinMulhern** [TheOdinProject/theodinproject#1857]
### Description 
previously we had a route to a paths courses, for example `/paths/full-stack-ruby-on-rails/courses`. This has been depreciated as the path page displays all the courses for that path, an example of the new route: `/paths/full-stack-ruby-on-rails`.

### Steps to Reproduce
1. Enter the old path courses url into your browsers address bar: https://www.theodinproject.com/paths/full-stack-ruby-on-rails/courses
2. The page will display an error message 💥 

### Expected
1. Go to the old path courses route for the full stack rails path: https://www.theodinproject.com/paths/full-stack-ruby-on-rails/courses
2. It should redirect you to the full stack rails path route instead: https://www.theodinproject.com/paths/full-stack-ruby-on-rails
3. Repeat for Foundations and Full Stack JS Paths.

### Additional Information
We've put all redirects from our old url structure to the new structure here: https://github.com/TheOdinProject/theodinproject/blob/master/config/routes/old_route_redirects.rb

**Comment by fernie-cpu** [comment]
Me. Can I?

**Comment by KevinMulhern** [comment]
Thanks @fernie-cpu, I've assigned it to you.
