### ISSUE TITLE
Chore: Rename student_id foreign key in lesson completions table to user_id.

### ISSUE THREAD

**Issue by KevinMulhern** [TheOdinProject/theodinproject#1883]
### Description:
We are using `user_id` everywhere else and should be consistent.

**Comment by BrianWisniewski** [comment]
I can get this done. Just to be clear, any instance of  `student_id` is to be replaced by `user_id`, correct?

**Comment by KevinMulhern** [comment]
> Just to be clear, any instance of student_id is to be replaced by user_id, correct?
Yep, spot on @BrianWisniewski 👍

**Comment by BrianWisniewski** [comment]
@KevinMulhern I replaced every instance of `student_id` with `user_id` across the repo but I am getting 13 errors, many of which are MissingAttributeErrors, cant write unknown attribute "student_id". Do you know what might be causing the tests to still look for the `student_id` attribute, even though there is no longer any instance of `student_id`?

**Comment by KevinMulhern** [comment]
Hey @BrianWisniewski, did you create a migration to rename the student_id column to user_id in the database?
