### ISSUE TITLE
Feature: Add resolved_by_id attribute to Flags

### ISSUE THREAD

**Issue by KevinMulhern** [TheOdinProject/theodinproject#1884]
### Description
We should be tracking who resolved flags for auditing purposes.

### Acceptance Criteria
1. Sign up for a new account
2. Use the rails console to set the `admin` attribute for that user as true
3. Go to the html and css project in the foundations course and flag one of the sample project submissions.
4. Find that flag in the admin dashboard: localhost:3000/admin/flags
5. Dismiss the flag
6. The resolved_by_id on the flag in the database should be the id of the user that dismissed it.

Repeat for banning a user

**Comment by Tenacious-Qi** [comment]
Hi there, I'd be happy to do this.

**Comment by KevinMulhern** [comment]
It's all yours, thanks @Tenacious-Qi 😄
