### ISSUE TITLE
Chore: Removing a Project Submission in Admin Flag Page Should not Also remove the Flag

### ISSUE THREAD

**Issue by KevinMulhern** [TheOdinProject/theodinproject#1885]
### Description
We should soft delete the project submission linked to the flag instead.  

### Acceptance Criteria
1. Sign up for a new account
2. Use the rails console to set the admin attribute for that user as true
3. Go to the html and css project in the foundations course and flag one of the sample project submissions.
4. Find that flag in the admin dashboard: localhost:3000/admin/flags
5. Remove the Submission
6. The flag should be in the resolved list.

### Additional Details
We have logic that users can only have one project submission per project. This will need to be taken into account when soft deleting.

Using a gem might be the best way to implement soft deletion, these two are the most popular: https://entrision.com/blog/comparing-paranoia-vs-discard/

**Comment by Tenacious-Qi** [comment]
I'd be happy to give this one a try.

**Comment by Tenacious-Qi** [comment]
This PR addresses issue #1885
