### ISSUE TITLE
HTTPS instead of HTTP in the working with APIs lesson's example snippet

### ISSUE THREAD

**Issue by bokonist** [TheOdinProject/theodinproject#1904]
https://www.theodinproject.com/paths/full-stack-javascript/courses/javascript/lessons/working-with-apis

In the page it says to try:
http://api.openweathermap.org/data/2.5/weather?q=London,uk&APPID=1111111111

Which won't work even with a valid API key because it's not HTTPS.

**Comment by twalton83** [comment]
Their own documentation uses http. https://openweathermap.org/history

**Comment by bokonist** [comment]
That's strange, 

`http://api.openweathermap.org/data/2.5/weather?q=London,uk&APPID=MY_KEY ` is not working for me but

`https://api.openweathermap.org/data/2.5/weather?q=London,uk&APPID=MY_KEY ` works.

Their current weather api doc mentions neither https nor http:
`https://openweathermap.org/current`

**Comment by twalton83** [comment]
I’ll close this because it’s something else- the only difference when called with https is that https is secured.
