### ISSUE TITLE
Feature: Change Title on Paths Index Page to 'All Paths'

### ISSUE THREAD

**Issue by KevinMulhern** [TheOdinProject/theodinproject#1918]
### Description
Feedback from @adachiu - The title should be the same as the wording in the nav.

### Acceptance Criteria
1. Go to the All Paths page
2. The title should be "All Paths" instead of "Learning Paths"

**Comment by EphemSpirit** [comment]
I can take care of this if that's cool (The name I use on discord doens't match my github username so just in case, it's Freya)

**Comment by EphemSpirit** [comment]
I can take care of this one, it's Freya btw
