### ISSUE TITLE
Feature: Redirect Back to Lesson Page After Logging In

### ISSUE THREAD

**Issue by KevinMulhern** [TheOdinProject/theodinproject#1954]
### Description
Just a quality of life feature,  if a user was on a lesson page and then logs in we should redirect them back to that lesson page instead of making them click back to the lesson through the dashboard.

### Acceptance Criteria
1. Visit a lesson page while logged out
2. Scroll down to the complete button , a log in button should be displayed instead - click it
3. Log in
4. You should be automatically redirected to the lesson page you were on previously.

---
It should redirect to the users dashboard if their last location was not a lesson page
1. Visit a course page while logged out
2. Click the login link in the nav
3. Log in
4. You should be automatically redirected to your dashboard.

### Additional Information
Devise has a [mechanism for this](https://github.com/heartcombo/devise/wiki/How-To:-Redirect-back-to-current-page-after-sign-in,-sign-out,-sign-up,-update), we probably want to override our [`after_sign_in_path_for`](https://github.com/TheOdinProject/theodinproject/blob/main/app/controllers/application_controller.rb#L32) method to use the stored_location if its a lesson url.

**Comment by OmarMoataz** [comment]
I'd like to take this if that's okay.

**Comment by KevinMulhern** [comment]
It's all your's @OmarMoataz :)
