### ISSUE TITLE
Refactor suggestion controller action on static pages

### ISSUE THREAD

**Issue by KevinMulhern** [TheOdinProject/theodinproject#201]
*Important* The tests for this controller should be done before working on this ticket https://github.com/TheOdinProject/theodinproject/issues/200

The suggestion action currently has a few code smells, it should be refactored to make it more maintainable.

**Comment by JeromeLC** [comment]
Dude. Shut the hell up with this god damn emails every 2 seconds. I've
muted the thread and am still annoyed by this constantly. Please remove.me
fro.thia list. It was been way too annoying the last few weeks. Thanks man

**Comment by KevinMulhern** [comment]
First don't be so rude!

second
>  You are receiving this because you are subscribed to this thread.
 Reply to this email directly, view it on GitHub

It says right there in your email that your subscribed to this thread, that's not my responsibility or fault. Unsubscribe if you don't want to receive emails. You might want to try and read the entire email before blasting your mouth off, the unsubscribe link is right there at the bottom of it.
