### ISSUE TITLE
Blockquotes are not visually distinguishable from surrounding text

### ISSUE THREAD

**Issue by gkikola** [TheOdinProject/theodinproject#2017]
### Description

On the site's pages, blockquote elements are not styled to look any different from a normal paragraph. This could lead to readers being confused or misled, as they might interpret a quote as being stated by the Odin Project contributors themselves rather than as being from an external source (see below for an example).

#### Steps to Reproduce

This can be seen on the [Factory Functions and the Module Pattern](https://www.theodinproject.com/paths/full-stack-javascript/courses/javascript/lessons/factory-functions-and-the-module-pattern) lesson, specifically in the [Scope and Closure](https://www.theodinproject.com/paths/full-stack-javascript/courses/javascript/lessons/factory-functions-and-the-module-pattern#scope-and-closure) section. There is a quote which begins, "All scopes in JavaScript are created...". The generated HTML for the page does include a blockquote tag around this paragraph, but it lacks a distinguishing style.

#### Expected Behaviour

In order for quotes to be clearly marked as such, they should be styled differently than surrounding text. For example, a left margin could be used, and/or a left border to set the text apart.

**Comment by cojohen** [comment]
I will work on this

**Comment by ZachBaird** [comment]
@cojohen Great! Are you fine with this task being assigned to you?

**Comment by cojohen** [comment]
Yes. Thanks
