### ISSUE TITLE
Refactor Index method on site maps controller

### ISSUE THREAD

**Issue by KevinMulhern** [TheOdinProject/theodinproject#203]
The index method on this controller currently has some code smells and is pretty messy. We should refactor it to make it more maintainable 
https://github.com/TheOdinProject/theodinproject/blob/master/app/controllers/sitemap_controller.rb

**Comment by poctek** [comment]
Can I take this?

**Comment by KevinMulhern** [comment]
Hey @poctek, yeah its all yours 😄 
Thanks you for helping

**Comment by KevinMulhern** [comment]
There isn't much to do to this one now that I look at it again. The `@static_pages' array value can be moved to its own private method and `@frequently_updated_pages` should be removed as we don't use the forum url anymore. 

A bit of refactoring in the view will be needed to remove the @frequently_updated_pages` instance variable. And thats should be it.

I'll work on getting a unit test made for this controller.

**Comment by poctek** [comment]
Here's the PR: https://github.com/TheOdinProject/theodinproject/pull/214, can also work on the tests

**Comment by KevinMulhern** [comment]
Thanks @poctek, that looks great. If you want to make a unit test for it here's the open issue for it https://github.com/TheOdinProject/theodinproject/issues/202
