### ISSUE TITLE
Chore: Create CSS class for upcoming knowledge-check answer links.

### ISSUE THREAD

**Issue by ZachBaird** [TheOdinProject/theodinproject#2095]
#### Description
Following a super old task Briggs spun up for identifying lessons w/out knowledge checks, some tasks have been groomed out in [Curriculum](https://github.com/theodinproject/curriculum) to add missing learning outcomes and knowledge checks to The Odin Project by course. A suggestion was made to have Knowledge Checks be linkable to the content that answers the check so the user can double-check their answer with effort.

The purpose of this task is to create a CSS class, "knowledge-check-link", that will simply remove `a` tag styling. It should prevent additional coloring, text-decoration, and states (:active, :visited, etc) so that the **existing** styling for the knowledge checks isn't accidentally removed.

#### Acceptance Criteria:
Create the `knowledge-check-link` CSS class. It should:

- inherit color
- inherit text-decoration
- have NO color or text-decoration styling on :active, :visited, and similar CSS states.

**Comment by cojohen** [comment]
I can work on this.

**Comment by ZachBaird** [comment]
Sounds good, I'll assign it to you @cojohen
