### ISSUE TITLE
fix the title of a section.

### ISSUE THREAD

**Issue by JuanDCeballos** [TheOdinProject/theodinproject#2209]
### Description
If you are in the block and inline lesson (the last lesson at the CSS Foundations) and you press the button move to the next lesson you are directly move to introduction but, introduction to what?

#### Steps to Reproduce
1. you  must be in the lesson block and inline (the last lesson at the CSS Foundations).
2. You press the button move to the next lesson.
3. You are directly move to a lesson without a descriptive title.
![image](https://user-images.githubusercontent.com/80058433/132751492-9d4fc054-90b3-4fa3-882a-137c712609a0.png)

#### Expected Behaviour
1. Must be in the lesson block and inline (the last lesson at the CSS Foundations).
2. the button move to the next lesson on its title attribute should say: Move on 'Introduction to Flexbox'.
![image](https://user-images.githubusercontent.com/80058433/132751038-0b4a140d-c4a1-43b8-b08f-b3799fbc8a95.png)
3. The lesson's title should say: Introduction to Flexbox.

**Comment by Janak2401** [comment]
I'd like to fix this issue.

**Comment by kashura** [comment]
Fixed and merged, thanks @Janak2401 and @JuanDCeballos
