### ISSUE TITLE
Set Complete button in lessons to immediately show Completed! when clicked and rename Incomplete state

### ISSUE THREAD

**Issue by msespos** [TheOdinProject/theodinproject#2215]
#### Description
(I know that this is not the first time this has been addressed, but I did not see a current issue for it. I hope that this issue is not too redundant.)

Currently when you click on the Complete button in a lesson, the immediate view of the button states Incomplete, which then only changes to Completed! when you have moved the cursor away from the button. I realize that the idea is that when you hover over a button that shows Completed! the option to select Incomplete should be visible, but I think the current setup is jarring, as when you first click Complete the first thing you see is Incomplete, without context. The solution would be some form of displaying Completed! immediately, and then only showing Incomplete after hovering away and back to the button.

In addition, the button would ideally be called something like Mark Incomplete (which is displayed in text when hovering, but the main button shows Incomplete). Incomplete is an adjective not a verb, and is an incorrect description of the state of the lesson after the Complete button has been clicked. I realize that that name could be problematic due to size constraints - maybe the two words can be placed on top of each other in the button?

#### Acceptance Criteria:

1. Log in
2. Visit a lesson page where Complete has not been clicked
3. Click the Complete button
4. The button immediately displays Completed!
5. Move the cursor away from the button
6. The button still displays Completed!
7. Move the cursor back to the button
8. The button displays Mark Incomplete (if size constraints allow for two words - Incomplete is not ideal as it is an adjective which incorrectly describes the state of the project, not a verb describing what will be done to the project)
9. Click the button now displaying Mark Incomplete
10. The button displays Complete
11. Move the cursor away from the button
12. The button still displays Complete and we are back at step 2

#### Additional Information:

A typical lesson page where this feature would be implemented:
https://www.theodinproject.com/paths/full-stack-ruby-on-rails/courses/ruby-on-rails/lessons/advanced-forms

**Comment by KevinMulhern** [comment]
Note: Blocked until the design refresh starts
