### ISSUE TITLE
Feature: Hide student solutions by default with a toggle

### ISSUE THREAD

**Issue by marvka** [TheOdinProject/theodinproject#2244]
#### Description
As it is discouraged to peek at other students solutions while working on a project, it might be beneficial to hide student solutions in project pages behind a toggle, rather than showing them by default. 
Hopefully, the small barrier of having to click a button first to show completed solutions provides further discouragement of using other peoples finished code to the users detriment. 
Optionally, student solutions could be shown by default once the user has submitted their own version of the project.

#### Acceptance Criteria:
1. Visit a project page
2. Student solutions are hidden
3. There's a toggle button that shows/hides student solutions when clicking on it

#### Additional Information:
It's just an idea, but I reckon it's worth discussing.

**Comment by rlmoser99** [comment]
Thanks for taking the time to submit this issue. I am curious on what other maintainers think about this idea, but I know that we are working on a few high priority things right now, so we have time to talk this idea through.

I like the intent behind this idea, but I think it would be cool to utilize a pop-up alert when someone (who has not submitted a project) clicks on **View Code** that says something like "If you have not completed this project, it is recommended to not look at someone else's finished code yet. This is like looking at a baked pizza to learn how to make pizza dough. You have no idea how many times this code has been refactored and you cheat yourself by skipping to their final product. If you are stuck, please ask questions in our Discord server."

You were not clear if you mean the "view code" and/or the "live preview", but I do not think there is a major problem to look at other people's live preview. Sometimes people who do not understand the game (like Ruby's Mastermind) use other's people's games to figure out how to play it. Plus some people need creative inspiration to help them style their own project.

**Comment by superspike7** [comment]
can I work on this issue?
