### ISSUE TITLE
Lesson preview tool lacks support for knowledge check links testing

### ISSUE THREAD

**Issue by wise-king-sullyman** [TheOdinProject/theodinproject#2321]
### Description

When putting lesson content into the preview tool knowledge check links cannot be adequately checked because the links are broken.

#### Steps to Reproduce

1. Go to [this preview](www.theodinproject.com/lessons/preview?content=IyMjIEludHJvZHVjdGlvbgpXaXRoIGFsbCB0aGUgY29uY2VwdHMgd2UgaGF2ZSBsZWFybmVkIGluIHRoaXMgc2VjdGlvbiwgeW91IGFyZSBtb3JlIHRoYW4gcmVhZHkgdG8gY3JlYXRlIHlvdXIgb3duIFJlYWN0IGFwcGxpY2F0aW9ucy4gSG93ZXZlciwgdGhlcmUgYXJlIGEgbG90IG9mIG90aGVyLCBtb3JlIGFkdmFuY2VkIGNvbmNlcHRzIG91dCB0aGVyZSB0aGF0IHdlIGhhdmVuJ3QgZGlzY3Vzc2VkLCBidXQgbmVlZCB0byBpbmZvcm0geW91IG9mLgpUaGlzIGxlc3NvbiB3aWxsIGJlIHVzZWQgdG8gaW50cm9kdWNlIHlvdSB0byBhIGZldyBhZHZhbmNlZCBjb25jZXB0cyBhbmQgZ2l2ZSB5b3Ugc29tZSB0aXBzIG9uIHlvdXIgcGF0aCBhcyBhIFJlYWN0IGRldmVsb3Blci4KVGhpcyBzZWN0aW9uIGlzbid0IG1lYW50IHRvIHRlYWNoIHRoZXNlIGNvbmNlcHRzLCBidXQgdG8gZ2l2ZSB5b3UgYSBoaWdoLWxldmVsIG92ZXJ2aWV3IHRvIGVuYWJsZSB5b3UgdG8gcmVzZWFyY2ggaW4gdGhlIGV2ZW50IHlvdSBuZWVkIHRoZW0gb3Igd2lzaCB0byBsZWFybiBtb3JlLgpUaGlzIGxlc3NvbiBpcyBtZWFudCBhcyBhIGNoZWNrbGlzdC4gT25jZSB5b3UgYXJlIHNlY3VyZSB3aXRoIHRoZSBiYXNpY3MsIGNvbWUgYmFjayB0byB0aGlzIGxlc3NvbiBhbmQgd29yayB0aHJvdWdoIHRoZSBhZHZhbmNlZCBjb25jZXB0cy4gVGhpcyBkb2Vzbid0IGhhdmUgdG8gYmUgbm93LiBJZiB5b3UgZmlyc3Qgd2FudCB0byBtb3ZlIGFoZWFkIGluIHRoZSBjdXJyaWN1bHVtIGFuZCBhcHBseSB5b3VyIGtub3dsZWRnZSBvciBmZWVsIGxpa2UgeW91IGRvIG5vdCBuZWVkIGEgcGFydGljdWxhciBjb25jZXB0IHJpZ2h0IG5vdywganVzdCBza2lwIGl0IGFuZCBjb21lIGJhY2sgYW5vdGhlciB0aW1lIHdoZW4geW91IGFyZSByZWFkeS4KQXMgYSBmcmllbmRseSByZW1pbmRlciwgR29vZ2xlIGFuZCBTdGFja092ZXJmbG93IGFyZSB5b3VyIGZyaWVuZHMhIFdlIHNob3VsZCBiZSBmYW1pbGlhciB3aXRoIHRoZXNlIHRvb2xzIGF0IG91ciBkaXNwb3NhbCBhdCB0aGlzIHBvaW50LgoKR29vZCBMdWNrIQoKIyMjIExlYXJuaW5nIE91dGNvbWVzCgpCeSB0aGUgZW5kIG9mIHRoaXMgbGVzc29uLCB5b3Ugc2hvdWxkIGJlIGFibGUgdG8gZG8gdGhlIGZvbGxvd2luZzoKCiogRXhwbGFpbiBQcm9wVHlwZXMuCiogRXhwbGFpbiBTdHlsZWQgQ29tcG9uZW50cy4KKiBFeHBsYWluIFJlZHV4IGFuZCBzdGF0ZSBtYW5hZ2VtZW50IHN5c3RlbXMuCiogRXhwbGFpbiBoaWdoZXItb3JkZXIgQ29tcG9uZW50cy4KKiBFeHBsYWluIFJvdXRlcnMgaW4gd2ViIHBhZ2VzLgoqIEV4cGxhaW4gaG93IHRvIG1ha2UgeW91ciBvd24gUmVhY3QgSG9va3MuCgojIyMgR3VpZGUgdG8gQWR2YW5jZWQgUmVhY3QKCiMjIyMgPHNwYW4gaWQ9InByb3AtdHlwZXMiPjEuIFByb3BUeXBlczwvc3Bhbj4KCk9uZSBjb21tb24gZGlzY3Vzc2lvbiBhYm91dCBKYXZhU2NyaXB0IGlzIHdoZXRoZXIgaXQgd291bGQgYmUgYmV0dGVyIGlmIHlvdSBjb3VsZCBkZWNsYXJlIHR5cGVzIGZvciB2YXJpYWJsZXMgYW5kIHByb3BlcnRpZXMuIE1hbnkgcHJvZ3JhbW1lcnMgYWdyZWUgdGhhdCB0aGUgcGF0dGVybiBvZiBkZWNsYXJpbmcgdHlwZXMsIHdoaWNoIHlvdSBoYXZlIGluIG1hbnkgb3RoZXIgcHJvZ3JhbW1pbmcgbGFuZ3VhZ2VzIGlzIHByZWZlcmFibGUgYmVjYXVzZSBpdCBhbGxvd3MgeW91IHRvIGNhdGNoIGVycm9ycywgc3VjaCBhcyBwYXNzaW5nIGEgc3RyaW5nIHRvIGEgdmFyaWFibGUgdGhhdCBzaG91bGQgYmUgYSBudW1iZXIuIFRoZXJlZm9yZSwgUmVhY3QgcHJvdmlkZXMgdGhlIHBvc3NpYmlsaXR5IHRvIGRlY2xhcmUgdHlwZXMgdXNpbmcgW1Byb3BUeXBlc10oaHR0cHM6Ly9yZWFjdGpzLm9yZy9kb2NzL3R5cGVjaGVja2luZy13aXRoLXByb3B0eXBlcy5odG1sKS4gQW5kIGlmIHRoYXQncyBub3QgZW5vdWdoIGZvciB5b3UsIHlvdSBjb3VsZCBhbHNvIHVzZSBbVHlwZVNjcmlwdF0oaHR0cHM6Ly93d3cudHlwZXNjcmlwdGxhbmcub3JnLykgd2l0aCBSZWFjdC4KCiMjIyMgPHNwYW4gaWQ9InN0eWxlZC1jb21wb25lbnRzIj4yLiBTdHlsZWQgQ29tcG9uZW50czwvc3Bhbj4KCklmIHlvdSBzdGFydCB3cml0aW5nIGxhcmdlciBhcHBsaWNhdGlvbnMgeW91IHdpbGwsIHdpdGggY2VydGFpbnR5LCBlbmNvdW50ZXIgdGhlIHByb2JsZW0gdGhhdCB5b3UgbWlnaHQgd2FudCB0byBzdHlsZSBidXR0b25zIG9yIGFueXRoaW5nIGVsc2UgYWNyb3NzIHlvdXIgYXBwbGljYXRpb24gc2ltaWxhcmx5LiBPbmUgd2F5IHlvdSBjb3VsZCBzb2x2ZSB0aGlzIHByb2JsZW0gaXMgdGhyb3VnaCBjb2RlIGR1cGxpY2F0aW9uICh3cml0aW5nIGV2ZW4gdGhlIG1vc3QgYmFzaWMgQ1NTIGZvciBlYWNoIGJ1dHRvbikuIEhvd2V2ZXIsIHRoaXMgd291bGRuJ3QgYmUgYSB2ZXJ5IGdvb2QgKG9yIGNsZWFuKSBjb2RlLiBUaGUgW3N0eWxlZC1jb21wb25lbnRzXShodHRwczovL3N0eWxlZC1jb21wb25lbnRzLmNvbS9kb2NzKSBwYWNrYWdlIHByb3ZpZGVzIGEgY2xlYW5lciB3YXkgdG8gZG8gdGhpcy4gSXQgYWxsb3dzIHlvdSB0byBnaXZlIHNvbWUgZGVmYXVsdCBzdHlsaW5ncyB0byBIVE1MIGVsZW1lbnRzLCBtZWFuaW5nIHlvdSBkZWZpbmUgYSBidXR0b24gd2l0aCBzb21lIGJhc2ljIHN0eWxpbmcgYW5kIHJldXNlIHRoaXMgYnV0dG9uIHRocm91Z2hvdXQgeW91ciBhcHBsaWNhdGlvbi4gVGhpcyB3YXkgdGhlcmUgaXMgbm8gY29kZSBkdXBsaWNhdGlvbiBhbmQgaXQgYWxsb3dzIHlvdXIgYXBwbGljYXRpb24gdG8gYmUgbW9yZSBzY2FsYWJsZS4KCiMjIyMgPHNwYW4gaWQ9InJlZHV4Ij4zLiBSZWR1eDwvc3Bhbj4KCllvdSBtaWdodCBoYXZlIGFscmVhZHkgaGVhcmQgYWJvdXQgUmVkdXguIFtSZWR1eF0oaHR0cHM6Ly9yZWFjdC1yZWR1eC5qcy5vcmcpIGlzIHRoZSBtb3N0IHBvcHVsYXIgc3RhdGUgbWFuYWdlbWVudCBzeXN0ZW0gb3V0IHRoZXJlLiBJdCBpcyBub3QgYSBwYXJ0IG9mIFJlYWN0LCBidXQgdGhlIHR3byBjYW4gYmUgdmVyeSBlYXNpbHkgY29tYmluZWQuIFRvZ2V0aGVyLCB0aGV5IG1ha2UgdXAgYW4gZXh0cmVtZWx5IHBvd2VyZnVsIGR1by4gVGhlIHB1cnBvc2UgaXMgdG8gc3RvcmUgeW91ciBhcHBsaWNhdGlvbidzIHN0YXRlIGluIGEgc2luZ2xlIHBsYWNlLCBjb21tb25seSBjYWxsZWQgYSAic3RvcmUiLiBZb3UgdGhlbiBkaXNwYXRjaCBhY3Rpb25zIHRvIHRoZSBzdG9yZSwgd2hlcmUgYSByZWR1Y2VyIHdpbGwgaGFuZGxlIHRoZSBzdGF0ZSBjaGFuZ2VzLiBUaGUgcHJpbWFyeSBiZW5lZml0IG9mIHVzaW5nIGEgc3RhdGUgbWFuYWdlbWVudCBsaWJyYXJ5IGlzIHRvIHByZXZlbnQgaGF2aW5nIHRvIHBhc3MgcHJvcHMgdGhyb3VnaCBtdWx0aXBsZSBsZXZlbHMgb2YgdGhlIGNvbXBvbmVudCB0cmVlLiBBIHN0YXRlIG1hbmFnZW1lbnQgbGlicmFyeSBpcyBvZnRlbiBvbmx5IHJlY29tbWVuZGVkIGZvciBsYXJnZXIgYXBwbGljYXRpb25zLgoKIyMjIyA8c3BhbiBpZD0iaGlnaGVyLW9yZGVyLWNvbXBvbmVudHMiPjQuIEhpZ2hlci1vcmRlciBDb21wb25lbnRzPC9zcGFuPgoKSGlnaGVyLW9yZGVyIFtjb21wb25lbnRzXShodHRwczovL3JlYWN0anMub3JnL2RvY3MvaGlnaGVyLW9yZGVyLWNvbXBvbmVudHMuaHRtbCkgYXJlIGNvbXBvbmVudHMgdGhhdCBjb25zdW1lIGFub3RoZXIgY29tcG9uZW50IGFuZCByZXR1cm4gYSB0aGlyZCBjb21wb25lbnQuCgojIyMjIDxzcGFuIGlkPSJ3aXRoLXJvdXRlciI%2BNS4gd2l0aFJvdXRlciAoaGlzdG9yeSwgbWF0Y2gsIGNoaWxkcmVuIG9iamVjdCk8L3NwYW4%2BCgpbYHdpdGhSb3V0ZXJgXShodHRwczovL3JlYWN0cm91dGVyLmNvbS9jb3JlL2FwaS93aXRoUm91dGVyKSBpcyBvbmUgZXhhbXBsZSBvZiBhIGhpZ2hlci1vcmRlciBjb21wb25lbnQgYW5kIGlzIHdvcnRoIGxvb2tpbmcgaW50byBpdC4gQnkgd3JhcHBpbmcgYHdpdGhSb3V0ZXJgIGFyb3VuZCBvbmUgb2YgeW91ciBjb21wb25lbnRzLCB0aGUgY29tcG9uZW50IHdpbGwgZ2V0IGFjY2VzcyB0byB5b3VyIGhpc3RvcnksIG1hdGNoLCBhbmQgY2hpbGRyZW4gb2JqZWN0cywgd2hpY2ggcHJvdmlkZSBzb21lIGFkZGl0aW9uYWwgc3ludGFjdGljIHN1Z2FyLiBGb3IgZXhhbXBsZSwgeW91IGNvdWxkIHVzZSB0aGUgaGlzdG9yeSBvYmplY3QgdG8gcHVzaCBhIHVzZXIgZnJvbSBvbmUgcm91dGUgdG8gYW5vdGhlci4KCiMjIyMgPHNwYW4gaWQ9Im1vcmUtaG9va3MiPjYuIE1vcmUgSG9va3M8L3NwYW4%2BCgpUaGVyZSBhcmUgYSBsb3Qgb2YgW2hvb2tzXShodHRwczovL3JlYWN0anMub3JnL2RvY3MvaG9va3MtcmVmZXJlbmNlLmh0bWwpIG91dCB0aGVyZSwgd2l0aCB0aGUgbnVtYmVyIG9ubHkgaW5jcmVhc2luZyBieSB0aGUgZGF5IChzaW5jZSB5b3UgY2FuIHdyaXRlIHlvdXIgb3duISkuIEFzIHlvdSBoYXZlIHNlZW4gaW4gcHJldmlvdXMgbGVzc29ucywgaXQgc2VlbXMgbGlrZSB0aGUgUmVhY3QgdGVhbSB3YW50cyB1cyB0byB1c2UgbW9yZSBmdW5jdGlvbmFsIGNvbXBvbmVudHMgd2l0aCBob29rcyBpbiB0aGUgZnV0dXJlLCBzbyBpdCBpcyBkZWZpbml0ZWx5IHdvcnRoIGdldHRpbmcgdG8ga25vdyBib3RoIHRoZSBob29rcyB0aGF0IGFyZSBidWlsdC1pbiB0byBSZWFjdCwgYXMgd2VsbCBhcyBob3cgdG8gY3JlYXRlIHlvdXIgW293bl0oaHR0cHM6Ly9yZWFjdGpzLm9yZy9kb2NzL2hvb2tzLWN1c3RvbS5odG1sKS4KCiMjIyBLbm93bGVkZ2UgQ2hlY2sKClRoaXMgc2VjdGlvbiBjb250YWlucyBxdWVzdGlvbnMgZm9yIHlvdSB0byBjaGVjayB5b3VyIHVuZGVyc3RhbmRpbmcgb2YgdGhpcyBsZXNzb24uIElmIHlvdeKAmXJlIGhhdmluZyB0cm91YmxlIGFuc3dlcmluZyB0aGUgcXVlc3Rpb25zIGJlbG93IG9uIHlvdXIgb3duLCByZXZpZXcgdGhlIG1hdGVyaWFsIGFib3ZlIHRvIGZpbmQgdGhlIGFuc3dlci4KCi0gPGEgY2xhc3M9Imtub3dsZWRnZS1jaGVjay1saW5rIiBocmVmPSIjcHJvcC10eXBlcyI%2BV2hhdCBhcmUgUHJvcFR5cGVzIGFuZCB3aHkgY2FuIGl0IGJlIGJlbmVmaWNpYWwgdG8gdXNlIHRoZW0%2FPC9hPgotIDxhIGNsYXNzPSJrbm93bGVkZ2UtY2hlY2stbGluayIgaHJlZj0iI3N0eWxlZC1jb21wb25lbnRzIj5XaGF0IGFyZSBTdHlsZWQgQ29tcG9uZW50cyBhbmQgaG93IGRvIHRoZXkgbWFrZSB5b3VyIGNvZGUgY2xlYW5lcj88L2E%2BCi0gPGEgY2xhc3M9Imtub3dsZWRnZS1jaGVjay1saW5rIiBocmVmPSIjcmVkdXgiPldoYXQgaXMgUmVkdXggYW5kIHdoeSBhcmUgc3RhdGUgbWFuYWdlbWVudCBzeXN0ZW1zIHVzZWQgaW4gbWFueSBsYXJnZSBhcHBsaWNhdGlvbnM%2FPC9hPgotIDxhIGNsYXNzPSJrbm93bGVkZ2UtY2hlY2stbGluayIgaHJlZj0iI2hpZ2hlci1vcmRlci1jb21wb25lbnRzIj5XaGF0IGlzIGEgSGlnaC1vcmRlciBDb21wb25lbnQ%2FPC9hPgotIDxhIGNsYXNzPSJrbm93bGVkZ2UtY2hlY2stbGluayIgaHJlZj0iI3dpdGgtcm91dGVyIj5XaGF0IGlzIGEgUm91dGVyIGluIGEgd2ViIHBhZ2UgYW5kIHNvbWUgb2YgaXRzIGJlbmVmaXRzPzwvYT4KLSA8YSBjbGFzcz0ia25vd2xlZGdlLWNoZWNrLWxpbmsiIGhyZWY9IiNtb3JlLWhvb2tzIj5Ib3cgY2FuIHlvdSBjcmVhdGUgeW91ciBvd24gSG9va3M%2FPC9hPg%3D%3D)
^This link isn't working and I can't make it work and I have no clue why. GitHub is appending stuff to it that isn't in the link I'm providing. Use the link in the comment below.

2. Go to the preview tab
3. Click one of the knowledge check links.
4. The link takes you back to the write page

#### Expected Behavior

1. Go to the preview
2. Click one of the knowledge check links
3. The link takes you to the corresponding place in the lesson

 #### Additional Information

**Comment by ChargrilledChook** [comment]
I've just tried this out and it seems to be working as intended, so it looks like it's been fixed somewhere along the way :shrug:
