### ISSUE TITLE
Add effect to curriculum tiles on hover

### ISSUE THREAD

**Issue by tiagoheras** [TheOdinProject/theodinproject#2343]
#### Description

The curriculum tiles in the section under the title "Learn everything you need to know to become a web developer" in the homepage don't have any noticeable on hover effect contrary of the rest of the clickables on the page. You can see the demonstration below:

https://user-images.githubusercontent.com/65797374/139926039-eb152c93-db6e-4fda-b492-0908a1337557.mp4

Adding some sort of effect (e.g accentuate box shadow) would make not only the tiles more obvious for users to click but it would also make the clickables styling more consisting by having an on hover effect on all of them.

**Comment by twalton83** [comment]
Thanks for the suggestion, the team will hash it out to see if this is something we want to implement.

**Comment by HiddenOgre28** [comment]
Hi! Could I take on this task?

**Comment by ZachBaird** [comment]
![image](https://user-images.githubusercontent.com/30800863/152836647-e4f21769-3177-456e-ad38-6cb5a14e43c2.png)
How does this look for a hover effect?

**Comment by thatblindgeye** [comment]
Closing as a PR was merged for this issue.
