### ISSUE TITLE
Typo on JS 101 Assignment

### ISSUE THREAD

**Issue by TomJRodrigues** [TheOdinProject/theodinproject#235]
"Complete the remainder of the dev tools **coures** from code school"

should be

"Complete the remainder of the dev tools **course** from code school"

**Comment by KevinMulhern** [comment]
Thanks for identifying this @TomJRodrigues, we will get this fixed asap 😄

**Comment by wuworkshop** [comment]
@KevinMulhern Mind if I submit a PR to fix this minor typo? Trying to get my Hacktoberfest tee. 😛

**Comment by KevinMulhern** [comment]
Hey @wuworkshop It's al yours 😄 
This will need to be fixed on our curriculum repo.
