### ISSUE TITLE
Section titles/links duplicating

### ISSUE THREAD

**Issue by ZachPoole** [TheOdinProject/theodinproject#2356]
### Description
I'm on this page: https://www.theodinproject.com/paths/full-stack-javascript/courses/javascript/lessons/objects-and-object-constructors and when I navigate to my dashboard (or settings) and then hit the back button, the section titles/links are duplicated. I can repeat this multiple times to keep on doubling the section title/links.

#### Steps to Reproduce

1. Go to this link (might occur on other pages) https://www.theodinproject.com/paths/full-stack-javascript/courses/javascript/lessons/objects-and-object-constructors
2. On the navbar click the Odin icon
3. Click "Dashboard"
4. On your browser click the back arrow/button
5. Scroll down till you see "Object Constructors" or "The Prototype" being duplicated
6. You can then click the forward arrow/button on your browser and pick up from step 4

#### Expected Behavior
1. Go to this link (might occur on other pages) https://www.theodinproject.com/paths/full-stack-javascript/courses/javascript/lessons/objects-and-object-constructors
2. On the navbar click the Odin icon
3. Click "Dashboard"
4. On your browser click the back arrow/button
5. Scroll down and only see 1 "Object Constructors" or "The Prototype" 

 #### Additional Information
<img width="1220" alt="Screen Shot 2021-11-08 at 8 46 24 PM" src="https://user-images.githubusercontent.com/46611063/140852518-589ef36f-8e53-435b-8fbf-09909403bd80.png">

**Comment by ZachPoole** [comment]
Maybe something in these two functions:

1. https://github.com/TheOdinProject/theodinproject/blob/e9accb007280412a0029b4a8ad7b2598b5728d62/app/javascript/src/js/lessons.js#L102
2. https://github.com/TheOdinProject/theodinproject/blob/e9accb007280412a0029b4a8ad7b2598b5728d62/app/javascript/src/js/lessons.js#L129

**Comment by CouchofTomato** [comment]
@ZachPoole Thanks for bringing this to our attention. The JS is currently being reviewed for an overhaul so this should get caught then. I'll leave this open as a reminder though that we need to make sure this works as intended once the JS is updated.

**Comment by wise-king-sullyman** [comment]
Seems to me like this was fixed in TheOdinProject/curriculum#23042, does it seem like it works properly now to you @ZachPoole?

**Comment by ZachPoole** [comment]
Yep!
