### ISSUE TITLE
Add proper styling to knowledge check links

### ISSUE THREAD

**Issue by thatblindgeye** [TheOdinProject/theodinproject#2360]
#### Description
The links for knowledge checks in lessons are difficult to recognize as links due to the link styling being removed, causing them to look like plain text. Proper styling needs to be added back.

#### Acceptance Criteria:
Based on the number of previously completed and current/ongoing PR's, lesson rewrites, and issues for the curriculum repo that added the `knowledge-check-link` class to all knowledge checks, I suggest for now editing the rule declarations for the selector in the CSS file.

1. In the [lesson_content.scss](https://github.com/TheOdinProject/theodinproject/blob/511339c40577ef6c81dfc82146d44b4188b6a342/app/assets/stylesheets/components/lesson/lesson_content.scss) file, update the declaration block for the `.knowledge-check-link` selector. 

    It should match the declaration block for the `[href]:not([class])` selector from the [global.scss](https://github.com/TheOdinProject/theodinproject/blob/08133883f87760be90605f56841d7afd79d60dab/app/assets/stylesheets/global.scss) file, except the `& > code {...}` declaration currently on the `.knowledge-check-link` selector should be kept.

**Comment by thomss23** [comment]
I am interested to do my first contribution during this weekend. Would it be ok to try to pick this up as i have finished the foundations course and 25% of js track from full stack js?

**Comment by redelephant8** [comment]
I'm not entirely sure how this works as I'm new but I really agree with "thatblindguy" on this issue. I didn't realize that the questions were links until I accidentally clicked on one so I think this is an important thing to bring up

**Comment by Ishmam156** [comment]
If no one has started working on this yet, would like to be assigned to this :)

**Comment by thatblindgeye** [comment]
@Ishmam156 Thanks for commenting, you've been assigned! Let us know if you have any questions :)
