### ISSUE TITLE
Update Javascript handling the Admin Flash

### ISSUE THREAD

**Issue by CouchofTomato** [TheOdinProject/theodinproject#2375]
#### Description
Some of the legacy Javascript can now be updated so we can eventually remove the depedency on jquery.

As part of this we need to update [this file](https://github.com/TheOdinProject/theodinproject/blob/main/app/javascript/src/js/admin_flash.js) to use a Stimulus Controller.

Suggest reading to help you: https://stimulus.hotwired.dev/ and https://www.betterstimulus.com/

#### Acceptance Criteria:

1. The dependency on JQuery is removed
2. The Admin Flash operates as it currently does
3. A stimulus controller is created to handle the interaction

#### Additional Information:

Stimulus controllers are all about finding the correct level of abstraction. The suggested reading for better stimulus covers this.

**Comment by linkonsat** [comment]
If this is available I would love to take it on. I know there are rewrites of the site happening so I'm not sure if that will affect it at all.

**Comment by CouchofTomato** [comment]
@KevinMulhern 

Is there anything you're doing with the revamp that would block this?

**Comment by KevinMulhern** [comment]
We'll be updating the styles at some point. But the JS can be moved to stimulus now with no issues. It's all yours @linkonsat
