### ISSUE TITLE
Update Javascript handling the New User Form Validations

### ISSUE THREAD

**Issue by CouchofTomato** [TheOdinProject/theodinproject#2377]
#### Description
Some of the legacy Javascript can now be updated so we can eventually remove the depedency on jquery.

As part of this we need to update [this file](https://github.com/TheOdinProject/theodinproject/blob/main/app/javascript/src/js/formValidations.js) to use a Stimulus Controller.

Suggest reading to help you: https://stimulus.hotwired.dev/ and https://www.betterstimulus.com/

#### Acceptance Criteria:

1. The Form still validates as it currently does
2. A stimulus controller is created to handle the interaction

#### Additional Information:

Stimulus controllers are all about finding the correct level of abstraction. The suggested reading for better stimulus covers this.

**Comment by bscottnz** [comment]
Hey am I able to take this?

**Comment by KevinMulhern** [comment]
All yours @bscottnz, 

It might be worth using something off the shelf like https://github.com/jwald1/stimulus-validation rather than rolling our own for this.
