### ISSUE TITLE
Update Javascript handling the user settings page

### ISSUE THREAD

**Issue by CouchofTomato** [TheOdinProject/theodinproject#2380]
#### Description
Some of the legacy Javascript can now be updated so we can eventually remove the depedency on jquery.

As part of this we need to update [this file](https://github.com/TheOdinProject/theodinproject/blob/main/app/javascript/src/js/settings.js) to use a Stimulus Controller.

Suggest reading to help you: https://stimulus.hotwired.dev/ and https://www.betterstimulus.com/

#### Acceptance Criteria:

1. The Admin Flash operates as it currently does
2. A stimulus controller is created to handle the interaction

#### Additional Information:

Stimulus controllers are all about finding the correct level of abstraction. The suggested reading for better stimulus covers this.

**Comment by linkonsat** [comment]
@CouchofTomato curious about why this issue was put on hold. If the situation has changed in regards to why this is on hold I can start working on this one.

**Comment by CouchofTomato** [comment]
I honestly can't remember mate. I should probably have made a note. I think it's because of a lot of other changes that were happening. I don't have an issue with it being worked on though.

**Comment by linkonsat** [comment]
Sweet. I'll start work on this one next then!

**Comment by KevinMulhern** [comment]
It would be worth researching a bit how others are doing this with Stimulus @linkonsat if you don't mind? It will be difficult and clunky adapting our existing form validation code to a Stimulus controller.

**Comment by linkonsat** [comment]
All good @KevinMulhern ! I'll pick it up eventually I'm sure if it's still around. I'll take a look at the other two stimulus issues.

**Comment by KevinMulhern** [comment]
Completed with: https://github.com/TheOdinProject/top-meta/issues/223
