### ISSUE TITLE
Make Progress Tiles Responsive 

### ISSUE THREAD

**Issue by charliebarger** [TheOdinProject/theodinproject#2417]
### Description

This problem pertains to the tile that displays the section a user is in, as well as the percentage of that section the user has completed on hover. 

The tile's sizing breaks when the default font size is changed in the browser. 

![Screen Shot 2021-12-03 at 2 13 53 PM](https://user-images.githubusercontent.com/72449213/144678658-d76482e2-f7ff-4c62-a2fa-b2bc71c9f156.png)

![Screen Shot 2021-12-03 at 2 13 11 PM](https://user-images.githubusercontent.com/72449213/144678598-e3a677b0-074b-457c-8e21-4adfe0542326.png)

Example:
1. Visit https://www.theodinproject.com/paths/full-stack-javascript/courses/nodejs
2. If using Chrome, Visit [chrome://settings/appearance](url) and change font size via the drop down menu labeled "Font Size". 
3. Check the tile on the odin project page 

#### Expected Behavior
The inner div and image should size proportionately to the outer div and be contained by it. The tile should look the same regardless of default font size. 
Only the size should change.

**Comment by charliebarger** [comment]
Can I take this one?

**Comment by KevinMulhern** [comment]
Thanks for reporting. It's all yours @charliebarger 💪
