### ISSUE TITLE
Add redirect for courses/curriculum

### ISSUE THREAD

**Issue by KevinMulhern** [TheOdinProject/theodinproject#244]
We are currently getting a lot of errors with users trying to access a nonexistent route `courses/curriculum`

This was once a route in the site but was deleted some time ago, There must be some external links out there that are directing people to this route.

To fix this issue we should redirect the user to the `/courses` route. This can be done in [routes.rb file](https://github.com/TheOdinProject/theodinproject/blob/master/config/routes.rb), there are already some redirects set up at the bottom of the routes file so those can be used as an example.

**Comment by narekvardanjan** [comment]
I take this one.

**Comment by KevinMulhern** [comment]
It's all yours @narekvardanjan 👍
