### ISSUE TITLE
Edge Case - Submitting a solution when there's already a solution set as private

### ISSUE THREAD

**Issue by xari4808** [TheOdinProject/theodinproject#2461]
### Description

A user can submit their project solution and mark it as private. If solution marked public, there's no "Add Solution" button on the project page. If marked private, there's an "Add Solution" button. When URL's are entered, the "submit" button doesn't seem to do anything, and the console logs an error (Status code: 422).

#### Steps to Reproduce

1. Log in 
2. On the dashboard, there's a heading "Project Submissions".
4. OPTIONAL: In case there aren't any project solutions. Submit one 
5. Set any solution as private after clicking the edit button
6. Navigate to the project page of the private solution
7. Submit a solution as intended. (Fill the URL fields)
8. Click the "Submit" button
9. Open the console, something similar should log

![image](https://user-images.githubusercontent.com/85733202/147178019-6d8d89af-4efd-4766-be22-b25cc81d7be0.png)

#### Expected Behavior

1. A modal pops up after clicking the "Submit" button that says something along the lines: "Solution already submitted", or
2. Hide the "Add Solution" button entirely

 #### Additional Information

**Comment by CouchofTomato** [comment]
Is this something you want to work on @xari4808

**Comment by KevinMulhern** [comment]
Thanks for reporting this @xari4808 

Resolved with https://github.com/TheOdinProject/theodinproject/pull/2474
