### ISSUE TITLE
Remove splash_email.js and forum.js from assets

### ISSUE THREAD

**Issue by KevinMulhern** [TheOdinProject/theodinproject#250]
These two files are no longer used and therefor can be safely deleted.

The two files in question:
[splash_email.js](https://github.com/TheOdinProject/theodinproject/blob/master/app/assets/javascripts/splash_emails.js.coffee)
[forum.js](https://github.com/TheOdinProject/theodinproject/blob/master/app/assets/javascripts/forums.js.coffee)

**Comment by stevenkayter** [comment]
on it

**Comment by KevinMulhern** [comment]
Hey @stevenkayter sorry this one was taken too 😄

**Comment by stevenkayter** [comment]
I guess am not keen :D

**Comment by KevinMulhern** [comment]
Theres a few more like this one I need to create issues for, keep an eye out for them 😛
