### ISSUE TITLE
Remove splash email model

### ISSUE THREAD

**Issue by KevinMulhern** [TheOdinProject/theodinproject#251]
This model is no longer being used and therefore is safe to delete.

Heres the file:
[splash_email.rb](https://github.com/TheOdinProject/theodinproject/blob/master/app/models/splash_email.rb)

**Comment by stevenkayter** [comment]
on it

**Comment by KevinMulhern** [comment]
Hey @stevenkayter sorry this has already been taken, just a few minutes ago.

**Comment by Art4** [comment]
@KevinMulhern Maybe this issue can be closed?

Btw: Great project. :+1: I just wanted to create some PRs but ended up on reading some interesting lessons. :smile:

**Comment by KevinMulhern** [comment]
Hey @Art4 yeah I'm going to close it now 😄 
Thanks for the kind words and your help with this one 👍
