### ISSUE TITLE
Lesson Navigation sidemenu missing in safari

### ISSUE THREAD

**Issue by ManonLef** [TheOdinProject/theodinproject#2511]
In safari the "lesson navigation" is missing on the left side of the screen. 
This happens in all sizes of the browser window. Here's a preview with safari on the left and chrome on the right:

![Screenshot 2022-01-09 at 20 10 12](https://user-images.githubusercontent.com/81025586/148833336-acd204a3-6422-4f75-8fb7-502fb1cc50a1.png)

I will share the inspector for both below.

Safari: 
![Screenshot 2022-01-10 at 21 12 56](https://user-images.githubusercontent.com/81025586/148833196-4f725f45-ec16-4c80-9dd8-8f7e404ae594.png)

Chrome:
![Screenshot 2022-01-10 at 21 13 08](https://user-images.githubusercontent.com/81025586/148833221-4129f3d8-334a-467c-b4d4-6efea5ab8e76.png)

**Comment by ezrahnyanat** [comment]
Hmm something to do with the JS here? https://github.com/TheOdinProject/theodinproject/blob/main/app/javascript/src/js/lessons.js#L81

Doesn't even look like the navigationElement markup is getting set on the page in Safari.

Quick google "safari innerhtml" shows some results where people have run into issues with .innerhtml on Safari.

Maybe .innerhtml needs to be replaced? https://marian-caikovski.medium.com/modern-alternatives-to-innerhtml-and-appendchild-296b9e5a5d28

(Side note: is Stickyfill still necessary now that `position: sticky` has good browser support?)

**Comment by KevinMulhern** [comment]
Resolved by: https://github.com/TheOdinProject/theodinproject/pull/2512
