### ISSUE TITLE
Live preview links should not be accepted in JavaScript: (Testing Practice) solutions submissions.

### ISSUE THREAD

**Issue by Cambuchi** [TheOdinProject/theodinproject#2530]
### Description
In JavaScript: (Testing Practice) solutions submissions, it is possible to submit a valid live preview link. Client side form validation normally prevents this: 

![image](https://user-images.githubusercontent.com/49548018/149871482-618da64e-c139-43f3-b0fa-e6c201da1ad9.png)

But since AJAX is available for access from the browser console it is relatively easy to spoof a PUT request including a live preview link that will be successfully received.

Suggestion: implement server-side validation or remove AJAX functionality availability from the document.

#### Steps to Reproduce
1. Log in
2. Visit the lesson page: [JavaScript: (Testing Practice)](https://www.theodinproject.com/paths/full-stack-javascript/courses/javascript/lessons/testing-practice)
3. Open the console in your browser
4. Spoof an AJAX put request with the appropriate headers and insert custom data e.g:
```
$.ajax({
type: "PUT",
/* insert correct headers here, depends per account, easy to retrieve by submitting via submit button and examining the response details from console*/
'data': {project_submission:{is_public: true, lesson_id: 555, live_preview_url: "your link of choice", repo_url: "also link"}}
})
```

5. See your live preview link in this list of submissions:
![image](https://user-images.githubusercontent.com/49548018/149871366-5311b37f-53df-4f0c-8768-a659761f9373.png)

#### Expected Behavior
Live preview links should not be accepted.

 #### Additional Information
Consider leaving in since seeing people have valid live-preview links is a tip that naturally encourages exploration of the internals of how forms and data are submitted.

**Comment by KevinMulhern** [comment]
Thanks for reporting, resolved with https://github.com/TheOdinProject/theodinproject/commit/cac3a9b2763a1605592e9d4ff8b41557713431a9

**Comment by KevinMulhern** [comment]
Thanks for reporting, resolved with https://github.com/TheOdinProject/theodinproject/commit/cac3a9b2763a1605592e9d4ff8b41557713431a9
