### ISSUE TITLE
links blend in with text when focused

### ISSUE THREAD

**Issue by khunhour** [TheOdinProject/theodinproject#2532]
When links are focused, they blend in with the text which might cause a bit of a problem to pick up where you left off (coming back from a link you just went to). Here are some screenshots to demonstrate.
![Screenshot_20220113_205404_com.android.chrome.jpg](https://user-images.githubusercontent.com/12671115/149439956-b0ebb336-f8ed-41d9-a1bb-101043b47ba0.jpg)
![Screenshot_20220113_205414_com.android.chrome.jpg](https://user-images.githubusercontent.com/12671115/149439975-03f8409b-1d83-458e-b89e-25c78fb40e16.jpg)

**Comment by nguyens20** [comment]
Can you describe what it means by focused? I'm having trouble reproducing this issue.

**Comment by Flinner** [comment]
hover your mouse?

**Comment by iawong** [comment]
Would it be sufficient to just change all link text to yellow so that when you hover, only the underline disappears?

**Comment by khunhour** [comment]
@nguyens20 focus refers to the pseudo class :focus in css. The css changes when when you click on it, but return to original when click else where.

@Flinner Yes, but in this case, with hover you'd probably know where you are in the paragraph so it might not be a problem

@iawong again, just to clarify, this is not a problem with hover, but a problem with when a link is focused (Clicked),but yeah your suggestion would work if apply to both.

**Comment by KevinMulhern** [comment]
We're in the middle of a major rewrite of the site's CSS and will be fixing this alongside it.

**Comment by thatblindgeye** [comment]
Issue #2605 relates to this @KevinMulhern

**Comment by KevinMulhern** [comment]
Thank you for reporting this, link focus has been fixed.
