### ISSUE TITLE
Color inconsistency throughout the site

### ISSUE THREAD

**Issue by Maheshkumar-novice** [TheOdinProject/theodinproject#2537]
Different kind of pages in the dark mode follows a little different approach in colors. Some pages use `dark-bg-color` for the whole page, some use `dark-bg-color` for whole bg and `dark-bg-accent` for `containers` and some use reverse approach of the previous one. The images are attached for reference. I think it'll be good if we make the colors consistent throughout the site.

My suggestion is to use `dark-bg-color` for the whole page background and use `dark-bg-accent` for the containers or the vice-versa. Whichever is better.

![sav](https://user-images.githubusercontent.com/67100964/150453803-1b51bf20-6f24-4ed9-a213-b3d8266705a5.png)
![1](https://user-images.githubusercontent.com/67100964/150453863-f14b5b2d-1114-47c6-9099-29e8a4a75fd4.png)
![2](https://user-images.githubusercontent.com/67100964/150453868-5b972f89-9391-43ca-8c0f-9158a6e7c87e.png)
![3](https://user-images.githubusercontent.com/67100964/150453875-2a841fe1-d6b4-4111-9d4a-6660d92313a3.png)
![4](https://user-images.githubusercontent.com/67100964/150453880-0637e8bf-73eb-4c17-91b8-ebdb70ef9b58.png)
![11](https://user-images.githubusercontent.com/67100964/150454440-cecc8ddc-3e38-4896-8e5e-3198ce89f3a3.png)
![12](https://user-images.githubusercontent.com/67100964/150454447-d3a055a9-46fd-45d8-8e84-c3d5c0f78687.png)
![13](https://user-images.githubusercontent.com/67100964/150454455-5f9386e2-3def-4ce5-aeb7-61da72b465ae.png)
![14](https://user-images.githubusercontent.com/67100964/150454675-7cfb2851-15ae-4639-b2f5-e192de761352.png)

**Comment by DevlinRocha** [comment]
I think this belongs here, these images on the [contributing page](https://www.theodinproject.com/contributing) need to have their background-colors changed:

![contOdin](https://user-images.githubusercontent.com/72491344/150702604-7ba7ad12-21d8-4ca3-b863-25b6c9a5660c.png)

**Comment by KevinMulhern** [comment]
We're in the middle of a major rewrite of the site's CSS and will be fixing this alongside it.

**Comment by Maheshkumar-novice** [comment]
> We're in the middle of a major rewrite of the site's CSS and will be fixing this alongside it.

Okay. All the best!

**Comment by ChargrilledChook** [comment]
Largely fixed by Tailwind updates. SVG's will be fixed in #3150. Dashboard probably needs a few minor tweaks to use the grey inside cards

**Comment by Maheshkumar-novice** [comment]
Nice Work!

**Comment by BLooDBRothER** [comment]
## Hi! I would like to inform a dark theme bug

# Description
* Hovering on `View Code` and `Live Preview` button under project section makes the text colour brighter. As the background colour is also brighter the text is not visible

# Screenshot

![image](https://user-images.githubusercontent.com/63643748/194708684-789da031-ca90-488f-90b6-4a94efe5ce84.png)

**Comment by KevinMulhern** [comment]
Thank you for reporting these issues everyone. They have all been fixed in the [new dark mode](https://github.com/TheOdinProject/top-meta/issues/235)

**Comment by Maheshkumar-novice** [comment]
Nice work everyone! @KevinMulhern @ChargrilledChook !
