### ISSUE TITLE
Dark Mode in Lesson Preview Tool makes font hard to read

### ISSUE THREAD

**Issue by dm-murphy** [TheOdinProject/theodinproject#2540]
### Description
Dark mode stays active when you open Lesson Preview Tool. But the text inside the Write window pane is a bit challenging to read and work with. 

#### Steps to Reproduce

1. Visit Lesson Preview Tool (https://www.theodinproject.com/lessons/preview)
2. Make sure Dark Mode is active
3. Start typing into the Write window pane and the font gets darker

#### Expected Behavior

1. Visit Lesson Preview Tool (https://www.theodinproject.com/lessons/preview)
2. Make sure Dark Mode is active
3. Start typing into the Write window pane and the font stays same color as default

 #### Additional Information
None

**Comment by KevinMulhern** [comment]
We're in the middle of a major rewrite of the site's CSS and will be fixing this alongside it.

**Comment by dm-murphy** [comment]
Thanks Kevin, sounds good! Let me know if I can be of any help.

**Comment by KevinMulhern** [comment]
Will do and thanks for reporting this @dm-murphy, it's much appreciated  😄

**Comment by ChargrilledChook** [comment]
Solved by recent Tailwind fixes
