### ISSUE TITLE
Resizing in hamburger menu on desktop causes dialog popup

### ISSUE THREAD

**Issue by dm-murphy** [TheOdinProject/theodinproject#2541]
### Description
If you click into the hamburger menu on desktop and then resize the browser window, a dialog popup appears. It is especially odd if you are in Dark Mode

#### Steps to Reproduce
1. Visit any page of theodinproject.com on a desktop browser
2. Size the browser window down until the hamburger menu appears
3. Click the hamburger menu
4. Resize the browser window wide again
5. A dialog popup box appears

#### Expected Behavior
1. Visit any page of theodinproject.com on a desktop browser
2. Size the browser window down until the hamburger menu appears
3. Click the hamburger menu
4. Resize the browser window wide again
5. No dialog popup appears and the site is visible again

 #### Additional Information
This bug looks worse in Dark Mode because none of the background site behind the dialog box appears at all. In Light Mode at least you can see the site behind the box.

**Comment by CouchofTomato** [comment]
This should be resolved now
