### ISSUE TITLE
Missing dark mode toggle switch in hamburger menu (Desktop)

### ISSUE THREAD

**Issue by devcheckmo** [TheOdinProject/theodinproject#2542]
### Description
The dark mode toggle switch does not remain when one zooms in and a hamburger icon replaces the regular nav section.

#### Steps to Reproduce

1. Zoom in until the hamburger iron replaces the standard site nav.
2. Click on the hamburger icon.
3. There is no dark mode toggle switch.

#### Expected Behavior
Dark mode should be toggled at any zoom level.

 #### Additional Information
This is my first issue report; I hope it isn't bad!

**Comment by CouchofTomato** [comment]
This should be resolved now
