### ISSUE TITLE
Footer doesn't display correctly

### ISSUE THREAD

**Issue by DevlinRocha** [TheOdinProject/theodinproject#2547]
### Description
The footer at the very bottom of the [Contributing](https://www.theodinproject.com/contributing) and [Success Stories](https://www.theodinproject.com/success_stories) pages (and possibly some others) doesn't display correctly. I've tested this on Firefox and Chrome.

Image of footer:

![footerOdin](https://user-images.githubusercontent.com/72491344/150702888-ddbb31d4-38e6-4adb-b20e-b4711da7462b.png)

#### Steps to Reproduce
Visit either the [Contributing](https://www.theodinproject.com/contributing) or [Success Stories](https://www.theodinproject.com/success_stories) page and scroll to the bottom.

#### Expected Behavior
Visit [any other page](https://www.theodinproject.com/) with a footer at the bottom, it will look like this:

![betterFooter](https://user-images.githubusercontent.com/72491344/150702943-8c121f95-e51d-4543-8209-6b34887840ad.png)

 #### Additional Information

**Comment by KevinMulhern** [comment]
Resolved https://github.com/TheOdinProject/theodinproject/pull/2548
