### ISSUE TITLE
Lesson Content CSS: ordered lists render as unordered lists

### ISSUE THREAD

**Issue by thatblindgeye** [TheOdinProject/theodinproject#2567]
#### Description
A recent updated to the [lesson content CSS](https://github.com/TheOdinProject/theodinproject/blob/921c10767855dbd416ed18fb98aa807409c782c4/app/assets/stylesheets/components/lesson/lesson_content.scss) fixed some spacing/margin styling on lists. A declaration block to add back the correct list style for ordered lists was done so incorrectly, however.

#### Acceptance Criteria:
1. Lines 71 to 73 of the lesson content CSS file being updated to the following should fix the issue:
```css
  ol {
    li {
      list-style: decimal;
    }
  }
```
2. Check that the above CSS fixes the issue by following the [Contributing Guide](https://github.com/TheOdinProject/theodinproject/wiki/Contributing-Guide)

**Comment by DigitalKnight0** [comment]
@thatblindgeye can i work on this?

**Comment by jmmarco** [comment]
I would like to take this one if possible 🙂

**Comment by thatblindgeye** [comment]
@jmmarco I will assign you, and thank you for attempting to take on the first website contribution!

For context for others who come by, this issue arose from https://github.com/TheOdinProject/curriculum/pull/23402

**Comment by jmmarco** [comment]
@thatblindgeye I got the fix ready but I'm currently finishing an upgrade to Mac OS Monterey (which is taking forever) as soon as it's done, I'll make the pull request.

**Comment by jmmarco** [comment]
Pull request #2575 ready for review 👍
