### ISSUE TITLE
The Odin Project title text color is not orange

### ISSUE THREAD

**Issue by Maheshkumar-novice** [TheOdinProject/theodinproject#2570]
### Description
Color of **The Odin Project** text in the nav bar is black but it was orange before

#### Steps to Reproduce
1. Open the current site
2. In the top nav near the icon we will see the text **The Odin Project** in black color
3. Open this [link](https://web.archive.org/web/20210101152756/https://www.theodinproject.com/) 
4. This shows the color in orange and this color is consistent with the theme also

#### Expected Behavior
1. Open the current site
2. In the top nav near the icon we will see the text **The Odin Project**  in orange color

**Comment by CouchofTomato** [comment]
The colour change is intentional as part of the redesign but thanks for reaching out
