### ISSUE TITLE
Intermediate HTML+CSS Section Card Text Is Overflowing 

### ISSUE THREAD

**Issue by rahulshawdev** [TheOdinProject/theodinproject#2573]
![the-odin-project-issue](https://user-images.githubusercontent.com/82671048/151347027-2d5a956a-946e-4c86-bd4a-19ac1d3ae2ec.png)

### Description
Intermediate HTML+CSS Section Card Text Is Overflowing on mobile devices.

#### Steps to Reproduce
You have to change the height of that card

#### Expected Behavior
It should look good as rest of the cards below.

**Comment by DevlinRocha** [comment]
A potential solution is adjusting the `width` and `max-width`. The minimum to avoid overflow (with the current wording) is 285px. It's currently set to 270px.

**Comment by CouchofTomato** [comment]
Hey. Thanks for raising this issue. We're currently in the middle of a redesign of some parts of the site and this will get picked up in that.
