### ISSUE TITLE
 Add an installation_lesson column to the lessons table in the db

### ISSUE THREAD

**Issue by 01zulfi** [TheOdinProject/theodinproject#2580]
related to #2506

### Task

Add an `installation_lesson` column to the lessons with a boolean value set to false by default

**Comment by KevinMulhern** [comment]
Hey @01zulfi, I have the db changes done: https://github.com/TheOdinProject/theodinproject/pull/2584

I set up a view and marked a couple of foundation lessons as installation lessons to make sure everything is hooked up properly:
 https://odin-feature-set-instal-oea8co.herokuapp.com/lessons/installation_lessons

**Comment by 01zulfi** [comment]
@KevinMulhern Thanks for doing this :rocket: 

Once this PR (#2584) is merged, I'll rewrite the other issues to account for these changes and have more detailed instructions for anyone to pick up.

**Comment by KevinMulhern** [comment]
@01zulfi sounds good 😄 merged and ready to go 🚀 

If you need/want me to help with anything else don't hesitate to reach out mate.
