### ISSUE TITLE
Set the installation_lesson property of the installation lessons as true

### ISSUE THREAD

**Issue by 01zulfi** [TheOdinProject/theodinproject#2581]
related to #2506 

### PR Instruction:

Add the closes keyword in this issue's PR: "closes #XXXX". Replace the X's with this issue's id (2581)

### Task:

Navigate to the directory `db/fixtures/lessons/`.

Find these lessons in the seeds and set their `installation_lesson` property as `true`:

1. Installation Overview (already marked true)
2. Prerequisites (already marked true)
3. Text Editors (already marked true)
2. Setting up git (in foundations)
3. Installing Node.js (in foundations)
4. Installing Ruby (in ruby programming)
5. Installing Rails (in rails programming)

and more lessons if applicable.

**Comment by LeoKirasic** [comment]
Hey, I'd like to take this on!

**Comment by 01zulfi** [comment]
@LeoKirasic Thanks :rocket:
