### ISSUE TITLE
Add an "appendix" link to the footer of the website

### ISSUE THREAD

**Issue by 01zulfi** [TheOdinProject/theodinproject#2583]
related to #2506 

### PR Instruction:

Add this in the PR description to automatically close this issue: "closes #XXXX" (where X's must be replaced with this issue's id i.e 2583)

### Task:

- Navigate to the file `app/views/shared/_footer.html.erb`
- Add a link called "Appendix" between the "Contribute" and "Terms of Use" links
- Make sure to follow the same syntax as the surrounding links
- Use the `lessons_installation_lessons_path` route helper. It will link to the "Installation Lessons Appendix" page on the website
- Make sure it has the class `hover:text-gray-500`

### Note:

If there seems to be a more suitable place to add the link, then that should be preferred over the placement mentioned in the above task

**Comment by DigitalKnight0** [comment]
Can i work on this?

**Comment by 01zulfi** [comment]
@DigitalKnight0 Yes, thanks for taking this on 🚀
