### ISSUE TITLE
Wiki page "Running The Odin Project Locally" displays incorrect ruby version

### ISSUE THREAD

**Issue by jmmarco** [TheOdinProject/theodinproject#2586]
### Description

Wiki page "[Running The Odin Project Locally](https://github.com/TheOdinProject/theodinproject/wiki/Running-The-Odin-Project-Locally)" contains an `rbenv` example code snippet that shows an incorrect ruby version under the section "[Installing Gems and Migrating the Database](https://github.com/TheOdinProject/theodinproject/wiki/Running-The-Odin-Project-Locally#installing-gems-and-migrating-the-database)"

#### Steps to Reproduce

1. Visit the Wiki "[Running TOP Locally](https://github.com/TheOdinProject/theodinproject/wiki/Running-The-Odin-Project-Locally)"
2. Look for the section titled "[Installing Gems and Migrating the Database](https://github.com/TheOdinProject/theodinproject/wiki/Running-The-Odin-Project-Locally#installing-gems-and-migrating-the-database)"
3. Look for the code snippet that sets the Ruby version using `rbenv`

#### Expected Behavior

According to the file [`.ruby-version`](https://github.com/TheOdinProject/theodinproject/blob/main/.ruby-version) it should be `2.7.4` instead of `2.7.3`

Example code snippet should display:
```
rbenv local 2.7.4
```

 #### Additional Information

N/A

**Comment by jmmarco** [comment]
I suspect this might be an easy Wiki edit, however this might only be available to members only.

**Comment by CouchofTomato** [comment]
Thanks. I've updated it.

**Comment by JustWaveThings** [comment]
Maybe we can add an evergreen comment to check the current ruby version with a link to the .ruby-version file in the repo and install that instead of the version listed in the Ruby installation guide.
