### ISSUE TITLE
Missing project submissions in new Intermediate HTML & CSS Module

### ISSUE THREAD

**Issue by StoicScript** [TheOdinProject/theodinproject#2600]
The Sign Up Form & Admin Console Projects are missing project submissions.
All other projects on TOP have project submissions and I think they're of great help for new students who need inspiration or to get unstuck. 

https://www.theodinproject.com/paths/full-stack-javascript/courses/intermediate-html-and-css/lessons/sign-up-form

https://www.theodinproject.com/paths/full-stack-javascript/courses/intermediate-html-and-css/lessons/admin-dashboard

The Personal Portfolio Project is also missing submissions in the Advanced HTML & CSS Module

https://www.theodinproject.com/paths/full-stack-javascript/courses/advanced-html-and-css/lessons/personal-portfolio

**Comment by Ishmam156** [comment]
@thatblindgeye I was looking through the repo yesterday to get a sense of what could solve this and haven't run TOP locally yet. I believe a little change in the lesson fixtures might solve this. 

For example, this is what it looks for a project that has the submission link:

```
'Library' => {
      title: 'Library',
      description: 'Library',
      is_project: true,
      url: '/javascript/organizing-js/library-project.md',
      accepts_submission: true,
      has_live_preview: true,
      identifier_uuid: '67338e32-0121-44bd-98c2-2f8e6b299adf',
    }
```

And this is how it looks like for the intermediate HTML and CSS courses which don't have the view currently:
```
'Sign-up Form' => {
      title: 'Sign-up Form',
      description: 'Learn about how browsers style your HTML.',
      is_project: true,
      url: '/html_css/project-sign-up-form/project-sign-up-form.md',
      identifier_uuid: '91ab41f2-9c9d-449a-8461-329a5f7ecb1e'
    },
```

Hopefully adding `accepts_submission` and `has_live_preview` boolean should make this work from my initial understanding but ofcourse might be missing more nuances here.

I could give it a try to make this work by first running TOP locally and double checking if this is indeed the way forward and I'll also understand if the team feels it better to assign someone who's had experience working with the website repo :)

**Comment by Ishmam156** [comment]
Since it wasn't much work and just wanted to test my own understanding, adding those two booleans made this appear and doesn't seem to have broken anything else in the local install of TOP.

<img width="1186" alt="Screen Shot 2022-02-03 at 8 27 15 PM" src="https://user-images.githubusercontent.com/64395142/152362157-4603aa7f-5903-4305-84de-4a624626bcb4.png">

**Comment by thatblindgeye** [comment]
Very nice! I'm going to assign you @Ishmam156 . Just make sure to follow any other steps for running locally (such as tests and whatnot) and feel free to make a PR when you're ready 🙂
