### ISSUE TITLE
Refactor Lesson completions model spec

### ISSUE THREAD

**Issue by KevinMulhern** [TheOdinProject/theodinproject#262]
This spec needs to be cleaned up to follow best practices.

* Replace factory girl with mocks and stubs
* Test validations and associations with shoulda matchers
* Remove test for "when lesson and student are duplicated"

**Comment by iamjhu** [comment]
I'll take a stab at this. By change, may we make this a Hacktoberfest PR? 😄

**Comment by KevinMulhern** [comment]
Hey @iamjhu yeah no problem, It's all yours 👍 
I'll add the hacktoberfest label
