### ISSUE TITLE
# curriculum-title not responsive

### ISSUE THREAD

**Issue by alamsameer** [TheOdinProject/theodinproject#2624]
### Description

The title of the * Intermediate HTML+CSS* section is coming out of the box in mobile 

![IMG_20220211_085712.jpg](https://user-images.githubusercontent.com/84589782/153533299-dcb3f702-37e3-48c3-8e4d-873e4ab152d6.jpg)

**Comment by CouchofTomato** [comment]
Thanks @alamsameer 

We are aware of this issue but the entire page is currently being rewritten to use tailwind and this will be addressed then.
