### ISSUE TITLE
Navbar issue in dark mode.

### ISSUE THREAD

**Issue by ls-madhu** [TheOdinProject/theodinproject#2627]
### Description
Unnecessary margin and unequal padding on the navbar.

#### Screensot

![navbar_issue](https://user-images.githubusercontent.com/90919727/153699807-4815001e-2c95-49d2-aaad-b3f579d8cc7a.png)

#### Steps to Reproduce

1. Go to any path.
2. Visit any course page.
3. You can see the navbar.

**Comment by Justin-Bento** [comment]
Hey @01zulfi  I think I fixed the issue, in Firefox. I removed the spacing from the Nav added the spacing to the banner section, where should I upload the code? Sorry I am new to this.

![Screenshot from 2022-02-12 10-02-41](https://user-images.githubusercontent.com/44421842/153716488-67173360-b6f1-4c0a-8453-7bdde710aa9f.png)

**Comment by KevinMulhern** [comment]
I'm addressing this in a story I'm working on atm: 

The margin was a temporary solution to get the new navbar in place until we could have a look at replacing the bootstrap container we use on every page. It looked fine on the light theme but I agree it doesn't work well with the dark theme.

To solve this, we'll be Including some top padding on a new container so it's consistent among all pages 😄
