### ISSUE TITLE
Refactor Sections model spec

### ISSUE THREAD

**Issue by KevinMulhern** [TheOdinProject/theodinproject#263]
This model spec needs to be cleaned up to follow best practices.

* Replace factory girl with mocks and stubs
* test associations and validations with shoulda matchers
* Remove test for duplicate positions

**Comment by iamjhu** [comment]
I can take this one, Kevin.

I can hardcode the course id into the course double and added in the necessary tests for the validations and associations. 

However, I'm not exactly sure how to approach the `let(:attrs)  { FactoryGirl.attributes_for(:section) }` though. Any suggestions?

**Comment by arun1595** [comment]
@iamjhu You can replace `FactoryGirl.attributes_for(:section)` with a hash containing the required attributes and their values.

**Comment by iamjhu** [comment]
That's what I was thinking but for whatever reason thought all that hardcoding wasn't the most efficient way to approach it, but then again, I'm probably over thinking it! 😝

**Comment by KevinMulhern** [comment]
It's all yours @iamjhu 😄

**Comment by iamjhu** [comment]
Can we... tag this as.. 🎃 👻  hacktoberfest? 😺

**Comment by KevinMulhern** [comment]
Of course 😄
