### ISSUE TITLE
Strange webpage behaviour on Chrome when restoring tabs

### ISSUE THREAD

**Issue by Funk3** [TheOdinProject/theodinproject#2630]
### Description
Whenever I log into Linux (Ubuntu Budgie 21.10) or Mac (macOS 12 Monterey) from suspend, I will open up Chrome and if I restore a odin project page, the top buttons take up the entire page and I have to manually refresh.

#### Steps to Reproduce
Boot from suspend on Mac or Linux and restore tabs on Chrome.

#### Expected Behavior
Page should load as normal when restoring tabs.

#### Additional comments

I have experienced this again (Feb 14th, 1100 UTC -8) while booting and opening up Chrome. I do have an issue with Chrome where I have to type in my password because the keyring does not have it. Don't know if it's related, wanted to give as much info as possible.

I have only experienced this twice, and both times I have restored my tabs on Chrome. It's a weird issue! I have attached a photo to show what it looks like.

![strange](https://user-images.githubusercontent.com/31976686/153783888-ecd3b269-d40c-41d8-947a-aea93c06e372.png)

**Comment by KevinMulhern** [comment]
Hey @Funk3, Thanks for reporting, it's much appreciated. We've pushed out a fix that should hopefully fix this 😄
