### ISSUE TITLE
Course tile box shadow should not be white for dark mode

### ISSUE THREAD

**Issue by thatblindgeye** [TheOdinProject/theodinproject#2647]
#### Description

PR #2619 recently added a box shadow effect on hover to course tiles (when not logged in). While this works fine on light mode, in dark mode the color used for this box shadow is white. Box shadows should not be white in use cases such as this, and should remain as a dark color.

If the intent is to have the box shadow still stand out against the background, then the background being lightened a bit in addition to changing the box shadow color would be a better alternative. Ultimately, in dark mode this effect is no long a box "shadow", but rather a box "light".

#### Acceptance Criteria:

1. Use the same color for the box shadow in dark mode as is used in light mode

**Comment by TruePadawan** [comment]
_Use the same color for the box shadow in dark mode as is used in light mode_

I don't understand. The current color for the darkmode box shadow (which is the same as lightmode' box shadow) shouldn't be changed? Then that means we should be changing the background color instead or what?

**Comment by thatblindgeye** [comment]
@TruePadawan The dark mode box shadow should be the same color as the light mode box shadow (so the same shade of black). I should actually wait to see what @KevinMulhern has to say and whether this is something that should just be fixed in the Tailwind conversion (since this isn't a *major* issue).

**Comment by jonro2955** [comment]
Hi, I'm new at contributing and this seems like something I'd like to take on as an assignment to the USING GIT IN THE REAL WORLD lesson of the JS track. 

So let me see if I understand the goal here. The box-shadow properties in both modes are currently the same at rgba(0, 0, 0, 0.15), so we just want to change the background color in dark mode only to make the box shadow in dark mode stand out more right? I can see that I can simply change the "--dark-bg-color" variable at the top of the app/assets/stylesheets/dark-mode.css file to make this change. If this is correct, please don't hesitate to assign this issue to me. If I'm wrong, please clarify what I need to do. Thank you.

**Comment by jonro2955** [comment]
Hi, I see that I can resolve this by changing the box-shadow color of the `.curriculum-details-tile:hover` selector in our `dark_mode.css` file to the same color of `rgba(0, 0, 0, 0.05)` that is used for the same selector in the light mode scss file `curriculum_details.scss`. May I be assigned this issue?

**Comment by thatblindgeye** [comment]
@jonro2955 you're assigned!
