### ISSUE TITLE
Dark mode grey text to dark mode dark blue? text

### ISSUE THREAD

**Issue by LeastAntelope** [TheOdinProject/theodinproject#2650]
#### Description
I am proposing to change how some of the text is displayed in dark mode. Currently some of the text shows up as grey, against a black background. This makes it a bit hard to read.  I was thinking maybe dark blue for these pieces of text instead.

#### Acceptance Criteria:
This feature would be accepted universally without any acceptance steps needed.

**Comment by KevinMulhern** [comment]
If the fix can be limited to the [dark mode CSS file](https://github.com/TheOdinProject/theodinproject/blob/main/app/assets/stylesheets/dark-mode.css) I think this will be worth doing. Otherwise, if it requires a lot of changes across the app, it may conflict with the [UI overhaul](https://github.com/TheOdinProject/top-meta/projects/7) we are currently undertaking. We'll be completely redoing the dark mode as part of this project.

**Comment by LeastAntelope** [comment]
> Thanks for reporting this. If the fix can be limited to the [dark mode CSS file](https://github.com/TheOdinProject/theodinproject/blob/main/app/assets/stylesheets/dark-mode.css) I think this will be worth doing. Otherwise, if it requires a lot of changes across the app, it may conflict with the [UI overhaul](https://github.com/TheOdinProject/top-meta/projects/7) we are currently undertaking. We'll be completely redoing the dark mode as part of this project.

I believe it will be limited to a couple lines in a couple places in just the css. But I haven't looked at it yet.

**Comment by LeastAntelope** [comment]
I know exactly how to change the code to get it looking right I believe. that is to add this to the css file.

.profile-card__link,
.skill__sub-title {
  color: var(--dark-font-color);
}

However I'm having quite a bit of trouble getting the site to run locally.  I invite someone else that has the infrastructure already in place to add the code.  I'm going to stop trying to get that running for now. I probably won't try again until I can grasp what ruby is doing and what the problems are.  Which might be a while.
