### ISSUE TITLE
Project submission with white space fails silently solution concept proposal.

### ISSUE THREAD

**Issue by linkonsat** [TheOdinProject/theodinproject#2672]
Complete the following REQUIRED checkboxes:

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `brief description of request` format, e.g. `Add dark mode to website`

The following checkbox is OPTIONAL:

-   [x] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Feature Request:**

Currently, if an individual submits a project solution with whitespace at the beginning or end of a project submission the solution submission will fail silently. I propose we create a flash to let users know when they have entered in white space and in that flash indicate the user needs to make sure there is no whitespace. When the submission occurs I want users to see a flash stating the above info to result in users knowing what exact issue is causing the submission to fail. I am more than happy to take this on as a side project in the interim until the Rails path overhaul occurs. I would just need to do a little bit of research to ensure that flash styling falls in line with the rest of the site.

After further research it appears a flash message already occurs however it could be more descriptive.
**2. Acceptance Criteria:**

**3. Additional Information:**

Source of the conversation where this was mentioned on discord.
https://discord.com/channels/505093832157691914/505093832157691916/947736137697480754

**Comment by KevinMulhern** [comment]
Hey @linkonsat, thanks for making this issue. We could trim whitespace instead of creating a flash. We use [yup](https://github.com/jquense/yup) to validate the submission form fields [here](https://github.com/TheOdinProject/theodinproject/blob/main/app/javascript/components/project-submissions/schemas/project-submission-schema.js). They have a [`trim()` function](https://github.com/jquense/yup#stringtrimmessage-string--function-schema) which should do the job for us.

**Comment by linkonsat** [comment]
That looks perfect. I can take that up and make a PR with that change!

**Comment by KevinMulhern** [comment]
I agree with adding a test case for it, that should catch any regressions in the future.

**Comment by linkonsat** [comment]
Sweet! I'll hop onto that then!

**Comment by linkonsat** [comment]
@KevinMulhern had a question to ask mate. So from reading the yup gem docs it should from my understanding be able to be called like so
~~~
 live_preview_url: yup.string()
    .trim()
    .matches(/^[http]{4}/, { message: 'Url must start with http or https', excludeEmptyString: true })
    .url('Must be a valid URL'),
~~~
this should be called on the string and be trimmed first before the URL and matches validations are run. However, for this test, I added based on how the other tests were built it still says it's an invalid URL.
it { is_expected.to allow_value(' https://www.github.com/fff ').for(:live_preview_url)  }
~~~ 

From my understanding of how the TOP tests are run this still runs it through the schema file that validates the repo URLs. Thus calling trim on the yup.string() should result in that white space being trimmed and removed and allowing it since the trim method is being called on the string _before_ the record is created. Wanted to check and make sure my understanding of yup is correct since google isn't being incredibly helpful of the moment.

**Comment by KevinMulhern** [comment]
Hey @KevinMulhern, the trim in the up schema only applies to the front end. We'll need to test that in these tests: https://github.com/TheOdinProject/theodinproject/blob/main/app/javascript/components/project-submissions/components/__tests__/create-form.test.jsx

If we want to ignore white space in urls when validating on the backend, we can do something like this in the [url validator](https://github.com/TheOdinProject/theodinproject/blob/main/app/validators/url_validator.rb#L8):

```diff
def url_valid?(url)
--url = URI.parse(url) rescue false
++url = URI.parse(url.strip) rescue false
    url.is_a?(URI::HTTP) || url.is_a?(URI::HTTPS)
  end
```

**Comment by linkonsat** [comment]
Ah! Okay i was getting the 'Must be a valid URL' I'm the RSpec failed test so i assumed it must have been running it through the yup file in order to get that message. That's quite interesting. I can go ahead and write it in the frontend end mate! I would rather just get rid of them to make sure the data is more clean. Appreciate it!
