### ISSUE TITLE
Bug: lesson preview does not allow to write more than one alphabet

### ISSUE THREAD

**Issue by swaubhik** [TheOdinProject/theodinproject#2717]
Complete the following REQUIRED checkboxes:

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `Bug: brief description of bug` format, e.g. `Bug: Lesson complete button does not update on click`

The following checkbox is OPTIONAL:

-   [x] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Bug:**

Lesson preview tool if you write and hit preview and if you again go to the write tab it make you wite one alphabet and then stops

**2. How To Reproduce:**

What steps one might need to take in order to reproduce this bug, e.g.:
1. Go to https://www.theodinproject.com/lessons/preview
2. Then write something on the text area
3. Click the preview tab and then again go to the write tab
4. The write tab does not allow you to write more than one alphabet 

**3. Expected Behavior:**

**4. Desktop/Device:**

-   Device: Desktop
-   OS: Windows 11
-   Browser: brave
-   Version: [Version 1.36.112 Chromium: 99.0.4844.51 (Official Build) (64-bit)](https://brave.com/latest/)

**5. Additional Information:**

**Comment by KevinMulhern** [comment]
Thanks for reporting @swaubhik

We recently updated the react tabs dependency https://github.com/TheOdinProject/theodinproject/commit/5b9f5ebf3675d0056c8e33a4203d25caadef6868 it's likely related to that. This PR on the react tabs repo specifically https://github.com/reactjs/react-tabs/pull/448.

**Comment by KevinMulhern** [comment]
This has been resolved
