### ISSUE TITLE
Bug: Links to courses on the homepage do not link properly

### ISSUE THREAD

**Issue by sagapsy** [TheOdinProject/theodinproject#2730]
Complete the following REQUIRED checkboxes:

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `Bug: brief description of bug` format, e.g. `Bug: Lesson complete button does not update on click`

The following checkbox is OPTIONAL:

-   [ ] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Bug:**

In the homepage of The Odin Project, the links that appear in the homepage that are supposed to link to specific contents of the course do not work.

![](https://media.discordapp.net/attachments/540903304046182425/952912250665041950/unknown.png)

![image](https://user-images.githubusercontent.com/99588828/158179465-21d9b53e-7e9e-4120-abad-112705a07dfb.png)

**2. How To Reproduce:**

Click on any of the links(except for Intermediate & Advanced HTML+CSS and Git Basics) for different courses in the homepage of The Odin Project while logged out.

**3. Expected Behavior:**

To open the expected page from the course contents

**4. Desktop/Device:**

-   Device: 
-   OS: 
-   Browser: 
-   Version: 

**5. Additional Information:**

**Comment by KevinMulhern** [comment]
Thanks for reporting @sagapsy 💯 

Sorry @swaubhik, I've already done it here https://github.com/TheOdinProject/theodinproject/pull/2732. We need to get a fix out for this asap since it's on the homepage.
