### ISSUE TITLE
Bug: Progress percentage text not showing when hovering in dark mode

### ISSUE THREAD

**Issue by ArudoPE** [TheOdinProject/theodinproject#2760]
Complete the following REQUIRED checkboxes:

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `Bug: brief description of bug` format, e.g. `Bug: Lesson complete button does not update on click`

The following checkbox is OPTIONAL:

-   [ ] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Bug:**
When you hover over the circle to see your progress percentage, the text doesn't show.
![odin_bug1](https://user-images.githubusercontent.com/74159611/159378308-28ef9f16-7852-4a9a-be2e-851b18c479b9.jpg)

**2. How To Reproduce:**
1. Log in
2. Activate Dark Mode
3. Visit a lesson page
4. Hover over the top circle to see your progress percentage 
5. The progress percentage text doesn't show

**3. Expected Behavior:**
1. Log in
2. Activate Dark Mode
3. Visit a lesson page
4. Hover over the top circle to see your progress percentage 
5. The progress percentage text shows
![odin_bug_fix1](https://user-images.githubusercontent.com/74159611/159378528-7d72ee3b-eafe-4d8a-a73a-e8b220871192.jpg)

**4. Desktop/Device:**

-   Device: Desktop Computer
-   OS: Linux Ubuntu 20.04
-   Browser: Google Chrome
-   Version: 99.0.4844.74 (Official Build) (64-bit)

**5. Additional Information:**
I was able to identify the class with the problem, this element has this class called " .progress-circle__content ", and I added "!important" to the color to affect the text, but this doesn't look like the best solution to this bug.
![odin_bug_attemp1](https://user-images.githubusercontent.com/74159611/159378832-b8ee2713-feec-40eb-85dc-841f45b9ff16.jpg)

**Comment by ArudoPE** [comment]
This also affects the dashboard page, in this case, you don't have to hover, you can't see your progress percentage:
![image](https://user-images.githubusercontent.com/74159611/159380601-72014b22-1ecb-4bdf-b8fe-abeff7c51c9a.png)
**2. How To Reproduce:**

1. Log in
2. Activate Dark Mode
3. Visit  [https://www.theodinproject.com/](https://www.theodinproject.com/)
4. The progress percentage text doesn't show

**Comment by Samuelodan** [comment]
I noticed the exact same issue since last week or so, I hope it gets fixed soon enough.

**Comment by joe-mccann-dev** [comment]
I see Kevin is on top of this, I was playing around and just thought I'd share what I found. Because the percentage display (`class="bold progress-circle__content"`) is contained within a paragraph tag, the following style, applied in dark-mode, is overriding its color:

Toggling this style `p { color: var(--dark-font-color) !important; }` shows what's happening.

If a darker background, e.g. gray, is applied to `.progress-circle__inner` the progress text becomes visible.
