### ISSUE TITLE
Bug: Skill Progress subtext for 'Foundations' path in 'User' dashboard should be removed

### ISSUE THREAD

**Issue by bappyasif** [TheOdinProject/theodinproject#2780]
Complete the following REQUIRED checkboxes:

-   [ ] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [ ] The title of this issue follows the `Bug: brief description of bug` format, e.g. `Bug: Lesson complete button does not update on click`

The following checkbox is OPTIONAL:

-   [ ] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Bug:**

Currently User dashboard for 'Foundations Path' shows this subtext ("The following courses should be taken in order."), even though there is just a 'single course' listed there, taking this out from there would make it more relevant.

current ui snapshot:
![image](https://user-images.githubusercontent.com/19854521/160184052-80bdb4db-abc7-4253-96a3-2be5afd98f57.png)

suggested ui snapshot:
![image](https://user-images.githubusercontent.com/19854521/160184101-771a6061-fa0f-4e89-b964-6a97721bf3ea.png)

**2. How To Reproduce:**

User dashboard for 'Foundations Path"

**3. Expected Behavior:**

Progress skills subtext should not be there as there is just only course enlisted there, please refer to snapshot number two for a visual  representation of that should look instead than it is now(snapshot one)

**4. Desktop/Device:**

-   Device:  notepad
-   OS:  windows 10
-   Browser:  chrome
-   Version:  latest

**5. Additional Information:**

looking to bring this change by myself too, with kevin's supervision, if i may!! discord conversation related to this can be found [here](https://discord.com/channels/505093832157691914/540903304046182425/956920946407669770)

**Comment by KevinMulhern** [comment]
> i assume its this "show.html.erb" file 

Yeah thats right, just an if around the [paragraph element here](https://github.com/TheOdinProject/theodinproject/blob/main/app/views/users/show.html.erb#L16)

> can i try using gitPod instead of installing it locally to see attempted changes?!

I'm not sure, I've never used that service before. I would try setting it up locally, I can help if you run into any issues but I won't be able to help with any issues encountered with gitpod due to lack of familiarity.

**Comment by bappyasif** [comment]
> Yeah thats right, just an if around the [paragraph element here](https://github.com/TheOdinProject/theodinproject/blob/main/app/views/users/show.html.erb#L16)

how do i access 'course' name in that 'if' statement, im guessing something like this (' :course ')?!

> I'm not sure, I've never used that service before. I would try setting it up locally, I can help if you run into any issues but I won't be able to help with any issues encountered with gitpod due to lack of familiarity.

im using 'windows 10' now, as my VM for some reason became way too much memory heavy, so much so that my terminal keeps freezing over frequently!! so, i suppose my question would be, is there any [guides](https://github.com/TheOdinProject/theodinproject/wiki/Running-The-Odin-Project-Locally) for installing it in windows10 or its generic for all platforms

thanks again @KevinMulhern for looking into this, much appreciated

looking forward to commit this with a fix soon

**Comment by KevinMulhern** [comment]
> how do i access 'course' name in that 'if' statement, I'm guessing something like this (' :course ')?!
 
You'll have access to the current user and through that their path and how many courses it contains, something like this:
`current_user.path.courses.size > 1`

We don't have any guides for Windows unfortunately, only mac and linux(ubuntu).

**Comment by bappyasif** [comment]
oh well, lets just focus on writing code for now to fix this, maybe i'll try again to revive my vm or wsl to run top repo locally

im considering to try this, as a fix, `<% current_user.path.courses.size > 1 ?  'The following courses should be taken in order' : null %>`

would that be enough, or should i just stick to 'if' conditionals strictly

thanks again @KevinMulhern for looking into this, much appreciated
