### ISSUE TITLE
Bug:  chapters link gets darker when clicked, while in dark mode!!

### ISSUE THREAD

**Issue by bappyasif** [TheOdinProject/theodinproject#2807]
Complete the following REQUIRED checkboxes:

-   [ ] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [ ] The title of this issue follows the `Bug: brief description of bug` format, e.g. `Bug: Lesson complete button does not update on click`

The following checkbox is OPTIONAL:

-   [ ] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Bug:**

chapters links from 'course' after 'clicking' gets 'darker' in 'dark mode', and stays that same until user 'clicks' again elsewhere on that page to get it's 'yellowish' font color back 'in view'
![image](https://user-images.githubusercontent.com/19854521/161397803-f1322a7e-aa9c-445a-8bc2-78d337839842.png)

**2. How To Reproduce:**

https://www.theodinproject.com/paths/foundations/courses/foundations => click on any chapters => you should be seeing that in your browser, that 'darkened color' chapter link text

**3. Expected Behavior:**

it should be visible enough, so that it doesn't seem bit surprising!!

**4. Desktop/Device:**

-   Device:  notebook / notepad
-   OS:  windows 10
-   Browser:  chrome
-   Version:  latest

**5. Additional Information:**

related conversation regarding this on discord server can be found [here](https://discord.com/channels/505093832157691914/540903304046182425/959868278623322122)

**Comment by ArudoPE** [comment]
I think this is already reported on issue #2587:
"We're in the middle of a major rewrite of the site's CSS and will be fixing this alongside it."

_Originally posted by @KevinMulhern in https://github.com/TheOdinProject/theodinproject/issues/2587#issuecomment-1027206778_

**Comment by bappyasif** [comment]
@ArudoPE i had a feeling, it must have been reported before!! but couldn't find it from 'open' issues, that why i opened this, should i just simply close it then?!

**Comment by ArudoPE** [comment]
> @ArudoPE i had a feeling, it must have been reported before!! but couldn't find it from 'open' issues, that why i opened this, should i just simply close it then?!

Yes, that would be a good idea, to avoid having a duplicate report.

**Comment by bappyasif** [comment]
closing as duplicated [issue](https://github.com/TheOdinProject/theodinproject/issues/2587)
