### ISSUE TITLE
Cuke test for user editing his/her profile

### ISSUE THREAD

**Issue by arun1595** [TheOdinProject/theodinproject#281]
In order to update my information
As a learner
I want to be able to edit my profile

**Comment by Evans-Munatsa** [comment]
l'm in for the assignment, and l also need more info.  Please let me know as soon as possible

**Comment by KevinMulhern** [comment]
Hey @evanburkey, have you written any cucumber tests before? 😄

**Comment by evanburkey** [comment]
@KevinMulhern I'm pretty sure you meant @Evans-Munatsa not me :laughing:

**Comment by KevinMulhern** [comment]
@evanburkey yip sorry 😄 
@Evans-Munatsa see above please 👍

**Comment by Evans-Munatsa** [comment]
@KevinMulhern yes l have written cucumber tests before

**Comment by arun1595** [comment]
@Evans-Munatsa Cool. Work on it and submit a PR :)

**Comment by KevinMulhern** [comment]
Its all yours @Evans-Munatsa let us know if you need for information about anything

**Comment by KevinMulhern** [comment]
Hey @Evans-Munatsa have you started this?

**Comment by Evans-Munatsa** [comment]
yes l have started, l'm have started but just having trouble pushing because of my remote branch, and l have also notice when l run the cucumber command that some of the tests are failing

**Comment by Evans-Munatsa** [comment]
hey guys l can't push its giving me this error 

remote: Permission to TheOdinProject/theodinproject.git denied to Evans-Munatsa.
fatal: unable to access 'https://github.com/TheOdinProject/theodinproject.git/': The requested URL returned error: 403

**Comment by arun1595** [comment]
You can't push to the OdinProject repository unless you have write access. You should fork the repo and clone it locally, make some changes, push the code to your fork and then submit a Pull Request. 

If you don't understand what I mean, please watch [this](https://www.youtube.com/watch?v=mENDYhfxH-o) video.

Thanks!

**Comment by KevinMulhern** [comment]
Hey @Evans-Munatsa please follow Arun's suggestion to push create a PR. Which tests are failing? everything is green on master.
