### ISSUE TITLE
Project: HTML/CSS - View in browser links are misleading/broken

### ISSUE THREAD

**Issue by jacob-on-github** [TheOdinProject/theodinproject#283]
Working on the project at: http://www.theodinproject.com/courses/web-development-101/lessons/html-css, I noticed that most of the "View in browser" links do not work.

It seems like most of the ones that don't work are GitHub repos in which "htmlpreview.github.io" is not functioning correctly. Maybe the documentation/method for how to share your solution needs to be updated?

**Comment by KevinMulhern** [comment]
Hey @jacob-on-github, this must be something broken on the htmlpreview.github side. The latest solutions previews are broken too and this is the first report of this problem. Which makes me think this problem has only started in the past day or two.

We will give it a couple of days to see if this problem resolves itself and take it from there if it doesn't.

Thanks for reporting this 😄

**Comment by jacob-on-github** [comment]
Just to note: This looks it is working again.
