### ISSUE TITLE
Chore: Upgrade to Latest Version of Ruby

### ISSUE THREAD

**Issue by KevinMulhern** [TheOdinProject/theodinproject#2860]
**1. Acceptance Criteria:**
The App is running on the latest version of Ruby - 3.1.2

**3. Additional Information:**

Our CI ruby image will also need to be updated: https://github.com/TheOdinProject/theodinproject/blob/main/.circleci/config.yml#L7

**Comment by ChargrilledChook** [comment]
Happy to take this one on 🤙

**Comment by ChargrilledChook** [comment]
@KevinMulhern Are you happy to go straight from 2.7 to 3.1 in a single PR? 

I can do the intermediate step of updating to 3.0 and checking deprecation warnings first, or we could upgrade to 3.0, let it sit for a week, and then complete the upgrade to 3.1. Happy to go with whatever you think is best.

**Comment by KevinMulhern** [comment]
Happy to go with the intermediary approach you've suggested @ChargrilledChook 💪

**Comment by ChargrilledChook** [comment]
Not an issue for Ruby 3, but for 3.1, `circleci` Ruby images are deprecated.

They are recommending the use of `cimg` instead, but the structure looks slightly different - there only appear to be node or browser versions, not both. I'm unsure what other changes might be required here, so I'd appreciate some guidance here for the best approach.

There is some information here about the changes from `circleci` to `cimg` [link](https://circleci.com/docs/2.0/next-gen-migration-guide/) - seems node is now included in browser versions, but specific browsers are not. May require more config changes.

New `cimg` Ruby images [here](https://circleci.com/developer/images/image/cimg/ruby?utm_source=google&utm_medium=sem&utm_campaign=sem-google-dg--japac-en-dsa-maxConv-auth-brand&utm_term=g_-_c__dsa_&utm_content=&gclid=Cj0KCQjwgYSTBhDKARIsAB8KukukSXbzP4VoFOIKda5OCmdQfX4IXtI9Jtden7p6Py4XYZrCK7Kr6Q4aAiRwEALw_wcB#image-name)

**Comment by ChargrilledChook** [comment]
PR for Ruby 2.7 -> 3.0 https://github.com/TheOdinProject/theodinproject/pull/2861

**Comment by KevinMulhern** [comment]
Thanks for the detailed write-up and links @ChargrilledChook, this is brilliant!

We need the chrome driver for system tests, I think we'll need the browsers version of the ruby image as well as the browser-tools orb with the [chrome install](https://circleci.com/developer/orbs/orb/circleci/browser-tools#usage-install_browsers).

**Comment by ChargrilledChook** [comment]
@KevinMulhern  Outside of needing to tweak the CI config, there have been a few minor hiccups for 3.0 -> 3.1:

A handful of gems were removed from the core library and need to be explicitly declared - there's a fix for this in Rails 7.0.1 but I've simply added them manually in the meantime. [More info](https://stackoverflow.com/questions/70500220/rails-7-ruby-3-1-loaderror-cannot-load-such-file-net-smtp)

I've had to manually bump the bundler version to fix a deprecation warning. [More info](https://github.com/rubygems/rubygems/issues/5234)

There are two new features in Ruby 3.1 that have upset Rubocop and need some bike shedding:

```ruby
# Now prefers shorthand syntax when assigning hash values
# Bad 
hash = { a: a, b: b }

# Good 
hash = { a:, b:, }

# Now prefers use of anonymous block forwarding
# Bad
def some_method(arg, &block); end

# Good
def some_method(arg, &); end
```
Both are safely auto-correctable, so I think we can go either way (fix the offenses or turn off the rule) without any drama. 

Once I've fixed up the CI with the new format and we make a decision on Rubocop, I think it should be good to go :muscle:

**Comment by KevinMulhern** [comment]
Hey, @ChargrilledChook, thanks for another detailed write-up. Autocorrecting those sounds great to me mate. Excited to get that hash shorthand syntax available in the app. That's always been an annoyance when switching between JS and Ruby for me 😆

**Comment by ChargrilledChook** [comment]
PR for part 2: https://github.com/TheOdinProject/theodinproject/pull/2882

I've never used Circleci before working on this so let me know my changes to the config are kosher. I did my best to follow the example [here](https://circleci.com/developer/orbs/orb/circleci/browser-tools)
