### ISSUE TITLE
Easy Fix: Duplication in FAQ, under Which technologies...

### ISSUE THREAD

**Issue by tommaho** [TheOdinProject/theodinproject#2891]
Complete the following REQUIRED checkboxes:

-   [ x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [ x] The title of this issue follows the `Bug: brief description of bug` format, e.g. `Bug: Lesson complete button does not update on click`

The following checkbox is OPTIONAL:

-   [ ] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Bug:**

https://www.theodinproject.com/faq

Under 'Which Technologies can one expect to learn from the Odin Project', the paragraph starting with 'The Full Stack Javascript path...' appears twice.

**2. How To Reproduce:**

Visit the FAQ:

https://www.theodinproject.com/faq

Expand the 'Which technologies..' accordion.

**3. Expected Behavior:**

The second instance of this paragraph appears to be a duplication. 

**4. Desktop/Device:**

-   Device: 
-   OS: 
-   Browser: 
-   Version: 

**5. Additional Information:**

**Comment by afkus3r** [comment]
I would like to work on this issue

**Comment by afkus3r** [comment]
I'm available to work on this issue

**Comment by KevinMulhern** [comment]
Thanks @afkus3r, I've assigned to you.
