### ISSUE TITLE
Reorder links on Installation Lessons Appendix page

### ISSUE THREAD

**Issue by mothodical** [TheOdinProject/theodinproject#2903]
Complete the following REQUIRED checkboxes:

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `brief description of request` format, e.g. `Add dark mode to website`

The following checkbox is OPTIONAL:

-   [x] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Feature Request:**

This enhancement will reorder the links on Installation Lessons Appendix (https://www.theodinproject.com/lessons/installation_lessons) FROM the following order with no section titles:

Installing Rails
Prerequisites
Text Editors
Installing Ruby
Installing Node.js
Setting Up Git
Installation Overview

TO the following order, with added section titles:

[section title] Foundations Path:
Installation Overview
Prerequisites
Text Editors
Setting Up Git

[section title] Ruby on Rails Path:
Installing Ruby
Installing Rails

[section title] Javascript Path:
Installing Node.js

This will provide more structure to the seemingly-random order that is currently present.

**2. Acceptance Criteria:**

**3. Additional Information:**

**Comment by mothodical** [comment]
I finally have TOP running locally on my machine, so I can work on this once assigned :)

**Comment by KevinMulhern** [comment]
Sorry for the delay @mothodical, you've been assigned 😄
