### ISSUE TITLE
All Projects: Default option to order submissions by latest submitted

### ISSUE THREAD

**Issue by ashoofly** [TheOdinProject/theodinproject#2948]
Complete the following REQUIRED checkboxes:
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `location for request: brief description of request` format, e.g. `NodeJS course: Add lessons on XYZ`

The following checkbox is OPTIONAL:

-   [x] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Feature Request:**

Currently, project submissions can be seen only in order of highest rated. 
The most recent project I looked at had 65 pages of submissions. 
It seems like the most recent project submissions will all go to the last page with 0 votes, and will most likely not be seen.
My guess is that the highest rated projects are old projects?

It seems valuable to be able to sort projects by most recently added, so we can see the most recent ones more easily.

**2. Acceptance Criteria:**

- [ ]  Dropdown option in project submission list to sort by Most Recently Submitted
- [ ] Perhaps have this be the default option? Not sure. 

**3. Additional Information:**

Please let me know if any of the assumptions I've made here are incorrect, or if this has been discussed before.

Also, I checked the box that I was interested in working on it, but I probably wouldn't be able to work on it for some time, so if anyone else wanted to pick it up, that would be fine too. 

Thank you!

**Comment by KevinMulhern** [comment]
Thanks for the suggestion @ashoofly; this is something we've talked about quite a bit internally.

Instead of defaulting to one specific order, I think we should give users the option to sort by different attributes.

Off the top of my head, we could have these sort options:
* Most liked
* Least Liked
* Newest
* Oldest

The design would be the blocker for this one as well. I'll talk to our designer and update this issue when I know more.

**Comment by binarygit** [comment]
Hello! 
This looks like something I can handle. After the designs have been finalized, could you give me a ping @KevinMulhern? I could take it up if nobody else is available.

**Comment by KevinMulhern** [comment]
Will do @binarygit, it may be a while though. Summertime is usually a bit slower with everyone taking time off/vacationing.

**Comment by binarygit** [comment]
That's alright. I'll be around.

**Comment by KevinMulhern** [comment]
Thanks again for for the suggestion @ashoofly. We're finally getting [this underway](https://github.com/TheOdinProject/theodinproject/issues/4222) 🚀
