### ISSUE TITLE
Feature: Add "seed curriculum" button to admin

### ISSUE THREAD

**Issue by ChargrilledChook** [TheOdinProject/theodinproject#2992]
### Description
This will be useful when we need to add new lessons to the site and want to test them via review apps. Currently to get the review app's to reseed lesson content we either have to do it manually through the console on Heroku or destroy and recreate the review app. Having a button to do it, will cut down on a lot of time and effort.

### Acceptance Criteria
1. Remove content for a lesson using the rails console
1. Visit the lesson - it should throw an error screen
1. Go to admin
1. Click on "Seed Curriculum" button on the dashboard
1. Wait about a minute
1. Visit the lesson again - it should load it's content

### Additional Information
The lesson content import service can be used to important content, but will need to be run async within a background job as it will take a while to complete and there is a strict 30 second response timeout on Heroku.

**Comment by ChargrilledChook** [comment]
@KevinMulhern I'm reasonably comfortable with background jobs so can have a crack at this one.

To clarify, do we want to run `db:seed` (or the live equivalent) as well as the curriculum import, or just the latter?

**Comment by KevinMulhern** [comment]
Ahh sorry @ChargrilledChook, I should have been clearer with the title/description of this. We just need to import the content with the button.No need to do a `db:seed`.
