### ISSUE TITLE
Separate out form lessons to their own section in Intermediate HTML/CSS

### ISSUE THREAD

**Issue by thatblindgeye** [TheOdinProject/theodinproject#3009]
Complete the following REQUIRED checkboxes:

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `brief description of request` format, e.g. `Add dark mode to website`

The following checkbox is OPTIONAL:

-   [ ] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Feature Request:**

Related to issue https://github.com/TheOdinProject/curriculum/issues/23639

The Intermediate HTML/CSS course should be restructured to the following format:

1. Intermediate HTML Concepts
    - Same lessons as-is, except Form Basics and Form Validations are removed
2. Intermediate CSS Concepts
    - Same lessons as-is, except the Project is removed
4. Forms
    - Form Basics
    - Form Validations
    - Project: Sign-up Form
5. Grid

**2. Acceptance Criteria:**

- [ ] Form lessons are removed from their current location within the Intermediate HTML/CSS course
- [ ] A new section within Intermediate HTML/CSS called Forms is added, and all form lessons + Sign Up Form project are moved there

**3. Additional Information:**

**Comment by ChargrilledChook** [comment]
@thatblindgeye Were you planning on putting this out for public contributions, or would you like me to whip it out?

A new section will also require some new copy for the tagline ie 

""Forms are a crucial building block of web dev for getting input from your users. In this section you'll learn the basics and get some hands on practice."

as a rough first sketch

**Comment by thatblindgeye** [comment]
@ChargrilledChook Either would work! I just put the help wanted tag in case, but if you'd want to tackle it definitely feel free. As for the copy, tweaking your rough sketch:

"Forms are a crucial building block for getting input from your users. In this section you'll learn some of the basics you'll need to create a functioning form."

Mainly removing the "web dev" bit to make it a bit more general, with some slight verbiage tweaks. Also a rough first sketch, though 😆

**Comment by binarygit** [comment]
Hey! I was looking for a issue to work on. If it's ok with @ChargrilledChook I could take this on!
