### ISSUE TITLE
Chore: Decide what to do about Webpacker

### ISSUE THREAD

**Issue by KevinMulhern** [TheOdinProject/theodinproject#3017]
Do we go to the effort of upgrading to Webpacker 6.X.X or switch to something like esbuild which should be faster?

**Comment by CouchofTomato** [comment]
The options are outlined [here](https://github.com/rails/jsbundling-rails/blob/main/docs/switch_from_webpacker.md) and should be pretty easy to spike either jsbundling or shakapacker to get webpacker working with webpack 5
