### ISSUE TITLE
Bug: Project submissions buttons at dashboard break for projects with long names

### ISSUE THREAD

**Issue by liridonloku** [TheOdinProject/theodinproject#3018]
Complete the following REQUIRED checkboxes:

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `Bug: brief description of bug` format, e.g. `Bug: Lesson complete button does not update on click`

The following checkbox is OPTIONAL:

-   [ ] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Bug:**

On the user dashboard at the bottom of the page where user submissions are listed, if a projects name is too long it makes the buttons lose their shape. See screenshot below:
![project-submissions-dashboard](https://user-images.githubusercontent.com/88339082/175834163-a36b2e77-9fc8-4bf3-a6af-516bf213fdc3.jpeg)

As far as I can tell, this happens only with 'Where's waldo' for the NodeJS path.

**2. How To Reproduce:**
1. Log in
2. Go to NodeJS path, project Where's Waldo
3. Mark the project as done and add links for code and live preview
4. Go to the dashboard and scroll down to the project submissions

**3. Expected Behavior:**
The buttons shape should be consistent no matter how long the projects name is.

**4. Desktop/Device:**
- Device: Laptop (15.6", 1080p)
- OS: Linux (ZorinOS)
- Browser: Brave 
- Version: 1.40.107 (June 24th, 2022)

**5. Additional Information:**
I tried giving the div that holds the buttons the property `flex-shrink: 0` and the div that holds the projects name `flex-shrink: 1`, and it seems to fix the issue. But I haven't tested it on different screen sizes.

**Comment by KevinMulhern** [comment]
Thanks for reporting @liridonloku 💪 

The react components for submissions were recently switched over to fully use Tailwind. This is probably just a hangover from that.

**Comment by ChargrilledChook** [comment]
Seems to be resolved via recent Tailwind fixes
![image](https://user-images.githubusercontent.com/58506115/195719797-9dbaa683-a439-4061-9aa6-ad5e552b6707.png)
