### ISSUE TITLE
Chore: Investigate Ignoring User Generated JS Errors in Sentry

### ISSUE THREAD

**Issue by ChargrilledChook** [TheOdinProject/theodinproject#3048]
### Description
We have been seeing quite a few JS errors that appear to be from users causing errors in the web inspector console. There may be a way of filtering these out by implementing the ignore rules here: https://docs.sentry.io/clients/javascript/tips/

Example:
https://sentry.io/organizations/the-odin-project-web-app/issues/3028197428/events/efd51eef95364dde981c3729edae3fc4/?project=5721923

### Additional Information
We never used to see so much of these, something may have changed in a recent update to the Sentry JS package.

**Comment by ChargrilledChook** [comment]
Did a little bit of a look, found some recommendations to filter out JS noise [here](https://blog.sentry.io/2017/03/27/tips-for-reducing-javascript-error-noise)

The suggestion to turn on [data filters](https://blog.sentry.io/2016/09/14/reduce-noise-inbound-data-filters) is very straightforward but needs admin permissions.

Can find the relevant part of the settings [here](https://sentry.io/settings/the-odin-project-web-app/projects/the-odin-project/filters/data-filters/)

There's other suggestions in the first article that may be worth exploring too

**Comment by KevinMulhern** [comment]
Thanks for finding that data filters suggestioin @ChargrilledChook. I enabled it all, I have noticed quite a few errors from a handful of Opera users so this should have a decent impact.
<img width="1166" alt="Screenshot 2022-07-02 at 14 30 42" src="https://user-images.githubusercontent.com/7963776/177003024-26838346-6dec-4ede-88a1-a63bef381967.png">

**Comment by KevinMulhern** [comment]
Been doing a bit more digging https://github.com/getsentry/sentry-javascript/issues/5179

We could wait for the Chromium fix to roll out or try implementing some of those workarounds.

**Comment by ChargrilledChook** [comment]
@KevinMulhern Do you have a preference for the workaround options? 3 seems like a pretty easy to implement and reverse fix, I'm not sure there's a ton of value in those errors regardless of browser

```js
// app/javascript/packs/error_tracking.js - quick pass at implementing their suggestion
import * as Sentry from '@sentry/browser';

const {
  SENTRY_DSN, currentUserLoggedIn, currentUserId, currentUserEmail,
} = window;

Sentry.init({
  dsn: SENTRY_DSN,
  environment: 'production',
  allowUrls: [
    /https?:\/\/(www\.)?theodinproject\.com/,
  ],
  ignoreErrors: [
    'Possible side-effect in debug-evaluate',
    'Unexpected end of input',
    'Invalid or unexpected token',
    'missing ) after argument list',
  ],
});
