### ISSUE TITLE
Chore: Update Oauth2

### ISSUE THREAD

**Issue by ChargrilledChook** [TheOdinProject/theodinproject#3057]
**Because**
Our current version (1.x) has reached EOL and is no longer supported. 

**Acceptance Criteria**
- [ ] The app is using oauth2 and there are no deprecation warnings

**Notes**

`bundle outdated` can be used to  check gems that are out of date. Adjacent gems (ie GitHub / Google Oauth) should be checked too.

Deprecation warning:
```
Post-install message from oauth2:

You have installed oauth2 version 1.4.10, which is EOL.
No further support is anticipated for the 1.4.x series.

OAuth2 version 2 is released.
There are BREAKING changes, but most will not encounter them, and upgrading should be easy!

Please see:
• https://github.com/oauth-xx/oauth2#what-is-new-for-v20
• https://github.com/oauth-xx/oauth2/blob/master/CHANGELOG.md

Please upgrade, report issues, and support the project! Thanks, |7eter l-|. l3oling
```

**Comment by JacobMarq** [comment]
@ChargrilledChook I would like to take on this chore if possible!

**Comment by ChargrilledChook** [comment]
Hi @JacobMarq, thanks for your interest, I've assigned it to you.

It's possible that this is blocked by other dependencies since we aren't directly using Oauth2, but it won't hurt to try updating the relevant gems. Let me know if you have any questions or problems.

**Comment by ChargrilledChook** [comment]
@JacobMarq Thanks for investigating this for us. The pace of changes on that gem seemed to have slowed right down, so perhaps longer term we may need to look at an alternative.

Good idea checking the source, I'll put your PR here so we can keep some visibility on it
https://github.com/zquestz/omniauth-google-oauth2/pull/428

**Comment by JacobMarq** [comment]
Update on more recent PR to allow compatibility up to v2.0.6 of Oauth2. There was a small mistake but the owner has officially acknowledged the PR and is preparing to merge after correction: (already corrected now) 
[zquestz/omniauth-google-oauth2#429](https://github.com/zquestz/omniauth-google-oauth2/pull/429)

**Comment by ChargrilledChook** [comment]
@JacobMarq Thanks for following that up, awesome work getting a result from the Oauth maintainer. Did you want to open a PR to  update Oauth here?

**Comment by ChargrilledChook** [comment]
```
Post-install message from oauth2:

You have installed oauth2 version 1.4.11, which is EOL.
No further support is anticipated for the 1.4.x series.

OAuth2 version 2 is released.
There are BREAKING changes, but most will not encounter them, and upgrading should be easy!

We have made two other major migrations:
1. master branch renamed to main
2. Github has been replaced with Gitlab

Please see:
• https://gitlab.com/oauth-xx/oauth2#what-is-new-for-v20
• https://gitlab.com/oauth-xx/oauth2/-/blob/main/CHANGELOG.md
• https://groups.google.com/g/oauth-ruby/c/QA_dtrXWXaE

Please upgrade, report issues, and support the project! Thanks, |7eter l-|. l3oling
```
