### ISSUE TITLE
Bug: Dark Mode colour inconsistency on Login Form

### ISSUE THREAD

**Issue by vndrewhk** [TheOdinProject/theodinproject#3068]
Complete the following REQUIRED checkboxes:

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `Bug: brief description of bug` format, e.g. `Bug: Lesson complete button does not update on click`

The following checkbox is OPTIONAL:

-   [x] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Bug:**

When using dark mode, the login form does not have consistent styling on certain elements that should be expected for dakr mode, or elements with low contrast colours, leading to possible accessibility issues.

<img width="486" alt="Screen Shot 2022-07-07 at 10 47 01 AM" src="https://user-images.githubusercontent.com/76503039/177804463-e55917c1-852e-4146-abe3-d62cf13a3ef0.png">
<img width="532" alt="Screen Shot 2022-07-07 at 10 47 52 AM" src="https://user-images.githubusercontent.com/76503039/177804475-537b7406-ce88-4685-86ad-abf41c172046.png">

**2. How To Reproduce:**

1. Enable Dark Theme
2. Click on Login Form

**3. Expected Behavior:**

1. Enable Dark Theme
3. Click on Login form
4. View correct/accessible styling on components

**4. Desktop/Device:**

- Device: Macbook Pro 2015, PC
- OS: iOS, Windows 11, Xubuntu
- Browser: Chrome

**5. Additional Information:**

**Comment by ChargrilledChook** [comment]
Hi @vndrewhk , cheers for the report. We're currently making a number of improvements to the site's design and updating the CSS to use Tailwind - this should be covered by the work being done there. Thanks for letting us know!

**Comment by ChargrilledChook** [comment]
Solved by recent rework of forms
