### ISSUE TITLE
New Footer

### ISSUE THREAD

**Issue by KevinMulhern** [TheOdinProject/theodinproject#3093]
### Why?
We have been adding more ancillary pages lately like the [Installations Appendix](https://www.theodinproject.com/lessons/installation_lessons) and have more planned. 

The current footer links to these pages along the bottom, but this space will soon run out:
![Image](https://user-images.githubusercontent.com/7963776/176905910-3bd8c1ec-80c4-4626-80e1-612e037834b5.png)

We could maybe use the cta space for links instead:

![Image](https://user-images.githubusercontent.com/7963776/176906656-878466f2-6e81-4c2e-875c-9c610f1eafe5.png)

Some ideas from TailwindUI
https://tailwindui.com/components/marketing/sections/footers#component-de25869ecf8c2903fbede9b3a7602adb
https://tailwindui.com/components/marketing/sections/footers#component-38c15f2c35def7c2c555175450d1448e

**Comment by adachiu** [comment]
Consider adding Open Source logo

**Comment by KevinMulhern** [comment]
During the meeting this kind of layout is what we thought would be best. It's close to what we have already, the right cta on our current footer would just be replaced with columns for links.

<img width="1452" alt="Screenshot 2022-07-16 at 22 49 05" src="https://user-images.githubusercontent.com/7963776/179372884-f03e5c7a-e7c2-4064-b1ac-6b556626f6cd.png">

**Comment by bestbuereland** [comment]
am in for this let get it done
