### ISSUE TITLE
[DARK MODE]Change the font color of input fields from Upload Your Project form card

### ISSUE THREAD

**Issue by VenkaSri** [TheOdinProject/theodinproject#3138]
Complete the following REQUIRED checkboxes:

-   [ x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x ] The title of this issue follows the `brief description of request` format, e.g. `Add dark mode to website`

The following checkbox is OPTIONAL:

-   [ x] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Feature Request:**

When in dark mode the inputted text colour is too dark. Making a little bit brighter would emphasize what the user has entered. Even the icon are dark.

<img width="655" alt="Screen Shot 2022-07-26 at 2 53 49 PM" src="https://user-images.githubusercontent.com/53845532/181088706-253edc93-b8d4-414a-9d9f-31c24c25c7f9.png">

**2. Acceptance Criteria:**

Making a font colour more bright. 
<img width="640" alt="Screen Shot 2022-07-26 at 2 59 33 PM" src="https://user-images.githubusercontent.com/53845532/181089826-9eec8448-248c-4c31-a253-282fe992b424.png">
The above image after I added color: grey to that property, it makes it stand out.

**3. Additional Information:**

**Comment by GabrielRuizVarela** [comment]
Can i work on this?

**Comment by KevinMulhern** [comment]
@VenkaSri do you still want to work on this one or would you mind if @GabrielRuizVarela worked on it?

**Comment by VenkaSri** [comment]
@KevinMulhern I would like to make a contribution, is that okay?

**Comment by KevinMulhern** [comment]
@VenkaSri yeah it's all yours
