### ISSUE TITLE
Bug: Broken formatting on Markdown preview and How to Ask Pages

### ISSUE THREAD

**Issue by scheals** [TheOdinProject/theodinproject#3169]
Complete the following REQUIRED checkboxes:

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `Bug: brief description of bug` format, e.g. `Bug: Lesson complete button does not update on click`

The following checkbox is OPTIONAL:

-   [] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Bug:**

It seems like some of the pages are not rendering the Markdown correctly. One of them is How to Ask article and the other is the Markdown preview itself.

**2. How To Reproduce:**
What steps one might need to take in order to reproduce this bug, e.g.:
1. Log in
2. Visit [How to Ask page](https://www.theodinproject.com/how_to_ask)
3. Scream in horror

**3. Expected Behavior:**
A brief description of what you expected to happen, e.g.:
1. Log in
2. Visit [How to Ask page](https://www.theodinproject.com/how_to_ask)
3. Page is correctly formatted

**4. Desktop/Device:**

-   Device: PC
-   OS: Windows 10
-   Browser: Firefox
-   Version: 103.0.1 (64-bit)

**5. Additional Information:**

https://www.theodinproject.com/lessons/preview also previews content the same way the How to Ask page renders.

**Comment by KevinMulhern** [comment]
Thanks for reporting @scheals 💪
