### ISSUE TITLE
Bug: Section on table of contents of SVG lesson doesn't lead to anything

### ISSUE THREAD

**Issue by arco-web** [TheOdinProject/theodinproject#3177]
Complete the following REQUIRED checkboxes:

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `Bug: brief description of bug` format, e.g. `Bug: Lesson complete button does not update on click`

The following checkbox is OPTIONAL:

-   [ ] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Bug:**

When clicking on the "What are bugs?" section of the the table of contents of [Intermediate HTML and CSS/SVG](https://www.theodinproject.com/lessons/node-path-intermediate-html-and-css-svg), it does not link to anything; The 

**2. How To Reproduce:**
What steps one might need to take in order to reproduce this bug, e.g.:
1. Log in
2. Visit the [Full Stack Javascript path](https://www.theodinproject.com/paths/full-stack-javascript)
3. Visit the [Intermediate HTML and CSS Course](https://www.theodinproject.com/paths/full-stack-javascript/courses/intermediate-html-and-css)
4. Visit the [SVG](https://www.theodinproject.com/lessons/node-path-intermediate-html-and-css-svg) lesson
5. Click on "What are SVGs?" on the table of contents
6. You're not autoscrolled to the [What are SVGs](https://www.theodinproject.com/lessons/node-path-intermediate-html-and-css-svg#what-are-svgs) section

**3. Expected Behavior:**
A brief description of what you expected to happen, e.g.:
1. Log in
2. Visit the [Full Stack Javascript path](https://www.theodinproject.com/paths/full-stack-javascript)
3. Visit the [Intermediate HTML and CSS Course](https://www.theodinproject.com/paths/full-stack-javascript/courses/intermediate-html-and-css)
4. Visit the [SVG](https://www.theodinproject.com/lessons/node-path-intermediate-html-and-css-svg) lesson
5. Click on "What are SVGs?" on the table of contents
6. You get autoscrolled to the [What are SVGs](https://www.theodinproject.com/lessons/node-path-intermediate-html-and-css-svg#what-are-svgs) section

**4. Desktop/Device:**

-   Device: PC
-   OS: Arch Linux (2022.08.05)
-   Browser: Firefox
-   Version: 103.0.1 (64-bit)

**5. Additional Information:**

- The section on the table of contents doesn't lead to anything because it leads to **#what-are-sv-gs** rather than **#what-are-svgs**
- This seems like an isolated case (A typo perhaps, or an accidental space between sv and gs which generates a dash when the id is generated)

**Comment by xandora** [comment]
Should be resolved in #3176.
