### ISSUE TITLE
Bug: Create review apps label does not create review apps originating from forks

### ISSUE THREAD

**Issue by KevinMulhern** [TheOdinProject/theodinproject#3193]
### Description
The Github Action we use for this has a check to stop PR's originating from forks from triggering this action: https://github.com/fastruby/manage-heroku-review-app/blob/main/src/index.ts#L30

* Is there an alternative action available for creating Heroku review apps we can use?
* Should we fork the action and remove that check?

### Steps to reproduce
1. Fork the TOP web app repo
2. Create a PR from the fork
3. Add the create-review-app label
4. 💥 review app will not be created

### Expected behaviour
1. Fork the TOP web app repo
2. Create a PR from the fork
3. Add the create-review-app label
4. ✅  Review app will be created

**Comment by JuanVqz** [comment]
There is a blog post about it

https://www.ombulabs.com/blog/heroku/github/managing-review-apps-from-github-pr.html

**Comment by KevinMulhern** [comment]
@JuanVqz nice! thats the guide I used to set set up these review app labels 😄  

But unfortunately, the action [has a limitation](https://github.com/fastruby/manage-heroku-review-app/blob/main/src/index.ts#L29) with creating review apps for PR's originating from forks.

**Comment by JuanVqz** [comment]
Let's ask them why they added that limitation and if it could be optional. 💎

**Comment by KevinMulhern** [comment]
Forgot to update this. I opened an issue a while back on the [Fast Ruby repo for this](https://github.com/fastruby/manage-heroku-review-app/issues/2).

**Comment by JuanVqz** [comment]
> Forgot to update this. I opened an issue a while back on the [Fast Ruby repo for this](https://github.com/fastruby/manage-heroku-review-app/issues/2).

if I had just known before I could have helped to push it forward (I work at FastRuby haha), but anyways it is already reviewed with a suggestion, let's see if by Wednesday it still in the same status I'll ping them to continue on merge it :+1:

**Comment by KevinMulhern** [comment]
Thanks @JuanVqz, we appreciate it mate!
