### ISSUE TITLE
Bug: The website is not working when i log in with google

### ISSUE THREAD

**Issue by Cherifi-Houdaifa** [TheOdinProject/theodinproject#3206]
Complete the following REQUIRED checkboxes:

-   [x ] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [ ] The title of this issue follows the `Bug: brief description of bug` format, e.g. `Bug: Lesson complete button does not update on click`

The following checkbox is OPTIONAL:

-   [ ] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Bug:**

**2. How To Reproduce:**

**3. Expected Behavior:**

**4. Desktop/Device:**

-   Device: 
-   OS: 
-   Browser: 
-   Version: 

**5. Additional Information:**
This is not the first time this happened to me it happens sometimes and suddenly it just start working normally.

**Comment by KevinMulhern** [comment]
Hey @Cherifi-Houdaifa, it's working for me at the moment. What are you seeing on your end? can you fill in the 
"1. Description of the Bug:"  bug report item please? if you have any screenshots those will be very helpful.

**Comment by KevinMulhern** [comment]
Closing due to no response.
