### ISSUE TITLE
Bug: ToS page refers to Contact page that does not exist

### ISSUE THREAD

**Issue by scheals** [TheOdinProject/theodinproject#3208]
Complete the following REQUIRED checkboxes:

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `Bug: brief description of bug` format, e.g. `Bug: Lesson complete button does not update on click`

The following checkbox is OPTIONAL:

-   [ ] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Bug:**
Currently, the [Terms of Use](https://www.theodinproject.com/terms_of_use) page refers to a [Contact](https://www.theodinproject.com/contact) page that does not exist. On top of that, the contact e-mail could be said to be somewhat buried in the FAQ. I have only accidentally found out you can click `send us an email` on the [About](https://www.theodinproject.com/about) page to be given the e-mail due to lack of visual feedback on Dark Mode - link text looks the same as any other text.

**2. How To Reproduce:**
1. Visit the [Terms of Use](https://www.theodinproject.com/terms_of_use) page
2. Find the mention of a Contact Page under `Reporting Infringements`
3. Try to go to the [Contact Page](http://theodinproject.com/contact)
4. 404

**3. Expected Behavior:**
1. Visit the [Terms of Use](https://www.theodinproject.com/terms_of_use) page
2. Find the mention of a Contact Page under `Reporting Infringements`
3. Try to go to the [Contact Page](http://theodinproject.com/contact)
4. I end up in the proper Contact Page that ToS describes

**4. Desktop/Device:**
-   Device: PC
-   OS: Windows 10
-   Browser: Firefox (dark mode TOP)
-   Version: 103.0.2 (64-bit)

**5. Additional Information:**
It seems that the e-mail link on the page doesn't look different from other text either on light mode. Checked on up-to-date Edge browser.

**Comment by kevinmonisit** [comment]
What would the contact page even look like? Is this a page that needs to be created or is it already created?

**Comment by KevinMulhern** [comment]
Our about page is the closest thing to a contact page. But to solve this issue, I think we should just display our contact email:

> If you discover any Content on the Platform that you believe infringes your copyright, please report this to us by sending an email to theodinprojectcontact@gmail.com
