### ISSUE TITLE
Bug: Cantact/Chat feature is inaccisible!

### ISSUE THREAD

**Issue by 4015-dev** [TheOdinProject/theodinproject#3226]
Complete the following REQUIRED checkboxes:

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `Bug: brief description of bug` format, e.g. `Bug: Lesson complete button does not update on click`

The following checkbox is OPTIONAL:

-   [ ] I would like to be assigned this issue to work on it

<hr>

**0. Context**

1. This is not a bug with the contact button, links or  with TOP website per se; But rather with the feature of being able to contact TOP community, in its current implementation, that's relying on discord.

2. I have opened this issue here because:
  - I am unable to send messages in [TOP discord server](https://discord.gg/V75WSQG) nor a direct message to the mods/maintainers that were on it at the time,
  - I didn't find any contact email, or form, or alternative way to communicate with TOP community (except for discord, which is not working for me right now)

**1. Description of the Bug:**

0. I was on TOP discord server for a while and i had only one role: Foundation
1. In TOP discord server, #roles channel, I have clicked on the Foundation role.
2. I got a message confirming that the role was removed, as expected, and another one telling me:
  **"You must verify your identity with phone before sending messages in this server."**
  
![phone-verification](https://user-images.githubusercontent.com/91027619/185112315-e177bf34-889e-4949-a355-fb0c8c5bfd2a.png)

**2. How To Reproduce:**

The step that I've followed are described above 

**3. Expected Behavior:**

IF discord is a must, and it is the only conceivable way of communication. 
THEN, I expect that I should be able to remove or modify my roles without getting blocked/muted. and without requiring my phone number, or other personal IDs, to do so.
(I don't suppose that I got officially blocked, since I was still technically in the server, but it's practically the same) 

ELSE
THEN, I expect (and I'd greatly appreciate) the existence of a contact email address or any other alternative communication channel.
It can then forward its messages to a discord channel or a mailing list, to contact the community or a subset of it without obliging the potential learners to use discord themselves.

**4. Desktop/Device:**

Irrelevant

**5. Additional Information:**

- I was searching and removing some of my old messages before getting this issue.
- I don't have a phone number associated with my discord account, and I don't want to
- I can recreate a new account, and rejoin the server, but I prefer if TOP offers better (or at least different) options   
- Finally, I assume that this is not the right place of this issue. but this is the issue ^^"

Thank you.

**Comment by KevinMulhern** [comment]
Hi @4015-dev, sorry you're having trouble accessing the community.

We recently reenabled phone verification due to an increase of trolls creating alt accounts to get around bans. They were degrading the community experience for our leaners and harassing our staff. Phone verification is the only tool we have at our disposal to curtail this kind of thing unfortunately.

However, we can grant access without phone verification on a case by case basis providing there is existing chat activity. You can reach out to a member of staff via our mod mail account on Discord to kick off that process.

**Comment by KevinMulhern** [comment]
>I couldn't find such email on TOP website, or the discord server, before opening this issue. I suppose that it would be good, if it was on TOP contact us page.

Sorry about this, we have an email link on the about page, but it seems the styling has regressed so its blending into the surrounding text. We'll get that fixed and add the contact email on a few other spots around the site to make it easier to find.

> I suppose there is still some of my activities there. but I don't like the idea of being exceptionally granted what I think should be a common right of privacy. So, when a discord server asks for phone numbers, selfies or IDs cards' screen shouts for users validation, I just walk away.

Totally understandable, we don't like putting any unnecessary obstacles in our learners way. But in this case it really was necessary for the health of the community. We've grown massively with the number of learners using TOP this past year and thats brought more trolls than we're used to dealing with. It's stretching the team's resources and bandwidth trying to keep up and adapt with it all at the moment.   

Sorry again for the inconvenience of all this, I hope we'll be able to provide more community options for yourself and everyone else someday soon when our available resources catch up to the growth.
