### ISSUE TITLE
Bug: Foundations Resume button doesn't work as intended

### ISSUE THREAD

**Issue by ssolunna** [TheOdinProject/theodinproject#3230]
Complete the following REQUIRED checkboxes:

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `Bug: brief description of bug` format, e.g. `Bug: Lesson complete button does not update on click`

The following checkbox is OPTIONAL:

-   [ ] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Bug:**
Foundations Resume button in [All Paths](https://www.theodinproject.com/paths) takes you to the [Foundations Path page](https://www.theodinproject.com/paths/foundations/courses/foundations) and not to the currently working lesson as intended.
![foundations](https://user-images.githubusercontent.com/65374099/185768799-90080fbf-84a5-4a45-8093-d6fafeef0f2e.png)

**2. How To Reproduce:**
1. Log in
2. Click All Paths
3. Click Resume button next to Foundations
4. It takes you to the Foundations Path page

**3. Expected Behavior:**
1. Log in
2. Click All Paths
3. Click Resume button next to Foundations
4. It should take you to the currently working lesson

**4. Desktop/Device:**
-   Device: Laptop
-   OS: Windows 10
-   Browser: Firefox
-   Version: 103.0.2 (64-bit)

**Comment by KevinMulhern** [comment]
Thanks for taking the time to report this. However it isn't a bug, this is the intended behaviour. That button is really only an indicator for what path the user is correctly on when they are viewing all paths.

But I can see how the "resume" wording can be confusing. We're planning on moving path selection to the paths themselves as part of this story - https://github.com/TheOdinProject/theodinproject/issues/3094 that will allow us to remove these buttons and use a different way to show the users current path.

**Comment by ssolunna** [comment]
Then why does the **Resume** button in the Dashboard page takes you to the current working lesson and this one doesn’t? It seems to me that both buttons are intended to do the same thing.

Also why have a **View** button next to it that takes you to the same page as the **Resume** button?

I'm not sure if I completely understood you or if I didn't describe the bug correctly.

**Comment by KevinMulhern** [comment]
Somebody asked about the same thing on Discord on recently - https://discord.com/channels/505093832157691914/997169784955342890/997179166594179112

> The main intention with the resume button is to be an indication to the user they are on that path. Clicking the button would ideally take you to the lesson you left off at in the path just like we do with the resume button and courses on the dashboard. However, we have to put some big changes in place to make that work. We'll be tackling it soon.

https://github.com/TheOdinProject/theodinproject/issues/3094 is going to be how we tackle it, that will allow us to remove the "Resume" and "Select" buttons on the path cards.

**Comment by ssolunna** [comment]
I see. Thanks for the clarification.
