### ISSUE TITLE
Bug: Hyperlink leads to a page with no content in FAQ

### ISSUE THREAD

**Issue by Akumarch** [TheOdinProject/theodinproject#3232]
Complete the following REQUIRED checkboxes:

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `Bug: brief description of bug` format, e.g. `Bug: Lesson complete button does not update on click`

The following checkbox is OPTIONAL:

-   [ ] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Bug:**

In the FAQ section of The Odin Project the "Which technologies can one expect to learn from the Odin Project" drop down the looking for employment hyperlink leads to what I assume is a section that was deprecated when the curriculum was split into Ruby and JavaScript.

**2. How To Reproduce:**

1. Go to https://www.theodinproject.com/faq
2. Open "Which technologies can one expect to learn from The Odin Project?"
3. Click the "looking for employment" hyperlink at the very bottom of the last paragraph.

**3. Expected Behavior:**

I assume it should link to either https://www.theodinproject.com/paths/full-stack-ruby-on-rails/courses/getting-hired or https://www.theodinproject.com/paths/full-stack-javascript/courses/getting-hired. Currently it sends you to https://www.theodinproject.com/courses/getting-hired which sends you to a "you're lost" page with no meaningful content. Not sure how the link should be handled. I assume this link broke when The Odin Project split into Ruby and JavaScript.

**4. Desktop/Device:**

-   Device: Desktop PC
-   OS: Windows 10
-   Browser: Chrome
-   Version: Version 104.0.5112.101

**5. Additional Information:**

**Comment by Enntek** [comment]
This seems simple enough for me to understand how to fix, can I please be assigned this bug fix.

**Comment by KevinMulhern** [comment]
All yours @Enntek

**Comment by GitBoatyy** [comment]
If Enntek is unable to progress this bug may I be assigned it?
Thank you

**Comment by KevinMulhern** [comment]
@Enntek are you still working on this?

**Comment by Enntek** [comment]
> @Enntek are you still working on this?

Sorry I got caught up working on other Odin assignments. Yes, I submitted a pull request.
