### ISSUE TITLE
Bug: Hyperlinks lead to 404 error in Ruby Wiki Contributing-Guide

### ISSUE THREAD

**Issue by kckuei** [TheOdinProject/theodinproject#3342]
Complete the following REQUIRED checkboxes:

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `Bug: brief description of bug` format, e.g. `Bug: Lesson complete button does not update on click`

The following checkbox is OPTIONAL:

-   [ ] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Bug:**

- The hyperlinks in the first two bullets of the [How to Contribute section in the Contributing Guide Wiki](https://github.com/TheOdinProject/theodinproject/wiki/Contributing-Guide) yield 404 errors.
- This guide is also referenced in the Ruby | Intermediate Git | Using Git in the Real World lesson. 
- Screenshots below of the Wiki page, and 404 errors for each link:

**Exhibit 1. Contributing Wiki**
<img src="https://i.postimg.cc/CLDZZH3W/faq.png"  alt="Wiki" width="400">

**Exhibit 2. Install Ruby Link 404**
<img src="https://i.postimg.cc/13Q8DVP4/error-1.png"  alt="Ruby-404" width="400">

**Exhibit 3. Install Rails Link 404**
<img src="https://i.postimg.cc/jS4Lcqdc/error-2.png"  alt="Rails-404" width="400">

**2. How To Reproduce:**

1. Go to the [Contributing Wiki page: https://github.com/TheOdinProject/theodinproject/wiki/Contributing-Guide](https://github.com/TheOdinProject/theodinproject/wiki/Contributing-Guide).
2. Under the section, *How to Contribute*, click on the first two links (Install Ruby here & Install Rails here). 

**3. Expected Behavior:**

Expect the hyperlinks to direct you to correct pages to either install ruby or rails. 

**4. Desktop/Device:**

- Device: Dell Precision 3560 Notebook
- OS: Ubuntu 20.04
- Browser: Chrome
- Version: Version 105.0.5195.102 (Official Build) (64-bit)

**5. Additional Information:**

😻 I like cats. 😻

**Comment by KevinMulhern** [comment]
Thanks for reporting @kckuei, those have been fixed.
