### ISSUE TITLE
Bug: 'View full list of solutions' links are not colored

### ISSUE THREAD

**Issue by hattima-tim** [TheOdinProject/theodinproject#3391]
Complete the following REQUIRED checkboxes:

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `Bug: brief description of bug` format, e.g. `Bug: Lesson complete button does not update on click`

The following checkbox is OPTIONAL:

-   [ ] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Bug:**

![view full list](https://user-images.githubusercontent.com/29122213/194685034-806472a3-1020-43f6-9fa2-403e0f4ef904.png)

`View full list of solutions` links from the project pages are not colored. I have seen some project pages of the Javascript course of Full stack Javascript path and all of them have the same problem. Because of this, it is not clear if the link is a link or just text.

**2. How To Reproduce:**

1. Log in
2. Visit [Project:recursion](https://www.theodinproject.com/lessons/javascript-recursion) page.
3. Scroll until `Next lesson` button.
4. Above the button there is the `View full list of collections` link.

**3. Expected Behavior:**

The link should have a gold like color that all other links in the curriculum have.

**4. Desktop/Device:**

-   Device:  laptop, android mobile
-   OS:  android, linux
-   Browser:  firefox, android chrome
-   Version: 
**5. Additional Information:**

**Comment by ChargrilledChook** [comment]
Thanks for the report @hattima-tim, well spotted. I've opened a fix here https://github.com/TheOdinProject/theodinproject/pull/3392
