### ISSUE TITLE
Confirmation Tokens not quite right...

### ISSUE THREAD

**Issue by eriktrautman** [TheOdinProject/theodinproject#340]
Hello,

I seem to be encountering the same problem of not getting the correct token for the confirmation email. It sends me the same error from both this new email that I set up and [redacted]

Is there any way of fixing this problem/getting my email confirmed to save progress on the site?

I have uploaded a screenshot of the problem.

Thanks,

Lucas
![capture](https://cloud.githubusercontent.com/assets/2977438/20290383/79d52776-aa94-11e6-8848-fa5155e09d2f.PNG)

**Comment by eriktrautman** [comment]
Another email:

```
Hey, 

Quick question for you guys, it's asking me to confirm my account on Odin project but when I get the link and click on the sohrtcut to confirm it says the Token ID is expired or invalid but I just got the email 20 seconds before hand. Is there something I'm missing? 


Thanks!
Chi
```

**Comment by KevinMulhern** [comment]
This has been resolved 🎉
