### ISSUE TITLE
Bug: Can't jump to headers nested in summary elements, discrepancy in lesson contents generation

### ISSUE THREAD

**Issue by scheals** [TheOdinProject/theodinproject#3444]
Complete the following REQUIRED checkboxes:

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `Bug: brief description of bug` format, e.g. `Bug: Lesson complete button does not update on click`

The following checkbox is OPTIONAL:

-   [ ] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Bug:**
You can't jump to headers that are nested in those show/hide sections: ![image](https://user-images.githubusercontent.com/95084627/196052952-0e76258c-481c-4820-9561-6e32ea24f027.png) 

The URL will change accordingly but you won't be taken properly to them. The easiest way to see this in action is clicking on various entries in `Lesson contents` to the right of the page - easiest to see in the [Installations lesson](https://www.theodinproject.com/lessons/foundations-installations). I'll try to make an issue for this on app's repo tomorrow.

**2. How To Reproduce:**

1. Visit a [lesson page](https://www.theodinproject.com/lessons/foundations-installations).
2. Try clicking on any of the links that being with `Step` in the `Lesson contents` section.
![image](https://user-images.githubusercontent.com/95084627/196134645-28e39eac-e431-4805-8279-21ee9b87cee6.png)

3. You are not taken to the section you clicked on, even if it is open.

**3. Expected Behavior:**
1. Visit a [lesson page](https://www.theodinproject.com/lessons/foundations-installations).
2. Click on a link in the `Lesson contents` section.
3. You are moved to where that linked header is, hopefully opening up the section it is in on its own or alternatively, only works if that section is already open.

**4. Desktop/Device:**
-   Device: Desktop
-   OS: Windows 10
-   Browser: Firefox
-   Version: 105.0.3 (64-bit)

**5. Additional Information:**
This bug only exists on Firefox due to the difference in creating the `Lesson contents` section:
- Chrome, Xubuntu
![image](https://user-images.githubusercontent.com/95084627/196134494-181abd24-5bef-4815-a8dd-270afa6904bf.png)
- Edge, Windows
![image](https://user-images.githubusercontent.com/95084627/196134574-5be1fd85-52a4-4555-8836-c0a9dbc6bce0.png)

**Comment by ChargrilledChook** [comment]
@scheals Did you want to have a go at implementing Kevin's suggested fix? I'm happy to assist if you need help getting the app running locally :wrench:

**Comment by kazuhirodk** [comment]
> @scheals Did you want to have a go at implementing Kevin's suggested fix? I'm happy to assist if you need help getting the app running locally 🔧

Hi folks! If no interest is expressed, can I work on this issue?

**Comment by scheals** [comment]
@ChargrilledChook I am happy to leave this to @kazuhirodk :) I'm going to be setting the app locally in the coming days since there's a fix I want to make that probably is as easy as slapping two key-value pairs but I want to do it the "proper" way :D So look out for my request for help!

**Comment by KevinMulhern** [comment]
It's all yours @kazuhirodk

**Comment by kazuhirodk** [comment]
Hi folks! I'll submit the @KevinMulhern quick fix suggestion and work on the enhanced solution (auto-open sections for nested collapsed content).
A question: How is the content of a lesson sent? I mean, the issue that @scheals has mentioned on `You are not taken to the section you clicked on, even if it is open` occurs because the nested sections don't contain any `id` for the anchor link. I wanted to investigate if this is due to manual input or a conversion failure.

**Comment by KevinMulhern** [comment]
@kazuhirodk It's a limitation of our markdown converter implementation. To keep it simple, we're only breaking the content into sections for top level h3's and ignoring any nested h3's: https://github.com/TheOdinProject/theodinproject/blob/main/lib/kramdown/converter/html_sections.rb#L14
