### ISSUE TITLE
Feature: Installation Appendix Style Refresh

### ISSUE THREAD

**Issue by KevinMulhern** [TheOdinProject/theodinproject#3468]
### Why?
The [installations appendix](https://www.theodinproject.com/lessons/installation_lessons) is just a list of un styled links, we can do better!

### Acceptance Criteria
We don't need anything too fancy, but turning each list item into a box with an icon and good hover effects will go a long way.

Just some ideas I've had for it:
* A layout [like this](https://tailwindui.com/components/application-ui/layout/list-containers#component-a0f475f9acf9194cd19255e19acde240).
* For icons, we could go with something generic from [heroicons](https://heroicons.com/)
* Another option for icons would be using the branding that represents the tech for each lesson. For example the node logo for the node installation lesson, ruby logo for ruby install etc.  SVG's for those can be sourced from [here](https://simpleicons.org/). If we go this route, we will need to add an `installation_icon` column to the lessons table which will reference the path to the icon in the assets. Check out the `badge_uri` attribute on courses and paths for an example of this.

Additional
To make this page easier to find and clearer
* Rename "Appendix" footer item to "Installation Guides"
* Change the title on the page from "Installation Lessons Appendix" to "Installation Guides"
* Does the installation overview lesson make sense within the context of this page? can we remove it?

**Comment by mgrigoriev8109** [comment]
Would love to take this one on @KevinMulhern

**Comment by ChargrilledChook** [comment]
Hey @mgrigoriev8109, how's this one coming along?

I don't ask to create pressure or urgency, more just checking in. I'm more than happy to offer assistance if I can :slightly_frowning_face:

**Comment by mgrigoriev8109** [comment]
Alas @ChargrilledChook , I don't have the bandwidth, and I'll have to be unassigned from this issue.

**Comment by KevinMulhern** [comment]
No problem @mgrigoriev8109, thanks for letting us know mate.

**Comment by wzhengg** [comment]
Is help still wanted for this issue? I've never contributed to open-source, but I figured this would be a good place to start.

**Comment by KevinMulhern** [comment]
All yours @wzhengg

**Comment by wzhengg** [comment]
Thanks @KevinMulhern! I'll try to have it done within the next couple of days.
