### ISSUE TITLE
Bug: dev installation documentation

### ISSUE THREAD

**Issue by JuanVqz** [TheOdinProject/theodinproject#3469]
Complete the following REQUIRED checkboxes:

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `Bug: brief description of bug` format, e.g. `Bug: Lesson complete button does not update on click`

The following checkbox is OPTIONAL:

-   [x] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Bug:**

I forked the project and then ran `./bin/setup`, it seems like everything is working well so far but when tried to see the lessons it is returning this error

```erb
# http://localhost:3000/lessons/ruby-how-this-course-will-work
# Showing /home/itox/code/projects/theodinproject/app/views/lessons/show.html.erb where line #11 raised:

undefined method `html_safe' for nil:NilClass

      <article class="col-span-full xl:col-span-7 xl:col-start-2">
        <%= render ContentContainerComponent.new(classes: 'xl:mx-0', data_attributes: { lesson_toc_target: 'lessonContent' }) do %>
          <%= @lesson.content.html_safe %>
        <% end %>
      </article>
``` 

**2. How To Reproduce:**
1. fork the repo
2. clone it locally
3. run `bin/setup`
4. visit any lesson Ex. `http://localhost:3000/lessons/ruby-how-this-course-will-work`
5. Error page

**3. Expected Behavior:**
Add dev documentation on how to install the repo locally, most important how to fetch the lesson's content data. 

**4. Desktop/Device:**

-   Device: pc
-   OS: linux
-   Browser:  chrome, safari

**5. Additional Information:**

**Comment by ChargrilledChook** [comment]
Hi @JuanVqz, your're right that this is something that could be improved. You can find more details for local installation on the wiki - it sounds you need an API token for the GH content  -https://github.com/TheOdinProject/theodinproject/wiki/Running-The-Odin-Project-Locally#get-a-github-api-token

I'm about to start on a larger refresh of some of the documentation and improving access to this information will be part of it - currently the wiki probably isn't signposted as well as it could be

**Comment by JuanVqz** [comment]
If you have it already in track to solving it, you can close this issue, thanks!

**Comment by ChargrilledChook** [comment]
> If you have it already on track to solving it, you can close this issue, thanks for sharing the link :)

No worries at all :+1: I've opened a fresh issue here #3470 and have a draft PR up to get the ball rolling. If you have any feedback or ideas, please feel free to comment on either one :raised_hands:

**Comment by JuanVqz** [comment]
> n either one raised_hands

I'll check it, I want to still contribute on this project :)

**Comment by JuanVqz** [comment]
I went to the wiki you shared [Get a GitHub Token](https://github.com/TheOdinProject/theodinproject/wiki/Running-The-Odin-Project-Locally#get-a-github-api-token).

Let's add a paragraph saying that it's okay if we don't select any scope from the `Select scopes` section, it is still working (I tested it).

**Comment by ChargrilledChook** [comment]
> I read the wiki you shared [Get a GitHub Token](https://github.com/TheOdinProject/theodinproject/wiki/Running-The-Odin-Project-Locally#get-a-github-api-token).
> 
> Let's add a paragraph saying that it's okay if we don't select any scope from the `Select scopes` section, it is still working (I tested it) if you agreed

Happy to add something there, I believe this was originally written before the fine grained PATs were a feature

**Comment by ChargrilledChook** [comment]
Going to close this one but please feel free to continue this discussion in #3470 :speech_balloon:
