### ISSUE TITLE
Docs: Remove Docker instructions from wiki

### ISSUE THREAD

**Issue by ChargrilledChook** [TheOdinProject/theodinproject#3482]
**Because**
There's no longer a docker / docker compose file in the repo, so the instructions no longer work

**Notes**
Simple change to make, but wanted to get a quick second opinion first since it's difficult to code review wiki changes

[Relevant page](https://github.com/TheOdinProject/theodinproject/wiki/Docker-Setup)

**Comment by KevinMulhern** [comment]
Lets do it @ChargrilledChook, Docker has been long gone from the app haha.

**Comment by ChargrilledChook** [comment]
:wastebasket: Done :heavy_check_mark:
