### ISSUE TITLE
Confirmation token not recognized when using Github for account creation

### ISSUE THREAD

**Issue by eriktrautman** [TheOdinProject/theodinproject#349]
We do occasionally have issues with people signing up using Github not being able to do the complete signup.  Not sure if this one is a symptom of a larger issue after the Rails 5 upgrade so wanted to flag it.  Sometimes it's just weird things like email mismatches.

His account can be found using his gmail email timothy.fung.04 

From the recent email chain:

Hi Erik,

I have attached a screenshot for your reference. I would type my email over and over buy the same message pops up.

Regards,

Timothy

On Wed, Nov 16, 2016 at 11:43 AM, Erik Trautman <erik@vikingeducation.com> wrote:
Hi Timothy, can you explain exactly the steps you took and exactly what error message you’re receiving?  Else it is very challenging to debug remotely.
Thanks!
Erik

—
Erik S. Trautman
Founder,  Viking Code School

On Nov 16, 2016, at 8:39 AM, Timothy Fung <timothy.fung.04@gmail.com> wrote:

I keep trying to verify my email using GitHub but it keeps giving me an error message. Can you help me?

Regards,

Timothy

verification error.png
![verification error](https://cloud.githubusercontent.com/assets/2977438/20357027/4aaeb4ba-abdb-11e6-9951-76b049748591.png)

**Comment by KevinMulhern** [comment]
I suspect this is fallout from the rails 5 upgrade, I manually confirmed this account.

**Comment by eriktrautman** [comment]
We may have something ongoing... just got another email (from the .org email rhahn@claytonps) that says:

Each time I click on the link in the email to verify my account it tells me that the "confirmation token is invalid".
-- 
Thank You,

**Comment by KevinMulhern** [comment]
Hmm I am looking into these accounts, those ones were created long before the upgrade. Devise had to be upgraded too. It seems like the old tokens are now invalid. I've been monitoring the creation of new users and they are fine. I'll manually confirm each of these cases as they come in.

**Comment by KevinMulhern** [comment]
Theres been no reports of this in the past 2 days, I'll leave it open for another week just incase though.

**Comment by KevinMulhern** [comment]
No reports of this since, I think its safe to close 🎉

**Comment by hugoroger** [comment]
It's 2017 and I just tried signing up but can't! Definitely wasted a lot of time trying to work around this. Why is your application trying to verify my Github password when I am already signed in, logged in and even typing here?

**Comment by KevinMulhern** [comment]
@hugoroger sorry for the trouble you have been having, I can help you with this issue. I've sent you a private message on gitter 😄
