### ISSUE TITLE
Add link to go back to project on Solutions page

### ISSUE THREAD

**Issue by Overlandcoder** [TheOdinProject/theodinproject#3518]
Complete the following REQUIRED checkboxes:

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `brief description of request` format, e.g. `Add dark mode to website`

The following checkbox is OPTIONAL:

-   [ ] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Feature Request:**

If you open up a project page and click "View full list of solutions" at the bottom, that [Solutions page](https://www.theodinproject.com/lessons/534/project_submissions?page=5) doesn't have a link to go back to the project page.

**2. Acceptance Criteria:**

- [ ] On the Solutions page, the project title should be a link to that project

**3. Additional Information:**

**Comment by c00kie123** [comment]
Hey, I would like to work on this. Please assign it to me

**Comment by KevinMulhern** [comment]
All yours @c00kie123

**Comment by c00kie123** [comment]
Hey, thanks for assigining me! This is my first time contributing to open-source and I need some help and guidance. 
I understand you are looking to create an additional link in the solution page back to the project page. May I ask where I can find this solution page in the directory? I have been trying to find it but it seems too complicated for me to navigate through.
I am also a bit confused with the requirements. What is the goal of this 
Is it to have a clickable link in the solution page back to the original project/lesson page? or to have a clickable link to each project to their project website for every submission? 

Thanks for helping out!

**Comment by c00kie123** [comment]
Hey, after looking through, I think this might be too difficult for me to do as I am quite new to open-source contribution. I think another person will fit this better. Thanks for your help anyway!

**Comment by scheals** [comment]
I -think- I can take this on.

**Comment by ChargrilledChook** [comment]
Thanks @scheals , don't be afraid to reach out if you need assistance
