### ISSUE TITLE
Wiki improvement

### ISSUE THREAD

**Issue by marcusicaro** [TheOdinProject/theodinproject#3544]
Complete the following REQUIRED checkboxes:

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `brief description of request` format, e.g. `Add dark mode to website`

The following checkbox is OPTIONAL:

-   [x] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Feature Request:**

I'd like to suggest a improvement. On the page [Linux Installation](https://github.com/TheOdinProject/theodinproject/wiki/Linux-Installation-Guide) from the wiki (on the how to contribute section) I believe would be nice to have a reference to [The Odin Project PostgreSQL Installation Guide ](https://www.theodinproject.com/lessons/ruby-on-rails-installing-postgresql). The Odin Project article is very well written, and gives a more in-depth guide on what should be done to install PostgresSQL as well as how to fix some common issues that students might be having to set everything up.

**2. Acceptance Criteria:**

**3. Additional Information:**

I couldn't find how to edit the wiki page directly and then send a PR, so I'm requesting it through a PR directly.

**Comment by KevinMulhern** [comment]
Thanks for the suggestion @marcusicaro, 

I agree that article is much better written and approachable for beginners. The only thing making me hesitant to drop it in is the differences in how the article handles env variables using the system bashrc and how our app handles them with dotenv. 

There was a bit of confusion in the ubuntu support channel on Discord the other day with someone following the article to setup Postgreql for the app and I believe much of the trouble came down to the different env var instructions.

**Comment by marcusicaro** [comment]
Hey, Kevin, thanks for answering.

I was the one asking for help with the PostgreSQL setup the other day, and I believe you were rhe one who helped me with the .env (btw thanks again).

I started following the wiki article, but, since I had already used PostgrSQL before, had somw troubles setting it up. What I believe would be helpful, would be dropping a link to the Odin Project PostgreSQL article. The advantage would be giving the person who is trying to setup their PostgreSQL an optional explanation of what they are doing. The disavantage os that ot couls cause confusion since the env variable os handled differently among them.

Another option could be giving a small explanation in the article regarding the .env matter with bold text?

Just some suggestions that I believe would improve it.

**Comment by KevinMulhern** [comment]
Hey @marcusicaro, I've been reviewing this again. I still think the difference with env var set up between the app and the lesson is too much unfortunately. If theres anything we can do to improve the installation instructions on the wiki, that would be the ideal way forward. I'll close this for now, but thank you for taking the time to make this suggestion.
