### ISSUE TITLE
Bug: Wiki - Broken Link in Linux Installation Guide

### ISSUE THREAD

**Issue by Asartea** [TheOdinProject/theodinproject#3545]
Complete the following REQUIRED checkboxes:

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `Bug: brief description of bug` format, e.g. `Bug: Lesson complete button does not update on click`

The following checkbox is OPTIONAL:

-   [ ] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Bug:**
On https://github.com/TheOdinProject/theodinproject/wiki/Linux-Installation-Guide the bolded text at the very top links to https://www.theodinproject.com/courses/ruby-programming/lessons/installing-ruby-ruby-programming, which is a 404. I assume it means to link to https://www.theodinproject.com/lessons/ruby-installing-ruby.

**2. How To Reproduce:**
1. Go to https://github.com/TheOdinProject/theodinproject/wiki/Linux-Installation-Guide
2. Click the link in "This guide assumes that you have already installed Ruby and rails. To get instructions on how to do that go through the installations project [here](https://www.theodinproject.com/courses/ruby-programming/lessons/installing-ruby-ruby-programming)"
3. There is a 404 page
4. The complete button does not update

**3. Expected Behavior:**
A brief description of what you expected to happen, e.g.:
1. The link links to a actual page

**4. Desktop/Device:**

-   Device: 
-   OS: 
-   Browser: 
-   Version: 

**5. Additional Information:**

**Comment by KevinMulhern** [comment]
Thanks for reporting @Asartea 💪  
Fixed.
