### ISSUE TITLE
Bug: styling discrepancy between lessons and lesson previews

### ISSUE THREAD

**Issue by scheals** [TheOdinProject/theodinproject#3555]
Complete the following REQUIRED checkboxes:

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `Bug: brief description of bug` format, e.g. `Bug: Lesson complete button does not update on click`

The following checkbox is OPTIONAL:

-   [ ] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Bug:**
At least one aspect of styling in [Lesson Preview Tool](https://www.theodinproject.com/lessons/preview) does not reflect the styling used for actual lesson pages - that'd be styling for `<code>` elements, using [Setting Up Git lesson](https://www.theodinproject.com/lessons/foundations-setting-up-git)'s Linux instructions as an example:

Preview's styling:
![image](https://user-images.githubusercontent.com/95084627/208407963-f8af33b5-e7ab-4bbd-8a20-7c5ee4f7b4c9.png)
Actual styling:
![image](https://user-images.githubusercontent.com/95084627/208408000-18a37688-fe44-49bc-8277-e419aa18fc36.png)

As can be seen, the padding is missing, the rounding of borders is missing and the font-weight is different. Going to the DevTools, I noticed those rules missing from the `Preview`'s case:
![image](https://user-images.githubusercontent.com/95084627/208408303-1bd72fdd-f134-4749-85d0-e680a59bec8c.png)

This is possibly due to these two pages being rendered differently, lessons using ViewComponents and the preview relying on a React component:
- [Lesson Preview's components](https://github.com/TheOdinProject/theodinproject/tree/main/app/javascript/components/lesson-preview) and [the View](https://github.com/TheOdinProject/theodinproject/blob/main/app/views/lessons/previews/show.html.erb)
- [Regular lesson's ViewComponent](https://github.com/TheOdinProject/theodinproject/blob/main/app/components/content_container_component.html.erb) and [the View](https://github.com/TheOdinProject/theodinproject/blob/main/app/views/lessons/show.html.erb)

but I know close to nothing about both React and ViewComponent so it might be absolutely the wrong angle to look at.

**2. How To Reproduce:**

What steps one might need to take in order to reproduce this bug, e.g.:
1. Grab Markdown of a lesson.
2. Throw that Markdown into the Lesson Preview Tool.
3. See how it renders.
4. It renders differently from what a real page renders like.

**3. Expected Behavior:**

A brief description of what you expected to happen, e.g.:
1. Grab Markdown of a lesson.
2. Throw that Markdown into the Lesson Preview Tool.
3. See how it renders.
4. Lesson renders just like the real one does.

**4. Desktop/Device:**

-   Device: VM, PC
-   OS: Xubuntu 22.04
-   Browser: Firefox
-   Version: 108.0.1 (64-bit) (snap)

**5. Additional Information:**
Issue also happens on Windows 10 with its Firefox 108.0.1 (64-bit) and Edge.

**Comment by KevinMulhern** [comment]
Thanks for reporting @scheals 😎 

Copying over the missing classes from the lesson page view component would be the quickest way to fix this right now. But longer term, it's going to be a pain to remembering to update both components when lesson content styling changes are modified.

With the advent of Hotwire, we can refactor the lesson preview to no longer user react, allowing us to use the view component for both pages. Thats quite a big story though, so I think we should go with the quick fix right now and spin out another issue for the refactor.

**Comment by scheals** [comment]
@KevinMulhern So like slapping this from [Regular lesson's ViewComponent](https://github.com/TheOdinProject/theodinproject/blob/main/app/components/content_container_component.html.erb):

![image](https://user-images.githubusercontent.com/95084627/209087233-456a262f-9fb3-4a6c-8ffb-e7ef9527cffa.png)

(pardon me for the screenshot but it felt like the most sensible way of including that, it's all one line...)

together with the `'xl:mx-0'` from `classes` variable passed in onto:

[this React component's classes](https://github.com/TheOdinProject/theodinproject/blob/main/app/javascript/components/lesson-preview/components/lesson-content-preview.jsx)

![image](https://user-images.githubusercontent.com/95084627/209087924-4fae0c14-0b53-4436-8c76-8b67de0668dc.png)

should do the trick?

**Comment by KevinMulhern** [comment]
Haha no worries, biggest drawback of TW are the massive class lists it produces. 

We need everything except `'xl:mx-0'`, thats only needed on the lesson page to fit the lesson nav.

**Comment by scheals** [comment]
@KevinMulhern If the duplication of rules is not a concern, I can submit a pull request. The stylings start working as they should I believe but those rules are duplicated once.

**Comment by KevinMulhern** [comment]
@scheals thanks Scheals, yep we can absolutely live with the duplication for now.

**Comment by scheals** [comment]
@KevinMulhern Turns out the duplication is not only on that page due to that. Maybe this is has something to do with my setup but the rules are duplicated all over the app in my development environment. I can create a separate issue for that.

**Comment by KevinMulhern** [comment]
Thanks @scheals 💪  where else are you seeing them duplicated?

**Comment by scheals** [comment]
@KevinMulhern Literally everywhere. It's like every stylesheet is loaded twice, because I'll see `base.css` be duplicated, `buttons.css` duplicated, `base.css`, `lesson-content.css` and so on. Dashboard, lessons themselves, project submissions page, the about page.

![image](https://user-images.githubusercontent.com/95084627/211901083-3b69c65d-3af7-433c-bcc9-a2f9befb127b.png)
![image](https://user-images.githubusercontent.com/95084627/211901115-0e18bd7a-3f79-4fb1-8491-5eeef57f993f.png)
![image](https://user-images.githubusercontent.com/95084627/211901145-6e041e5c-8692-483b-85ae-58d861e16247.png)

`includes.css` is not duplicated:
![image](https://user-images.githubusercontent.com/95084627/211901352-0d866f6b-da30-45a0-b47e-6fd7c73abc6c.png)

And these don't seem to be duplicated:
![image](https://user-images.githubusercontent.com/95084627/211901522-8127bcc5-a2aa-4631-be6c-537d0d6c7102.png)

Issue happens on both Firefox and Chrome on my Xubuntu both logged in and logged out. Going to `Style Editor` in Firefox's DevTools gives me this error:
![image](https://user-images.githubusercontent.com/95084627/211902160-5bbd095a-6074-49ee-9db3-a1908d378692.png)

Which seems to be about that `<no source>` thing. I think webpack might possibly be running twice?

**Comment by KevinMulhern** [comment]
Ahh gotcha, yeah I've seen that too. It's something Webpacker is doing only in development mode. Most likely some misconfiguration with how we are handling CSS with Webpacker.
