### ISSUE TITLE
Bug: Contribution Guides to the TOP repos recommend discord channels that do not exist

### ISSUE THREAD

**Issue by vvrestler** [TheOdinProject/theodinproject#3556]
Complete the following REQUIRED checkboxes:
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `Bug: brief description of bug` format, e.g. `Bug: Lesson complete button does not update on click`

The following checkbox is OPTIONAL:
-   [ ] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Bug:**
In the contribution guides regarding the github repos for TOP, there are multiple references to a Discord channel that is not functional anymore.

**2. How To Reproduce:**
[Visit the "How to Contribute" part of this guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md#how-to-contribute) and the [Further Help](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md#further-help) of the same page.
There is also a broken reference at the bottom of [this page](https://github.com/TheOdinProject/odin-bot-v2/wiki/Contributing-Guide#need-help-with-anything-here) in the Odin Bot repo.

Clicking the "[suggestions-bugs Discord channel](https://discordapp.com/channels/505093832157691914/540903304046182425)" hyperlinks on these pages will recreate the issue.

**3. Expected Behavior:**
The hyperlinks should take you to a channel that allows for discussion of bugs and suggestions. I think this channel has been replaced with the [suggestions-bugs](https://discord.com/channels/505093832157691914/1010231881033330819) forum now.

**4. Desktop/Device:**
-   Device: PC (Acer)
-   OS: Xubuntu
-   Browser: Chrome
-   Version: 108.0.5359.124

**5. Additional Information:**
The channel I am taken to when I click the hyperlink does exist, but it says I do not have permission to post, and the messages are hidden. i would be wary of someone with permissions investigating but not being able to see the issue due to them having adequate permissions for the old channel.

**Comment by ChargrilledChook** [comment]
Thanks for the report @vvrestler, much appreciated. I think you're correct that the issue is the link pointing to the old channel, and not the new forum. 

Befiore I open this up for others to fix, are you interested in having a go? It should be a pretty straightforward change.

**Comment by vvrestler** [comment]
@ChargrilledChook I can have a go at it. Originally I didn't check the interest box because I was busy at the time, but I've got some free time to work on it now.
