### ISSUE TITLE
Bug: Inactive link in Javascript course

### ISSUE THREAD

**Issue by nikolaizhnikolov** [TheOdinProject/theodinproject#3566]
Complete the following REQUIRED checkboxes:

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `Bug: brief description of bug` format, e.g. `Bug: Lesson complete button does not update on click`

The following checkbox is OPTIONAL:

-   [x] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Bug:**

The second link in the **Scope and Closure** section at: 
https://www.theodinproject.com/lessons/node-path-javascript-factory-functions-and-the-module-pattern
seems to be missing. After posting in the Discord the user _console.log(`Asarta')_ found out the content is now at:
https://ultimatecourses.com/blog/everything-you-wanted-to-know-about-javascript-scope

**2. How To Reproduce:**
1. Sign in
2. Go to https://www.theodinproject.com/lessons/node-path-javascript-factory-functions-and-the-module-pattern
3. Click the second link in the **Scope and Closure** section, that starts with **2. This article...**
4. The browser shows error 404

**3. Expected Behavior:**
1. Sign in
2. Go to https://www.theodinproject.com/lessons/node-path-javascript-factory-functions-and-the-module-pattern
3. Click the second link in the **Scope and Closure** section, that starts with **2. This article...**
4. The link opens

**4. Desktop/Device:**

-   Device: [Laptop] 
-   OS: [Windows]
-   Browser:  [Brave]
-   Version: [1.46.144]

**5. Additional Information:**

**Comment by Asartea** [comment]
With https://github.com/TheOdinProject/curriculum/pull/24988 merged I believe this issue can be closed?

**Comment by ChargrilledChook** [comment]
@nikolaizhnikolov Thanks for the report and fix, @nikolaizhnikolovm, much appreciated. For future reference this repo is for the web app itself - for content related issues the best place to report them is in the [ curriculum repo.](https://github.com/TheOdinProject/curriculum)

Closed by https://github.com/TheOdinProject/curriculum/pull/24988
