### ISSUE TITLE
Bug: https://www.theodinproject.com/lessons/installation_lessons returns a 500 internal server error

### ISSUE THREAD

**Issue by Asartea** [TheOdinProject/theodinproject#3657]
Complete the following REQUIRED checkboxes:

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `Bug: brief description of bug` format, e.g. `Bug: Lesson complete button does not update on click`

The following checkbox is OPTIONAL:

-   [ ] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Bug:**
- The page https://www.theodinproject.com/lessons/installation_lessons, which is supposed to be a list of all lessons covering installations, is completely broken and returns a 500 internal server error

**2. How To Reproduce:**
1. Visit https://www.theodinproject.com/lessons/installation_lessons

**3. Expected Behavior:**
The page displays the content included via <https://github.com/theodinproject/theodinproject/blob/main/app/views/lessons/installation_lessons/index.html.erb>

**4. Desktop/Device:**

-   Device: 
-   OS: 
-   Browser: 
-   Version: 

**5. Additional Information:**

**Comment by ChargrilledChook** [comment]
Thanks for the report, should be resolved soon :+1:
