### ISSUE TITLE
Bug: Contributors Hall of Fame images are vertically stretched in Safari

### ISSUE THREAD

**Issue by jasonisrailov** [TheOdinProject/theodinproject#3662]
Complete the following REQUIRED checkboxes:

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `Bug: brief description of bug` format, e.g. `Bug: Lesson complete button does not update on click`

The following checkbox is OPTIONAL:

-   [x] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Bug:**

The [Contribute Page](https://www.theodinproject.com/contributing) has a bug with the images in the Hall of Fame section showing as stretched vertically. This issue did not occur on Chrome or Firefox browsers and only occurs using the Safari browser on Mac, iPad, and iPhone as shown below:

macOS Safari Browser:
![macOS Safari Hall of Fame Image bug](https://user-images.githubusercontent.com/20525117/222623190-9eda69ea-279e-40e2-b11e-1e781a92eb5e.png)
iPadOS Safari Browser:
![iPadOS Safari Hall of Fame Image bug](https://user-images.githubusercontent.com/20525117/222623446-071e449f-051c-4111-ad25-fd19e4e14577.jpeg)
iOS Safari Browser:
![iOS Safari Hall of Fame Image bug](https://user-images.githubusercontent.com/20525117/222623642-20165b62-6b78-421c-91e9-19ee08fdc037.jpeg)

**2. How To Reproduce:**

1. Open the Safari browser on an Apple device (e.g. Mac, iPad, iPhone)
2. Visit the [Contribute Page](https://www.theodinproject.com/contributing)
3. Scroll down to the _Hall of _Fame_ section 
4. Notice the images vertically stretched

**3. Expected Behavior:**

1. Open the any browser on any device other than the Safari browser
2. Visit the [Contribute Page](https://www.theodinproject.com/contributing)
3. Scroll down to the _Hall of _Fame_ section
4. Notice the images are **not** vertically stretched

**4. Desktop/Device:**

-   Device: **MacBook Pro**
    -   OS: macOS Ventura 13.2.1
    -   Browser: Safari
    -   Version: 16.3 (18614.4.6.1.6)

-   Device: **iPad Pro**
    -   OS: iPadOS 16.3.1
    -   Browser: Safari
    -   Version: 16.3 

-   Device: **iPhone**
    -   OS: iOS 16.3.1
    -   Browser: Safari
    -   Version: 16.3 

**5. Additional Information:**

I tested this issue with a private window in other browsers. The screenshot below shows the expected behavior of the Hall of Fame section on the same macOS device as above in the Chrome browser.
![macOS Chrome Hall of Fame Image](https://user-images.githubusercontent.com/20525117/222625294-038fac0d-8c42-4bea-82ab-886eae4260de.png)

**Comment by KevinMulhern** [comment]
Thanks for reporting this @jasonisrailov, would you like to take it on?

**Comment by jasonisrailov** [comment]
> Thanks for reporting this @jasonisrailov, would you like to take it on?

Hi @KevinMulhern! Yes, I would love to take this issue on!
