### ISSUE TITLE
Bug: Inconsistent code block styles

### ISSUE THREAD

**Issue by JoshDevHub** [TheOdinProject/theodinproject#3665]
Complete the following REQUIRED checkboxes:

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `Bug: brief description of bug` format, e.g. `Bug: Lesson complete button does not update on click`

The following checkbox is OPTIONAL:

-   [ ] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Bug:**

I noticed while working on [this PR](https://github.com/TheOdinProject/curriculum/pull/25167) for the curriculum repo that code blocks seem to have inconsistent margin styles. 

**2. How To Reproduce:**

 A great example can currently be seen on the [Installing Postgres lesson](https://www.theodinproject.com/lessons/ruby-on-rails-installing-postgresql) in the Rails course.
 
 In the Ubuntu instructions section, one of the code blocks and a note block above it look like this:
 ![linux_section_note](https://user-images.githubusercontent.com/88392688/222938409-60bce4aa-1d9f-485d-982b-db611414051d.png)
 
 In the Mac instructions section, the code block looks like this:
![mac_section_note](https://user-images.githubusercontent.com/88392688/222938383-1db79128-5c2c-4375-8c25-4df1c322b91a.png)

From inspecting the HTML and experimenting, I'm pretty sure the this is caused by the code block in the Ubuntu section having the `bash` language identifier on it. The element ends up with less `margin-top` than the code block in the MacOS instructions.

**3. Expected Behavior:**

Kevin and I both agree that the way the code block appears in the MacOS section is preferable and the styles should be tweaked such that other code blocks demonstrate the same margin behavior.

**4. Desktop/Device:**
N/A

**5. Additional Information:**

- The solution to this likely lies with editing [these code syntax custom styles](https://github.com/TheOdinProject/theodinproject/blob/main/app/javascript/stylesheets/prism-theme.css)
- [Markdown for the lesson](https://github.com/TheOdinProject/curriculum/blob/main/ruby_on_rails/advanced_forms_and_activerecord/installing_psql.md?plain=1) referenced above if that helps any

**Comment by KevinMulhern** [comment]
Thanks for reporting this @JoshDevHub 💪

**Comment by Aditya-A-G** [comment]
hey @JoshDevHub i would like to work on this issue

**Comment by CouchofTomato** [comment]
All yours @Aditya-A-G

**Comment by Aditya-A-G** [comment]
Hey @CouchofTomato can you please review this pr #3676
