### ISSUE TITLE
Bug: Project Solutions are not displaying Project Title

### ISSUE THREAD

**Issue by rlmoser99** [TheOdinProject/theodinproject#3688]
Complete the following REQUIRED checkboxes:

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `Bug: brief description of bug` format, e.g. `Bug: Lesson complete button does not update on click`

The following checkbox is OPTIONAL:

-   [ ] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Bug:**
I believe the sub-text under "Solutions" should have the title of the project.

<img width="1288" alt="Screenshot 2023-03-18 at 8 18 13 AM" src="https://user-images.githubusercontent.com/33227096/226109309-1ea22f2f-e0f4-45a9-acf0-071bf1ff7bd9.png">

**2. How To Reproduce:**
1. Sign in
2. Visit a project page
3. Scroll down to the Solutions
4. The name of the project is not present

**3. Expected Behavior:**
1. Sign in
2. Visit a project page
3. Scroll down to the Solutions
4. The name of the project is present

**5. Additional Information:**

**Comment by CouchofTomato** [comment]
Thanks @rlmoser99 

For anyone interested this is a Javascript problem most likely as we use React for that small part

https://github.com/TheOdinProject/theodinproject/blob/main/app/javascript/components/project-submissions/containers/project-submissions-container.jsx#L124

**Comment by JoshDevHub** [comment]
I have this working locally and matched with what it looked like prior to the breaking change.
![image](https://user-images.githubusercontent.com/88392688/228140538-99f9b18a-8588-4c39-9d47-df2a4850af27.png)

Seems to come from this commit where the `Lesson` decorator was removed: https://github.com/TheOdinProject/theodinproject/commit/bd06ea5fda405050ffda3cd2d059652a7f6d95d1

This ended up replacing many instances of `lesson.title` with `lesson.display_title`, including in `project-submissions-container.jsx`. But the `lesson` object in that component doesn't have a `display_title` property.

**Comment by KevinMulhern** [comment]
Thanks for digging into it @JoshDevHub, that was an oversight on my part 🙈 

The only thing `display_title` gives us in this case is prefixing the title with "Project:" - but we can live without that here. Definitely PR your fix please mate.
