### ISSUE TITLE
Chore: Update Mermaid to version 10

### ISSUE THREAD

**Issue by JoshDevHub** [TheOdinProject/theodinproject#3716]
We recently added support for mermaid diagramming to site. See here for the PR: https://github.com/TheOdinProject/theodinproject/pull/3708

With the latest version of mermaid installed (version 10.0.2), the CircleCI tests fail. This is caused by a webpack compilation issue that emerges from some incompatibility between TOP's webpacker config and mermaid's exports, which are ESM only in v10+.

With the latest version of mermaid installed, you can recreate the errors that happen in CI locally by running `NODE_ENV=test RAILS_ENV=test rails webpacker:compile`.

The three things that need to happen to resolve this issue:
1. Run `yarn install mermaid` to install the latest version of mermaid.
2. [This line](https://github.com/TheOdinProject/theodinproject/blob/main/app/javascript/components/lesson-preview/index.jsx#L27) in the lesson preview component needs to become `await mermaid.run()`. This is due to [changes in the mermaid API in v10](https://mermaid.js.org/config/usage.html#calling-mermaid-init-deprecated).
3. Make sure that `NODE_ENV=test RAILS_ENV=test rails webpacker:compile` runs without errors. This should guarantee that it will pass CI. This likely involves some small change to the webpacker config to properly grab mermaid's exports. Reading through [this conversation](https://github.com/TheOdinProject/theodinproject/pull/3708#discussion_r1153048829) in the mermaid PR should help with getting the full context for this problem.

**Comment by KevinMulhern** [comment]
Reopening: https://github.com/TheOdinProject/theodinproject/pull/3721
