### ISSUE TITLE
Bug: Light/Dark UI setting labels are implemented backwards

### ISSUE THREAD

**Issue by RyanMcEntire** [TheOdinProject/theodinproject#3785]
Complete the following REQUIRED checkboxes:

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `Bug: brief description of bug` format, e.g. `Bug: Lesson complete button does not update on click`

The following checkbox is OPTIONAL:

-   [ ] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Bug:**

The current implementation of the theme toggle is from the perspective of the developer accurately labelling the state of the product, and not serving the UX needs of the user.

In my opinion, a good practice for a toggle switch between light and dark mode, is to label the toggle with a moon when you're in light mode, and a sun when you're in dark mode. The reason you'd want a moon in light mode, is because the user is looking for the setting to change to dark mode. They will be looking for a dark mode label. The opposite is true for light mode.

The user does not need to have the current theme mode be labelled because it is already apparent from the current color, which the user can see. Their intended destination is a mystery and has to be taken on faith that dark mode will show up if they click on the light mode icon. This is unintuitive.

**2. How To Reproduce:**

1. look for icon to pick theme
2. click sun to go to dark mode
3. click moon to go to light mode

**3. Expected Behavior:**

1. look for icon to pick theme
2. click sun to go to light mode
3. click moon to go to dark mode

**4. Desktop/Device:**

-   device agnostic

**5. Additional Information:**

**Comment by KevinMulhern** [comment]
Thanks for the suggestion and great write up @RyanMcEntire. I generally agree with this, but other people do find the icons representing the current state of the system more intuitive which complicates the solution. 

We have an existing issue for this with more details about what we're planning to do to solve this for both camps: https://github.com/TheOdinProject/theodinproject/issues/3497 

Closing this to avoid duplicated issues, but feel free to join in the discussion in the other issue, thanks again!
