### ISSUE TITLE
Add a view to display all the submissions of a project

### ISSUE THREAD

**Issue by arun1595** [TheOdinProject/theodinproject#379]

**Comment by SoteroX** [comment]
do you mean display all the submission the user submitted to the user? or let users view every submissions submitted

**Comment by KevinMulhern** [comment]
Hey @soterox, this is for displaying all submission for a particular project. It will be a new page that the user can access though the project lesson page.

**Comment by codyloyd** [comment]
do we still need this issue?

**Comment by adachiu** [comment]
Probably not since we are having a full page for viewing all submissions to a lesson.

**Comment by KevinMulhern** [comment]
👍 I'll get the backend done for it and put an issue up for the front end styling
