### ISSUE TITLE
Bug: Broken Link - Code of Conduct

### ISSUE THREAD

**Issue by taladan** [TheOdinProject/theodinproject#3794]
Complete the following REQUIRED checkboxes:

-   [x ] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [ x] The title of this issue follows the `Bug: brief description of bug` format, e.g. `Bug: Lesson complete button does not update on click`

The following checkbox is OPTIONAL:

-   [ ] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Bug:**

Link from:
https://github.com/TheOdinProject/theodinproject/wiki 

to: 
https://github.com/TheOdinProject/theodinproject/tree/main/doc/code_of_conduct.md 
is giving a 404 error.

**2. How To Reproduce:**
See above link

**3. Expected Behavior:**
To see a code of conduct page

**4. Desktop/Device:**
Desktop PC running Ubuntu 22.04.02 LTS, Firefox v. 113.0.1 (64-bit)

**Comment by James-N-M** [comment]
I'll pick this up

**Comment by CouchofTomato** [comment]
Thanks. I've updated this to the correct link.
