### ISSUE TITLE
Styling issue: title h1 is incorrectly capitalised in lessons, unlike in the course lesson overview.

### ISSUE THREAD

**Issue by ManonLef** [TheOdinProject/theodinproject#3812]
Complete the following REQUIRED checkboxes:

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `brief description of request` format, e.g. `Add dark mode to website`

The following checkbox is OPTIONAL:

-   [x] I would like to be assigned this issue to work on it
- I wouldn't mind working on it if you find this issue valid enough to be worked on in the future, but I have not yet worked with this repo and I am not entirely sure how elaborate that process would be.
<hr>

**1. Description of the Feature Request:**

Currently the lesson `h1` has `text-transform: capitalize;` applied through the `capitalize` class. This will lead to titles like  `Async And Await` and `A Very Brief Intro To CS`. This is not a huge problem but generally in titles, words like `and` or `to` are not capitalized. It seems thought has been put into this for the course overview of lessons but it gets discarded with the `text-transform` on the `h1` title for the individual lessons. 

note that `with` actually is capitalized usually. It's not in the JS course lesson overview for `Form Validation with Javascript` but it is in the h1 of the lesson itself because of the `.capitalize` class. 

**2. Acceptance Criteria:**

- [x] Titles of lessons should be capitalized correctly

**3. Additional Information:**

Course overview:
![Screenshot 2023-05-21 at 21 27 57](https://github.com/TheOdinProject/theodinproject/assets/81025586/08dd97e6-86f8-43e3-bd08-e82a6c3a5925)
Lesson title:
![Screenshot 2023-05-21 at 21 27 33](https://github.com/TheOdinProject/theodinproject/assets/81025586/338f9507-512a-4333-b67e-46fc9c85ce4f)
Proposed lesson title:
![Screenshot 2023-05-21 at 21 28 55](https://github.com/TheOdinProject/theodinproject/assets/81025586/3c972e77-e8f0-4aad-9c01-d24b670bbd2d)

**Comment by ChargrilledChook** [comment]
Seems reasonable @ManonLef, for context:

- The capitalize is being applied in [the lesson header partial](https://github.com/TheOdinProject/theodinproject/blob/b8ea99361f8d8d1d29bdae177b76be3001423956/app/views/lessons/_header.html.erb)

- The original text is set in the `titlle` keys in all the files in [db/fixtures/lessons](https://github.com/search?q=repo%3ATheOdinProject%2Ftheodinproject++db%2Ffixtures+path%3A%2F%5Edb%5C%2Ffixtures%5C%2Flessons%5C%2F%2F&type=code)

Two broad solutions I can see are either trying to do it programatically, or removing the `capitalize` class from the `h1` element and manually ensuring the titles are formatted correctly.

There isn't really a good option for the former that I know of - the [Rails method `titlecase` ](https://www.rubydoc.info/docs/rails/String:titlecase)has the same behaviour as the CSS class, so t hat would mean finding a library or writing our own, which I don't think would be worth it.

The second option might have a bit more manual work but should be very straightforward. At a glance it looks like many of the titles are already correctly cased, so it would probably just be a matter of looking through the courses and checking for inconsistencies.

Ithink you'd be more than capable of taking this one on if you're interested - happy to assist if you need help setting up the app, but reading through the installation lessons for Ruby, Rails and Postgres in the Rails path should get you most of the way there.
