### ISSUE TITLE
Advice for the root page

### ISSUE THREAD

**Issue by OlehSliusar** [TheOdinProject/theodinproject#382]
It would be better for logged in users to have [this page](http://www.theodinproject.com/courses) as the home page instead of [this page](http://www.theodinproject.com/home). Because from current home page I can't even go directly to my profile, and it would be great to see my progress on the curriculum every time I visit www.theodinproject.com

**Comment by KevinMulhern** [comment]
Hey @OlehSliusar, did you see the link to the redesign I posted in gitter the other day?
https://marvelapp.com/1gii457/screen/24177849

We will be doing something very similar to what you suggested 😄 logged in users home page will be a dash board that will allow them to see their progress and jump back into their last lesson
