### ISSUE TITLE
Showing course completion

### ISSUE THREAD

**Issue by OlehSliusar** [TheOdinProject/theodinproject#383]
What about to show course completion on http://www.theodinproject.com/courses page? Something like [this](http://image.prntscr.com/image/27fc0b2deb7e4b2eb46d7f1b9bafeb00.png)

**Comment by KevinMulhern** [comment]
Hey @OlehSliusar This is something that might be part of the redesign. We just have a few more mock ups to finish and then we will show them to the TOP community for feedback and suggestions 😄
