### ISSUE TITLE
Bug: Wiki needs updating: suggestion/bugs Discord Channel not in use anymore for GH issues

### ISSUE THREAD

**Issue by ManonLef** [TheOdinProject/theodinproject#3837]
Complete the following REQUIRED checkboxes:

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `Bug: brief description of bug` format, e.g. `Bug: Lesson complete button does not update on click`

The following checkbox is OPTIONAL:

-   [x] I would like to be assigned this issue to work on it

wiki's can't easily be collaborated on. I'd be happy to create and edit a personal version that you can then copy over into the wiki. 

<hr>

**1. Description of the Bug:**

At the bottom of the wiki guide for running TOP locally, there's a link to discord for when you encounter issues. 

I suggest linking to the GH `issues` page for the curriculum instead

**2. How To Reproduce:**

Not applicable

**3. Expected Behavior:**

Not applicable

**4. Desktop/Device:**

Not relevant

**5. Additional Information:**

**Comment by ManonLef** [comment]
@ChargrilledChook I do not and either way works for me. I'll have my draft ready!

**Comment by ManonLef** [comment]
https://gist.github.com/ManonLef/9ff7609277664f5a2c66c33edec09974 You can find my draft here

**Comment by ManonLef** [comment]
@ChargrilledChook not sure if you saw the above since I didn't tag you, but it can just be copy pasted into the wiki if you want.

**Comment by KevinMulhern** [comment]
Thanks for doing this @ManonLef 🙌 
I updated that page with your new content: https://github.com/TheOdinProject/theodinproject/wiki/Running-The-Odin-Project-Locally

If that all looks good to you, we'll get this issue closed.

**Comment by ManonLef** [comment]
@KevinMulhern LGTM 😊
