### ISSUE TITLE
Subtle design improvement

### ISSUE THREAD

**Issue by OlehSliusar** [TheOdinProject/theodinproject#384]
[See a screenshot](http://image.prntscr.com/image/79930dd89da14173bcd505151640e3f7.png). Maybe move it to bottom a bit?

**Comment by KevinMulhern** [comment]
@OlehSliusar this will be part of the redesign too. Thanks for opening these issues, but I think it might be misplacing effort, time and resources to make any improvements to the current design when the new design is so close to being implemented. All of these improvements will probably be implemented with the new design or changed to something else entirely.

Keep an eye out for when we release the full mock ups for the new site, we will greatly value any suggestions and feedback you can provide for those 😄
