### ISSUE TITLE
Bug: Before Asking Page 404 Error

### ISSUE THREAD

**Issue by br55r** [TheOdinProject/theodinproject#3840]
Complete the following REQUIRED checkboxes:

-   [ x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [ x] The title of this issue follows the `Bug: brief description of bug` format, e.g. `Bug: Lesson complete button does not update on click`

The following checkbox is OPTIONAL:

-   [ ] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Bug:**

![image](https://github.com/TheOdinProject/theodinproject/assets/132231719/e269c873-3d0a-47be-a1db-e362b0055c1a)
https://www.theodinproject.com/before_asking

It seems the page is not showing the information I need or maybe a broken link..

**2. How To Reproduce:**
 
This page seems to be broken on multiple devices

**3. Expected Behavior:**

I expected the page to work.

**4. Desktop/Device:**

-   Device:  Iphone 12
-   OS:  Xubuntu / Windows
-   Browser:  Chrome
-   Version:  114

**5. Additional Information:**

**Comment by CouchofTomato** [comment]
Thanks @br55r 

Can I just ask where you are clicking to link to this?

**Comment by br55r** [comment]
Of course!
You can find the clickable link on "Do Your Own Legwork"
https://www.theodinproject.com/guides/community/how_to_ask

**Comment by ManonLef** [comment]
This is the current link it should lead to; https://www.theodinproject.com/guides/community/before_asking

**Comment by Asartea** [comment]
Would be willing to tackle this; seems there is only two places where this is wrong (although that does raise the larger question if there should be some better system than hardcoding those links"

**Comment by CouchofTomato** [comment]
What kind of better system?

**Comment by Asartea** [comment]
Ideally there'd be some way to ensure these links get updated whenever the actual page location changes; right now they are just hard-coded relative links, which means every time the website gets restructured someone needs to remember to re sync all those links to the new location

**Comment by CouchofTomato** [comment]
I don't disagree but I'm not sure how easy that would be.

We could potentially run some sort of check for dead links maybe.

**Comment by Asartea** [comment]
Something to consider in a later issue; will file a PR to fix these at least for now
