### ISSUE TITLE
Enhancement: Fix redirection on Success Stories section 

### ISSUE THREAD

**Issue by haveariceday** [TheOdinProject/theodinproject#3851]
Complete the following REQUIRED checkboxes:

- [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
 - [x] The title of this issue follows the brief description of request format, e.g. Add dark mode to website
 
The following checkbox is OPTIONAL:

 - [ ] I would like to be assigned this issue to work on it
1. Description of the Feature Request:

On the main landing page, there is “Success Stories” section. This section has students’ icons, names, the beginning sentence of the stories, and a button to go to the static page of the success stories.
When clicking on their names, each leads to the student’s social media link if it is specified on this [file](https://github.com/TheOdinProject/theodinproject/blob/main/db/seeds/success_stories.rb). However, if the student does not specify anything, then the click takes it to the very top of the landing page. It is the same response on their [static page](https://github.com/TheOdinProject/theodinproject/blob/main/app/views/static_pages/success_stories.html.erb) as it is rendered. I believe it will make more sense if clicking anywhere on this section can lead to the success stories page instead of going to different websites or the front of the landing page.

![Screenshot 2023-06-14 140654](https://github.com/TheOdinProject/theodinproject/assets/65250204/20209ccd-3e35-4626-bb2b-41ecc27add79)
2. Acceptance Criteria:

Click on the card on the Success Stories section on the landing page and it takes you to the static page
On the static page, click on the user without the social media link and it does nothing (maybe remove '#' on the [file](https://github.com/TheOdinProject/theodinproject/blob/main/db/seeds/success_stories.rb))

3. Additional Information:

**Comment by wise-king-sullyman** [comment]
I could definitely see the interaction here feeling odd, and it doesn't seem _ideal_ to me from an a11y perspective since when browsing the page with a screenreader you would just a bunch of names that are ambiguous in where they lead, and sometimes don't lead anywhere.

@TheOdinProject/maintainers thoughts?

**Comment by rlmoser99** [comment]
I agree that this is an awkward UX. I'm not sure I like the proposed solution though because it feels like an after thought & still slightly awkward.

I'd opt for a redesign of this area. Maybe just have the names and pictures of people in on the main homepage. Then if you click on a name, it takes you to that person's story on `https://www.theodinproject.com/success_stories`. 

(That and maybe some new success stories too!)

**Comment by wise-king-sullyman** [comment]
I like the sound of that!

**Comment by BigO-Dev** [comment]
Has anyone been assigned this issue? If not, I'd like to volunteer. 

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md?rgh-link-date=2023-06-14T21%3A13%3A08Z)
- [X] The title of this issue follows the brief description of request format, e.g. Add dark mode to website

The following checkbox is OPTIONAL:

- [X] I would like to be assigned this issue to work on it

**Comment by rlmoser99** [comment]
Before we assign it, I'd really like to see what @KevinMulhern thinks of this idea.

> I'd opt for a redesign of this area. Maybe just have the names and pictures of people in on the main homepage. Then if you click on a name, it takes you to that person's story on https://www.theodinproject.com/success_stories.

**Comment by BigO-Dev** [comment]
I am intrigued by the idea of redesigning the Homepage/Success Stories. A dedicated page showcasing the success stories of TOP could attract more people to sign up. In the Discord community, I have noticed people asking if anyone has landed a job and how long it took. A prominent page displaying people's success stories can alleviate such doubts. It should be one of the first things visible on the landing page.

I suggest we split the approach into two phases. In phase one, we can implement the proposed solution of changing the home page success stories links to anchor links. Once clicked, users would be directed to the success stories page and auto-scrolled to the specific story they clicked. Social links for the story can be displayed on the story card. In phase two, we can consider various redesigns for the Success Stories page. These are just my thoughts; what do you think?

**Comment by KevinMulhern** [comment]
Thank sounds good to me @BigO-Dev.

@rlmoser99 @wise-king-sullyman do you have any thoughts about this approach?

**Comment by wise-king-sullyman** [comment]
Sounds great to me as well!

**Comment by rlmoser99** [comment]
Yes, this sounds like a good approach!

**Comment by KevinMulhern** [comment]
This is all yours @BigO-Dev 💪

**Comment by KevinMulhern** [comment]
Hey @BigO-Dev, I'm doing some house keeping on the repo today.

Do you still want to work on this one or would you like us to open it up for someone else to take on?

**Comment by KevinMulhern** [comment]
Thanks @ZachBaird 😄
