### ISSUE TITLE
Bug: Logging in via Google accounts to the TOP website does not work

### ISSUE THREAD

**Issue by ensarokumus** [TheOdinProject/theodinproject#3853]
<hr>

**1. Description of the Bug:**
On the main page of TOP website, the logging in option via Google accounts does not work.

**2. How To Reproduce:**

What steps one might need to take in order to reproduce this bug, e.g.:
1. Visit https://www.theodinproject.com/sign_in
2. Click on Google accounts button
3. Nothing happens

**3. Expected Behavior:**

A brief description of what you expected to happen, e.g.:
1. Visit https://www.theodinproject.com/sign_in
2. Click on Google accounts button
3. Log in via Google account credentials

**4. Desktop/Device:**

-   Device: HP laptop
-   OS:  Ubuntu 23.04 
-   Browser: Chrome
-   Version: Version 114.0.5735.133 (Official Build) (64-bit)

**Comment by Eduardo06sp** [comment]
I experienced the same issue.

I did notice I could log in normally just using my username & password, but I can't access the login via GH/Google.

**Comment by xandora** [comment]
Same for me on mobile with Chrome and Firefox.
