### ISSUE TITLE
Bug: Going back on the website

### ISSUE THREAD

**Issue by FelinationGX** [TheOdinProject/theodinproject#3863]
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `Bug: brief description of bug` format, e.g. `Bug: Lesson complete button does not update on click`

The following checkbox is OPTIONAL:
-   [ ] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Bug:**
When clicking on the back button at the top right of the browser the "Lesson content" duplicates itself. (Happens to all browsers and every lesson)
Normal
![image](https://github.com/TheOdinProject/theodinproject/assets/85888089/7c531817-379a-4370-8560-20b091abd0f2)
Bug
![image](https://github.com/TheOdinProject/theodinproject/assets/85888089/1341e369-3062-4424-b37a-03abe7b7603b)

**2. How To Reproduce:**
1. Go on any page of TOP where you can learn stuff
2. Scroll down and click on next lesson
3. Click the back button on the top left in your browser
4. It duplicates the "Lesson content"

**3. Expected Behavior:**
1. Go on any page of TOP where you can learn stuff
2. Scroll down and click on next lesson
3. Click the back button on the top left in your browser
4. The "Lesson Content" does not duplicate

**4. Desktop/Device:**

-   Device: PC
-   OS: Windows and Xubuntu
-   Browser: Chrome and Opera

**Additional Information:**
It works fine when refreshing the browser

**Comment by wise-king-sullyman** [comment]
Seems like something that should be fixed to me. Thanks!

**Comment by KevinMulhern** [comment]
I haven't been able to recreate with the steps to reproduce (chrome/firefox) but it is very likely related to us recently enabling turbo globally.

The caching introduced in [this PR](https://github.com/TheOdinProject/theodinproject/pull/3718) _could_ possibly be conflicting with turbos caching mechanism.

**Comment by luuu-xu** [comment]
I can reproduce this bug as well, on Firefox, Chrome and Safari. I am on MacOS.

**Comment by KevinMulhern** [comment]
Thanks for raising this @FelinationGX, @luuu-xu. I missed it was the lesson contents table on the side of the page 🙈 
I'm too used to associating "lesson content" with the actual content of a lesson itself and had blinders on lol.

We should have a fix out for this in the next day or so.
