### ISSUE TITLE
Chore: Remove Turbo true Attributes

### ISSUE THREAD

**Issue by KevinMulhern** [TheOdinProject/theodinproject#3873]
**1. Description:**
Previously, we had Turbo disabled globally. We enabled it manually where we needed it by using the `data-turbo='true'` attribute. But, now we have Turbo enabled globally and can remove these attributes.

**2. Acceptance Criteria:**
* Remove `turbo: true` from the [complete/icon_component.html.erb file](https://github.com/TheOdinProject/theodinproject/blob/main/app/components/complete/icon_component.html.erb#L1)
* Remove `turbo: 'true'` from the [theme/switcher_component.html.erb file](https://github.com/TheOdinProject/theodinproject/blob/main/app/components/theme/switcher_component.html.erb#L5)
* Remove `data-turbo="true"` from the [complete/button_component.html.erb file](https://github.com/TheOdinProject/theodinproject/blob/main/app/components/complete/button_component.html.erb#L2)

**Comment by hebiscus** [comment]
Could I take it?

**Comment by KevinMulhern** [comment]
It's all yours, thanks @hebiscus
