### ISSUE TITLE
Feature: Email field is autofocused when visiting sign in page

### ISSUE THREAD

**Issue by KevinMulhern** [TheOdinProject/theodinproject#3874]
**1. Description of the Feature Request:**
_When I'm signing in, then I want the email field to be focused automatically, so I can start entering my credentials straight away_

**2. Acceptance Criteria:**

1. Click the "Sign in" link on the navbar
2. The email field should be auto focused.

**Comment by j-mcQueen** [comment]
Hey, I'd love to work on this! I'll also put my name in the hat to work on #3875, but if you'd rather give someone else an opportunity to do that one I'd totally understand.

**Comment by KevinMulhern** [comment]
Thanks @j-mcQueen, this ones all yours.

**Comment by j-mcQueen** [comment]
Great! I'll get working on this after wrapping up some projects today.
