### ISSUE TITLE
Chore: (re)consider how TOP handles error pages

### ISSUE THREAD

**Issue by Asartea** [TheOdinProject/theodinproject#3876]
Complete the following REQUIRED checkboxes:
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `brief description of request` format, e.g. `Add dark mode to website`

The following checkbox is OPTIONAL:
-   [x] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Feature Request:**

Ruby on Rails offers three ways of handling error pages:
1. Static pages in the `/public` folder
2. A custom defined controller
3. Route based matching and mappping via `routes.rb`

Currently TOP uses a mix between 1 and 2; `422.html` and `500.html` are static pages in `/public`, while `404.html` gets handled with a custom controller.

Both of these approaches however offer disadvantages:
* Pages in the `/public` folder are outside the app scope, so they can't be `.erb` files or use tools such as Tailwind, necessitating hardcoding links and CSS.
* While the custom controller as such is not bad, its essentially just a complex way of achieving the same effect as directly using `routes.rb`

Moving to route based handling would simplify both of these, but also offers risks: if something else that that code relies on also contains a error, Rails will be unable to render custom pages, and will instead emit plaintext error pages. Per @KevinMulhern  however, this only affects exceptions raised from within app itself, as Heroku already handles it otherwise. This risk should therefore be minimizable by reducing the amount of shared code and having full test coverage  

**2. Acceptance Criteria:**
- [ ] A single way to handle error page is decided upon
- [ ] All error pages use this method

**Comment by CouchofTomato** [comment]
@KevinMulhern Anything to add to this mate?

**Comment by KevinMulhern** [comment]
Not much to add @CouchofTomato, @Asartea and I were Dm'ing about this before the issue was made.

To reduce the risks of the errors controller possibly not rendering custom error pages due to an exception in that part of the app, we talked about:
* Changing the ErrorsController to inherit from `ActionController::Base` instead of `ApplicationController`
* Increased test coverage by adding request specs for all actions in the errors controller

**Comment by Asartea** [comment]
So I was poking at this, and switching to a error controller that inherits from `ActionController::Base` has one major disadvantage: by decoupling from `ApplicationController` it also decouples it from the default layout, and re implementing that layout in full would essentially bring all of the `ApplicationController` code, which kind of defeats the point of decoupling in the first place. We could either design an entire new layout, or decouple `500` from `404` and `422`, with `500` gettings its own controller which inherits from `ActionController::Base` and has its own layout, while `404` and `422` still use `ErrorsController` and inherit from `ApplicationController`

**Comment by KevinMulhern** [comment]
Nice find @Asartea, we can use a new, minimal layout file for this. Something similar to the layout file we have for [component previews](https://github.com/TheOdinProject/theodinproject/blob/main/app/views/layouts/component_preview.html.erb) should do the job.

It we name the new layout file `errors.html.erb` - the errors controller should just pick it up automagically.
