### ISSUE TITLE
Typography error

### ISSUE THREAD

**Issue by just-Muzz** [TheOdinProject/theodinproject#3879]
A typographical error is in the "Hall of Fame" section on the contributing page.
![Screenshot 2023-06-25 122053](https://github.com/TheOdinProject/theodinproject/assets/102549811/fa47b030-1050-4c93-a7f4-f9a32862818e)

**Comment by manrajsandhu23** [comment]
There is no problem in this sentence. It states that the members of the Hall of Fame are the hardworking developers who have built The Odin Project into the website that is currently being viewed.
