### ISSUE TITLE
Fix: Remove hardcoded ids in project submission serializer spec

### ISSUE THREAD

**Issue by ChargrilledChook** [TheOdinProject/theodinproject#3897]
The project submission serializer specs (`spec/serializers/project_submission_serializer_spec.rb`) contain several hard-coded ids. Since FactoryBot increments ids each time a factory is created, there is potential for these specs to flake depending on the randomised run order. 

[Example failure:](https://app.circleci.com/pipelines/github/TheOdinProject/theodinproject/5520/workflows/2332dfb1-2297-46bf-96f2-1825794b85e8/jobs/15650)

```
Failures:

  1) ProjectSubmissionSerializer#as_json 
     Failure/Error: let(:current_user) { create(:user) }
     
     ActiveRecord::RecordNotUnique:
       PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "users_pkey"
       DETAIL:  Key (id)=(123) already exists.
     # ./spec/serializers/project_submission_serializer_spec.rb:18:in `block (2 levels) in <top (required)>'
```

The spec should be refactored to remove the potential clash / flakyness and be deterministic.

**Comment by jonichi16** [comment]
Hi, can I work on this? Thanks. :)

**Comment by jonichi16** [comment]
Hi. Can I work on this? Thanks :)

**Comment by ChargrilledChook** [comment]
@jonichi16 All yours :+1:
