### ISSUE TITLE
Add tick-boxes for assignment steps in lessons.

### ISSUE THREAD

**Issue by Demo318** [TheOdinProject/theodinproject#390]
Oftentimes, the assignment has 1 to 5 steps, each of which might take a significant amount of time. I don't always do these in one sitting. It would be super if I could check them off as I go so when I return later, I can recall which sections of the assignment I had completed more easily. Thanks!

**Comment by KevinMulhern** [comment]
Hey @Demo318 thanks for opening this issue, I agree that this would be a awesome feature to have 😄 

Implementing it, presents a technical challenge though. Currently the content for each lesson is pulled in from our curriculum repo as markdown files. That included the assignments. I'll add this to our development backlog.

**Comment by KevinMulhern** [comment]
This is on our dev backlog 😄 thanks for opening it @Demo318
