### ISSUE TITLE
Add lock section to submitted projects

### ISSUE THREAD

**Issue by adisuyash** [TheOdinProject/theodinproject#3905]
Complete the following REQUIRED checkboxes:

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `brief description of request` format, e.g. `Add dark mode to website`

The following checkbox is OPTIONAL:

-   [ ] I would like to be assigned this issue to work on it

<hr>

### 1. Description of the Feature Request:

I found that the projects submitted during learning are available in the public & anyone can clone that project and resubmit it.
So I suggest to protect the submissions by adding a **SUBMIT FIRST** then check the other submissions.

### 2. Acceptance Criteria:

I know that in the curriculum, it is mentioned specifically not to check others' projects
but
I think that it would be most helpful for learners to create & submit their self-made projects first😊

### 3. Additional Information:

Here's the reference screenshots I have found in some websites -
![image](https://github.com/TheOdinProject/theodinproject/assets/116362593/fab959df-fba1-4785-aa73-2cbef10c31a9)

**Comment by rlmoser99** [comment]
Thank you for taking the time to submit your idea. However, we have discussed a similar idea in the past and the majority of our team does not see this as an issue that needs to be resolved. We believe that anyone who has the mindset to look at submissions for answers will also work to get around any measures that we put in place to stop them.

https://github.com/TheOdinProject/theodinproject/issues/2244

**Comment by adisuyash** [comment]
> Thank you for taking the time to submit your idea. However, we have discussed a similar idea in the past and the majority of our team does not see this as an issue that needs to be resolved. We believe that anyone who has the mindset to look at submissions for answers will also work to get around any measures that we put in place to stop them.
> 
> #2244

Okay @rlmoser99 😊
