### ISSUE TITLE
Another origin question in FAQ

### ISSUE THREAD

**Issue by CBID2** [TheOdinProject/theodinproject#3917]
I was looking through the FAQ section, and I couldn't help but imagine people wondering who originally started TOP(I asked this myself). I think adding this question would help readers learn more about the curriculum.

Complete the following REQUIRED checkboxes:

-   [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [X] The title of this issue follows the `brief description of request` format, e.g. `Add dark mode to website`

The following checkbox is OPTIONAL:

-   [X] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Feature Request:**

When I go to the FAQ section, I want to learn more about how the project started.

**2. Acceptance Criteria:**

**3. Additional Information:**

As usual, I'm open to collaborate

**Comment by ManonLef** [comment]
That’s already mentioned in the [about page](https://www.theodinproject.com/about) which I think makes sense since those pages usually mention the background of a company.
