### ISSUE TITLE
Look into changing TOP's link color on lightmode

### ISSUE THREAD

**Issue by Asartea** [TheOdinProject/theodinproject#3918]
Complete the following REQUIRED checkboxes:

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `brief description of request` format, e.g. `Add dark mode to website`

The following checkbox is OPTIONAL:

-   [x] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Feature Request:**
During #3915 I ran Google Lighthouse to test the accessibility impact of those changes, and discovered as a side effect that our current light mode link color (tailwind gold-600) doesn't meet the WCAG AA standards for contrast, and the same goes for it as a background with white text (on eg the "Next Lesson" button). In that PR @KevinMulhern mentioned

> Thanks for reporting that back @Asartea. I think we should start a separate discussion about changing the link colors. There are some UX improvements beyond just improving accessibility we could gain from changing to a different color.

We should look into if we want to change those colors, and if so to what

**2. Acceptance Criteria:**
```[tasklist]
### Acceptance Criteria
- [x] A color is decided upon, which should ideally apply to as much of the light mode as possible
- [ ] All currently inacessible elements are converted to this new color
```

**Comment by KevinMulhern** [comment]
My preference would be tried and tested blue. Besides being very familiar and fixing the accessibility issue, it would also allow us to easily add a purple visited state to links. Similar to how Wikipedia and Google do it. 

With the amount links we have throughout our lesson content, something that helps users keep track of what they've already visited would be a **big** QOL improvement.

Exact colors would probably be slightly different, but just to give an idea:
<img width="1501" alt="Screenshot 2023-07-06 at 17 28 55" src="https://github.com/TheOdinProject/theodinproject/assets/7963776/e1844d3f-0786-4ba5-a60b-79430c37ebbc">

<img width="1494" alt="Screenshot 2023-07-06 at 17 23 23" src="https://github.com/TheOdinProject/theodinproject/assets/7963776/2fed676c-3f5c-4501-a87c-582082b4c464">

**Comment by Asartea** [comment]
Hows the contrast for those links on dark mode?


Also I was playing around with some of Wikimedia's colors, and as a far more radical change, I was messing around with this:
![image](https://github.com/TheOdinProject/theodinproject/assets/76259120/c11e2c09-f091-4440-914e-0b236bd4ee0c)
![image](https://github.com/TheOdinProject/theodinproject/assets/76259120/9e1c5728-1a87-492a-845b-f2a4a4976e64)


This is a much bigger change, but is easily recognizable as links, and provides WCAG AAA contrast. Would also need to look how any proposed colors look on buttons, which suffer from the same issue.

**Comment by KevinMulhern** [comment]
> Hows the contrast for those links on dark mode?

It's pretty good, just needs tweaked to be one shade lighter to pass all contrast checks
<img width="500" alt="Screenshot 2023-07-06 at 23 13 51" src="https://github.com/TheOdinProject/theodinproject/assets/7963776/1be70aa7-04ba-42be-a795-aa6c468a384f">

I really like the white, it looks clean ✨. It could maybe be too subtle, but it's really hard to judge by screenshots alone.
Whats your thoughts on having a link visited state? do you think it would be useful?

I missed buttons being mentioned in the issue. It could maybe be split out into its own issue. It does have the same underlying issue, but affects different UI components. 

Buttons should thankfully be straight forward though. No color/transparent buttons work best with secondary UI actions

<img width="1155" alt="Screenshot 2023-07-06 at 23 26 03" src="https://github.com/TheOdinProject/theodinproject/assets/7963776/610e8af8-1cce-43da-9f17-32ad02df47e8">

<img width="1167" alt="Screenshot 2023-07-06 at 23 20 57" src="https://github.com/TheOdinProject/theodinproject/assets/7963776/0fb1c7cd-c975-424b-829a-573cbf2da25e">


We've been moving that way with all of our most recent features.

**Comment by luuu-xu** [comment]
I was actually working on another open-source project's a11y improvement and noticed TOP's colour contrast issues too. I like the blue! Especially with the purple visited state on links! I think a **visited** state would indeed improve ux a lot since we have quite some external links to go through.

**Comment by Asartea** [comment]
>  Whats your thoughts on having a link visited state? do you think it would be useful?

Oh absolutely, given the huge amount of external links we have

> No color/transparent buttons work best with secondary UI actions

Hmmm, agred, but I'm not sure what the primary action actually is; I'd argue that "next lesson" is as important/if not more important than the "mark completed" button. I'll file a separate issue for it

**Comment by Asartea** [comment]
Playing around with visited/unvisited:
![image](https://github.com/TheOdinProject/theodinproject/assets/76259120/6499912d-bab5-41ac-9cde-5efd8dba7771)
![image](https://github.com/TheOdinProject/theodinproject/assets/76259120/9903e2eb-93db-4df6-b7d1-a69487b28719)


I'm not really sold on the dark mode visited; I feel like its not clear at a glance what is visisted/unvisited? But this does give us AAA contrast

**Comment by KevinMulhern** [comment]
> I'm not really sold on the dark mode visited; I feel like its not clear at a glance what is visisted/unvisited? But this does give us AAA contrast

Yeah I see what you mean, I think dark mode link default colors will have to be blue as well for it to work. [The visited state color is recommended to be a duller and more washed out version of the default color](https://ux.stackexchange.com/questions/46060/dilemma-how-to-determine-the-color-for-active-unvisited-links). Thats why blue and purple work so well and used everywhere. Their right beside each other on the color triangle 🔺

**Comment by Asartea** [comment]
> I think dark mode link default colors will have to be blue as well for it to work
Same visited color, bluer default:
![image](https://github.com/TheOdinProject/theodinproject/assets/76259120/826753fb-aae2-4da8-ad36-166bd26b60ea)

**Comment by KevinMulhern** [comment]
That looks pretty close to me, If we're settled on the overall colors of blue/purple, I think this is ready for PR. It'll be easier to tweak further with something to play with.

**Comment by Asartea** [comment]
Hmmm, a quick question then: These aren't Tailwind colors, but rather me fiddling with some sliders; what would be the preferred way to incorporate them via Tailwind? Also where are the link colors even defined; all I can find is a React component, but I think that is just for the preview tool

**Comment by KevinMulhern** [comment]
We've been using Tailwinds out of the box [color palette](https://tailwindcss.com/docs/customizing-colors) for everything besides the gold branding. They have a pretty good range of blues and purples we can use for this.

Good point about the React and erb file. Changes will need to be made in both for now. We're planning on changing the preview tool to erb soon ™️

**Comment by Asartea** [comment]
Also looking at it, I think it would be best to also define this as a custom class in `app/javascript/stylesheets/typography.css`, mostly for the (lot of) random hardcoded links that are floating around; these currently just set `text-gold-600`, but because I've split link styling into both dark/light and visited/not visited I'd need to replace those all with `text-blue-800 visited:text-purple-800 dark:text-blue-300 dark:visited:text-purple-300`, which feels like it would get overly wordy

**Comment by Asartea** [comment]
Hmm, I've run into a issue I can't quite figure out how to fix:

All of the lesson section headers are also links, so they also get targeted by the new link colors. Now for lightmode that seems to be overriden by this snippet in tailwind.config.js:

https://github.com/TheOdinProject/theodinproject/blob/786ff727d43f1e678d06fcd6cd8a1eed067d85e2/tailwind.config.js#L35-L45

Now that I am specifying explicit `dark:` link colors that seems to be getting ignored in favor of those however, and I can't quite figure out how to get those to be the correct color again

**Comment by KevinMulhern** [comment]
> Also looking at it, I think it would be best to also define this as a custom class in app/javascript/stylesheets/typography.css, mostly for the (lot of) random hardcoded links that are floating around; these currently just set text-gold-600, but because I've split link styling into both dark/light and visited/not visited I'd need to replace those all with text-blue-800 visited:text-purple-800 dark:text-blue-300 dark:visited:text-purple-300, which feels like it would get overly wordy

Sorry, I should have made this clearer before. We only want the blue/purple combo on lesson content. Just the content container and preview components need updated.

The links on other pages are part of UI and don't need to stand out as much, the text usually is a good enough indication what they do. We'll need to do something different for those. Simplest and safest thing to do would be to make them dark gray on light theme and a very light gray on dark theme. Kind of like what you had in one of your early screenshots in this thread.

----

We've had some trouble trying to override the specific of the Tailwinds prose plugins. Some of those overirdes in the config are probably not quite right. I was having a play and I think we should just always inherit off the h3 color. That will cover both themes and we'll always want those links to be the same color as their h3 parent.

```css
.lesson-content h3 a {
  color: inherit !important;
}
```
