### ISSUE TITLE
Restore link underlines or increase contrast between links and body text

### ISSUE THREAD

**Issue by crystalsolenoid** [TheOdinProject/theodinproject#3931]
Complete the following REQUIRED checkboxes:

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `brief description of request` format, e.g. `Add dark mode to website`

The following checkbox is OPTIONAL:

-   [ ] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Feature Request:**

Commit 3f6cf7f improved the contrast of links to meet WCAG AAA contrast standards with the background, which is awesome. However I'm really struggling with the removal of underlines in this commit. I can feel the eyestrain coming on, and I can't just hover the mouse over everything I read... especially on mobile, where I do most of my reading. The 500 font-weight is a nice thought, but it's too subtle to help.

I really value the links given throughout the lessons to give more context, and open every one-- at least take a peek. This change is going to increase my cognitive load as I try to read and recognize hard-to-see links at the same time. Being able to go back and skim for resources I remember seeing in earlier lessons (either to help myself or someone on Discord) is another case I'm worried about with this change.

I found this WCAG technique [G183: Using a contrast ratio of 3:1 with surrounding text and providing additional visual cues on focus for links or controls where color alone is used to identify them](https://www.w3.org/TR/2008/NOTE-WCAG20-TECHS-20081211/G183) and this blog post [The Contrast Triangle](https://chipcullen.com/the-contrast-triangle/) and companion tool [The Contrast Triangle (tool)](https://contrast-triangle.com/?linkColor=rgb%2830%2C64%2C175%29&textColor=rgb%2855%2C65%2C81%29&underlines=false) that helped me be able to articulate what was bothering my eyes so much with the underline removal. Underline removal means that there needs to be serious attention paid to the contrast between the links and _the surrounding text_, not just between the links and the background. In light mode, according to that tool, TOP currently has a 1.18:1 ratio between link and surrounding text. I think that the slight boldness doesn't help because this contrast is just too far off.

Getting a 3:1 contrast between link and body text colors while maintaining AAA contrast with the background is a difficult design constraint. If that proved to be too difficult, the much easier way of restoring link underlines might be better.

The underline removal was justified citing other parts of TOP and the convention set by large websites like Google and Wikipedia. Other parts of TOP have a user interface context that makes underlines or link contrast less needed. A link in the body of a paragraph is a very different context. Google and Wikipedia are extremely link-heavy websites. Google uses very large click-areas for its links so it's less required to find which text is the link, and has a strong user interface context for those links. It's not uncommon to find a Wikipedia paragraph with over 50% link text, which would be made unreadable if underlined.

The Odin Project's lessons are prose (no UI context to help) and have a low-to-moderate link density within the prose. I suggest we look at web development documentation and blog posts to get a more representative TOP-relevant section of the web to compare against. Of the four I looked at which I've become familiar with through where I'm at (just finished Foundations!), [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML), [Chrome's devtools documentation](https://developer.chrome.com/docs/devtools/console/), and [W3Schools](https://www.w3schools.com/tags/ref_eventattributes.asp) all use underlines for their links within a page's main content. ([Javascript.info](https://javascript.info/hello-world) was the one that didn't.)

Whew, that was a lot. Thank you for considering my request :)

**2. Acceptance Criteria:**

- [ ] Link and body text colors for light mode have a contrast ratio of 3:1
- [ ] Link and body text colors for dark mode have a contrast ratio of 3:1
- [ ] Link and body contrasts with the background all meet AAA standards

OR

- [ ] Links have underlines

OR maybe (I'm not sure if it's enough.)

- [ ] Boldness is increased to 700
- [ ] Link and body text colors for light mode have a contrast ratio of 2.5:1
- [ ] Link and body text colors for dark mode have a contrast ratio of 2.5:1
- [ ] Link and body contrasts with the background all meet AAA standards

**3. Additional Information:**

[WebAIM has a tool for contrast checking links, too.](https://webaim.org/resources/linkcontrastchecker/?fcolor=374151&bcolor=FFFFFF&lcolor=1E40AF)

**Comment by Asartea** [comment]
A very faiur point this; I had indeed not fully considered the effect this would have on differentiating links from normal prose text. One of my concerns with the underlines was say the set of links in a typical knowledge check section, were its not unusual to have ~10 links all stacked on top of each other; I feel that gets cramped, and also due to the nature of the section (its always only links), I also feel it needs less indication.


What do you think of restoring underlines in normal prose, and then excluding them specifically in the knowledge check section? My one concern with that would be visual inconsistency. Alternatively I'm not married to the no underlinks.

## Screenshots
### Current
https://github.com/TheOdinProject/theodinproject/assets/76259120/0d2f13c1-7396-4665-99b1-c90ce570f30c

### Underlines everywhere
https://github.com/TheOdinProject/theodinproject/assets/76259120/ae19eeab-f922-410e-bac8-fb86ea3c90ba

### Underlines everywhere except knowledge section
https://github.com/TheOdinProject/theodinproject/assets/76259120/8a8eaad9-cb9e-48d0-b57c-afbdf7b75bd3

**Comment by KevinMulhern** [comment]
Thanks for the detailed write up @crystalsolenoid 

We're getting quite a bit of feedback about this on GH and Discord. I think we should add the underline back as default for now to see if that improves things for users. We can discuss doing something different with knowledge links once the pressure is off.

**Comment by crystalsolenoid** [comment]
Thanks, both of you.

@Asartea, I agree that the context of those knowledge check sections is different, and that might justify a different decision there. The links feeling cramped in those big lists is a real readability concern, and it deserves to get taken seriously too.

I'm not so sure that it's worth the inconsistency to fix it by changing how links look, because links are a core interactive feature that needs to be predictable. It would fix my problem, but I wouldn't want someone to assume they aren't links and not have access to that information. But I don't think it's the _only_ way to fix it, either.

One really easy solution for the links feeling cramped would be to just give them what they want: more space! What if list elements had more vertical padding in the knowledge check section? I have other ideas, but that one's just so simple, it begs to be tried first.

**Comment by KevinMulhern** [comment]
Forgot to close this yesterday (https://github.com/TheOdinProject/theodinproject/pull/3934) thanks again for reporting @crystalsolenoid 💪
