### ISSUE TITLE
Bug: 404 page link has bad contrast on dark theme

### ISSUE THREAD

**Issue by cColds** [TheOdinProject/theodinproject#3932]
Complete the following REQUIRED checkboxes:

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `Bug: brief description of bug` format, e.g. `Bug: Lesson complete button does not update on click`

The following checkbox is OPTIONAL:

-   [ ] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Bug:**

![invalidpath](https://github.com/TheOdinProject/theodinproject/assets/103373668/c50abe20-af71-4d6f-aff0-53cfe0491437)
The links are inaccessible on dark theme and has a contrast of 1.21.

**2. How To Reproduce:**

Visit theodinproject.com/lessons/invalidpath (just an example, any path that doesn't exist will work).
Note: Adding lessons as the first path followed by another invalid path to the domain name seems necessary. I tried omitting it and the contrast is fine because the nav is gone and can't change the theme. Example: theodinproject.com/invalidpath works fine

**3. Expected Behavior:**

The contrast between the links and the background color to have a good contrast.

**Comment by Asartea** [comment]
Could probably just switch these to a light white ish or the new color we use within the lessons; that ought to make it clear enough what is happening.

> Note: Adding lessons as the first path followed by another invalid path to the domain name seems necessary. I tried omitting it and the contrast is fine because the nav is gone and can't change the theme. Example: theodinproject.com/invalidpath works fine

Okay, I have no clue whats going on there; that seems worthy of a follow up issue. I have no clue what could have caused that to start happening.

**Comment by ManonLef** [comment]
@KevinMulhern perhaps you have any insights here since you've been keeping an eye on all the recent changes?

**Comment by Asartea** [comment]
Okay, so this is probably my not-fault; The no navbar/footer behavior is expected; this is part of the changes #3906 ; we opted to go for this because otherwise we'd need to have used a separate controller due to layout issues. I am just not certain how in the `/lessons/` path it is showing up again; somewhere rails is changing which layout its using

**Comment by KevinMulhern** [comment]
Thats something we're doing when[ Rails can't find a db record](https://github.com/TheOdinProject/theodinproject/blob/main/app/controllers/application_controller.rb#L11). Thats ok though. We just need some dark mode variants for those links.
