### ISSUE TITLE
Chore: Bump to Shakapacker v7

### ISSUE THREAD

**Issue by KevinMulhern** [TheOdinProject/theodinproject#3946]
**1. Description of the Feature Request:**
A new major version of Shakapacker just dropped.

* [Dependabot attempted to bump us but CI is failing](https://github.com/TheOdinProject/theodinproject/pull/3944)
* [Upgrade guide can be found here](https://github.com/shakacode/shakapacker/blob/master/docs/v7_upgrade.md)

**2. Acceptance Criteria:**
- [ ] CI passes with Shakapacker v7
- [ ] Review app builds with Shakapacker v7

**Comment by ahasunos** [comment]
I could help with this issue.

**Comment by ahasunos** [comment]
However, we have the latest version of Shakapacker here as 7.1.0 https://rubygems.org/gems/shakapacker/versions/7.1.0
