### ISSUE TITLE
Feature: Give homepage hero background full width and height

### ISSUE THREAD

**Issue by KevinMulhern** [TheOdinProject/theodinproject#3949]
**1. Description of the Feature Request:**

When initially loading the homepage, the hero background moves around or jitters a little. This is caused by the browser trying to work out the images width and height.

We need to give [this element ](https://github.com/TheOdinProject/theodinproject/blob/main/app/views/static_pages/home.html.erb#L15) Tailwinds full width and height classes.

**2. Acceptance Criteria:**
- [ ] The hero background image does not move on page load.

**3. Additional Information:**
After page load, the page will be cached by the browser and subsequent loads will not show the image moving. In order to recreate again and verify you've fixed the issue, open an incognito tab to load an uncached version of the home page.

**Comment by yashchaddha** [comment]
Hi @KevinMulhern I would like to contribute on this issue, it would be very helpful if i can be assigned on this one

**Comment by KevinMulhern** [comment]
Hey @yashchaddha, nice work on that other issue 💪. We'd like to give someone else a chance to get a first time contribution under their belt with this one.

**Comment by yashchaddha** [comment]
No problem @KevinMulhern, thank-you for the appreciation.

It would be very helpful if you could review the PR on other one and provide your constructive feedback 

Thanks

**Comment by janaiscoding** [comment]
Hello @KevinMulhern, I would kindly appreciate if you would allow me to have this as my first contribution!

**Comment by ManonLef** [comment]
@janaiscoding all yours!

**Comment by janaiscoding** [comment]
@ManonLef @KevinMulhern Thank you so much for allowing me to contribute!

**Comment by ManonLef** [comment]
We should thank you @janaiscoding ! Thanks so much ☺️

**Comment by KevinMulhern** [comment]
👆 this lol

Thanks for contributing @yashchaddha 🎉

**Comment by yashchaddha** [comment]
Thankyou @KevinMulhern
