### ISSUE TITLE
Feature: Fix header hierachy on main page

### ISSUE THREAD

**Issue by Asartea** [TheOdinProject/theodinproject#3954]
Complete the following REQUIRED checkboxes:

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `brief description of request` format, e.g. `Add dark mode to website`

The following checkbox is OPTIONAL:

-   [ ] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Feature Request:**
- When running lighthouse it points out that our h_x_ ordering isn't quite right; both "How it works" and "Learn everything you need to know" are `h2`, but the items under those headers are all `h4`. They should be `h3`, to make the hierarchy work

**2. Acceptance Criteria:**
- [ ] all the item headers under "How it works" are changed from `h4` to `h3`
 -  "Learn"
 - "Build"
 - "Connect"
- [ ] All the item headers under "Learn everything you need to know" are changed from `h4` to `h3`
 - Ruby
 - Databases
 - Ruby on Rails
 - Intermediate HTML & CSS
 - JavaScript
 - Advanced HTML & CSS
 - NodeJS
 - Getting Hired

**3. Additional Information:**
Could be a good first issue?

**Comment by KevinMulhern** [comment]
Thanks @Asartea, sounds like a great first time issue.

**Comment by yashchaddha** [comment]
I would like to work on this issue, hence would like to request for it to be assigned to me 
Thanks in advance

**Comment by KevinMulhern** [comment]
Thanks @yashchaddha, its yours.

**Comment by yashchaddha** [comment]
Thanks @KevinMulhern

**Comment by yashchaddha** [comment]
Hi @KevinMulhern, have done the required changes and created a pull request regarding the same. Kindly review it as per your convenience and provide your constructive feedback, if any.
Thankyou
