### ISSUE TITLE
Project Solution Report Options

### ISSUE THREAD

**Issue by KevinMulhern** [TheOdinProject/theodinproject#3957]
**Summary**
At the moment, we only provide users with a text input when they need to report a project solution. This often leads to confusion and the report feature being misused by some users.

<img width="300" alt="Screenshot 2023-07-11 at 23 11 42" src="https://github.com/TheOdinProject/theodinproject/assets/7963776/029f11d0-cdc5-4e7d-8c09-b90ace992420">

**Solution**
Providing a list of options to choose from is a standard feature of report forms on other sites; we should do that too.

For example, this is the report form on YouTube:
<img width="300" alt="Screenshot 2023-07-11 at 23 12 44" src="https://github.com/TheOdinProject/theodinproject/assets/7963776/e202697c-88ef-453d-bb44-8bcefe6f23fc">

These two options will cover most of the legitimate reports we get:
* The project solution links do not work
* The project solution contains inappropriate imagery or language

But we'll need to cover more scenarios. So I've made this issue to gather up ideas from the wider community. Any and all ideas are welcome.

**Additional Information**
We will still include the text input, probably below these new options. It will still be useful for telling us exactly where to look and expanding on the chosen option.

**Comment by KevinMulhern** [comment]
@rlmoser99 you've dealt with lots of reports. I'd hold a lot of value in any input you have with this please 😁

**Comment by rlmoser99** [comment]
Off the top of my head, we sometimes get ones that are site not secure or reported as unsafe, like the ones that are clones of websites. Also an occasional, the links are not to a project code or preview.

Occasionally, we also get a useful one that would not ever be in a list of reasons, like the person who created accounts to like their submission. Would we have an "other" option that people could write their own. I think with the list of reasons, it will be more clear to not report things like "cool project".

**Comment by KevinMulhern** [comment]
Thanks @rlmoser99 💪 

Adding an other option is great idea. Do you think one "link is broken" option would cover dead and insecure links?

**Comment by rlmoser99** [comment]
I think I would keep them separate, but it is not a strong opinion. Looking back at the youtube example, I also like the spam/misleading one. However if you think 5 is too much, I am good with removing the second one.

- does not work
- not secure/safe
- spam/misleading
- inappropriate imagery or language
- other

**Comment by KevinMulhern** [comment]
That list looks great to me - 5 is just enough for a radio list 🔥

**Comment by ZachBaird** [comment]
I can take this.

**Comment by KevinMulhern** [comment]
All yours @ZachBaird 🎸
