### ISSUE TITLE
Fix color of the copyright in the footer

### ISSUE THREAD

**Issue by Asartea** [TheOdinProject/theodinproject#3963]
Complete the following REQUIRED checkboxes:

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `brief description of request` format, e.g. `Add dark mode to website`

The following checkbox is OPTIONAL:

-   [x] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Feature Request:**
For reasons I'm not entirely sure on the copyright statement in the footer "© 2023 The Odin Project. All rights reserved." uses its own unique styling (`text-gray-400`), which presents contrast issues on lightmode. My assumption is that this lighter color was chosen to make it blend in better(?), but honestly I think its just fine if it uses the default text styling (`text-gray-600 dark:text-gray-300`)

**2. Acceptance Criteria:**
- [ ] The styling on these is changed to the default text styling (`text-gray-600 dark:text-gray-300`)

**3. Additional Information:**
Could be a good first issue for someone? In that case I'd rather yield it to someone new than take it on.

Current - lightmode
![image](https://github.com/TheOdinProject/theodinproject/assets/76259120/5ab9adf9-5b34-40a1-9880-c58dae4cea1d)

Current - darkmode
![image](https://github.com/TheOdinProject/theodinproject/assets/76259120/43ab9859-7aec-496c-ace5-1edd8c880f9d)

Changed - lightmode
![image](https://github.com/TheOdinProject/theodinproject/assets/76259120/30fbbf4d-afad-4dcb-81a3-418fd3597f84)

Changed - darkmode
![image](https://github.com/TheOdinProject/theodinproject/assets/76259120/8f0e3581-40b9-4c02-ba8b-a108daebe8f4)

**Comment by KevinMulhern** [comment]
Thanks @Asartea, not sure why we (probably me) choose to make it that light either. This looks like a good change to me.
