### ISSUE TITLE
Fix some headings not following the proper hierachy

### ISSUE THREAD

**Issue by Asartea** [TheOdinProject/theodinproject#3965]
Complete the following REQUIRED checkboxes:

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `brief description of request` format, e.g. `Add dark mode to website`

The following checkbox is OPTIONAL:

-   [x] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Feature Request:**
Some headings aren't following proper hierarchy behavior (ie, they aren't properly arranged in sequential descending order). As a spot check I noticed this on the following pages:

- `/about`, the text "Help the Odin Project stay current and meaningful to all future students, please contribute!" is a `h4`. I think the next higher up is a `h2`, but as the container its in is a direct descendant of the `body` element I think it would make more sense to convert it to a simple `div`
- `/faq`, all the faq headings are `h3` while the "Frequently Asked Questions" itself is `h1`. All of the `h3`'s should be converted to `h2`
- `/paths`, the "start here" and "PATH" headings are `h3`'s. Again I don't think these necessarily make sense as headings; should just be converted to a `div` or a `p`

**2. Acceptance Criteria:**
- [ ] `/about` is fixed
- [ ] `/faq` is fixed
- [ ] `/paths` is fixed

**3. Additional Information:**
Could be a decent first issue?

**Comment by luuu-xu** [comment]
@Asartea Seems like an easy fix, please assign to me so I can submit PR later.

**Comment by ManonLef** [comment]
@luuu-xu all yours

**Comment by luuu-xu** [comment]
@Asartea I was working on fixes and I felt like 
1. for `/about`, the original `h4` for "Help the Odin Project stay current and meaningful to all future students, please contribute!" should be better be changed to a simple `p` since it is a text after all?
2. for `/paths`, I did see "Start here" is originally `h3` and should be a `p`, but I see the two "PATH" are already `p` now. So no need to change them right? I'm just double checking with you.
3. for `/contributing`, I am not sure whether "There are two main ways you can contribute:" should be a `h3`? Maybe a `h2` is better for it since its higher-up is `h1`. And "Hall of Fame" definitely needs to be changed from `h3` to a `h2`. What do you think?

**Comment by Asartea** [comment]
> for /about, the original h4 for "Help the Odin Project stay current and meaningful to all future students, please contribute!" should be better be changed to a simple p since it is a text after all?

Yes; however I just noticed this is being generated by `app/view/shared/_bottom_cta.html.erb`, and messing with that could have farther reaching consequences, especially since it can make sense for it to be a header if a sub heading is present. @KevinMulhern thoughts? My immediate idea is to simply extend the if `sub_heading` statement to make the `h4` a `p` if no subheader is present.

> for /paths, I did see "Start here" is originally h3 and should be a p, but I see the two "PATH" are already p now. So no need to change them right? I'm just double checking with you.

You don't have to touch those at all actually; as mentioned PATH is already a `p`, and the "Start here" is getting dropped with #3971 

> for /contributing, I am not sure whether "There are two main ways you can contribute:" should be a h3? Maybe a h2 is better for it since its higher-up is h1. And "Hall of Fame" definitely needs to be changed from h3 to a h2. What do you think?

Makes perfect sense to me

**Comment by luuu-xu** [comment]
>Makes perfect sense to me
I will go ahead and make these changes to `/contributing` as well then.

>My immediate idea is to simply extend the if sub_heading statement to make the h4 a p if no subheader is present.

Let's wait for Kevin's input and I like the idea where if a `sub_heading` is present, we will have `heading` to be a `h4`, or a `p` if no `sub_heading` is following it.

**Comment by Asartea** [comment]
> we will have heading to be a h4

Although really, it should be a `h2` in that case shouldn't it? Most pages should have at one `h1` as the page title, and this logically is a direct descendant of it, because its a stand alone callout

**Comment by KevinMulhern** [comment]
Hey @luuu-xu @Asartea, sorry for the delay. I think you're right Asartea, h2 makes the most sense.
It should be fine to have it a h2 in all cases, whether theres a subheading present or not.
