### ISSUE TITLE
Mobile Lesson-navbar

### ISSUE THREAD

**Issue by mindovermiles262** [TheOdinProject/theodinproject#397]
The course lesson navbar is unclickable on mobile. Text in parent directories is blue like a link, but user can't click to go back. 

Using iPhone 5SE, iOS 10.2.1 
Mobile Chrome (v57.0.2987.100)
and Mobile Safari (v602.4.6)

**Comment by mindovermiles262** [comment]
Course Lesson Navbar is also unclickable on desktop computer when top navbar displays dropdown icon

![2017-03-21-122719_1920x1080_scrot](https://cloud.githubusercontent.com/assets/14863257/24166956/51c6096a-0e32-11e7-9942-beeec5f276e6.png)

![2017-03-21-122726_1920x1080_scrot](https://cloud.githubusercontent.com/assets/14863257/24166957/51cc30b0-0e32-11e7-9f06-cfe9f65bab80.png)

**Comment by KevinMulhern** [comment]
Hey @mindovermiles262, thanks for opening this 😄 

The course bread crumb navigation component isn't in the new design 🎉 so we might be able to get away with ignoring this for now.

If the redesign takes longer than expected it would be worth fixing though.
