### ISSUE TITLE
Community Guide: contains broken link to Understanding Errors lesson

### ISSUE THREAD

**Issue by kunehenry** [TheOdinProject/theodinproject#3970]
### Describe your suggestion

The link: https://www.theodinproject.com/guides/community/lessons/foundations-understanding-errors from this page: https://www.theodinproject.com/guides/community/before_asking#:~:text=Examine%20Error%20Messages,Errors%20lesson is broken / come out as "Page Not Found".

### Path

Foundations

### Lesson Url

https://www.theodinproject.com/guides/community/before_asking#:~:text=Examine%20Error%20Messages,Errors%20lesson

### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [x] Would you like to work on this issue?

### (Optional) Discord Name

kunehenry

### (Optional) Additional Comments

Issue reported in here: https://discord.com/channels/505093832157691914/514204667245363200/1129164175491465317

**Comment by rlmoser99** [comment]
File to fix: https://github.com/TheOdinProject/theodinproject/blob/main/app/views/guides/community/before_asking.html.erb

Link needs an `/` at the beginning, so it should be: "/lessons/foundations-understanding-errors"

Please also check the remainder of this file for other lesson links that are not correct.

**Comment by Eveieve** [comment]
This isn't my first PR, but can I work on the issue?

**Comment by rlmoser99** [comment]
@Eveieve Thanks for offering, but because I see that you've done several PRs to our curriculum, I'd really like to let a brand new person get their feet wet with this one.

**Comment by kunehenry** [comment]
I can fix this if you need me to. I haven't made any PR yet to TOP.

**Comment by rlmoser99** [comment]
@steff2401 Thanks for the offer. I appreciate your honesty, but I really would like this to be a first time contributor.

**Comment by rlmoser99** [comment]
@kunehenry Yes, I'll take you up on the opportunity as a first-time contributor!

If you have any questions, please feel free to ping me and ask them here.

**Comment by kunehenry** [comment]
Thank you so much!
