### ISSUE TITLE
Bug: 422 Unprocessable Entity when trying to sign in with GitHub

### ISSUE THREAD

**Issue by endulum** [TheOdinProject/theodinproject#3978]
Complete the following REQUIRED checkboxes:

-   [**x**] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [**x**] The title of this issue follows the `Bug: brief description of bug` format, e.g. `Bug: Lesson complete button does not update on click`

The following checkbox is OPTIONAL:

-   [ ] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Bug:**

I tried to sign up for a new account with TOP. There was an option to continue with GitHub which I selected. After logging into GitHub, however, I was met with a "422 Unprocessable Entity" page.

**2. How To Reproduce:**
1. Visit the Sign Up page
2. Click on the GitHub button under "or continue with"
3. If not signed into GitHub already, sign in with GitHub
4. The next page is [this error.](https://i.imgur.com/ef2DDWk.png) Text: `422 Unprocessable entity
The change you wanted was rejected. Maybe you tried to change something you didn't have access to`

This persisted with all adblocking/trackers off, and through the Sign In page as well.

**3. Expected Behavior:**
I expected to be signed in to the website and taken to the curriculum as normal.

**4. Desktop/Device:**

-   **Device:** Encountered this issue repeatedly on all my owned devices - my laptop, my pc, my phone
-   **OS:** My laptop runs Linux (Arch), my PC runs Windows 10, my phone is the latest version of Android.
-   **Browser:** Tried on Chrome, Firefox, Microsoft Edge, Opera Mobile so far
-   **Version:** I'm sorry, version of what?

**5. Additional Information:**

- I did have an account prior to this, and deleted it. It was only linked to an email, never connected to my GitHub or Gmail. On that account I did submit links to my GitHub's repos on the prior account.
- On the error page screenshotted above, the page's title was `Unprocessable entity (500) | The Odin Project`. The page's URL was `https://www.theodinproject.com/users/auth/github/callback?code=[long string of numbers and letters]&state=[long string of numbers and letters]`, omitting the exact strings in case that's unsafe.
- Even after failing to create an account, GitHub claims TOP has been added to my account as an OAuth application, and sent me an email saying so.

Apologies if I had overlooked something small. I found no previous issues related to this and [the MDN page on this type of error](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/422) wasn't revealing much, so I'm at a loss of what to do. Thank you for your help.

**Comment by ChargrilledChook** [comment]
Thanks for the detailed report @endulum, we'll investigate this :+1:

**Comment by ChargrilledChook** [comment]
@endulum I've had a look and seems like this is a problem specific to your GitHub account, specifically because your user name is a single character ( μ ). Currently we validate that a username is at least 2 characters long. 

The easiest short term fix would be to add (at least) another character to your screen name on GitHub. This should be simple, since it's the display name affecting this not your more static account name.

**Comment by endulum** [comment]
Sorry for reading this quite late, I should probably figure out how to get notified for this sort of thing.

@ChargrilledChook Thank you for identifying the issue, I adjusted my display name as you suggested and I was able to log in without error!
