### ISSUE TITLE
Give the user visible feedback if they attempt to change their TOP profile email to one already in use

### ISSUE THREAD

**Issue by fullstackjess** [TheOdinProject/theodinproject#3984]
Complete the following REQUIRED checkboxes:

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `brief description of request` format, e.g. `Add dark mode to website`

The following checkbox is OPTIONAL:

-   [ ] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Feature Request:**

When I visit the TOP edit profile page, I want an error notification to appear below the email field if changing my email and the email is already in use. Currently, there is no feedback and it leads the user to believe something is wrong with the website or that their changes may have been saved.

**2. Acceptance Criteria:**

[ ] Red text appears beneath the email field stating "email already in use"
[ ] "email already in use" only appears if the email is being used by another TOP user

**3. Additional Information:**

The edit profile page appears to already check if an email is in use, as it won't save any changes you make if you try to change your email to one already in use, but simply has no feedback telling the user that they can't use the email they entered.

The edit profile page already checks if you leave the email field blank, as it gives you an "invalid email" error.
![Screenshot 2023-07-16 at 11 10 12 AM](https://github.com/TheOdinProject/theodinproject/assets/108513108/8a3ae88e-9e1c-49d1-9289-de5d0f4264a7)

**Comment by KevinMulhern** [comment]
Thanks for reporting @jessbrislin. This is due to our recent move to turbo

We just need to change [this line](https://github.com/TheOdinProject/theodinproject/blob/main/app/controllers/users/profiles_controller.rb#L11), to:
```ruby
render :edit, status: :unprocessable_entity
```

**Comment by j-mcQueen** [comment]
Hey, I can make these changes. I've worked on one other TOP issue before, so if you'd like to give someone new a shot then no worries :-)

**Comment by KevinMulhern** [comment]
Thats fine thanks @j-mcQueen, its all yours.
