### ISSUE TITLE
Bug: Invalid TheOdinProject email provided

### ISSUE THREAD

**Issue by mbiesiad** [TheOdinProject/theodinproject#3999]
Hi,

Complete the following REQUIRED checkboxes:

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `Bug: brief description of bug` format, e.g. `Bug: Lesson complete button does not update on click`
 

<hr>

**1. Description of the Bug:**
Email message from `contact@theodinproject.com` constains invalid TheOdinProject email address.

**2. How To Reproduce:**
1. Go to https://www.theodinproject.com/sign_up and register in
2. Open email with welcome message from contact@theodinproject.com titled "Getting started with The Odin Project"
3. Scroll down to see "(...) or feel free to reach out to theodinprojectcontact@gmail.com." - hover on email address or copy content - see `+theodinprojectcontact@gmail.com` instead of `theodinprojectcontact@gmail.com`

**3. Expected Behavior:**
In mentioned place, email address is changed to proper one - `theodinprojectcontact@gmail.com`

**4. Desktop/Device:**
NA

**5. Additional Information:**
Screenshot:
![image](https://github.com/TheOdinProject/theodinproject/assets/18367606/2a45d6b6-f686-4b1a-987c-c043581ad9fa)

![image](https://github.com/TheOdinProject/theodinproject/assets/18367606/761e6881-576b-425f-9558-2661cc5ba3d9)

At this moment this incorrect email address is invalid from Gmail point of view.

Best wishes,

**Comment by CouchofTomato** [comment]
For anyone that wants to work on this I think the issue is line 229 of this file https://github.com/TheOdinProject/theodinproject/blob/main/app/views/user_mailer/welcome_email.html.erb

I think we need to remove the after `mailto:` and before the email address.

**Comment by mbiesiad** [comment]
Thanks for quick reaction. If i may suggest - `space` before `mailto:` is redundant.

**Comment by CouchofTomato** [comment]
Yes, that is what I meant to say 😆 Thanks

**Comment by mbiesiad** [comment]
FYI: issue fixed, screenshot:
![image](https://github.com/TheOdinProject/theodinproject/assets/18367606/b9c959b9-0fd1-4c87-9ce2-a7c45b6b72f2)
all is fine now 🎉
