### ISSUE TITLE
Chore: Rename project submissions `has_live_preview` to `previewable`

### ISSUE THREAD

**Issue by KevinMulhern** [TheOdinProject/theodinproject#4003]
Because:
* https://github.com/TheOdinProject/theodinproject/pull/3968#discussion_r1264594293
* It's a more Rails-esque name.

**2. Acceptance Criteria:**
* The `has_live_preview` column name is renamed to `previewable` on the project submissions table
* All occurrences of `has_live_preview` throughout the codebase have been switched to `previewable`

**3. Additional Information:**

**Comment by KevinMulhern** [comment]
Blocked until we move fully to the new Hotwire version of submissions.

**Comment by ZachBaird** [comment]
I can take this @KevinMulhern
