### ISSUE TITLE
Create SECURITY.md

### ISSUE THREAD

**Issue by psmoros** [TheOdinProject/theodinproject#4004]
Hello 👋

I run a security community that finds and fixes vulnerabilities in OSS. A researcher (@coderbm1) has found a potential issue, which I would be eager to share with you.

Could you add a `SECURITY.md` file with an e-mail address for me to send further details to? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) a security policy to ensure issues are responsibly disclosed, and it would help direct researchers in the future.

Looking forward to hearing from you 👍

(cc @huntr-helper)

**Comment by 01zulfi** [comment]
Hello @psmoros, thank you for filing this issue. We'll look into creating a `SECURITY.md` file as well as looking into GitHub docs on the topic. For now, you can use theodinprojectcontact@gmail.com to send us emails, thank you.

**Comment by KevinMulhern** [comment]
Thanks for reporting @psmoros, we're awaiting the email disclosure.

Closing this in favour of https://github.com/TheOdinProject/.github/issues/6. We'd like the `SECURITY.md` to be in that repo so it is applied to all of our repos.
