### ISSUE TITLE
Redesign: Contribution Page

### ISSUE THREAD

**Issue by KevinMulhern** [TheOdinProject/theodinproject#401]
This task is to implement a redesigned contributing page as shown in the mock up images below. This is our current contributing page and where you can find the content for the page http://www.theodinproject.com/contributing

### Working on this task

- [ ] If you want to work on this task, please claim it by commenting below   
- [ ] Branch off the redesign branch                                                                 
- [ ] Check out our [styleguide](https://staging-odin-project.herokuapp.com/styleguide)
- [ ] When you are submitting your pull request for this task please ensure the base branch you want to merge into is the redesign branch  

If you have any questions or need clarification about anything related to this task please contact the maintainers in our [contributing channel on Gitter](https://gitter.im/TheOdinProject/Contributing)

### Contributing redesign mock up
![contribution](https://cloud.githubusercontent.com/assets/7963776/24629402/c9a4e8a6-18b0-11e7-94e4-e433daadf4d9.png)

**Comment by wanyamaman** [comment]
I'd like to work on this one

**Comment by arun1595** [comment]
@wanyamaman  :+1: 

It's all yours. Follow the instructions mentioned in the issue description to get started.

Contact us in the [Contributing](https://gitter.im/TheOdinProject/Contributing) chatroom if you've any questions

**Comment by KevinMulhern** [comment]
Hey @wanyamaman, just checkin in 😄 
Have you made much progress with this one? let us know if you need any assistance with anything.

**Comment by wanyamaman** [comment]
Hey @KevinMulhern, sorry I've been extremely busy over the past two weeks but I will wrap it up this weekend. Thanks for checking up on me :+1:

**Comment by arun1595** [comment]
Resolved in https://github.com/TheOdinProject/theodinproject/issues/432 by @wanyamaman
