### ISSUE TITLE
Bug: Bad contrast in light theme for submissions

### ISSUE THREAD

**Issue by Sharkri** [TheOdinProject/theodinproject#4013]
Complete the following REQUIRED checkboxes:

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `Bug: brief description of bug` format, e.g. `Bug: Lesson complete button does not update on click`

The following checkbox is OPTIONAL:

-   [x] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Bug:**

In light mode, the contrast for the like count, the edit icon, and the flag icon is very bad (1.47 contrast):

![image](https://github.com/TheOdinProject/theodinproject/assets/95330865/0649eba3-bf65-47d8-8768-f63c0f12f9e8)

However, it is fine in dark mode though:

![image](https://github.com/TheOdinProject/theodinproject/assets/95330865/3a8911a6-3198-4e9a-9fd3-ca4f3af94075)

**2. How To Reproduce:**

1. Sign in
2. Go to any project submission page
3. Turn on light theme
4. Inspect element and look at the contrast
5. The contrast is 1.47

**3. Expected Behavior:**

1. Sign in
2. Go to any project submission page
3. Turn on light theme
4. Inspect element and look at the contrast
5. The contrast is at least 4.5:1

**4. Desktop/Device:**

-   Device: Computer
-   OS: Ubuntu 
-   Browser: Chrome 
-   Version: 114 

**5. Additional Information:**
Note: also shows in dashboard submissions
I think something like text-gray-500 for light theme and no change for dark theme would be fine.

**Comment by KevinMulhern** [comment]
Thanks for reporting @Sharkri, we're currently rolling out a [new version of submissions](https://github.com/TheOdinProject/theodinproject/issues/3908). This problem is fixed in the new version:

<img width="1281" alt="Screenshot 2023-07-21 at 22 00 10" src="https://github.com/TheOdinProject/theodinproject/assets/7963776/72e39aea-3575-44e2-a8aa-7ca17bda4c44">



Should be fully enabled for all users by early next week.

**Comment by Sharkri** [comment]
@KevinMulhern The changes have rolled out to me, but the text is still a bit hard to see:
![image](https://github.com/TheOdinProject/theodinproject/assets/95330865/03d89e18-0a7b-43d0-a6db-26bcab9d2d23)

Maybe text-gray-500 instead of 400 (passes AA test):
![image](https://github.com/TheOdinProject/theodinproject/assets/95330865/041e1888-0afb-4d61-9559-16363ad8d628)

**Comment by KevinMulhern** [comment]
Sorry for closing this prematurely @Sharkri . Yeah we can increase to 500, would you like to be assigned?

**Comment by Sharkri** [comment]
Yes, I would like to be assigned. @KevinMulhern

**Comment by KevinMulhern** [comment]
Thanks @Sharkri, it's all yours.
