### ISSUE TITLE
Bug: Lesson Preview tool `Share button` not working on safari

### ISSUE THREAD

**Issue by ManonLef** [TheOdinProject/theodinproject#4014]
Complete the following REQUIRED checkboxes:

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `Bug: brief description of bug` format, e.g. `Bug: Lesson complete button does not update on click`

The following checkbox is OPTIONAL:

-   [ ] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Bug:**

When using the [lesson preview tool](https://www.theodinproject.com/lessons/preview) on Safari Version 16.4 (don't judge), I noticed the share button does not work as it does on Google Chrome. 

**2. How To Reproduce:**

1. Sign in
2. Visit [the lesson preview tool](https://www.theodinproject.com/lessons/preview) on safari
3. type something in the `write` section
4. Click the `Share` button
5. The `Share` button does not copy a link to clipboard as it does on Chrome

**3. Expected Behavior:**

1. Sign in
2. Visit [the lesson preview tool](https://www.theodinproject.com/lessons/preview) on safari
3. type something in the `write` section
4. Click the `Share` button
5. The `Share` button copies a link to clipboard as it does on Chrome

**4. Desktop/Device:**

-   Device: Mac Mini M2
-   OS: Ventura 13.3.1 (a) 
-   Browser: Safari 
-   Version: 16.4

**5. Additional Information:**

none

**Comment by KevinMulhern** [comment]
Great reporting @ManonLef 💪 

Looks like it might have something to do with this:
https://stackoverflow.com/questions/62327358/javascript-clipboard-api-safari-ios-notallowederror-message

**Comment by ManonLef** [comment]
You're right. Looks like it needs to utilize the `navigator.clipboard` API. Some more info on that here in the [Async Clipboard API section](https://webkit.org/blog/10247/new-webkit-features-in-safari-13-1/) for reference in case someone picks this up

**Comment by ZachBaird** [comment]
@ManonLef I should have commented before putting a PR out: I can take this :)

**Comment by ManonLef** [comment]
Thanks @ZachBaird ! I saw your pr and that's why I removed the labels indicating help was needed 😊. I couldn't assign you since I think you can only assign people active in the issue. But I figured the link showing your PR above your comment made it clear. 

Thanks for taking this on! I asked Kevin to review.
