### ISSUE TITLE
Redesign: About Page

### ISSUE THREAD

**Issue by KevinMulhern** [TheOdinProject/theodinproject#402]
This task is to implement a redesigned about page as shown in the mock up images below. This is our current about page and where you can find the content for the page http://www.theodinproject.com/about

### Working on this task

- [x] If you want to work on this task, please claim it by commenting below   
- [x] Branch off the redesign branch                                                                 
- [x] Check out our [styleguide](https://staging-odin-project.herokuapp.com/styleguide)
- [x] When you are submitting your pull request for this task please ensure the base branch you want to merge into is the redesign branch  

If you have any questions or need clarification about anything related to this task please contact the maintainers in our [contributing channel on Gitter](https://gitter.im/TheOdinProject/Contributing)

### Redesigned about page mock up
![about](https://cloud.githubusercontent.com/assets/7963776/24629753/13cfb57c-18b2-11e7-9905-4f229340f0f2.png)

**Comment by karenfreemansmith** [comment]
I'd like to do this one.

**Comment by arun1595** [comment]
@karenfreemansmith   Awesome :) It's all yours. Follow the instructions mentioned in the issue description to get started with the task.

If you have any questions, talk with us in the [Contributing](https://gitter.im/TheOdinProject/Contributing) chatroom

**Comment by karenfreemansmith** [comment]
I'm seeing differences in the existing text and the mockup... particularly the timeline with the lorem ipsum. Should I be styling the existing text, or replacing it with the text from the mockup?

**Comment by KevinMulhern** [comment]
Sorry for the late reply @karenfreemansmith, we will be updating the copy on these pages so I think its best to use lorem ipsum with it,

**Comment by karenfreemansmith** [comment]
Ok, thanks!
