### ISSUE TITLE
Redesign: Success Stories page

### ISSUE THREAD

**Issue by KevinMulhern** [TheOdinProject/theodinproject#403]
This task is to implement a new success stories page as shown in the mock up images below. We are working on gathering content for this page, in the meantime fake lorem ipsum content can be used to get the page built 

### Working on this task

- [x] If you want to work on this task, please claim it by commenting below   
- [x] Branch off the redesign branch                                                                 
- [x] Check out our [styleguide](https://staging-odin-project.herokuapp.com/styleguide)
- [x] When you are submitting your pull request for this task please ensure the base branch you want to merge into is the redesign branch  

If you have any questions or need clarification about anything related to this task please contact the maintainers in our [contributing channel on Gitter](https://gitter.im/TheOdinProject/Contributing)

### Success stories mock up
![success-stories](https://cloud.githubusercontent.com/assets/7963776/24629880/818b4b3a-18b2-11e7-9c71-423b95f5bc9b.png)

**Comment by gionaufal** [comment]
I would like to do this one!

**Comment by arun1595** [comment]
@gionaufal Go ahead :) Follow the instructions mentioned in the issue description to get started.

Feel free to join the [Contributing](https://gitter.im/TheOdinProject/Contributing) chatroom if you have any questions.

**Comment by gionaufal** [comment]
@arun1595 and @KevinMulhern, one small doubt: today, in the redesign branch, this page is a partial being rendered in Home. Does it need to continue only in this partial, or will this partial be presented as a standalone page also?

Thanks!

**Comment by arun1595** [comment]
@gionaufal I think you shouldn't modify the existing partial(rendered in home page) and instead, create a new one for 'Success Stories' page.

/cc @KevinMulhern

**Comment by gionaufal** [comment]
@arun1595 got it! thanks for clarifying

**Comment by KevinMulhern** [comment]
@gionaufal this will be brand new page, it doesn't currently exist on the site. That means you'll have to do a few extra things to get it working.

* A new `success_stories` action needs to go into the `StaticPagesController`
* A new route for the success stories page needs to be added to `routes.rb`
* A new `success_stories.html.erb` view needs to be added to the `static_pages` folder within the views folder

If you need help or more clarification on anything, don't hesitate to reach out to us 😄

**Comment by gionaufal** [comment]
Thanks @KevinMulhern! I was doing exactly these things =). Will open the pull request soon.
