### ISSUE TITLE
Bug: Link for submissions-list.jsx is broken on Mocking Call Back Components lesson in React Course

### ISSUE THREAD

**Issue by AResoluteMaverick** [TheOdinProject/theodinproject#4041]
Complete the following REQUIRED checkboxes:

-   [x ] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [ x] The title of this issue follows the `Bug: brief description of bug` format, e.g. `Bug: Lesson complete button does not update on click`

The following checkbox is OPTIONAL:

-   [ ] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Bug:**

This link: https://github.com/TheOdinProject/theodinproject/blob/main/app/javascript/components/project-submissions/components/submissions-list.jsx is not working as intended. There is no access to the lesson material.

**2. How To Reproduce:**

**3. Expected Behavior:**
1. Go to React Course
2. Click Mocking Callbacks and Components
3. Go to "React testing in the real world" section
4. Click submissions-list.jsx

**4. Desktop/Device:**

-   Device: Laptop
-   OS:  Windows 10
-   Browser:  Edhe
-   Version: 

**5. Additional Information:**

**Comment by ManonLef** [comment]
Thanks for reporting. Closed by https://github.com/TheOdinProject/curriculum/pull/25990#issuecomment-1656786205
