### ISSUE TITLE
Bug: Project Solutions w/o Live Preview URL show Live Preview button

### ISSUE THREAD

**Issue by rlmoser99** [TheOdinProject/theodinproject#4059]
Complete the following REQUIRED checkboxes:

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `Bug: brief description of bug` format, e.g. `Bug: Lesson complete button does not update on click`

The following checkbox is OPTIONAL:

-   [ ] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Bug:**

We got a flagged submission saying that someone's live preview just linked to the lesson. However, this solution does not provide a live preview url.
<img width="680" alt="Screenshot 2023-08-03 at 6 44 00 AM" src="https://github.com/TheOdinProject/theodinproject/assets/33227096/c84107de-179a-4319-aa57-529892c45680">

**2. How To Reproduce:**

1. Sign In
2. Visit https://www.theodinproject.com/lessons/nodejs-messaging-app
3. Find the solution for procell and click on "Live preview"
4. This just reloads the current page

OR

1. Sign In
2. Visit https://www.theodinproject.com/lessons/nodejs-messaging-app
3. Add a new solution, but only add a link for a GitHub repository. Click on Save.
4. Find this new solution and click on "Live preview"
5. This just reloads the current page.
6. Delete your test project submission, since it is not an actual project solution.

**3. Expected Behavior:**

1. Sign In
2. Visit https://www.theodinproject.com/lessons/nodejs-messaging-app
3. Find the solution for procell
4. When a solution does not have a life preview url, the button should either not show up or possibly some other behavior that the maintainer team decides.

**4. Desktop/Device:**

-   Device: MacBook
-   OS: 13.2
-   Browser: Chrome
-   Version: 114.0.5735.133 (Official Build) (arm64)

**5. Additional Information:**

**Comment by JustWaveThings** [comment]
I didn't even think to make an issue about this.  Thanks @rlmoser99 !

**Comment by luuu-xu** [comment]
I can confirm this bug can be reproduced. If the preview url is not present, the current behavior is opening a new tab of the current page. Instead, the correct behavior should be not showing the preview button at all if there is no such preview url provided.

I can try work on this issue! But I might be slow since I am not used to Ruby.

**Comment by ManonLef** [comment]
@luuu-xu I will assign you. Please give us a head up if you need help, change your mind or run into issues figuring it out.

**Comment by luuu-xu** [comment]
@ManonLef Thank for the assignment. It turns out to be an easy fix. It's just that as I mentioned in PR #4064, I am not sure whether adding a method in the class is necessary in this case. If not, I have also provided alternative solution too.
