### ISSUE TITLE
Redesign: Course page

### ISSUE THREAD

**Issue by KevinMulhern** [TheOdinProject/theodinproject#406]
This task is to implement the redesign for our course show page as shown in the mock up images below. For reference this is the current course show page for the rails course http://www.theodinproject.com/courses/ruby-on-rails

### Working on this task

- [ ] If you want to work on this task, please claim it by commenting below   
- [ ] Branch off the redesign branch                                                                 
- [ ] Check out our [styleguide](https://staging-odin-project.herokuapp.com/styleguide)
- [ ] When you are submitting your pull request for this task please ensure the base branch you want to merge into is the redesign branch  

If you have any questions or need clarification about anything related to this task please contact the maintainers in our [contributing channel on Gitter](https://gitter.im/TheOdinProject/Contributing)

### Redesigned Course show page mock up
![lesson](https://cloud.githubusercontent.com/assets/7963776/24771700/6dc3a6aa-1b06-11e7-8bb3-fd4971bbbf0d.png)

**Comment by arun1595** [comment]
@KevinMulhern I'll work on this too as I go on with the courses index page :)
