### ISSUE TITLE
Adopt same `improve lesson/report issue` footer that are in lessons for non lesson pages where appropriate

### ISSUE THREAD

**Issue by JustWaveThings** [TheOdinProject/theodinproject#4061]
Complete the following REQUIRED checkboxes:

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `brief description of request` format, e.g. `Add dark mode to website`

The following checkbox is OPTIONAL:

-   [x] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Feature Request:**

Once #4057 is merged, Kevin suggested I make an issue to bring this feature into places that have the old style of 'Improve this lesson on GitHub' footer links.   Example: https://www.theodinproject.com/guides/community/before_asking 
![image](https://github.com/TheOdinProject/theodinproject/assets/48169481/21108783-5e59-4a1a-892a-3e5d972cf83d)
to:
![image](https://github.com/TheOdinProject/theodinproject/assets/48169481/ad77cdb3-845f-4d2b-9529-f7d3375d128c)

**2. Acceptance Criteria:**

 
- [ ] All pages that currently have the option to 'Improve this lesson on GitHub' be converted to the new format

**3. Additional Information:**

While I checked the box to want to be assigned to the issue because I think I can apply what I learned in the implementation of #4057 to get this to work. However, if someone more capable wants to take it on, I'd happily defer. I am working my way through the node path and without @KevinMulhern and @JoshDevHub's help, I wouldn't have been able to get #4057 done.

**Comment by ManonLef** [comment]
You've got this!

**Comment by JustWaveThings** [comment]
So it seems like the community guides a built a bit differently than the lesson content and while I can see the TW classes when I inspect the local instance of the web app, I can't seem to find where they are coming from in the code. 

I'd be up for pairing with someone on this who knows a little bit about ruby/rails/TW or throwing it back for someone else to pick up. 

Additional note: I found the 'suggest improvements' link is broken (404) for the community guide articles. See Screenshot: 
<img width="919" alt="image" src="https://github.com/TheOdinProject/theodinproject/assets/48169481/dcb25039-ad1b-4c0a-bc5f-2c19d012e157">

**Comment by JoshDevHub** [comment]
I could probably help you with this some time this week if you want @JustWaveThings

**Comment by KevinMulhern** [comment]
No worries @JustWaveThings, it's not that obvious with how it's abstracted away behind the container. You're in very capable hands with Josh. If either of you need anything from me, hit me up ✌️

**Comment by JustWaveThings** [comment]
Sounds like a plan, Josh. Thanks, Kevin!

**Comment by JustWaveThings** [comment]
Apologize for the delay! I just got TOP running locally again, and hopefully this afternoon or this weekend you have time @JoshDevHub, I'm ready to bang this out and put it to bed.
