### ISSUE TITLE
Add a quick video on Object.assign - Advanced JS Course

### ISSUE THREAD

**Issue by i5x64BIT** [TheOdinProject/theodinproject#4065]
This is a much simpler way to explain the concept and its real-world implications.
[Video on Object.assign()](https://www.youtube.com/watch?v=JmGJUzNsGFs)

**Comment by ManonLef** [comment]
Hi @i5x64BIT , 

Would you mind filing the issue in the curriculum repo [by following this link and clicking `new issue`](https://github.com/TheOdinProject/curriculum/issues/new/choose)?

Please fill out the template that comes up and explain which topics are covered that aren't covered in the lesson for the video resource, or other details you have on where this should reside, be added or what it should replace.

Thanks so much in advance!
