### ISSUE TITLE
Redesign: Login Page

### ISSUE THREAD

**Issue by KevinMulhern** [TheOdinProject/theodinproject#407]
This task is to implement a redesigned login page as shown in the mock up images below. For reference this is our current login page http://www.theodinproject.com/login

### Working on this task

- [ ] If you want to work on this task, please claim it by commenting below   
- [ ] Branch off the redesign branch                                                                 
- [ ] Check out our [styleguide](https://staging-odin-project.herokuapp.com/styleguide)
- [ ] When you are submitting your pull request for this task please ensure the base branch you want to merge into is the redesign branch  

If you have any questions or need clarification about anything related to this task please contact the maintainers in our [contributing channel on Gitter](https://gitter.im/TheOdinProject/Contributing)

### Redesigned login page mock up
![login](https://cloud.githubusercontent.com/assets/7963776/24771804/e32ea35e-1b06-11e7-8059-06707f4ff308.png)

**Comment by 105ron** [comment]
Can I be responsible for this?

**Comment by KevinMulhern** [comment]
Its all yours @105ron san

**Comment by Mark3z** [comment]
HI @105ron, I'm here to help if you will ever need it :)

**Comment by 105ron** [comment]
@Mark3z I'm beyond help but maybe post in the pair programming room and we can work together on it? I'm only available on weekends though..

**Comment by arun1595** [comment]
@105ron How is the login page coming along? :wink:

**Comment by faraazahmad** [comment]
Is a Google button also needed?
 [#512](https://github.com/TheOdinProject/theodinproject/issues/512)

**Comment by KevinMulhern** [comment]
That can be added later @faraazahmad 😄

**Comment by faraazahmad** [comment]
Sure 😅
