### ISSUE TITLE
Redesign: Lesson Page

### ISSUE THREAD

**Issue by KevinMulhern** [TheOdinProject/theodinproject#408]
This task is to implement a redesigned lesson page as shown in the mock up images below. For reference this is our current lesson page http://www.theodinproject.com/courses/ruby-on-rails/lessons/sinatra-basics

**Important**
Please ignore the solutions component at the bottom of the mock up. We will create another issue for implementing that feature when we merge in the backend work for it in the next few weeks.

### Working on this task

- [ ] If you want to work on this task, please claim it by commenting below   
- [ ] Branch off the redesign branch                                                                 
- [ ] Check out our [styleguide](https://staging-odin-project.herokuapp.com/styleguide)
- [ ] When you are submitting your pull request for this task please ensure the base branch you want to merge into is the redesign branch  

If you have any questions or need clarification about anything related to this task please contact the maintainers in our [contributing channel on Gitter](https://gitter.im/TheOdinProject/Contributing)

### Redesigned lesson page mock up
![lesson-detail-1](https://cloud.githubusercontent.com/assets/7963776/24772136/10e44ee2-1b08-11e7-869b-cd111b387484.png)

**Comment by iansowinski** [comment]
I would love to tak it

**Comment by KevinMulhern** [comment]
Its all yours @iansowinski 😄

**Comment by iansowinski** [comment]
I'll comment here for the sake of documentation :)

I see two UX problems as far - one is the lack of "previous lesson button" - it used to be on the left from "mark lesson complete", the second one is the lack of path to current lesson - it can be pain it the ass for some users. Also I'm not sure what to do with the header ("sinatra basis") - now it is rendered based on markdown, should I keep it that way or try to extract it from the lesson path?

**Comment by iansowinski** [comment]
Also - there used to be great feature of octocat icon redirecting to the lessons file on github - it made it easy to contribute.

**Comment by KevinMulhern** [comment]
Hey @iansowinski, thanks for providing us with this feedback 😄 I'll do what I can to justify some of the decisions we made.

1. For the previous button, we used google anaylitics event tracking to see how often the previous button was clicked. It was one of the lowest clicked components we are tracking on the site. A small sample of just the clicks this week is 5031 clicks for the next lesson button vs 120 clicks for the previous lesson button.

This indicated to use that it wasn't used all that much by users and could be removed.

2. We have a dashboard page that will be a logged in users home page which will include a link to the current lesson the user is on 😄 we haven't put it up as an issue yet because it relies on the student submission feature being completed. We should hopefully have it up as an issue to work on soon.

3. I agree on the octocat, it was a handy little feature. I'll raise it as something to discuss with Ada about maybe putting back in.

**Comment by adachiu** [comment]
@iansowinski Thanks for the feedback!
1. What Kevin said. However, we could replace "view course" with "previous lesson" and put "view course in the center, replacing "Mark lesson completed" 
@KevinMulhern what if we merge the "mark lesson completed" button with the "add solution" ? So for example, once the user adds their solution, the lesson auto-marks as completed. That way, we save a step. Let me mock something up. I'll post back here. 

3. The octocat contributing button could be added to the bottom "Got questions" section. I'll post back a mock up version.

**Comment by KevinMulhern** [comment]
@adachiu that could work on project pages, standard lesson pages won't have solutions though so we will have to keep mark lesson as completed on those pages. 

I'm a little reluctant about having adding a solution as a requirement to mark the lesson as complete as we get a lot of students at the moment who don't submit a solution but mark the lesson as complete. I assume a lot of those people aren't comfortable with the process of adding their solution via git and thats the reason for it. But we can't be sure, maybe a lot of people would rather not share their solution. Regardless we can try implementing it and seeing how it performs 😄

**Comment by iansowinski** [comment]
@KevinMulhern is right about solutions - for example I never posted mine :P 

Maybe we will just make course icon clickable instead of adding extra button to view course?

I think contributing button is extra important though.

**Comment by KevinMulhern** [comment]
Hey @iansowinski, just checking in 😄 
Have you made much progress with this one? let us know if you need any help with anything.

**Comment by iansowinski** [comment]
@KevinMulhern I'm doing it in slow peace if it's not a problem for you guys :)

**Comment by KevinMulhern** [comment]
No problem 😄 take your time.

**Comment by KevinMulhern** [comment]
Hey @iansowinski, haven't heard anything from you. Are you still working on this one?

**Comment by KevinMulhern** [comment]
Hey @iansowinski, sorry because I haven't heard from you in the past two weeks I have to assume this is not going to be done 😞 . I'm going to close the issue and create a new one so it can be picked up by someone else.
