### ISSUE TITLE
Redesign: Curriculum page

### ISSUE THREAD

**Issue by KevinMulhern** [TheOdinProject/theodinproject#409]
This task is to implement a redesigned curriculum page as shown in the mock up images below. This is our current curriculum page for reference http://www.theodinproject.com/courses?ref=home

### Working on this task

- [x] If you want to work on this task, please claim it by commenting below   
- [x] Branch off the redesign branch                                                                 
- [x] Check out our [styleguide](https://staging-odin-project.herokuapp.com/styleguide)
- [x] When you are submitting your pull request for this task please ensure the base branch you want to merge into is the redesign branch  

### Redesigned curriculum page mockup
![curriculum](https://cloud.githubusercontent.com/assets/7963776/24772272/95406342-1b08-11e7-8751-ba3a6c7e1c82.png)

**Comment by KevinMulhern** [comment]
@arun1595 is working on this

**Comment by factsfinder** [comment]
I'm working on this.

**Comment by KevinMulhern** [comment]
Hi @factsfinder, this one has already been taken I'm afraid. I commented a little further up that @arun1595 is working on it 😄 

There will be more complete page redesigns and smaller tweak tasks being put up here over the next few weeks.

Thanks for showing being interested in contributing.

**Comment by factsfinder** [comment]
Oops. My bad. OK then I will check for other tasks. Thank you @KevinMulhern
