### ISSUE TITLE
Bug: broken link in rules page. 

### ISSUE THREAD

**Issue by ManonLef** [TheOdinProject/theodinproject#4101]
### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] The title of this issue follows the `Bug: brief description of bug` format, e.g. `Bug: Lesson complete button does not update on click`
- [ ] Would you like to work on this issue?

### Bug description

the "improve this lesson on GitHub" button doesn't link to the correct file anymore. 

I know @JoshDevHub has been working on making this file an md file instead (thanks for that by the way!) and I kind of lost track about the progress on the full conversion. 

### How to reproduce

1. Go to this [page which contains our rules](https://www.theodinproject.com/guides/community/rules) 
2. click the link at the bottom "improve this lesson on GitHub"
3. be met with a 404

### Expected behavior

1. Go to this [page which contains our rules](https://www.theodinproject.com/guides/community/rules) 
2. click the link at the bottom "improve this lesson on GitHub"
3. be met with the file on GH

### What browsers are you seeing the problem on?

Safari

### What OS are you using?

MacOS

**Comment by ManonLef** [comment]
@Asartea thanks. The file itself is already merged in top-meta. I am sorry about the confusion, I was more interested in the entire move/overhaul. If the status is `nearing completion` it would make more sense to point to the intended file residence and not the old erb file.

**Comment by Asartea** [comment]
@ManonLef given thats it been 3 weeks, I think its probably worth taking them time to fix it

**Comment by ManonLef** [comment]
@Asartea you're free to work on it if you want :). Considering we have other team members working on related issue with the md switch, this issue has no priority/rush at the moment for us to bump since it's expected to be caught in there. But do let me know if you want it assigned to you!

**Comment by Asartea** [comment]
Should be a quick enough fix; I'll do it

**Comment by KevinMulhern** [comment]
Resolved by: https://github.com/TheOdinProject/theodinproject/pull/4149
