### ISSUE TITLE
/blog should redirect to TOP's dev.to account

### ISSUE THREAD

**Issue by 01zulfi** [TheOdinProject/theodinproject#4108]
Complete the following REQUIRED checkboxes:

-   [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [X] The title of this issue follows the `brief description of request` format, e.g. `Add dark mode to website`

The following checkbox is OPTIONAL:

-   [ ] I would like to be assigned this issue to work on it

<hr>

**1. Description of the Feature Request:**

I expect https://theodinproject.com/blog to redirect to https://dev.to/theodinproject

**2. Acceptance Criteria:**

 https://theodinproject.com/blog redirects to https://dev.to/theodinproject

**3. Additional Information:**

n/a

**Comment by Asartea** [comment]
Agree that that sounds sensibly, but do we currently link to `/blog` anywhere on the main site?

Also, if possible, could I be assigned to work on this?

**Comment by KevinMulhern** [comment]
Thanks @01zulfi, this is a good idea.

Good question @Asartea, it looks like nothing is using it atm. We're good to go - I'll assign it to you.
<img width="567" alt="Screenshot 2023-09-04 at 08 20 28" src="https://github.com/TheOdinProject/theodinproject/assets/7963776/97a0ca48-bf42-4311-a90f-4eca67a8144d">

**Comment by Asartea** [comment]
Looking at it, we currently link to the blog directly from the footer; should ptobabky replace that link with one to `/blog`?

**Comment by KevinMulhern** [comment]
Yeah thats a good shout - it’ll probably be better for seo if we use there.
