### ISSUE TITLE
Cleanup uses of ODIN_CHAT_URL

### ISSUE THREAD

**Issue by Asartea** [TheOdinProject/theodinproject#4116]
Complete the following REQUIRED checkboxes:

-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `brief description of request` format, e.g. `Add dark mode to website`

The following checkbox is OPTIONAL:

-   [x] I would like to be assigned this issue to work on it, but am also willing to leave it open for a first task

<hr>

**1. Description**
We already have a redirect to the Discord server invite at `/discord`, but a lot (all?) of the codebase still uses raw `ODIN_CHAT_URL` redirects

**2. Acceptance Criteria:**
- Add a `as: discord` statement in the redirects:
https://github.com/TheOdinProject/theodinproject/blob/2b890ab9b8448dcb41c6d6e597b1dd8471caf5d5/config/routes/redirects.rb#L5

Replace all usage of `ODIN_CHAT_URL` with `discord_path`

**3. Additional Information:**

**Comment by KevinMulhern** [comment]
Thanks @Asartea, assigned to you.
