### ISSUE TITLE
Redesign Fix:  Underline link on home page

### ISSUE THREAD

**Issue by adachiu** [TheOdinProject/theodinproject#413]
This task is to update the link decoration on the home page's Success Stories section for “Read more success stories” 

1.  Font-family should be OpenSans
2. Text-decoration should be underline

It should look like this screenshot:
<img width="1439" alt="screen shot 2017-04-15 at 9 20 36 pm" src="https://cloud.githubusercontent.com/assets/13413986/25068733/63e1da58-2222-11e7-946c-53effb99aae7.png">

### Working on this task

- [ ] If you want to work on this task, please claim it by commenting below   
- [ ] Branch off the redesign branch                                                                 
- [ ] When you are submitting your pull request for this task please ensure the base branch you want to merge into is the redesign branch

**Comment by sdg123** [comment]
I'd like to work on this!

**Comment by KevinMulhern** [comment]
It all yours 😄  thanks @sdg123

**Comment by codyloyd** [comment]
@sdg123 have you made any progress on this yet?

**Comment by sdg123** [comment]
Hey, I haven't.
Busy with school work, if anyone else wants to pick it up, feel free to do so.
I'll continue contributing from May 8th.

**Comment by codyloyd** [comment]
alright... I'll do it.

**Comment by codyloyd** [comment]
done
