### ISSUE TITLE
Chore: Remove stickyfilljs

### ISSUE THREAD

**Issue by KevinMulhern** [TheOdinProject/theodinproject#4131]
**1. Description of the Chore:**
We don't use this package anywhere in the codebase.

**2. Acceptance Criteria:**
- [ ] Stickyfilljs is no longer in our package.json

**3. Additional Information:**

To remove packages with yarn, run `yarn remove stickyfilljs`

**Comment by rishikumars-in** [comment]
@KevinMulhern Can I work on this?

**Comment by KevinMulhern** [comment]
Thanks @rishikumars-in, I've assigned it to you 😄

**Comment by rishikumars-in** [comment]
@KevinMulhern Done. 💪🏼

Created PR. Kindly checkout and give your feedback.
