### ISSUE TITLE
Bug: <brief description of the issue>

### ISSUE THREAD

**Issue by ManonLef** [TheOdinProject/theodinproject#4133]
### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] The title of this issue follows the `Bug: brief description of bug` format, e.g. `Bug: Lesson complete button does not update on click`
- [ ] Would you like to work on this issue?

### Bug description

I noticed today that the note icons have been replaced by squares. I did not have time to look further into what causes it. I inspected one lesson and the markdown seemed to be following the usual syntax. 

Previews:
<img width="478" alt="Screenshot 2023-09-13 at 23 42 30" src="https://github.com/TheOdinProject/theodinproject/assets/81025586/aee40202-dbc1-4d41-8b91-9b86783ade60">
<img width="604" alt="Screenshot 2023-09-13 at 23 42 23" src="https://github.com/TheOdinProject/theodinproject/assets/81025586/659ab193-b2ee-4c8e-a9bf-9e6de1be6ef0">

### How to reproduce

1. sign in
2. visit a page with a note like [this lesson on state](https://www.theodinproject.com/lessons/node-path-react-new-more-on-state)
3. scroll down to any note box
4. there are no icons visible that were previously there to depict the kind of note

### Expected behavior

1. sign in
2. visit a page with a note like [this lesson on state](https://www.theodinproject.com/lessons/node-path-react-new-more-on-state)
3. scroll down to any note box
4. there should be a note icon, lightbulb or warning icon depending on the type of note block. 

### What browsers are you seeing the problem on?

Chrome, Safari

### What OS are you using?

MacOS

### Discord Name

manual

**Comment by KevinMulhern** [comment]
Thanks @ManonLef, we changed how our CSS is loaded on the site recently. This likely is just an edgecase from that. I'll look into it.
