### ISSUE TITLE
Add "Chore" Issue template

### ISSUE THREAD

**Issue by Asartea** [TheOdinProject/theodinproject#4134]
-   [x] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/theodinproject/blob/main/CONTRIBUTING.md)
-   [x] The title of this issue follows the `brief description of request` format, e.g. `Add dark mode to website`

The following checkbox is OPTIONAL:

-   [x] I would like to be assigned this issue to work on it

<hr>

### Discussed in https://github.com/TheOdinProject/theodinproject/discussions/4119

<div type='discussions-op-text'>

<sup>Originally posted by **Asartea** September  7, 2023</sup>
A lot of the time when I'm opening issues against this repo they aren't a bug report or a feature request, but moreso a clean this thing up (A chore). It would be nice if there was a seperate issue template for that. It would also mean that we nicely have one issue template for each PR type (Fix > Bug Report, Feature > Feature Request, Chore > This new one (probs just called Chore?)

Would appreciate thoughts</div>

**Comment by KevinMulhern** [comment]
Thanks for opening this @Asartea - sounds like a great idea to me
