### ISSUE TITLE
Bug: I cannot create an account. When I submit it says Error.

### ISSUE THREAD

**Issue by LaurenCast99** [TheOdinProject/theodinproject#4139]
### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] The title of this issue follows the `Bug: brief description of bug` format, e.g. `Bug: Lesson complete button does not update on click`
- [ ] Would you like to work on this issue?

### Bug description

When I click submit to create an account it says Error.

### How to reproduce

1. Click Get Started
2. Fill the informations
3. Click Sign Up

### Expected behavior

It will say Server Error

### What browsers are you seeing the problem on?

Safari

### What OS are you using?

MacOS

**Comment by KevinMulhern** [comment]
Thanks for reporting @LaurenCast99, a fix will be out shortly.
