### ISSUE TITLE
Chore: Convert feature_request.md to issue template syntax

### ISSUE THREAD

**Issue by Asartea** [TheOdinProject/theodinproject#4144]
### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] The title of this issue follows the `Chore: brief description of chore` format, e.g. `Chore: Lesson complete button does not update on click`
- [X] Would you like to work on this issue?

### Chore description

After the work done on `bug_report.md` and `chore.md` feature request is the only issue template still using the old syntax. Given the advantages of using the newer syntax we should probably convert it as well

### Acceptance criteria

- [ ] Feature Request uses the new syntax

**Comment by KevinMulhern** [comment]
Sounds great, i've assigned it to you. Thanks for all you're doing ❤️
