### ISSUE TITLE
Redesign Fix: Footer link change

### ISSUE THREAD

**Issue by adachiu** [TheOdinProject/theodinproject#415]
This task is to edit the links in the footer.

1. Remove the links "Legal" and "Press" from the footer
2. Add a footer link called "Success Stories" that links to the `/success_stories` page
3. Change the "Blog" link to point to https://medium.com/the-odin-project

### Working on this task

- [ ] If you want to work on this task, please claim it by commenting below   
- [ ] Branch off the redesign branch                                                                 
- [ ] When you are submitting your pull request for this task please ensure the base branch you want to merge into is the redesign branch

**Comment by mbabaian** [comment]
I'll work on this one.

**Comment by cakleimeier** [comment]
I'd like to give this a try.

**Comment by adachiu** [comment]
@cakleimeier all yours!

**Comment by KevinMulhern** [comment]
Resolved by @cakleimeier 😄
