### ISSUE TITLE
Redesign Fix: Update Global H1, H2, H3

### ISSUE THREAD

**Issue by adachiu** [TheOdinProject/theodinproject#416]
This task is to update H1, H2, H3

1. The current global font-weight for H1 is 500. Change it to 300.
2. The current global font-weight for H2 is 500. Change it to 700.
3. Update the H2 and H3 color to `#4a4a4a`
4. Change H3 to font-size 1.5em (28px) so there's differentiation between H2 and H3 sizes.

### Working on this task

- [ ] If you want to work on this task, please claim it by commenting below   
- [ ] Branch off the redesign branch                                                                 
- [ ] When you are submitting your pull request for this task please ensure the base branch you want to merge into is the redesign branch

**Comment by rdavid1099** [comment]
I will take care of this for you guys.

**Comment by arun1595** [comment]
@rdavid1099 Thanks! It is yours :)

**Comment by arun1595** [comment]
Resolved by https://github.com/TheOdinProject/theodinproject/pull/428
