### ISSUE TITLE
Enhancement: increase "gap" between buttons on the contact-us page

### ISSUE THREAD

**Issue by ManonLef** [TheOdinProject/theodinproject#4160]
### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] The title of this issue follows the `Feature Request: brief description of feature request` format, e.g. `Feature Request: Lesson complete button does not update on click`
- [ ] Would you like to work on this issue?

### Description of the Feature Request

On the [contact page](https://www.theodinproject.com/contributing) the two buttons are spaced a little tight.
<img width="724" alt="Screenshot 2023-09-18 at 13 25 34" src="https://github.com/TheOdinProject/theodinproject/assets/81025586/9a940f6b-1dad-4a30-851b-cad0d9cc8014">

I suggest to make the spacing equal to the other pages like [the contributing page](https://www.theodinproject.com/contributing)
<img width="576" alt="Screenshot 2023-09-18 at 13 25 46" src="https://github.com/TheOdinProject/theodinproject/assets/81025586/075f413c-36c1-4143-893a-361ad747ee97">

### Acceptance criteria

- [ ] button spacing/gap consistent with rest of the site

**Comment by KevinMulhern** [comment]
Good spot, thanks @ManonLef 💪

**Comment by ascodeasice** [comment]
Hi, I would like to work on this issue if there's not any first contributor taking it

**Comment by KevinMulhern** [comment]
Thanks @ascodeasice, it's been assigned to you :)
