### ISSUE TITLE
Chore: Update Twitter logo and name in footer

### ISSUE THREAD

**Issue by WebSnke** [TheOdinProject/theodinproject#4161]
### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] The title of this issue follows the `Chore: brief description of chore` format, e.g. `Chore: Lesson complete button does not update on click`
- [X] Would you like to work on this issue?

### Chore description

The footer still uses the old Twitter logo and name.

### Acceptance criteria

- [ ] Change name to 'X'
- [ ] Update SVG

**Comment by Asartea** [comment]
Twitter is still the commonly used name for the social media platform, and the site is still located at twitter.com. In this stage I think it would be premature to switch over

**Comment by WebSnke** [comment]
> Twitter is still the commonly used name for the social media platform, and the site is still located at twitter.com. In this stage I think it would be premature to switch over

Yeah, I understand. It is obvious however that Elon really wants to change it to 'X' and that the old name will be phased out.

**Comment by Asartea** [comment]
> It is obvious however that Elon really wants to change it to 'X' and that the old name will be phased out.

...and? As long as Twitter is still clearly the name people recognize I don't think that provides a compelling argument, although I'm of course not a maintainer

**Comment by KevinMulhern** [comment]
Thanks for the suggestion @WebSnke. As mentioned, with brand recognition still being much stronger for the old logo, we'd like to wait and see how this rebranding goes and defer this for now.
