### ISSUE TITLE
Redesign: Buttons font-family to OpenSans

### ISSUE THREAD

**Issue by adachiu** [TheOdinProject/theodinproject#417]
This task requires updating the navigation buttons and CTA buttons to font-family OpenSans. Currently, the body tag has different font families. Change the body tag font-family to OpenSans.

### Working on this task

- [ ] If you want to work on this task, please claim it by commenting below   
- [ ] Branch off the redesign branch                                                                 
- [ ] When you are submitting your pull request for this task please ensure the base branch you want to merge into is the redesign branch

**Comment by mbabaian** [comment]
I'll take this one if it's still available

**Comment by faisal3389** [comment]
Hi,
I want to work on this issue.

**Comment by KevinMulhern** [comment]
Hi @faisal3389, sorry this one should have been closed. It was resolved in a unrelated PR 😬 
We have other open issues you can work on though, thank you for wanting to contribute 😄

**Comment by arun1595** [comment]
@faisal3389 Kevin's right. Can you help us fix [this](https://github.com/TheOdinProject/theodinproject/issues/414) issue?

**Comment by faisal3389** [comment]
Okay, I'll try to resolve the alignment issue.
This is my first time trying to contribute to Open source community. I'll
do my best

**Comment by arun1595** [comment]
@faisal3389 Awesome, thanks!

**Comment by KevinMulhern** [comment]
Thanks @faisal3389, if you need any assistance with anything be sure to let us know 😄
