### ISSUE TITLE
Redesign: Success Stories page

### ISSUE THREAD

**Issue by adachiu** [TheOdinProject/theodinproject#418]
The tasks involve updating the spacing so that we maintain consistency to match the other pages.

1. Remove `margin-top` from class `.success-stories-sign-up`
2. Add `margin-bottom: 6em;` to `.success-stories-container` 
3. Increase the padding between the "Sign Up" button and the footer. Match it to the spacing between the `.success-stories-container` and the "Start learning for free now" text.
4. The name in each card are too close to the bottom story text. Add a class to the p tag and give it 20px padding to space it out. Screenshot below to show what I mean:
<img width="855" alt="screen shot 2017-04-16 at 1 55 54 am" src="https://cloud.githubusercontent.com/assets/13413986/25070051/ec509d64-2247-11e7-930e-324c07377c65.png">

### Working on this task

- [ ] If you want to work on this task, please claim it by commenting below   
- [ ] Branch off the redesign branch                                                                 
- [ ] When you are submitting your pull request for this task please ensure the base branch you want to merge into is the redesign branch

**Comment by rdavid1099** [comment]
@adachiu I'll work on this issue.

**Comment by arun1595** [comment]
@rdavid1099 Thanks! Please go ahead :)

**Comment by arun1595** [comment]
Resolved in https://github.com/TheOdinProject/theodinproject/pull/435 by @rdavid1099
