### ISSUE TITLE
Bug: Bug in favicon logo while viewing  after bookmarking through reading list in chrome.

### ISSUE THREAD

**Issue by jeeva-learner** [TheOdinProject/theodinproject#4215]
### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] The title of this issue follows the `Bug: brief description of bug` format, e.g. `Bug: Lesson complete button does not update on click`
- [x] Would you like to work on this issue?

### Bug description

after bookmarking, the dashboard webpage, and when viewing it through reading list option available in chrome. The favicon shows 
some one else's photo instead of the odin project logo. 
![image](https://github.com/TheOdinProject/theodinproject/assets/86639800/8379e44a-6e25-409d-8cac-1bdbbc1b3553)

### How to reproduce

1.Open chrome
2. go to odin project website
3. bookmark the dashboard
4. open reading list feature in chrome
5. view the odin project bookmark
6. it shows some one else's personal photo

### Expected behavior

1.Open chrome
2. go to odin project website
3. bookmark the dashboard
4. open reading list feature in chrome
5. view the odin project bookmark
6. it should show the odin project logo

### What browsers are you seeing the problem on?

Chrome

### What OS are you using?

Windows

### Discord Name

oreki_houtorou

**Comment by KevinMulhern** [comment]
Thanks for reporting and being willing to work on it @jeeva-learner. It's assigned to you :)

**Comment by jeeva-learner** [comment]
Hello, Team so i surfed through some archives and found the issue is not with the website rather than with the browser, and it can be fixed by deleting and adding the bookmark again. I will attach the screenshot here as well. With that said i will be closing this issue since it isn't necessary anymore. Thank You ! 
![image](https://github.com/TheOdinProject/theodinproject/assets/86639800/d26b7581-a61a-4f34-95d5-1998f0ba7801)
