### ISSUE TITLE
Redesign Fix: Home page header image

### ISSUE THREAD

**Issue by adachiu** [TheOdinProject/theodinproject#422]
This task is to update the home page header image. There is also a gradient background for the header. Refer to Zeplin for more information. https://zpl.io/14j8Nn (comment your email address to be added to the Zeplin project to gain access)

SVG File:
[home-isometric.svg.zip](https://github.com/TheOdinProject/theodinproject/files/927000/home-isometric.svg.zip)

<img width="1083" alt="screen shot 2017-04-17 at 5 48 12 pm" src="https://cloud.githubusercontent.com/assets/13413986/25110044/17bc57d2-2396-11e7-83fa-e77efbc6a50e.png">

### Working on this task

- [ ] If you want to work on this task, please claim it by commenting below   
- [ ] Branch off the redesign branch                                                                 
- [ ] When you are submitting your pull request for this task please ensure the base branch you want to merge into is the redesign branch

**Comment by codyloyd** [comment]
I'm on it.

**Comment by codyloyd** [comment]
done
