### ISSUE TITLE
Bug: Broken image for Ada Chiu on team page

### ISSUE THREAD

**Issue by Asartea** [TheOdinProject/theodinproject#4227]
### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] The title of this issue follows the `Bug: brief description of bug` format, e.g. `Bug: Lesson complete button does not update on click`
- [ ] Would you like to work on this issue?

### Bug description

On the team page, the image for Ada Chui isn't loading, and instead, the alt text is displayed. The link for the image is <https://twitter.com/adachiu_design?s=21&t=7GZYEoXo0zA059kKCNhTdA>, but that just seems to lead to their Twitter profile

### How to reproduce

1. Go to the team page (https://www.theodinproject.com/team)
2. Scroll down to alumni
3. Look at the last person in the list (Ada Chui)

### Expected behavior

1. An image is displayed

### What browsers are you seeing the problem on?

Firefox, Chrome

### What OS are you using?

Windows

**Comment by wise-king-sullyman** [comment]
Thanks for reporting! Does look like something we should fix.

**Comment by KevinMulhern** [comment]
I've reached out to Ada to get an alternative avatar url.
