### ISSUE TITLE
Redesign Fix: Home page course section

### ISSUE THREAD

**Issue by adachiu** [TheOdinProject/theodinproject#423]
This task involves updating the home page's courses section.

Refer to https://zpl.io/14j8Nn (comment your email address to get added to the Zeplin project to gain access to assets and design details).

Updated version:
<img width="1079" alt="screen shot 2017-04-17 at 6 33 39 pm" src="https://cloud.githubusercontent.com/assets/13413986/25110917/6e578ac0-239c-11e7-9a89-3ae110e7a397.png">

Current old version:
<img width="665" alt="screen shot 2017-04-17 at 6 36 11 pm" src="https://cloud.githubusercontent.com/assets/13413986/25110975/d7a39cb2-239c-11e7-9215-31bdf58f4123.png">

### Working on this task

- [ ] If you want to work on this task, please claim it by commenting below   
- [ ] Branch off the redesign branch                                                                 
- [ ] When you are submitting your pull request for this task please ensure the base branch you want to merge into is the redesign branch

**Comment by sdg123** [comment]
I'd like to work on this!
My email address is sgonsal@ncsu.edu

**Comment by adachiu** [comment]
@sdg123 great! adding you to Zeplin now

**Comment by arun1595** [comment]
@sdg123 Thanks! You should've got an invitation email to access the Zeplin project. Do check you inbox.
