### ISSUE TITLE
Bug: Broken Links on Success Stories Page

### ISSUE THREAD

**Issue by thanmaisai** [TheOdinProject/theodinproject#4239]
### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] The title of this issue follows the `Bug: brief description of bug` format, e.g. `Bug: Lesson complete button does not update on click`
- [X] Would you like to work on this issue?

### Bug description

Several links on the [Success Stories page](https://www.theodinproject.com/success_stories) are not functioning when clicked. It seems like they are either broken or not properly linked.

### How to reproduce

1. Visit the [Success Stories page](https://www.theodinproject.com/success_stories).
2. Attempt to click on the links of different individuals.

### Expected behavior

The links should redirect to the respective profiles of the individuals when clicked.

### What browsers are you seeing the problem on?

Firefox

### What OS are you using?

MacOS

### Discord Name

noobcoder10

### Additional Comments

Please assign me this issue, and do add the labels for the issue/PR raised in order to make it a valuable contribution for hacktoberfest 2023

**Comment by ManonLef** [comment]
Thanks for reporting. I think I've tried them all and only Sean's website was not opening for me which might be an issue with their personal website at the moment which I think we should wait out for a bit. From your issue it seems you had issues with other links as well, could you tell me which ones those are?

**Comment by thanmaisai** [comment]
Sean Szurko and Olivia's links are not working. Sean Szurko's website is also having some issues. I can fix this by linking their LinkedIn profiles to their links.

In other words, I can change their links so that they point to their LinkedIn profiles instead of their websites.

**Comment by ManonLef** [comment]
Thanks for the quick response!

@KevinMulhern can probably shed some more light on this, but I am quite confident that those people themselves have the say on which link (if any) to include. It seems Olivia has no link, which might be a personal choice. It could be that Sean's site is down temporarily and if not, perhaps the team has a way to reach out to them personally. I suggest we wait for Kevin or someone else to respond on this matter.

**Comment by KevinMulhern** [comment]
> those people themselves have the say on which link (if any) to include

Yeah this is correct. How they are represented is their choice. We can't add or change links without their permission. I agree with @ManonLef, we should wait a couple of weeks to see if Seans site comes back online. If it doesn't we can remove his link.

**Comment by thanmaisai** [comment]
Absolutely, respect for privacy and permissions is crucial. Fully agree with @ManonLef's suggestion.
