### ISSUE TITLE
Update Twitter logo to X

### ISSUE THREAD

**Issue by Kaushik080** [TheOdinProject/theodinproject#4255]
Twitter logo is not updated in the current version of the website in the footer.
![image](https://github.com/TheOdinProject/theodinproject/assets/120493528/1f5f88d9-dc00-47aa-9c2b-e6519fef6cd7)

**Comment by Kaushik080** [comment]
I am working on it please assign it to me

**Comment by KevinMulhern** [comment]
Thanks for the suggestion @Kaushik080, we addressed this recently https://github.com/TheOdinProject/theodinproject/issues/4161
