### ISSUE TITLE
Bug: link not working in Setting Up React Environment Lesson

### ISSUE THREAD

**Issue by jwaddell10** [TheOdinProject/theodinproject#4302]
### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] The title of this issue follows the `Bug: brief description of bug` format, e.g. `Bug: Lesson complete button does not update on click`
- [X] Would you like to work on this issue?

### Bug description

the link at the end of the lesson with guide to React Developer tools isn't working. It leads to a site with various courses, and there's no guide to React Dev tools on the site.

### How to reproduce

1. Sign in
2. Visit "Setting Up A React Environment" Lesson https://www.theodinproject.com/lessons/node-path-react-new-setting-up-a-react-environment
3. Click on the link at the end of the lesson under the Assignments portion labeled "guide for React Developer Tools"

### Expected behavior

1. When I click on the link I expect to see a guide for React Dev Tools, but instead it takes me to a website that doesn't discuss React Dev Tools

### What browsers are you seeing the problem on?

Chrome

### What OS are you using?

MacOS

### Discord Name

saltypirate10

### Additional Comments

this is my first contribution! I read the instructions and followed as close as best I could but apologize if there were any errors

**Comment by rlmoser99** [comment]
Thanks for taking the time to make an issue. However, issues regarding curriculum content should be on our `curriculum` repo. This repo is a Ruby on Rails web app that imports the curriculum's markdown files.

In addition, there is already an PR to address this issue, so I will be closing this issue.
https://github.com/TheOdinProject/curriculum/pull/26949
