### ISSUE TITLE
Feature Request: Improve dark mode submission page selection readibility

### ISSUE THREAD

**Issue by scheals** [TheOdinProject/theodinproject#4307]
### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] The title of this issue follows the `Feature Request: brief description of feature request` format, e.g. `Feature Request: Add a dark mode to the website`
- [X] Would you like to work on this issue?

### Description of the Feature Request

Light mode clearly shows you which page of the submissions you are on:
![image](https://github.com/TheOdinProject/theodinproject/assets/95084627/55dd4655-1b0a-47ad-b4f7-1435b93ea717)

Dark mode doesn't seem to offer a different colour for current page:
![image](https://github.com/TheOdinProject/theodinproject/assets/95084627/c6f8a2f0-afc8-45bd-8bba-fff0789fa3c2)

So it'd be nice if dark mode got this neat Odin gold for current selection.

Issue persists on both Chrome and Firefox on Windows 11. I tried to troubleshoot this a little but I haven't gotten to the gist of it, seems like there are plenty of rules clashing in dark mode:
![darkmodepagy](https://github.com/TheOdinProject/theodinproject/assets/95084627/4294d126-c71a-4e9e-bc79-23800fe26945)

While light mode doesn't have this issue (or at least, the conflicts end up resolving in a way that the gold colour comes out on top):
![lightmodepagy](https://github.com/TheOdinProject/theodinproject/assets/95084627/aabe85d2-b561-4023-8c2d-6368eec65e73)

The rule `.pagy-nav .page.active, .pagy-nav-js .page.active` with its `color: #ce973e` seems to be the one that should grant the gold colour: https://github.com/TheOdinProject/theodinproject/blob/20cf49422d7c4c7cafe9c8bba614e753f693d090/app/assets/stylesheets/stylesheets/pagy.css#L35-L44

I can't find the exact bit that is dealing with pagy partial, sadly. If that is the place to look at, even. I was able to get gold to appear, although it made other text there appear grey:

![image](https://github.com/TheOdinProject/theodinproject/assets/95084627/634420e9-fe17-42a5-bcd0-e9888e5859b7)

So disabling:
- ` :is(.dark .pagy-nav .page a), :is(.dark .pagy-nav .page.active), :is(.dark .pagy-nav .page.next.disabled), :is(.dark .pagy-nav .page.prev.disabled), :is(.dark .pagy-nav-js .page a), :is(.dark .pagy-nav-js .page.active), :is(.dark .pagy-nav-js .page.next.disabled), :is(.dark .pagy-nav-js .page.prev.disabled)` rule's `color:` property and 
- `:is(.dark .pagy-nav .page a), :is(.dark .pagy-nav .page.active), :is(.dark .pagy-nav .page.next.disabled), :is(.dark .pagy-nav .page.prev.disabled), :is(.dark .pagy-nav-js .page a), :is(.dark .pagy-nav-js .page.active), :is(.dark .pagy-nav-js .page.next.disabled), :is(.dark .pagy-nav-js .page.prev.disabled)` rule's `color:` property seems to get the gold out.

### Acceptance criteria

- [ ] Dark mode clearly shows which page of submissions user is currently on.

**Comment by KevinMulhern** [comment]
Great spot 😎  thanks @scheals!
