### ISSUE TITLE
Bug: Dark/light mode text is smaller than other entries in hamburger menu

### ISSUE THREAD

**Issue by scheals** [TheOdinProject/theodinproject#4310]
### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] The title of this issue follows the `Bug: brief description of bug` format, e.g. `Bug: Lesson complete button does not update on click`
- [ ] Would you like to work on this issue?

### Bug description

While using a very small viewport like a phone, the navbar at the top turns into a hamburger menu. The `Dark mode` and `Light mode` text is using smaller font size.

![image](https://github.com/TheOdinProject/theodinproject/assets/95084627/89f79997-88cb-4c95-9d46-0e8876763455)

See this image for what font-size `Settings` uses:
![image](https://github.com/TheOdinProject/theodinproject/assets/95084627/c84b450e-015f-4545-9a3f-b323fab82ce8)

And this image for what `Dark mode` and `Light mode` use:
![image](https://github.com/TheOdinProject/theodinproject/assets/95084627/a7707119-a39f-4ca1-b2d7-7663c1efbd63)

Seems like there's a `.text-sm` class applied that shouldn't be, overwriting `.text-base`.

### How to reproduce

1. Grab a phone. Or perhaps use the Responsive Design Mode or equivalent.
2. Note that the top navbar is now a hamburger.
3. Click it.
4. See that the `Dark mode`/`Light mode` text is smaller than other entries in the menu.

### Expected behavior

1. Grab a phone. Or perhaps use the Responsive Design Mode or equivalent.
2. Note that the top navbar is now a hamburger.
3. Click it.
4. Don't see any difference in `Dark mode`/`Light mode`'s text size compared to other entries in the menu.

### What browsers are you seeing the problem on?

Firefox, Chrome

### What OS are you using?

Windows, Android

### Additional Comments

Just an aside - should #4307 also be a bug report instead of a feature request? 🤔

**Comment by KevinMulhern** [comment]
Nice find, thanks @scheals. This should hopefully be an easy one to fix.

**Comment by KevinMulhern** [comment]
And... theres already a PR 😆
