### ISSUE TITLE
Feature Request: Display amount of projects in each section

### ISSUE THREAD

**Issue by nikitarevenco** [TheOdinProject/theodinproject#4331]
### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] The title of this issue follows the `Feature Request: brief description of feature request` format, e.g. `Feature Request: Add a dark mode to the website`
- [ ] Would you like to work on this issue?

### Description of the Feature Request

**Why?**
I believe this will be a good change because it will show learners a preview of the content they're going to do in each section. Projects should be distinct from Lessons. 

In my opinion, "41 lessons" for JavaScript is misleading for example, as it includes both the lessons where the learner is taught something, and the projects where they apply their newfound knowledge. For this reason, I think its better to split it up into "29 Lessons | 12 Projects".

eg instead of:
![image](https://github.com/TheOdinProject/theodinproject/assets/154856872/9da8d91d-e176-4eee-b429-1ab1f8609309)

it should display:
![image](https://github.com/TheOdinProject/theodinproject/assets/154856872/cc0afafc-c7aa-4f0f-952d-e7650cbea72b)

some more examples:
![image](https://github.com/TheOdinProject/theodinproject/assets/154856872/158df272-9ba4-4ecb-b8f5-2b391e6a9b53)
![image](https://github.com/TheOdinProject/theodinproject/assets/154856872/8076afa6-46ef-4de8-868f-b3dd78f4e969)
![image](https://github.com/TheOdinProject/theodinproject/assets/154856872/123dd60a-1f6e-474f-bbed-3d377546a9e9)
![image](https://github.com/TheOdinProject/theodinproject/assets/154856872/eb87741e-3456-4fe1-9ac8-8f72351ff558)
![image](https://github.com/TheOdinProject/theodinproject/assets/154856872/ad69e692-2e04-4493-a909-cbcd9f16c8fd)

### Acceptance criteria

It should display the correct amount of lessons and projects for each section:
- [ ] Intermediate HTML and CSS: 21 Lessons | 2 Projects
- [ ] JavaScript: 29 Lessons | 12 Projects
- [ ] Advanced HTML and CSS: 15 Lessons | 1 Project
- [ ] React: 23 Lessons | 3 Projects
- [ ] NodeJS: 19 Lessons | 9 Projects
- [ ] Getting Hired: 12 Lessons | 2 Projects

**Comment by KevinMulhern** [comment]
Thanks for the suggestion, I think this a good idea. I've assigned you.

Just a couple of notes from me.

I'm not sure if a pipe will be enough of a visual separator between the two counts. But we could maybe use the same icons we use on course pages to do something like this:  
<img width="959" alt="Screenshot 2024-01-12 at 14 13 19" src="https://github.com/TheOdinProject/theodinproject/assets/7963776/72837251-f55d-4886-909b-02b2fd3e9600">

To make getting these counts simpler and to save us needing to make two count queries for each course we render. We can add `lessons_count` and `projects_count` columns to our courses table 

Rails has a [counter cache](https://guides.rubyonrails.org/association_basics.html#options-for-belongs-to-counter-cache) utility but it I don't think we can use it here with the lesson model needing to be filtered by is_project.

Our courses can only be updated through our seeds files, so we could add a script that updates lesson and project counts for each course after the the curriculum is seeded in [this file](https://github.com/TheOdinProject/theodinproject/blob/main/db/seeds.rb#L16).


Whats your thoughts?

**Comment by nikitarevenco** [comment]
> Thanks for the suggestion, I think this a good idea. I've assigned you @nikitarevenco
> 
> Just a couple of notes from me.
> 
> I'm not sure if a pipe will be enough of a visual separator between the two counts. But we could maybe use the same icons we use on course pages to do something like this: <img alt="Screenshot 2024-01-12 at 14 13 19" width="959" src="https://private-user-images.githubusercontent.com/7963776/296443833-72837251-f55d-4886-909b-02b2fd3e9600.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUyMzAzNDAsIm5iZiI6MTcwNTIzMDA0MCwicGF0aCI6Ii83OTYzNzc2LzI5NjQ0MzgzMy03MjgzNzI1MS1mNTVkLTQ4ODYtOTA5Yi0wMmIyZmQzZTk2MDAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMTRUMTEwMDQwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDI1NGU0ODY5NmY5OWNkNmU4ODUzMzNmZDM2MmQ0YmJmMjJjMzE2N2UyNTRmNTMzMjVhZGVlNjQ5MjU0OGZhOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.SxuIm7aLAHJ4T_wYSk4MYZle4hr4eGVy7M3BepusBDY">
> 
> To make getting these counts simpler and to save us needing to make two count queries for each course we render. We can add `lessons_count` and `projects_count` columns to our courses table
> 
> Rails has a [counter cache](https://guides.rubyonrails.org/association_basics.html#options-for-belongs-to-counter-cache) utility but I don't think we can use it here with the lesson model needing to be filtered by is_project.
> 
> Our courses can only be updated through our seeds files, so we could add a script that updates lesson and project counts for each course after the the curriculum is seeded in [this file](https://github.com/TheOdinProject/theodinproject/blob/main/db/seeds.rb#L16).
> 
> Whats your thoughts?

What a wonderful idea. I really like it a lot, however I don't think I will be able to complete this, as I have only just finished the foundations section and don't know anything about Rails to add a script like that. Can you please assign someone else?

**Comment by sparshalc** [comment]
@KevinMulhern Can i work on this?

**Comment by sparshalc** [comment]
Does this mean i can work on this? @KevinMulhern

**Comment by KevinMulhern** [comment]
Yep all yours @sparshalc, are you happy with the approach outlined in [this comment](https://github.com/TheOdinProject/theodinproject/issues/4331#issuecomment-1890410003)?

**Comment by sparshalc** [comment]
> Yep all yours @sparshalc, are you happy with the approach outlined in [this comment](https://github.com/TheOdinProject/theodinproject/issues/4331#issuecomment-1890410003)?


"I'd like clarification on the statement: 'Our courses can only be updated through our seeds files, so we could add a script that updates lesson and project counts for each course after the curriculum is seeded in this file.' Can you please provide more details to help me understand this process better?"

**Comment by KevinMulhern** [comment]
Sure thing! we create and update our curriculum using Rails seeds in all environments including production. If we need to add, remove or update a lesson or project, we do it in the seeds. It's the perfect place to perform the counts we need for this feature. Our [seeds docs](https://github.com/TheOdinProject/theodinproject/wiki#working-with-the-curriculum-seeds) might help make it clearer.


We basically need something like this in the seeds after we create all the curriculum records:
```ruby
Course.all.each do |course|
  course.update!(lessons_count: ..., projects_count: ...)
end
```

Does that make sense? happy to clarify anything that doesn't.
