### ISSUE TITLE
Redesign Fix: badge section of home page

### ISSUE THREAD

**Issue by adachiu** [TheOdinProject/theodinproject#437]
Tasks include adjusting the spacing and size of the badges on the home page.
Refer to https://zpl.io/14j8Nn to see the mock up with design details. To access Zeplin, comment your email in this issue in order to be invited to view the link.

This is how the update would look like:
<img width="1025" alt="screen shot 2017-04-25 at 2 20 02 am" src="https://cloud.githubusercontent.com/assets/13413986/25377990/e19f6090-295d-11e7-92fe-78615f7f06ff.png">

Complete the following tasks:

**1. Update global H2 to 24px with 35px line height**

**2. Badges should be 160 x 160 px**
<img width="255" alt="screen shot 2017-04-25 at 12 02 15 am" src="https://cloud.githubusercontent.com/assets/13413986/25372484/78d3f6f6-294a-11e7-9773-a03be0c8251a.png">

**3. Badges spacing should be 124px**
<img width="547" alt="screen shot 2017-04-25 at 12 01 48 am" src="https://cloud.githubusercontent.com/assets/13413986/25372471/66ec26fc-294a-11e7-8643-a3dbcdf285d0.png">

**4. 40px spacing between rows**
<img width="260" alt="screen shot 2017-04-25 at 1 39 11 am" src="https://cloud.githubusercontent.com/assets/13413986/25376150/1727b7c2-2958-11e7-9f65-f3c0329c479f.png">

**5. `View Curriculum` button is 60px from last badge title**
<img width="350" alt="screen shot 2017-04-25 at 1 42 04 am" src="https://cloud.githubusercontent.com/assets/13413986/25376300/7c90a56a-2958-11e7-8874-ad95b641d3fc.png">

**6. Add white card as background for badge section. 1110px x 1085px. Remember to add box shadow (refer to https://zpl.io/14j8Nn for details of shadow values)**
<img width="1220" alt="screen shot 2017-04-25 at 2 09 59 am" src="https://cloud.githubusercontent.com/assets/13413986/25377415/5956182e-295c-11e7-935d-7e32b819f7d7.png">

**7. White card padding is 70px**
<img width="354" alt="screen shot 2017-04-25 at 2 14 58 am" src="https://cloud.githubusercontent.com/assets/13413986/25377723/2b9a4774-295d-11e7-9234-ea7ec29663cd.png">
<img width="831" alt="screen shot 2017-04-25 at 2 15 16 am" src="https://cloud.githubusercontent.com/assets/13413986/25377730/2eb18cba-295d-11e7-8733-38aad736889c.png">

### Working on this task

- [ ] If you want to work on this task, please claim it by commenting below   
- [ ] Branch off the redesign branch                                                                 
- [ ] When you are submitting your pull request for this task please ensure the base branch you want to merge into is the redesign branch

**Comment by eating247** [comment]
I'd like to work on this! ttwang.303@gmail.com

**Comment by adachiu** [comment]
@eating247 great! Invited you to access Zeplin.

**Comment by arun1595** [comment]
@eating247 is working on this.

**Comment by codyloyd** [comment]
@adachiu the spacing between the badges is flexible based on the browser resolution... would you like it fixed?  Also, how would you like the layout to break down on smaller screens?

(tagging @eating247 so she sees the convo...)

**Comment by adachiu** [comment]
There would need to be media queries for the badge spacing. The mobile mock
up is going up to zeplin today.

**Comment by codyloyd** [comment]
good news about the mobile mockup 💃

**Comment by adachiu** [comment]
@eating247 There are some updates reflected on the home page desktop view to match the mobile view. I'm closing this issue, and will add new issues to address the updates.

**Comment by eating247** [comment]
Got it!

**Comment by adachiu** [comment]
Keep an eye out for the upcoming issues! I'm creating them now. Thanks!
