### ISSUE TITLE
Feature Request: Automatic OS theme adaptability

### ISSUE THREAD

**Issue by shravzzv** [TheOdinProject/theodinproject#4378]
### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] The title of this issue follows the `Feature Request: brief description of feature request` format, e.g. `Feature Request: Add a dark mode to the website`
- [ ] Would you like to work on this issue?

### Description of the Feature Request

When I visit TOP website, I would like to set the theme toggle to use the system theme. This will prevent the need to change the theme manually every time when the OS theme changes.

### Acceptance criteria

- [ ] A dropdown to select **system theme** option in the header.
- [ ] The website adapts to the system theme after selecting this option.
- [ ] The user's choice persists after leaving the website.

**Comment by CouchofTomato** [comment]
There is already a PR being worked on for this so closing this out.

https://github.com/TheOdinProject/theodinproject/pull/4341

**Comment by shravzzv** [comment]
Alright
