### ISSUE TITLE
Feature request: Reorder rendering techniques/keys/props lessons

### ISSUE THREAD

**Issue by MaoShizhong** [TheOdinProject/theodinproject#4379]
### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] The title of this issue follows the `Feature Request: brief description of feature request` format, e.g. `Feature Request: Add a dark mode to the website`
- [X] Would you like to work on this issue?

### Description of the Feature Request

The current React course has the following order of lessons:
1. Rendering techniques (lists/conditional)
1. Keys
1. Passing data between components

The first two lessons include code examples that demonstrate and rely on the use of keys (which in turn, benefits from the understanding of props). In each of those first two lessons, there are notes saying "don't worry about XYZ, they will be covered later", and the assigned react.dev lessons also include examples and sections on those topics which the course says to ignore for now.

Meanwhile, the props lesson and its assigned react.dev lesson do not include examples of conditional rendering, nor rendering lists and keys.

A recent issue with the current order involved the rendering techniques lesson not being 100% explicit that the react.dev rendering techniques exercises should be skipped, as they involve using keys/extracting out components with props. It only says to ignore the last section on keys. Recently, a learner had a lot of trouble with one of these exercises which was further made more difficult because I and other helpers did not realise they were attempting those exercises before learning about keys and props.

### Acceptance criteria

- [ ] Reorder the three lessons to:
   1. Passing data between components
   1. Rendering techniques
   1. Keys (I actually think introducing list rendering before keys makes more sense)
- [ ] In the curriculum repo, amend the above lessons as necessary to accommodate for the new order (e.g. remove mentions of "don't worry about props", reference the previous props lesson if appropriate etc.)

### Additional Comments

[Link](https://discord.com/channels/505093832157691914/664184123061174274/1204428951250796595) to reordering suggestion in the react discord channel

**Comment by CouchofTomato** [comment]
@TheOdinProject/react Can someone take a look please.

**Comment by ParagPalkar** [comment]
I would like to contribute !!

**Comment by MaoShizhong** [comment]
I'm going to leave this issue open in case any other maintainers want to share thoughts on it. 

In the meantime, I'm personally leaning a little more on the "leave the order as it is" side currently as:
- confusions caused by this haven't been too common lately - will reevaluate if needs be
- changing the lesson order *will* cause confusion for some who are going through these lessons and a potentially silent order change can cause them to miss a lesson or two

**Comment by MaoShizhong** [comment]
Closing for now - no planned action.
