### ISSUE TITLE
Entire course: Remove 'Projects:' from the title of every project.

### ISSUE THREAD

**Issue by nikitarevenco** [TheOdinProject/theodinproject#4390]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

The image on the left-hand side already conveys that this will be a project. Normal lesson's dont have a 'Lesson:' prefix, so why would it make sense to have every project have a 'Project:' prefix when we already have an image that conveys exactly that? 

Please let me know what you think about this.

![image](https://github.com/TheOdinProject/curriculum/assets/154856872/775352f2-cc06-48ed-9d23-0feb42ba41aa)

### Path

Foundations, Ruby / Rails, Node / JS

### Lesson Url

Entire course, all projects

### (Optional) Discord Name

Revenco

### (Optional) Additional Comments

We can also rename some other lessons to be more descriptive. A previous issue renamed Fundamentals part X lessons to be more descriptive, but there are some lessons in the course that could also use this rename. As an example:

**Comment by AngeloThys** [comment]
I find the added context more important than the subjectively _sleeker_ look.

**Comment by Asartea** [comment]
In addition to the points @KevinMulhern and @AngeloThys have raised, I would also like to note that the project icon is only shown on the course overview; as far as I'm aware there is no indication on a lesson page itself if something is a project

**Comment by nikitarevenco** [comment]
Thank you everyone for giving your opinions. I'm going to close this issue as it seems that more people are in favor of keeping the projects indicator!
