### ISSUE TITLE
Lesson occasionally skipped when pressing next lesson

### ISSUE THREAD

**Issue by crasion528** [TheOdinProject/theodinproject#4404]
### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] The title of this issue follows the `Bug: brief description of bug` format, e.g. `Bug: Lesson complete button does not update on click`
- [ ] Would you like to work on this issue?

### Bug description

When clicking "next lesson" button on JavScript Developer Tools lesson in Foundations curriculum, there is an occasional skip over of the lesson Function Basics and instead puts you through to Problem Solving lesson. The skipped over lesson does not mark as completed.

### How to reproduce

N/A seems to happen sporadically.

### Expected behavior

Expected to click next lesson at the bottom of the JavaScript Developer Tools lesson and be directed to Function Basics.

### What browsers are you seeing the problem on?

Chrome

### What OS are you using?

Ubuntu

### Discord Name

crasion528

### Additional Comments

I have seen this happen more than once because I like to sometimes click next lesson for time management and planning reasons. It happened once before and after I had finished the JavaScript Developer Tools lesson.

**Comment by KevinMulhern** [comment]
Thanks for reporting @crasion528. I've been unable to recreate this myself. But I've got a couple of questions which should help track down the cause:

- Was the previous time this happened recent? - within the past week?
- When using TOP, do you always start it in a new tab or would you leave TOP running in its own tab that you keep coming back to over longer periods of time like days or weeks?

**Comment by crasion528** [comment]
No problem @KevinMulhern! And to answer your question I leave the TOP tab I'm running open for extended periods of time (can't give exacts because sometimes I need to restart chrome and recover tabs). But I usually keep a singular tab open where I'm currently at in the curriculum at all times.

**Comment by KevinMulhern** [comment]
Thanks @crasion528, has it happened anytime since you've opened this issue?

We renamed the JS lessons around the time this started happening for you, that might have screwed with the caching system we use, especially for long running tabs.

**Comment by KevinMulhern** [comment]
No reports of this happening since. If it happens again feel free to reopen please.
