### ISSUE TITLE
Bug: Eric's image on the team page is broken

### ISSUE THREAD

**Issue by Asartea** [TheOdinProject/theodinproject#4437]
### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] The title of this issue follows the `Bug: brief description of bug` format, e.g. `Bug: Lesson complete button does not update on click`
- [ ] Would you like to work on this issue?

### Bug description

The image for Eric on https://www.theodinproject.com/team doesn't load, and the image link returns a 403

### How to reproduce

1. Go to https://www.theodinproject.com/team
2. Scroll down to maintainers
3. Look at Eric Olkowski
4. The image does not display

### Expected behavior

1. The image displays

### What browsers are you seeing the problem on?

Firefox

### What OS are you using?

Windows

### Discord Name

asarta

### Additional Comments

tagging @thatblindgeye

**Comment by thatblindgeye** [comment]
Was about to ask how you knew to tag me as if my name isn't in my GH profile 🤣 

Thanks for bringing this up, I'll need to put a PR up to use a working image

**Comment by Asartea** [comment]
_Hides suspiciously large book titled: Maintainers: Names, Ages, Locations, and other Personal info_


Also, in addition to the name, your GitHub is linked on the team page ;)
