### ISSUE TITLE
Chore: Remove climate control gem

### ISSUE THREAD

**Issue by KevinMulhern** [TheOdinProject/theodinproject#4453]
### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] The title of this issue follows the `Chore: brief description of chore` format, e.g. `Chore: Lesson complete button does not update on click`
- [ ] Would you like to work on this issue?

### Chore description

We use Climate Control to stub out env vars in our tests. But this functionality is now included in the [latest version of dot env](https://github.com/bkeepers/dotenv/discussions/476). 

### Acceptance criteria

- [ ] Replace all instances of `ClimateControl.modify` in our specs with the dot env equivalent 
- [ ] Remove climate_control from our Gemfile.

**Comment by Asartea** [comment]
Would be willing to take this

**Comment by KevinMulhern** [comment]
Thanks @Asartea
