### ISSUE TITLE
Redesign: Settings Page

### ISSUE THREAD

**Issue by codyloyd** [TheOdinProject/theodinproject#446]
This task is to implement the design for user settings page and to add in-place editing feature for updating the user profile.

### Working on this task

- [ ] If you want to work on this task, please claim it by commenting below   
- [ ] Branch off the redesign branch                                                                 
- [ ] Check out our [styleguide](https://staging-odin-project.herokuapp.com/styleguide)
- [ ] When you are submitting your pull request for this task please ensure the base branch you want to merge into is the redesign branch  

If you have any questions or need clarification about anything related to this task please contact the maintainers in our [contributing channel on Gitter](https://gitter.im/TheOdinProject/Contributing)

**Comment by codyloyd** [comment]
I intend to do this one.. but want to do something else first, so I decided to go ahead and create an issue in case anyone else wants to jump in on it, and also for a place to put some notes.

**Comment by codyloyd** [comment]
This idea was mentioned by Arun, and I think it's a fine idea.

https://github.com/bernat/best_in_place

I might give some thought to implementing it myself without jQuery... but there isn't a ton of reason not to just use that gem.

**Comment by codyloyd** [comment]
@KevinMulhern, @arun1595, what's the backend for this page?  Is there already a controller/route for it?

**Comment by KevinMulhern** [comment]
I believe this page is generated by devise, Here it is on live https://www.theodinproject.com/users/edit

I think the controller for this page needs to be generated for us to customize it, let me look getting the backend for it sorted out over the weekend.

**Comment by codyloyd** [comment]
ah ok.. yeah devise can generate the controllers/views so that we can do what we like.

**Comment by codyloyd** [comment]
@KevinMulhern did you generate the controller/view?

If not.. or if you aren't working on it I can go ahead and do so.

**Comment by KevinMulhern** [comment]
Hi @codyloyd I didn't 🙈 I've been super busy with work stuff. Its all yours 😄

**Comment by codyloyd** [comment]
cool
I'll try to break stuff this afternoon.

**Comment by codyloyd** [comment]
it's looking like I'm not going to have to do this... seems like it's been done... but we'll see.  I'm still poking around trying to get a feel for were all the pieces are.

**Comment by codyloyd** [comment]
@KevinMulhern @arun1595 I've got the design of the page more or less done.. and now I need to figure out what's going on in the back.

I've already got the easy stuff like username and email editable.

how are we going to implement the 'learning goals' and 'notification settings'?  I suppose the goal can just be another column in the DB, but I don't know about notifications.

**Comment by KevinMulhern** [comment]
I would leave notifications out for now, There will potentially be a lot of emails sent out with that feature. We would need to have a background worker set up to handle all of that traffic to make sure the performance of the main site doesn't suffer. I think this is something best tackled after the redesign 😄 

As for the learning goals, yeah you can create a couple of new columns for those. We already have a `about` column which you can use for the learning goal.

**Comment by codyloyd** [comment]
aha nice.

**Comment by codyloyd** [comment]
@adachiu I'm making progress and have had to deviate from the mockup a bit.  The password settings require 3 inputs as in the following screenshot, as such, I thought it best to put them on their own card.

Shall I continue this way?  How do you want me to style it?

![1_034](https://cloud.githubusercontent.com/assets/18574792/25847048/0b2c3fec-347a-11e7-8747-425b103ea26a.png)

**Comment by KevinMulhern** [comment]
We can go over this page in the next review with @adachiu 😄
