### ISSUE TITLE
Redesign: Mobile view Footer

### ISSUE THREAD

**Issue by adachiu** [TheOdinProject/theodinproject#447]
This task includes creating a media query for the footer in mobile view (320px width). Comment your email to get access to the Zeplin file for full design details https://zpl.io/14dBXX

**Please refer to the Zeplin file's details for spacing between objects.**

This is the footer in desktop view (1440px width)
<img width="1142" alt="screen shot 2017-04-28 at 12 09 29 am" src="https://cloud.githubusercontent.com/assets/13413986/25518051/0371a5d4-2ba7-11e7-90f5-83fc037fbe1e.png">

This is the mobile media query outcome for the footer.
<img width="404" alt="screen shot 2017-04-28 at 12 07 59 am" src="https://cloud.githubusercontent.com/assets/13413986/25518026/d3f09cca-2ba6-11e7-920b-56f1eeece1e8.png">

> Idea: 
> Use `visibility: hidden;` to hide all the extra links and logo in the mobile view.

### Working on this task

- [ ] If you want to work on this task, please claim it by commenting below   
- [ ] Branch off the redesign branch                                                                 
- [ ] When you are submitting your pull request for this task please ensure the base branch you want to merge into is the redesign branch

**Comment by codyloyd** [comment]
on it...
@adachiu do you have any preference for how the footer breaks down on medium sized screens?  How do you feel about the current implementation?

**Comment by codyloyd** [comment]
@adachiu Here's what I've got right now.  3 screenshots are fullscreen, 'tablet view (< 768px)' and 'mobile view (< 480px)'

let me know what you think.
![learn web development for free using ruby on rails the odin project - chromium_006](https://cloud.githubusercontent.com/assets/18574792/25532877/69b39972-2bf4-11e7-897f-44f5775f91b9.png)

![learn web development for free using ruby on rails the odin project - chromium_007](https://cloud.githubusercontent.com/assets/18574792/25532886/6e46cff4-2bf4-11e7-8e3f-e61bd8c79ca7.png)

![learn web development for free using ruby on rails the odin project - chromium_008](https://cloud.githubusercontent.com/assets/18574792/25532894/72def38e-2bf4-11e7-9d0c-a0b1b53664d7.png)

**Comment by adachiu** [comment]
I have a mock up and will add to Zeplin for you. I was originally going to
add another issue for it, but I'll add that here since you're already doing
it. Expect it later today.

**Comment by adachiu** [comment]
@codyloyd Is the logo horizontally aligned with the logo text? It looks like a couple px off.

Here's the tablet mock up. We don't need the logo at the bottom for this view since the navbar is fixed. https://zpl.io/Z1pmHap

**Comment by codyloyd** [comment]
awesome.  Will get this done this afternoon.
