### ISSUE TITLE
Cannot do Migration

### ISSUE THREAD

**Issue by bKP451** [TheOdinProject/theodinproject#4473]
### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] The title of this issue follows the `Bug: brief description of bug` format, e.g. `Bug: Lesson complete button does not update on click`
- [ ] Would you like to work on this issue?

### Bug description

I am trying to setup the odin project locally. 
When I try to migrate, 
I get 
PG::UndefinedTable: ERROR:  relation "lessons" does not exist
/home/pandeybikashcom/Pictures/theodinproject/db/migrate/20210622162155_add_course_id_to_lessons.rb:3:in `change'

Caused by:
ActiveRecord::StatementInvalid: PG::UndefinedTable: ERROR:  relation "lessons" does not exist (ActiveRecord::StatementInvalid)
/home/pandeybikashcom/Pictures/theodinproject/db/migrate/20210622162155_add_course_id_to_lessons.rb:3:in `change'

Caused by:
PG::UndefinedTable: ERROR:  relation "lessons" does not exist (PG::UndefinedTable)`
`

### How to reproduce

sdf

### Expected behavior

The migration should happen successfully.

### What browsers are you seeing the problem on?

Chrome

### What OS are you using?

Ubuntu

**Comment by KevinMulhern** [comment]
Hey @bKP451, try running `$ rails db:schema:load` instead of `$ db:migrate`

**Comment by bKP451** [comment]
Hello there, @KevinMulhern Thanks.

**Comment by bKP451** [comment]
Good.
