### ISSUE TITLE
Feature Request:  Display a zoom-in  cursor when hovering over images within lesson lesson content

### ISSUE THREAD

**Issue by KevinMulhern** [TheOdinProject/theodinproject#4474]
### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] The title of this issue follows the `Feature Request: brief description of feature request` format, e.g. `Feature Request: Add a dark mode to the website`
- [ ] Would you like to work on this issue?

### Description of the Feature Request

When hovering over images within lesson content, we want to display a zoom-in cursor instead of a pointer cursor. This will provide more accurate feedback to the user - clicking on an image will open it up in a new tab so its "zoomed-in".

### Acceptance criteria

- [ ] Visit the git basics lesson
- [ ] Hover over one of the images
- [ ] A zoom-in cursor should appear

### Additional Comments

- We use Tailwind - their cursor utility classes [can be found here](https://tailwindcss.com/docs/cursor).
- A new style rule should be added to the [lesson-contents.css](https://github.com/TheOdinProject/theodinproject/blob/main/app/assets/stylesheets/stylesheets/lesson-content.css) file - any img tags within an a tag should display the new cursor on hover

**Comment by BryanF1nes** [comment]
If you don't either @KevinMulhern or @Rllopez0410 are not going to work on this I would like the opportunity. :)

**Comment by KevinMulhern** [comment]
Ah sorry, I forgot to untick "Would you like to work on this issue?". 

@Rllopez0410 I'll assign it to you since you were first. But I appreciate you offering as well @BryanF1nes. I've got a few more small stories to add over the weekend that might be up your street. I'll keep you posted.

**Comment by BryanF1nes** [comment]
No worries @KevinMulhern I appreciate it!

**Comment by Rllopez0410** [comment]
@KevinMulhern, i would love to work on this issue.

**Comment by Rllopez0410** [comment]
hey @KevinMulhern, should I go through all the lessons in TOP or are there specific pages that require this feature?

**Comment by KevinMulhern** [comment]
Hey @Rllopez0410, it should be applied to all imgs that are children of a tags within lesson content. Creating a new css rule for it in [this file](https://github.com/TheOdinProject/theodinproject/blob/main/app/assets/stylesheets/stylesheets/lesson-content.css) should do the job.

**Comment by Rllopez0410** [comment]
@KevinMulhern thank you. My apologies for the confusion.
