### ISSUE TITLE
Feature Request: Jobs List For the Community

### ISSUE THREAD

**Issue by 00MB** [TheOdinProject/theodinproject#4475]
### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] The title of this issue follows the `Feature Request: brief description of feature request` format, e.g. `Feature Request: Add a dark mode to the website`
- [X] Would you like to work on this issue?

### Description of the Feature Request

**Description:** A new tab in the navigation bar, titled "Jobs", which would lead to a new page containing a list full of remote coding jobs and freelance positions. It uses the [CrackedDevs API](https://api.crackeddevs.com) which contains all the relevant job information such as junior, senior, front end specific and more. The CrackedDevs API is 100% free for life, and I would do all the maintenance.

**How would it be useful?** Having a jobs list would add a ton of value to users in the community. The main reason most community members are learning to code is to get a job. By having this jobs list, it would make it easier to get one. It also acts as great motivation towards current learners, seeing that there are jobs they can apply for once they feel ready. Finally, it would create more returning users to The Odin Project, as there are actions they can take even after learning to code (if they ever need a job they can come back to The Odin Project to find one).

Mock design
<img width="1305" alt="image" src="https://github.com/TheOdinProject/theodinproject/assets/56583386/672eadbc-1687-40a5-9671-ca787f3a0666">

You can check the demo concept I made here: https://the-oden-project-mvp.vercel.app/

The designs are v1 and happy for changes and improvements. Possible improvements could be adding a filter and sorting.

Open to all feedback and questions (:

### Acceptance criteria

- [] A new tab in the navigation bar - "Jobs"
- [] A new page /jobs
- [] The /jobs page contains a list of jobs, fetched via the [CrackedDevs API](https://api.crackeddevs.com)
- [] Initially it would show a loading skeleton, until the first 10 jobs are loaded, by most recent date created
- [] After you scroll to the bottom, it would load the next 10 jobs (infinite loading)

### Additional Comments

I would do all the work necessary here, I looked through the entire codebase and know exactly what to change. I have already cloned the project to create my demo concept which you can view here: https://the-oden-project-mvp.vercel.app/

**Comment by kahmoh** [comment]
I think this idea makes perfect sense. As you said, most people are here to look for jobs, so this aids that goal very well. A problem I see, that I think would need consideration is, people feeling as though this tells them to apply early in the curriculum.

**Comment by bycdiaz** [comment]
@00MB I'm curious about how familiar you are with The Odin Project. Asking since I feel like a lot of this runs contrary to what the platform is.

I think one thing that makes our community and curriculum great is the very narrow focus. I think a job board ads things to think about outside of helping people learn programming fundamentals in the context of web technologies.

Additionally, I'm not sure of the utility of showing positions outside of entry level to people learning here, who will be pursuing entry level work. In our discord, we also regularly discourage pursuing freelance work.

This is also just a personal perspective: A lot of people, in a lot of ways, have petitioned the inclusion of adding content that will keep people coming back. I suppose it is the educator background in me but I don't want people to linger here, or come back. I think if we do what we do well, which I think we do, people will be equipped to go off and do great on their own.

I'm personally always open to being swayed. So I have some questions:

- How does an internal job board, specifically the one provided by this API, make it easier for people to get jobs over an external board? Is there some mechanism that comes with this API that would give folks using it an edge when applying to one of these roles?
- You mentioned you'd do the maintenance. Can you commit to that indefinitely?
- Can you share why you feel job listings would increase motivation? If increasing motivation is the goal, I wonder if there are alternatives.

**Comment by MaoShizhong** [comment]
Given that the proposer is affiliated with the API used, that alone is enough for me to vote against this implementation.
But even if there was genuinely no affiliation in the slightest, I share the same opinion shared by @bycdiaz above, and do not think this is the most necessary feature, nor appropriate given TOP's goal.

**Comment by 00MB** [comment]
> I think this idea makes perfect sense. As you said, most people are here to look for jobs, so this aids that goal very well. A problem I see, that I think would need consideration is, people feeling as though this tells them to apply early in the curriculum.

Good points, it could be built to only be shown to a certain level of user. Also given that most of the users are entry level, the job board could be pre filtered to only junior positions, making it more realistic to apply.

**Comment by kahmoh** [comment]
I agree that would be a good fix. It seems there's a feeling against this change. Some mentions of this not fitting the goal of the course make me wonder whether there's a disconnect between what the course is intended for and what people use it for. I think a survey would suggest that a large majority of learners use TOP to get a web dev job, not just to learn the technologies, but that's just a feeling.

**Comment by bycdiaz** [comment]
@kahmoh We are fairly confident that people are coming here to learn the skills that would ready them for a job search by learning about the technologies. I don't think we need a survey to confirm that. Having a job board does not help people learn the technologies. But if you can tell me how a job board helps people learn, I'm interested in learning about that.

**Comment by MaoShizhong** [comment]
> I agree that would be a good fix. It seems there's a feeling against this change. Some mentions of this not fitting the goal of the course make me wonder whether there's a disconnect between what the course is intended for and what people use it for. I think a survey would suggest that a large majority of learners use TOP to get a web dev job, not just to learn the technologies, but that's just a feeling.

@kahmoh There's a difference between people using something like TOP as a part of their journey to getting a job in web dev, and TOP being a tool for finding and sharing job postings.
TOP's goal is to teach programming and web dev fundamentals. When an individual is personally ready to go job hunting, they ought to start exploring and using tools that are designed for that purpose, and by that point would surely be more than capable of exploring such resources and tools independently.

TOP would best stick to what it aims to do, and tries to do so as well as it can.
That's on top of a huge issue regarding the proposer's own affiliation with the API used, which goes directly into realm of self-promotion. We cannot confirm what they do and don't get out of the API being used, and given the above points, it's likely not something we have a need to explore anyway.

**Comment by wbray93** [comment]
while I agree mostly with @bycdiaz here I can understand that seeing a job board showing there are places actually hiring for the beautifully created curriculum you have made might encourage people to not have doubts. Especially if it does indeed show actual entry jobs and not the jobs that claim to be entry on linked in but ask for senior dev level skills. I know that often people might think well its cool im learning these skills but job board x says i need this this and this arbitrary skill which is not taught in the curriculum(For good reason I know) but to the learner it might show an even deeper level of trust for the skeptics. However like I said I agree with @bycdiaz and @MaoShizhong on then one pretty much 100 percent. At this point TOP has had tons of success stories and i feel that speaks for itself that their program works if you work the program. It is an interesting idea though.

**Comment by fabulousgk** [comment]
I think a job board would take time away from contributors improving the curriculum.  I am a big fan of do what you do best.  I think when it comes time to find a job people know the best places to go, and those places are going to do a far better job with far better tools.

Yes, people come to Odin to learn webdev to get a job, that is not an argument, what is at question is, is Odin a curriculum or a job site.  I argue it is a curriculum.

**Comment by kahmoh** [comment]
I'm not saying a job board improves a persons abilities in using web technologies, although I believe it does indirectly as a job is the best way to learn. I'm pointing out that a job board not fitting the narrow goal of TOP suggests that it's just a step in the journey to being job ready. I agree that it is, but I also believe that many would believe that TOP is the only step towards getting a job. This suggestion from a potentially new user is evidence of that and I think it's something that is an issue itself.

**Comment by kahmoh** [comment]
My previous comment was addressed to Carlos, but I think it is also a fitting response to the other comments on here.

**Comment by kahmoh** [comment]
@MaoShizhong I agree that the proposer having affiliation with the API (I believe as founder) is worth considering, but I wonder if the rule against self promotion is flexible. TOP would be reduced to a lot less than it currently is, if it couldn't link to outside sources, how do you differentiate a trustworthy and useful source from one that's intent is personal gain. Is it the fact that the sources commonly seen throughout TOP were picked by TOP contributors where as this suggestion has the exchange the other way round?

**Comment by bycdiaz** [comment]
While useful to know, I personally think their affiliation is a non-issue when weighing this addition.

**Comment by fabulousgk** [comment]
There is a huge difference between links and an API that is required for core functionality.

**Comment by bycdiaz** [comment]
Anywho - There has also been discussion among our curriculum maintainers.

Adding this would take us in a direction we aren't interested in at the moment.

Thank you @00MB for the proposal. And thanks to everyone who chimed in!

**Comment by MaoShizhong** [comment]
My main concerns are primarily unrelated to the affiliation, but even if I personally felt the feature was beneficial, the affiliation issue would be a blocker.

@kahmoh We don't know and can't confirm what they do or don't get from the API used. There is sensibility in approaching such things with caution, in case the motivation behind its use is for the author's personal gain. We also do not know nor will it be easy to confirm whether the API breaks any T&Cs for sites where it gets the job postings from - that's a whole separate thing that would need exploring on top of the previous issue.

But anyway, the primary issue to discuss is the feature's value for TOP, for which points have been shared above.

**Comment by kahmoh** [comment]
I wonder want to drag this out with too much unnecessary discussion, I agree that there's a big difference and that's quite obvious, I just wonder what the difference is specifically and why it's important here.

**Comment by kahmoh** [comment]
@MaoShizhong that makes a lot of sense, was just trying my best to provide my view. Thanks for clearing that part up.

**Comment by MaoShizhong** [comment]
@kahmoh Discussion and opinions are always welcome! Don't be afraid to share your opinions. You may discover things you didn't consider but equally, you may end up sharing things others didn't consider either :+1:
