### ISSUE TITLE
Redesign: Mobile view Success Stories (Home page)

### ISSUE THREAD

**Issue by adachiu** [TheOdinProject/theodinproject#448]
This task involves creating mobile media queries (320px width) for the `Success Stories` section on the home page. Also, limit the `success stories posts` to 2 only for the mobile view. This is because we don't want the scrolling to be too long on mobile.

Comment your email to get access to the Zeplin file for full design details https://zpl.io/14dBXX
**Please refer to the Zeplin file's details for spacing between objects.**

<img width="321" alt="screen shot 2017-04-28 at 12 22 47 am" src="https://cloud.githubusercontent.com/assets/13413986/25518510/e6968fea-2ba8-11e7-9203-5c3f42f6556e.png">

### Working on this task

- [ ] If you want to work on this task, please claim it by commenting below   
- [ ] Branch off the redesign branch                                                                 
- [ ] When you are submitting your pull request for this task please ensure the base branch you want to merge into is the redesign branch

**Comment by codyloyd** [comment]
merged: closing
