### ISSUE TITLE
Bug: Markdown preview tool does not render dropdowns and summaries

### ISSUE THREAD

**Issue by MaoShizhong** [TheOdinProject/theodinproject#4488]
### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] The title of this issue follows the `Bug: brief description of bug` format, e.g. `Bug: Lesson complete button does not update on click`
- [ ] Would you like to work on this issue?

### Bug description

Collapsibles are handled in our lesson md files via

```md
<details markdown="block">

<summary class="dropDown-header">TITLE</summary>

CONTENTS OF COLLAPSIBLE BLOCK

</details>
```

While these render completely fine on the main website, the same markdown does not render as a collapsible in the [markdown preview tool](https://www.theodinproject.com/lessons/preview). The result does not render a `<details>` parent, and the `<summary class="dropDown-header">TITLE</summary>` is rendered as a plain text node `" TITLE "` instead.

An example can be found with the Foundations "Setting up Git" lesson.

### How to reproduce

1. Go to the ["Setting up Git" lesson md file in the curriculum repo](https://github.com/TheOdinProject/curriculum/blob/main/foundations/installations/setting_up_git.md?plain=1) and copy the raw markdown.
1. Go to the [markdown preview tool](https://www.theodinproject.com/lessons/preview), paste in the markdown and preview it.
1. Observe how under `Step 1: Install Git`, `Linux` is a plain text node and its contents laid out in full, as opposed to being a collapsible `<details>` element. The same applies to the following `MacOS` and `ChromeOS` sections.
1. Compare this to the page in production at [Setting up Git](https://www.theodinproject.com/lessons/foundations-setting-up-git).

![image](https://github.com/TheOdinProject/theodinproject/assets/122839503/6f5bcc46-a46a-4e8e-a678-b39bc144b29f)

### Expected behavior

1. Go to the ["Setting up Git" lesson md file in the curriculum repo](https://github.com/TheOdinProject/curriculum/blob/main/foundations/installations/setting_up_git.md?plain=1) and copy the raw markdown.
1. Go to the [markdown preview tool](https://www.theodinproject.com/lessons/preview), paste in the markdown and preview it.
1. `Linux` underneath `Step 1: Install Git` should be rendered as a `<summary>` within a collapsed `<details>` element that can be toggled open/closed. The same should apply for the following `MacOS` and `ChromeOS` sections.

![image](https://github.com/TheOdinProject/theodinproject/assets/122839503/dd18bf37-054d-4e98-aa94-94a66a276326)

### What browsers are you seeing the problem on?

Firefox, Chrome

**Comment by CouchofTomato** [comment]
@KevinMulhern can you take a look at this please mate

**Comment by KevinMulhern** [comment]
Thanks for letting us know @MaoShizhong. This looks to be related to https://github.com/TheOdinProject/theodinproject/pull/4479. I'll get a fix put together.
