### ISSUE TITLE
Redesign: Mobile view Courses (Home page)

### ISSUE THREAD

**Issue by adachiu** [TheOdinProject/theodinproject#449]
This task involves creating mobile media queries (320px width) for the `Courses` section on the home page.

Comment your email to get access to the Zeplin file for full design details https://zpl.io/14dBXX
**Please refer to the Zeplin file's details for _spacing, sizing and typography_!!!!** 😄 

This is the 📱  mobile view you'll be creating:

<img width="160" alt="screen shot 2017-04-28 at 12 35 48 am" src="https://cloud.githubusercontent.com/assets/13413986/25518961/c3c4310a-2baa-11e7-8073-249a055c64e6.png">

This is the 💻 laptop view just for reference to see (this will be another issue)

<img width="719" alt="screen shot 2017-04-28 at 12 43 06 am" src="https://cloud.githubusercontent.com/assets/13413986/25519212/c24f7ca2-2bab-11e7-945d-4c28e6816b4b.png">

### Working on this task

- [ ] If you want to work on this task, please claim it by commenting below   
- [ ] Branch off the redesign branch                                                                 
- [ ] When you are submitting your pull request for this task please ensure the base branch you want to merge into is the redesign branch

**Comment by arun1595** [comment]
I am on it.

**Comment by codyloyd** [comment]
nice work @arun1595: closing issue.
