### ISSUE TITLE
Suggestion: Change links to 'unvisited' once a lesson has been unmarked as complete 

### ISSUE THREAD

**Issue by Looch8** [TheOdinProject/theodinproject#4493]
### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] The title of this issue follows the `Feature Request: brief description of feature request` format, e.g. `Feature Request: Add a dark mode to the website`
- [ ] Would you like to work on this issue?

### Description of the Feature Request

**Problem:**
Currently, when a user revisits a lesson that was previously completed, the visited links within the lesson remain marked as visited. This can lead to confusion for users who wish to revisit all links within the lesson.

**Proposed Solution:**
Implement a feature that resets the visited status of links within a lesson when the lesson is marked as 'incomplete' again. 

<img width="766" alt="Screenshot 2024-04-10 at 12 44 29 pm" src="https://github.com/TheOdinProject/theodinproject/assets/101569600/979f3033-e3e2-4c20-a524-a84dcedd78ce">

<img width="750" alt="Screenshot 2024-04-10 at 12 44 38 pm" src="https://github.com/TheOdinProject/theodinproject/assets/101569600/c2186b38-2fe0-47de-80b3-3d52730de5d9">

### Acceptance criteria

Reset Visited Status: Upon changing the status of a lesson from 'complete' to 'incomplete', trigger a process that resets the visited status of all links within that lesson to 'unvisited'.

**Comment by fabulousgk** [comment]
I am with @Asartea . The visited status of links is a browser function.  In fact it is not even a website by website property.  If you go to another website that has the same link on it, it will also show as visited.
