### ISSUE TITLE
Bug: EJS syntax highlighting not supported

### ISSUE THREAD

**Issue by MaoShizhong** [TheOdinProject/theodinproject#4497]
### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] The title of this issue follows the `Bug: brief description of bug` format, e.g. `Bug: Lesson complete button does not update on click`
- [ ] Would you like to work on this issue?

### Bug description

At least going by the markdown preview tool, `ejs` as a fenced code block language does not produce any syntax highlighting at all, unlike other languages including `erb`.

### How to reproduce

1. Go to the [markdown preview tool].
2. Enter the following code:
   ````markdown
   ```ejs
    <nav>
      <ul>
        <% for (let i = 0; i < links.length; i++) { %>
          <li>
            <a href="<%= links[i].href %>">
              <span> <%= links[i].text %> </span>
            </a>
          </li>
        <% } %>
      </ul>
    </nav>
    ```
    ````
4. Preview it - observe how there is no syntax highlighting at all. No difference if the language is `eta` (Prism's alternative language code for EJS).
5. Change the code block language to `html` or `erb` - see how there is syntax highlighting (albeit not complete due to being the incorrect language).

### Expected behavior

The above, except with the code block appropriately coloured as per ejs ([Prism should support EJS highlighting](https://prismjs.com/#supported-languages)).

### What browsers are you seeing the problem on?

Firefox, Chrome

### What OS are you using?

Ubuntu

**Comment by JoshDevHub** [comment]
Yep that's definitely a problem, but should be an easy fix. I'll knock it  out real quick.
