### ISSUE TITLE
Redesign: Courses section on Home page

### ISSUE THREAD

**Issue by adachiu** [TheOdinProject/theodinproject#450]
This task involves updating the `Courses` section on the home page (1440px width).

Comment your email to get access to the Zeplin file for full design details https://zpl.io/14j8Nn
**Please refer to the Zeplin file's design details for _assets, spacing, sizing and typography_!!!!** 👍  

<img width="719" alt="screen shot 2017-04-28 at 12 43 06 am" src="https://cloud.githubusercontent.com/assets/13413986/25519517/fdc45fe0-2bac-11e7-83dc-f9a960a2494d.png">

### Working on this task

- [ ] If you want to work on this task, please claim it by commenting below   
- [ ] Branch off the redesign branch                                                                 
- [ ] When you are submitting your pull request for this task please ensure the base branch you want to merge into is the redesign branch

**Comment by arun1595** [comment]
I am working on this.

**Comment by codyloyd** [comment]
@arun1595 you might as well claim #449 as well and do it all at once.
