### ISSUE TITLE
Chore: Additional Prism language support

### ISSUE THREAD

**Issue by MaoShizhong** [TheOdinProject/theodinproject#4501]
### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] The title of this issue follows the `Chore: brief description of chore` format, e.g. `Chore: Lesson complete button does not update on click`
- [X] Would you like to work on this issue?

### Chore description

#4498 added EJS to our Prism support languages, as we were previously missing it.
I was thinking about any other languages we would reasonably see in code blocks in our curriculum that have Prism support but aren't added to our supported languages list.

At least in Node land, it would be reasonable for us to see `.env` file snippets when we revamp the relevant lessons. This would require the `properties` language to appropriately highlight. The below snippet can be pasted into the [Prism test drive playground](https://prismjs.com/test.html#language=properties) using the `properties` language.

```text
foo=bar
blip=blop
```

Additional languages that may be reasonable for us to add to the PrismJS languages array:
- JSON
- YAML
- Bash

### Acceptance criteria

- [ ] Add any combination of the above languages to the PrismJS languages array in `.babelrc`

**Comment by JoshDevHub** [comment]
I agree on all fronts. I'm particularly surprised `bash` isn't currently highlighted, which is something I've somehow not noticed before your post :laughing: . There are snippets with the `bash` language set all over the curriculum.

**Comment by KevinMulhern** [comment]
those all sound like solid additions to me too @MaoShizhong. I thought we definitely had bash as well 😆
