### ISSUE TITLE
Add Feature Flag

### ISSUE THREAD

**Issue by bycdiaz** [TheOdinProject/theodinproject#4524]
- [ ] Add feature flag
- [ ] Add placeholder content (content we're hiding)
- [ ] Add test confirming users with flag can observe hidden content
- [ ] Add test confirming users without flag cannot observe hidden content.

## Acceptance Criteria

1. Enable flag for your current user
2. Navigate to x
3. Observe hidden content

**Comment by JustWaveThings** [comment]
From meeting on 5/11:	

- Set up user feature flag check as one first backend tasks and frontend tasks
		- Feature flag conditional:
https://github.com/TheOdinProject/theodinproject/blob/a04874d606f4bae3dddf03b684c14855c66972e8/app/views/static_pages/home.html.erb#L24
