### ISSUE TITLE
Backend: Get wordlist for predefined options

### ISSUE THREAD

**Issue by JustWaveThings** [TheOdinProject/theodinproject#4528]
**Not for the simple version**

I brought up that Mclilzee when making a TOP search engine made a word graph to count how many times each word showed up in the curriculum and thought that might be a starting point on where we can pull TOP mentioned concepts from.

Additionally, @BryanF1nes suggested going through and grabbing the big concepts in the curriculum, in both paths.

**Comment by KevinMulhern** [comment]
Hey @JustWaveThings, just closing this and the other related issues to try to keep the issue list actionable.
