### ISSUE TITLE
Redesign: Update the Odin logo on every page

### ISSUE THREAD

**Issue by adachiu** [TheOdinProject/theodinproject#454]
This task is to update the Odin logo on every page of the site.

Comment your email to get access to the Zeplin file to get the Odin logo asset https://zpl.io/14j8Nn

The logo with the ✨  **golden helmet** ✨  is the updated one to use.
<img width="975" alt="screen shot 2017-04-28 at 1 31 08 am" src="https://cloud.githubusercontent.com/assets/13413986/25520860/630e106c-2bb2-11e7-97f7-287720cefb09.png">

### Working on this task

- [ ] If you want to work on this task, please claim it by commenting below   
- [ ] Branch off the redesign branch                                                                 
- [ ] When you are submitting your pull request for this task please ensure the base branch you want to merge into is the redesign branch

**Comment by codyloyd** [comment]
💥
