### ISSUE TITLE
Redesign: Mobile view Navigation Bar

### ISSUE THREAD

**Issue by adachiu** [TheOdinProject/theodinproject#455]
This task involves creating the mobile media queries (320px width) for the navigation bar. The navbar will stick to the top of the viewport.

Comment your email to get access to the Zeplin file for full design details https://zpl.io/14dBXX
Please refer to the Zeplin file's details for spacing, sizing and typography!!!! 🔍

This is the 📱 mobile view you'll be creating for the nav bar:

<img width="320" alt="screen shot 2017-04-28 at 1 15 52 am" src="https://cloud.githubusercontent.com/assets/13413986/25521077/286693d4-2bb3-11e7-9cee-680a3c7d38cb.png">

Keep in mind that the nav bar has a background that is blurred, so it would look like this when the page scrolls up. Check Zeplin for all the details for the values.

<img width="321" alt="screen shot 2017-04-28 at 1 49 28 am" src="https://cloud.githubusercontent.com/assets/13413986/25521562/f792f61a-2bb4-11e7-876b-b367fe27a4cc.png">

The nav bar drop down menu is in another issue #456 

### Working on this task

- [ ] If you want to work on this task, please claim it by commenting below   
- [ ] Branch off the redesign branch                                                                 
- [ ] When you are submitting your pull request for this task please ensure the base branch you want to merge into is the redesign branch

**Comment by codyloyd** [comment]
@adachiu backdrop filter doesn't work in most browsers :(

http://caniuse.com/#feat=css-backdrop-filter

A couple of options are use a box shadow to make it 'fade' like so:
![2_013](https://cloud.githubusercontent.com/assets/18574792/25537185/234b9f02-2c03-11e7-8ac8-2fb4a18a2b09.png)

OR: keep it solid and add a shadow to make it 'layered' above the page not unlike material design (haven't implemented that yet)

**Comment by adachiu** [comment]
Try this:
https://jordanhollinger.com/2014/01/29/css-gaussian-blur-behind-a-translucent-box/

Last alternative:
Solid with shadow. This change will affect the other issue that's about the
drop down menu too.

**Comment by codyloyd** [comment]
ah.. the trick in that link only works for static backgrounds :(

I'm gonna do a little more research, but fall back to solid with shadow if I don't find anything.

**Comment by codyloyd** [comment]
done!
