### ISSUE TITLE
Media Queries: <Short description of your suggestion>

### ISSUE THREAD

**Issue by ezDecode** [TheOdinProject/theodinproject#4550]
Heading are not adjusted properly!![IMG_20240530_082256.jpg](https://github.com/TheOdinProject/curriculum/assets/164205358/a9fe14bc-a0a7-40bf-b3cc-67513f42fa7f)

**Comment by JoshDevHub** [comment]
I'm transferring this to the main site repo, as this is about how the site is styled rather than about the curriculum content itself.

Some followup questions I have for you @ezDecode 
1. What device are you using?
2. What browser are you using to view the site?

**Comment by ezDecode** [comment]
Device - Mobile 
Browser - G. Chrome

**Comment by JoshDevHub** [comment]
@ezDecode

What mobile device are you using specifically? The headings render fine for me using the latest Google Chrome on an iPhone 11.

**Comment by ezDecode** [comment]
I'm using OnePlus Nord 2 phone specifically!

**Comment by KevinMulhern** [comment]
sdfsd
