### ISSUE TITLE
Redesign: Mobile view navigation bar drop down menu

### ISSUE THREAD

**Issue by adachiu** [TheOdinProject/theodinproject#456]
This task involves creating the drop down menu for the mobile view navigation bar. A separate issue will be created for the laptop 1440px media query view for this.

Comment your email to get access to the Zeplin file for full design details https://zpl.io/Z1WxUH5
Please refer to the Zeplin file's details for spacing, sizing and typography!!!! 🔍

1. Drop down menu fills the entire viewport

<img width="479" alt="screen shot 2017-04-28 at 2 00 24 am" src="https://cloud.githubusercontent.com/assets/13413986/25522032/79cad1ce-2bb6-11e7-8003-da63a0d6a8e2.png">

2. Background is blurred, so it would look something like this if the the drop down menu is on top of something (Check Zeplin for blur values please):

<img width="319" alt="screen shot 2017-04-28 at 1 54 45 am" src="https://cloud.githubusercontent.com/assets/13413986/25521863/09869f74-2bb6-11e7-9633-54cd976871e7.png">

### Working on this task

- [ ] If you want to work on this task, please claim it by commenting below   
- [ ] Branch off the redesign branch                                                                 
- [ ] When you are submitting your pull request for this task please ensure the base branch you want to merge into is the redesign branch

**Comment by codyloyd** [comment]
working on this
