### ISSUE TITLE
Wrong URL

### ISSUE THREAD

**Issue by erencataltepe** [TheOdinProject/theodinproject#457]
Hi,

I think the url of last additional resource "About.com Agile Development Entry" is wrong.
Section: Web 101 > How Are Websites Actually Built in the Real World?

**Comment by codyloyd** [comment]
this issue is more appropriate for the curriculum repo https://github.com/TheOdinProject/curriculum/issues

Can you give the broken link, and are you able to find the correct one?

**Comment by erencataltepe** [comment]
I'll, thanks for info
