### ISSUE TITLE
Bug: Password recovery e-mails flagged as phishing by Gmail breaking hyperlinks

### ISSUE THREAD

**Issue by scheals** [TheOdinProject/theodinproject#4573]
### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] The title of this issue follows the `Bug: brief description of bug` format, e.g. `Bug: Lesson complete button does not update on click`
- [ ] Would you like to work on this issue?

### Bug description

Seems that the e-mail provider has been flagged for spam/phishing OR there have been indeed similar e-mails being sent as phishing. The red bit is exactly that - that the e-mails like these were used for identity theft and not to click any links, download any attachments or provide any information. Clicking the button tells Gmail that it is a safe e-mail and allows for the hyperlinks to appear (see top e-mail).

![image](https://github.com/TheOdinProject/theodinproject/assets/95084627/73e399cd-4ede-4201-a76d-22c43ca4b4c1)

Now, I do not know whether this is only Gmail's issue but from the very, very basic understanding of how these kinds of e-mail filters/blocklists work, that being is that they're shared, I imagine all the big players would be affected.

### How to reproduce

1. Go to [sign in page](https://www.theodinproject.com/users/sign_in).
2. Click [Forgot your password?](https://www.theodinproject.com/users/password_reset/new).
3. Provide your e-mail and click the button to send the e-mail.
4. Receive e-mail that was automatically flagged and thus hyperlinks were removed.

### Expected behavior

1. Go to [sign in page](https://www.theodinproject.com/users/sign_in).
2. Click [Forgot your password?](https://www.theodinproject.com/users/password_reset/new).
3. Provide your e-mail and click the button to send the e-mail.
4. Receive e-mail without any security concerns and thus a working hyperlink.

### What browsers are you seeing the problem on?

Firefox

### What OS are you using?

Windows

**Comment by KevinMulhern** [comment]
Thanks for the report @scheals!

It looks like it might be intermittent, I'm not getting alerts on those emails. But I think theres few things we can set up on our email provider to reduce this kind of thing. Leave this one with me!

**Comment by KevinMulhern** [comment]
We recently switched to a new email provider, with proper SPF and DMARC settings. This should hopefully be resolved now, but please reopen if it pops up again
