### ISSUE TITLE
Display active announcement count on admin v2 dashboard

### ISSUE THREAD

**Issue by KevinMulhern** [TheOdinProject/theodinproject#4619]
When I am visiting admin v2, I want to see the number of active announcements from my dashboard, so I can get an overview of how many announcements are running without needing to go to the announcements page.

### Acceptance criteria
1. Sign into admin v2 - admin@odin.com, password123
2. The dashboard should display a card with "Active announcements 0"
3. Click the card
4. You should be on the announcements page
5. Create a new announcement
6. Visit the dashboard again
7. The dashboard should display a card with "Active announcements 1"

Note:
We already have a card on the dashboard for unresolved flags which can be copied, pasted and tweaked for this.

**Comment by MikhailWahib** [comment]
Hi @KevinMulhern, is this issue open for contribution?

**Comment by KevinMulhern** [comment]
Hey @MikhailWahib, @ZachBaird is on this one. But keep an eye on the issue list, we might be adding more over the next couple of weeks.
