### ISSUE TITLE
Bug: Databases section appears twice on the homepage

### ISSUE THREAD

**Issue by mathdebate09** [TheOdinProject/theodinproject#4624]
### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] The title of this issue follows the `Bug: brief description of bug` format, e.g. `Bug: Lesson complete button does not update on click`
- [X] Would you like to work on this issue?

### Bug description

On the homepage, two databases resources appear, which seem to have same content, though one of them has tags of `new`, I'm not sure if it's really a bug or just to specify the newer course whilst keeping the older one.

### How to reproduce

1. Open the [theodinproject website](https://www.theodinproject.com/)
2. Scroll down to find 'databases'
3. Two of the databases sections appear (one has new tags, another has none)

### Expected behavior

1. Open the [theodinproject website](https://www.theodinproject.com/)
2. Scroll down to find 'databases'
3. Only one database section appears (it has tags `new`?)

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### What OS are you using?

Ubuntu

### Discord Name

mathdebate09

### Additional Comments

This would be my first time contributing on this repo so I'd appreciate all help i can get for my main work domain is nodejs whereas website is in ruby.

*Edit: Add additional comments*

**Comment by KevinMulhern** [comment]
Thanks for reporting @mathdebate09. This should be a simple and quick one to fix. We just need [this line](https://github.com/TheOdinProject/theodinproject/blob/main/db/fixtures/paths/full_stack_javascript/courses/databases.rb#L8) removed. I've assigned it to you. Let us know if you need anything!
