### ISSUE TITLE
Project: SQL Zoo: No need for community solutions

### ISSUE THREAD

**Issue by dilpreetsinghaulakh** [TheOdinProject/theodinproject#4630]
### Checks

- [X] This is not a duplicate of an existing issue (please have a look through our [open issues list](https://github.com/TheOdinProject/curriculum/issues) to make sure)
- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] Would you like to work on this issue?

### Describe your suggestion

SQL Zoo is solved in the browser so there is no need for community solutions as there is no obvious way to share the solution.

Also, ["feedback form for the SQL course"](https://docs.google.com/forms/d/e/1FAIpQLSenvMG6WFbOOEap_biQOwqfbH-j-xsf5Eyv4ir2Rx5FsYSecQ/viewform?usp=sf_link) leads to _(says)_ ruby on rails form even in NodeJS path.

### Path

Node / JS

### Lesson Url

https://www.theodinproject.com/lessons/node-path-databases-sql-zoo

### (Optional) Additional Comments

Just small discrepancies!

**Comment by dilpreetsinghaulakh** [comment]
I think it can actually stay as I have just seen a submission in which the submitter put the solutions for SQL Zoo in a repository. Although I still don't think it is the best implementation here.

**Comment by MaoShizhong** [comment]
I feel like user submissions isn't really that relevant here given the SQLZoo exercises are marked right or wrong when you do them. So I'm in favour of just removing the submissions component for that lesson.

**Comment by Asartea** [comment]
Agree with Mao that there is no real point to storing these, since there is already build in checking
