### ISSUE TITLE
Bug: h1 lesson name heading is not centered

### ISSUE THREAD

**Issue by mahmoudmerghani** [TheOdinProject/theodinproject#4654]
### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] The title of this issue follows the `Bug: brief description of bug` format, e.g. `Bug: Lesson complete button does not update on click`
- [X] Would you like to work on this issue?

### Bug description

h1 lesson name heading is not centered on widths between 640px to 1280px

### How to reproduce

1. visit a lesson page

### Expected behavior

the heading centered

### What browsers are you seeing the problem on?

Microsoft Edge

### What OS are you using?

Windows

### Discord Name

mahmoudmerghani3027

**Comment by KevinMulhern** [comment]
Thanks for reporting @mahmoudmerghani, can you post a screenshot of what you're seeing on the lesson page please? It looks centered to me.

**Comment by mahmoudmerghani** [comment]
![Screenshot 2024-07-27 171842](https://github.com/user-attachments/assets/c47f8205-b112-4a23-b48a-a7c07bf30b85)

**Comment by KevinMulhern** [comment]
Thanks @mahmoudmerghani, looks like there is an issue with shorter lesson titles. Do you still want to work on this one?

**Comment by KevinMulhern** [comment]
No worries. Just for the future, if you don't want to work on a issue you're creating, please leave this box unticked:

<img width="367" alt="Screenshot 2024-08-02 at 17 05 32" src="https://github.com/user-attachments/assets/8ed0760a-2835-4f33-a09e-ba3de0db8547">

**Comment by MaoShizhong** [comment]
Looks like `app/views/lessons/_header.html.erb` line 6 just needs `sm:flex-row` changed to `xl:flex-row`. Just the wrong breakpoint for that property.

**Comment by ItsTosh** [comment]
Hey 👋 I would like to work on this if possible.

**Comment by MahmoodHashem** [comment]
Is it possible for me to solve this and make a contribution? It would be fantastic because it would mark my first contribution on GitHub.
