### ISSUE TITLE
Redesign: Global H1 consistency 

### ISSUE THREAD

**Issue by adachiu** [TheOdinProject/theodinproject#467]
This task is to make the global H1 (36px into REMS) titles for each page.

### Working on this task

- [ ] If you want to work on this task, please claim it by commenting below   
- [ ] Branch off the redesign branch                                                                 
- [ ] When you are submitting your pull request for this task please ensure the base branch you want to merge into is the redesign branch

**Comment by codyloyd** [comment]
merged... closing issue
