### ISSUE TITLE
Home page copy update

### ISSUE THREAD

**Issue by adachiu** [TheOdinProject/theodinproject#468]
This task involves updating the copy “Stop wasting time...  Here's what you need to know.” in the homepage.
The current copy is too vague and we'll need to be a bit more specific about what The Odin Project is.

We could emphasize:
- Open Source
- Curriculum for Front-End, Back-End, and Full-Stack
- Job-ready portfolio

Tagging @KevinMulhern to continue discussion.

### Working on this task

- [ ] If you want to work on this task, please claim it by commenting below   
- [ ] Branch off the redesign branch                                                                 
- [ ] When you are submitting your pull request for this task please ensure the base branch you want to merge into is the redesign branch

**Comment by KevinMulhern** [comment]
If anyone has any ideas for this please post them in here 😄

**Comment by codyloyd** [comment]
"I am ODIN you can trust me."

https://www.lingscars.com/

**Comment by KevinMulhern** [comment]
😂 perfect 🚗
