### ISSUE TITLE
Redesign: Navbar logo size and spacing media queries

### ISSUE THREAD

**Issue by adachiu** [TheOdinProject/theodinproject#469]
This task involves updating the media queries for the navbar.

1. Logo size 67 x 87 px at media query 1024px width screen and up
2. `.logo-text` needs to be aligned horizontally with the logo and menu bar in all media query views. It's currently slightly off.
3. Media query `.navbar` padding:
- 320 px width screen: `padding: 0 20px;`
- 768 px width screen: `padding: 0 33px;` (The menu icon needs to have the same padding to match. Or is it possible to put the menu button inside the `.navbar` ?)
- 1024 px width screen: `padding: 0 42px;`
- 1440 px width screen: `padding: 0 168px;`
4. Logo and logo text should be side by side for screens width of 320px to 768px (to look the same like it is on screen widths 1024px and up) Add a bit of space between logo and logo text `.logo-text` `padding-left: 20px;`

### Working on this task

- [ ] If you want to work on this task, please claim it by commenting below   
- [ ] Branch off the redesign branch                                                                 
- [ ] When you are submitting your pull request for this task please ensure the base branch you want to merge into is the redesign branch

**Comment by codyloyd** [comment]
on it

**Comment by codyloyd** [comment]
@adachiu The alignment of the logo text looks ok to me... which makes me wonder if there's some browser compatibility issue going on here (maybe it looks good on my machine, but nowhere else lol).  If that's not the case then we just have different opinions on the correct alignment, and I'm more than happy to adjust it however you like. 

Can you screenshot the error and let me know if you want the text to be adjusted up or down.

**Comment by codyloyd** [comment]
nevermind... I saw it.  I was looking at the wrong thing.  Should be fixed in the latest PR

**Comment by adachiu** [comment]
@codyloyd 
Just make sure the top and bottom spacing are even 😄 
To illustrate what I mean:
<img width="651" alt="screen shot 2017-04-30 at 2 55 59 pm" src="https://cloud.githubusercontent.com/assets/13413986/25568346/8e4e45bc-2db5-11e7-96b2-c26be03bc187.png">

**Comment by codyloyd** [comment]
fixes were merged.  Closing the issue
