### ISSUE TITLE
Remove admin column from users

### ISSUE THREAD

**Issue by KevinMulhern** [TheOdinProject/theodinproject#4712]
### Because:
- It is no longer needed

### Acceptance criteria:
- Drop the admin column from users
- It will also need to be removed from the users factory

### Notes:
- It'll need to be dropped using a data migration - basic Rails knowledge is needed.

**Comment by davidumoru** [comment]
Hey @KevinMulhern , I'd like to work on this :)

**Comment by KevinMulhern** [comment]
Thanks @davidumoru, it's all yours!

**Comment by KevinMulhern** [comment]
Hey @davidumoru, how are you getting on? do you need any help with this?

**Comment by davidumoru** [comment]
> Hey @davidumoru, how are you getting on? do you need any help with this?

Hey! Sorry for the delay. I'm working on it now and will push my changes soon!
