### ISSUE TITLE
Bug: The more options button on the upper right corner is not working.

### ISSUE THREAD

**Issue by epic-quester** [TheOdinProject/theodinproject#4716]
### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] The title of this issue follows the `Bug: brief description of bug` format, e.g. `Bug: Lesson complete button does not update on click`
- [ ] Would you like to work on this issue?

### Bug description

When clicking the more options button it’s is supposed to give me a list of options, but now nothing happens, the device i’m using is an iphone and the browser is safari, i tried tge same thing on opera gx but i still have the same issue.
![1E113D4F-D844-49D0-9F8D-990A6B8FA950](https://github.com/user-attachments/assets/526bb9be-bc8f-45fd-845d-1fb7c91ebf5a)

### How to reproduce

1. Click the more options button at the upper right corner(the 3 lines buttons).

### Expected behavior

1.click the button
2.more options appear

### What browsers are you seeing the problem on?

Safari

### What OS are you using?

iOS

### Discord Name

epic_quester

**Comment by epic-quester** [comment]
> Thanks for the report @epic-quester. What version of iOS are you running?
> 
> This is working ok for me, can anybody else recreate?



> Thanks for the report @epic-quester. What version of iOS are you running?
> 
> This is working ok for me, can anybody else recreate?
I have iOS 16.3.1.

> Thanks for the report @epic-quester. What version of iOS are you running?
> 
> This is working ok for me, can anybody else recreate?

I have iOS 16.3.1

**Comment by epic-quester** [comment]
> Thanks for the report @epic-quester. What version of iOS are you running?
> 
> This is working ok for me, can anybody else recreate?

I have iOS 16.3.1.

**Comment by epic-quester** [comment]
I tried multiple browsers, and all of them have the same issue.

**Comment by KevinMulhern** [comment]
Yeah that makes sense. As far as I'm aware, all browsers on iOS use the same underlying Webkit browser engine (Safari). They just have different skins.

The only way I've been able to recreate this is by disabling JS in safari, but I doubt its that. Still worth checking. Can you go to settings > safari > advanced, and make sure Javascript is enabled please?

**Comment by epic-quester** [comment]
> Yeah that makes sense. As far as I'm aware, all browsers on iOS use the same underlying Webkit browser engine (Safari). They just have different skins.
> 
> The only way I've been able to recreate this is by disabling JS in safari, but I doubt its that. Still worth checking. Can you go to settings > safari > advanced, and make sure Javascript is enabled please?

It was enabled, someone on discord has the sane problem on his iphone

**Comment by epic-quester** [comment]
> Yeah that makes sense. As far as I'm aware, all browsers on iOS use the same underlying Webkit browser engine (Safari). They just have different skins.
> 
> The only way I've been able to recreate this is by disabling JS in safari, but I doubt its that. Still worth checking. Can you go to settings > safari > advanced, and make sure Javascript is enabled please?

It was enabled, someone on discord has the sane problem on his iphone.
![Uploading 83C04DD6-A61E-4D78-A034-5387B6511C7F.jpeg…]()

**Comment by KevinMulhern** [comment]
When you get a moment, can you try it again to see if its still broken please @epic-quester?

There was one exception in our error tracker that looked somewhat related to this, we pushed out a fix for that earlier.

**Comment by epic-quester** [comment]
> When you get a moment, can you try it again to see if its still broken please @epic-quester?
> 
> There was one exception in our error tracker that looked somewhat related to this, we pushed out a fix for that earlier.

The problem still exists, i tried using Google(the app) but the button still doesn’t work.

**Comment by KevinMulhern** [comment]
Ah well, it was along shot. I can't do much more myself without being able to reliably recreate it. Hopefully someone else has an idea about whats going on.

**Comment by MaoShizhong** [comment]
@epic-quester just in case, what version of Safari on iPhone did you use which exhibited the broken behaviour?

**Comment by epic-quester** [comment]
> @epic-quester just in case, what version of Safari on iPhone did you use which exhibited the broken behaviour?

I have iOS 16.3.1

**Comment by MaoShizhong** [comment]
Oh wait, I forgot this is iOS so Safari's version is tied to it :facepalm:

**Comment by KevinMulhern** [comment]
I found an old iPhone and recreated it, its for sure the iOS version. We might have bumped something recently that caused it. I'll try reverting and testing.

**Comment by KevinMulhern** [comment]
Hey @epic-quester, can you confirm if this is still happening for you please? I _think_ we've got got to the bottom of it.

**Comment by epic-quester** [comment]
Hey @KevinMulhern , it's working now, but there are rare instances where it stops working and i have to refresh the tab to make it work, but it's 100 times better.

**Comment by KevinMulhern** [comment]
Great stuff, thanks for getting back to me @epic-quester!

I've run into that too and think it might a separate issue with the transition lib we use. We'll look into it 👀

**Comment by epic-quester** [comment]
> Great stuff, thanks for getting back to me @epic-quester!
> 
> 
> 
> I've run into that too and think it might be a separate issue with the transition lib we use. We'll look into it 👀  

Happy to help!
