### ISSUE TITLE
Redesign: How It Works section (Home page)

### ISSUE THREAD

**Issue by adachiu** [TheOdinProject/theodinproject#472]
Update the How It Works section on the home page.

1. Change `.how-it-works-title` `margin-bottom` to  70px
2. `.how-it-works` have `padding-top: 100px;` for screen widths 1024px and up
3. Reword the text under "How It Works" title so that the paragraph's last line doesn't have only 2 words. It looks very unbalanced right now.
4.  Remove `min-height` from `.how-it-works-tiles`
5. The sub titles “Learn” “Build” “Connect” needs `margin-top` 50px and` margin-bottom` 20px (Should probably add a class to the h3)
6. Mobile view of “How It Works” images to have `height` of 80px instead of 48px
7. At screen width 768 px, the `.tile` is too wide. Add media queries to make sure the `.tiles` width are balanced.

### Working on this task

- [ ] If you want to work on this task, please claim it by commenting below   
- [ ] Branch off the redesign branch                                                                 
- [ ] When you are submitting your pull request for this task please ensure the base branch you want to merge into is the redesign branch

**Comment by KevinMulhern** [comment]
👍 LGTM
