### ISSUE TITLE
Redesign: Favicon

### ISSUE THREAD

**Issue by adachiu** [TheOdinProject/theodinproject#473]
This task is to update the favicon (use the social avatar png).

### Working on this task

- [ ] If you want to work on this task, please claim it by commenting below   
- [ ] Branch off the redesign branch                                                                 
- [ ] When you are submitting your pull request for this task please ensure the base branch you want to merge into is the redesign branch

**Comment by Toughee** [comment]
Hello. I can help with this issue.  Would you like the image to look like this? 


![transparent](https://cloud.githubusercontent.com/assets/21093554/25566423/347bf43a-2d8d-11e7-9504-c7cd9953e8df.png)

**Comment by KevinMulhern** [comment]
thats the old logo @Toughee, this is the new one. it may need resized for the favicon format
![image](https://cloud.githubusercontent.com/assets/7963776/25566563/29ac1df0-2dd3-11e7-92aa-7493e6bbe752.png)

**Comment by adachiu** [comment]
@Toughee Here you go! I used https://realfavicongenerator.net to create this:
[favicons.zip](https://github.com/TheOdinProject/theodinproject/files/966893/favicons.zip)

Instructions:
<img width="1147" alt="screen shot 2017-04-30 at 11 24 45 am" src="https://cloud.githubusercontent.com/assets/13413986/25566900/bed43d5e-2d97-11e7-8bd6-7ec785946fa1.png">


```
<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
<link rel="manifest" href="/manifest.json">
<link rel="mask-icon" href="/safari-pinned-tab.svg" color="#5bbad5">
<meta name="theme-color" content="#ffffff">
```

**Comment by codyloyd** [comment]
@Toughee hows it going on this?

**Comment by Toughee** [comment]
It's done. I had to remove the transparancy for the image. I also added more favicons for iOS. 

They're all in the public folder. Was thinking about putting them all in one folder, but I wasn't sure if you wanted that  (Image sourcing issues could have happened).

**Comment by KevinMulhern** [comment]
Thank for the very extremely thorough job @Toughee 😄 
Your contribution to this project is very much appreciated.
