### ISSUE TITLE
Redesign: Success Stories section (Home page)

### ISSUE THREAD

**Issue by adachiu** [TheOdinProject/theodinproject#474]
Tasks for the Success Stories section on the home page include the following:

`.success-stories-title` padding-top to 70px

Mobile view of  “Success Stories”
- Move avatar to above the name
 - Center alignment for avatar, name and text.
- Bold the name
- Limit mobile view stories to show only 2 stories.

### Working on this task

- [ ] If you want to work on this task, please claim it by commenting below   
- [ ] Branch off the redesign branch                                                                 
- [ ] When you are submitting your pull request for this task please ensure the base branch you want to merge into is the redesign branch

**Comment by codyloyd** [comment]
except for padding the title this is a duplicate issue (#448).. I'll close this one as I have already fixed teh title
