### ISSUE TITLE
Typography classes

### ISSUE THREAD

**Issue by adachiu** [TheOdinProject/theodinproject#475]
Investigate using classes for typography based on https://zpl.io/ZQIHmt

Use media queries for mobile typography. (Not too many need media queries. Mostly just H1 and H2) @KevinMulhern

**Comment by codyloyd** [comment]
this is a good idea... I've been considering doing it, but was too lazy.  Should be easy enough.  Kev: when you get it done we should put up new issues to convert existing pages to those classes.

**Comment by KevinMulhern** [comment]
@codyloyd since you seem to be looking for issues to close 😛 do you want to take this one? I haven't started it yet and I'm sure you'll do a better job than me with it 😄.

**Comment by codyloyd** [comment]
lol I'll look at it tomorrow

**Comment by codyloyd** [comment]
I propose that if we convert the rest of the pages to using the typography classes we should get rid of the 'global' styling for headings... just make them all default to the normal 'body' styling (16px normal weight etc.)  Then whoever is styling can use whatever text element is semantically appropriate in the context (i.e. h1 for big titles, h2 for subheaders etc.)

**Comment by KevinMulhern** [comment]
My concern is if we need specific classes for the heading styles, people working on the site will need to know about them. I think that might lead to some confusion with new people working on the site. 

I think a part of the problem with inconsistencies with the headings on the site was all the different people working on different pages and implementing their own styles.

 We could maybe do a clean up to make global styles for the headings and have classes for the few instances where the headings are different? that would make things much easier to maintain imo and take away the need to know about the typography classes.

I could be wrong about all of this though, what do you think?

**Comment by codyloyd** [comment]
Well... That was something else I had considered... But people would still have to know which heading tag to use, and would still end up doing their own styles.  I was thinking that my proposal would be easier to keep track of and look up (because they're all in the "typography" file) but I could be all wrong. Maybe we just need some clear documentation for whatever we choose.

**Comment by adachiu** [comment]
I think Cody has a good point about keeping classes in typography file. If
we ever needed to change something, we could go into typography to fix it
all. This would be more organized and efficient for future contributors.

There's just a few invidual instances for mobile media queries on some
typography classes (Kevin, one example is the "em" sizing for FAQ mobile
view)

Thoughts?

**Comment by KevinMulhern** [comment]
Sounds good 👍 I'm happy to proceed with the typography classes. Lets :shipit:

**Comment by KevinMulhern** [comment]
Sorry just had another thought 🙈 if we had the typography all under a commented typography section in the global stylesheet would that make it easier to look up?

I'm thinking from a development perspective, having to add a class to a heading tag adds an extra unexpected step and bloats the html a bit more than necessary imo. I think you're right @codyloyd it needs clear documentation. This is something we can add to the style guide.

**Comment by codyloyd** [comment]
I'll document it on the style guide.       
  
  
  
  
  

  
  
>

**Comment by adachiu** [comment]
Clear documentation and commented typography section in global style sheet
makes sense to avoid HTML bloat. 😆Speed matters. I trust your expert
analysis of this 😄

**Comment by codyloyd** [comment]
alright.. I got a plan then.

I'll make the h_n_ tags uniform like the normal font-weight and color seen here: https://zpl.io/ZQIHmt
then I'll make a few classes to get the 'bold' font and/or change the color.

Then I'll document it all on the styleguide page.  Let's see if I can get that done today 🗡

**Comment by codyloyd** [comment]
:tada:
