### ISSUE TITLE
Bug: Outdated info in the FAQ

### ISSUE THREAD

**Issue by rlmoser99** [TheOdinProject/theodinproject#4762]
### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] The title of this issue follows the `Bug: brief description of bug` format, e.g. `Bug: Lesson complete button does not update on click`
- [ ] Would you like to work on this issue?

### Bug description

People who are reading our website read that TOP is for anyone that wants to freelance. However, for as long as I have been part of TOP's Discord the team frequently talks about how we are not meant for freelancing, since there is so much more to know (like security and business concerns).

In addition, this also mentions that our curriculum is meant to for users to skim through lessons. This is also another point that we frequently tell people to complete the curriculum in order.

<img width="1266" alt="Screenshot 2024-08-15 at 6 17 51 PM" src="https://github.com/user-attachments/assets/8b14a855-e9f3-44f6-83a6-813f6139f116">

### How to reproduce

1. Vist https://www.theodinproject.com/faq
2. Click on "Who is The Odin Project for?"
3. See reference to freelancing and skimming our lessons.

### Expected behavior

1. Vist https://www.theodinproject.com/faq
2. Click on "Who is The Odin Project for?"
3. Do not see reference to freelancing or skimming our lessons.

### What browsers are you seeing the problem on?

Chrome

### What OS are you using?

MacOS

### Discord Name

rlmoser

### Additional Comments

Changes will need to be made to this file: https://github.com/TheOdinProject/theodinproject/blob/main/config/locales/en.yml#L165-L167

**Comment by KevinMulhern** [comment]
Nice spot @rlmoser99 😎
