### ISSUE TITLE
Change odin logo in contact section of about page to provided gif

### ISSUE THREAD

**Issue by KevinMulhern** [TheOdinProject/theodinproject#477]
This task is to replace the Odin-logo image in the contact section of the [about page](https://staging-odin-project.herokuapp.com/about) with the `odin-wink.gif` which can be found under the assets for the about page.

This is the section in question:
<img width="1102" alt="screen shot 2017-04-30 at 14 48 02" src="https://cloud.githubusercontent.com/assets/7963776/25564882/6c81e0b6-2db4-11e7-9562-ee37f28ba9e4.png">

### Working on this task

- [ ] If you want to work on this task, please claim it by commenting below   
- [ ] Branch off the redesign branch                                                                 
- [ ] When you are submitting your pull request for this task please ensure the base branch you want to merge into is the redesign branch

**Comment by codyloyd** [comment]
I don't see the gif in zeplin... am I missing something, or has it not been added yet?

**Comment by KevinMulhern** [comment]
I've added it to the app in the redesign branch, it should be under `assets/images/about_page/odin-wink.gif`

**Comment by codyloyd** [comment]
Cool?
![1_024](https://cloud.githubusercontent.com/assets/18574792/25580300/8651911c-2e45-11e7-916c-0704012e1d81.png)

![1_025](https://cloud.githubusercontent.com/assets/18574792/25580306/96c9930a-2e45-11e7-9b86-7763d4a8a072.png)

![1_026](https://cloud.githubusercontent.com/assets/18574792/25580338/da5bb364-2e45-11e7-900e-ef81f7938cba.png)

**Comment by KevinMulhern** [comment]
LGTM 👍 
Paging @adachiu 😄

**Comment by adachiu** [comment]
@codyloyd @KevinMulhern Let's have the grey chat box removed so the text is just on white background. It should look cleaner 😄 
Everything else is 👌

**Comment by codyloyd** [comment]
do you mean only on smaller screens or in every context?

**Comment by adachiu** [comment]
Every context @codyloyd

**Comment by codyloyd** [comment]
I like it.
![learn web development for free using ruby on rails the odin project - chromium_028](https://cloud.githubusercontent.com/assets/18574792/25586998/a372e044-2e67-11e7-87d5-506f520bcae8.png)

![1_029](https://cloud.githubusercontent.com/assets/18574792/25587015/b4c5a0ac-2e67-11e7-998a-702caadbe028.png)

**Comment by KevinMulhern** [comment]
😍

**Comment by adachiu** [comment]
Same! But add some padding! 👍

Desktop view: more padding between gif and text. Also lower the text side (including button) so it's horizontally aligned to the gif.

Mobile view: add padding between gif and text. Center vertical alignment of gif and text.

**Comment by codyloyd** [comment]
ezpz 🗡

**Comment by arun1595** [comment]
@codyloyd Looks awesome :tada:

**Comment by codyloyd** [comment]
hows that?
![3_030](https://cloud.githubusercontent.com/assets/18574792/25615327/27cbe3d8-2efc-11e7-8224-38ec1db83ae4.png)
