### ISSUE TITLE
Bug: Rendering HTML tag in markdown preview tool refreshes page

### ISSUE THREAD

**Issue by MaoShizhong** [TheOdinProject/theodinproject#4795]
### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] The title of this issue follows the `Bug: brief description of bug` format, e.g. `Bug: Lesson complete button does not update on click`
- [ ] Would you like to work on this issue?

### Bug description

In the markdown preview tool, everything is fine until you render any valid HTML tag. The page the automatically refreshes, clearing the textarea.

### How to reproduce

1. Go to the [markdown preview page](https://www.theodinproject.com/lessons/preview).
2. Enter any text except for a an HTML tag - no issues should be observed.
3. Type any HTML opening tag e.g. `<div>`, `<a>` or `<span>`.
4. Upon completing the tag with `>`, the page refreshes, clearing the textarea.

### Expected behavior

1. Go to the [markdown preview page](https://www.theodinproject.com/lessons/preview).
2. Enter any text except for a an HTML tag - no issues should be observed.
3. Type any HTML opening tag e.g. `<div>`, `<a>` or `<span>` - the page should not refresh nor clear the textarea.

### What browsers are you seeing the problem on?

Firefox, Chrome, Microsoft Edge, Other

### What OS are you using?

Ubuntu, Android

**Comment by Asartea** [comment]
I tried reproducing this locally, but even using an up-to-date clone (git commit locally is `3c4fc971`, which matches the latest commit to `main`) I'm unable to reproduce this. I then wondered if it might be Browser/OS specific, but I can reproduce the bug on the TOP website using the exact same setup. This suggests something is broken in prod/happens only when rails is being run in production

**Comment by SumonGFC** [comment]
I am able to reproduce this issue. The behaviour is exactly as Mao's video shows: once the previewer's text area reads a div or any other html tag, the text is deleted and the page refreshes.

Lubuntu 22.04
Google Chrome 128.0.6613.84

**Comment by MaoShizhong** [comment]
Should be fixed now. There were some recent prod changes that were a bit overenthusiastic and ended up overenthusiastic on blocking and sanitising this stuff here. 

Could others confirm it's back to how it used to be?

**Comment by Asartea** [comment]
Can confirm it works fine for me on production now
