### ISSUE TITLE
Bug: The Odin Project's website is not being rendered correctly on Safari

### ISSUE THREAD

**Issue by huy2000vu** [TheOdinProject/theodinproject#4813]
### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] The title of this issue follows the `Bug: brief description of bug` format, e.g. `Bug: Lesson complete button does not update on click`
- [X] Would you like to work on this issue?

### Bug description

Website not being rendered correctly. HTML elements are all fullscreened.

### How to reproduce

1. Open Safari browser using MACOS
2. Visit the official The Odin Project's website

### Expected behavior

The website should be rendered correctly just like how the official website looks.

### What browsers are you seeing the problem on?

Safari

### What OS are you using?

MacOS

### Discord Name

essentially

**Comment by KevinMulhern** [comment]
Thanks for the report @huy2000vu. What do you mean by not rendering correctly? screenshots if possible please and what version of Safari are you using?

**Comment by huy2000vu** [comment]
<img width="1470" alt="Screenshot_2024-09-19_at_4 55 29_PM" src="https://github.com/user-attachments/assets/e834c214-7fa8-4960-b594-a072dc01aa89">

Safari Version: Version 17.4.1 (19618.1.15.11.14)

**Comment by KevinMulhern** [comment]
Thanks @huy2000vu, that looks like our CSS is blocked from loading. It's working fine on my machine (Safari 17.6). Are there any errors in your JS console when you inspect that page with the Safari web inspector?
