### ISSUE TITLE
Redesign: Hero background gradient (Home page)

### ISSUE THREAD

**Issue by adachiu** [TheOdinProject/theodinproject#482]
- Merge isometric image and H1 title into hero div
- Apply background gradient into hero div and increase the opacity a bit (it is currently too light to tell)

https://zpl.io/14j8Nn (Comment your email address to access Zeplin mock up)
The following gradient values are taken from the Zeplin file.
```
background-image: linear-gradient(to bottom, #ffffff, #eeeeee);
background-image: linear-gradient(to bottom, #ffffff;
```

### Working on this task

- [ ] If you want to work on this task, please claim it by commenting below   
- [ ] Branch off the redesign branch                                                                 
- [ ] When you are submitting your pull request for this task please ensure the base branch you want to merge into is the redesign branch

**Comment by codyloyd** [comment]
the gradient is already there and has no opacity.. but I think the reason it is hard to tell is because the area that is covered by the gradient is too long, so the shift is too gradual I think I can make it look nicer by moving the color stops.. I'll work on it and post a screenshot or two

**Comment by codyloyd** [comment]
it's subtle.. but I think it's better.  I just moved the 'transition point' a bit higher.
![1_020](https://cloud.githubusercontent.com/assets/18574792/25570964/f47b3fcc-2def-11e7-8111-f73b8f654e84.png)

original for comparison:
![1_021](https://cloud.githubusercontent.com/assets/18574792/25570974/19da880e-2df0-11e7-83d6-e86d2d418c64.png)


let me know what you think.  I can tweak further if you like

**Comment by KevinMulhern** [comment]
It looks way better to me @codyloyd 😄 LGTM 👍

**Comment by codyloyd** [comment]
cool I'll do the PR then
