### ISSUE TITLE
Feature Request: Add Accordion Functionality to FAQ Section

### ISSUE THREAD

**Issue by achintyasrivastav** [TheOdinProject/theodinproject#4824]
### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] The title of this issue follows the `Feature Request: brief description of feature request` format, e.g. `Feature Request: Add a dark mode to the website`
- [X] Would you like to work on this issue?

### Description of the Feature Request

I'd like to suggest adding an accordion-style toggle feature to the FAQ section of the freeCodeCamp website. This feature would allow users to click on a "+" sign next to a question to reveal its answer. Upon revealing the answer, the "+" would change to a "-" sign. Clicking the "-" would collapse the answer, hiding it and returning the "+" sign.

How It Would Be Useful/Beneficial:
Currently, all FAQ answers are displayed at once, making the page appear cluttered and harder to navigate, especially for users who are looking for specific information. 
This accordion feature would:
-Keep the FAQ section clean and organized by only showing the answers when users interact with specific questions.
-Improve the user experience by minimizing the amount of text displayed at once, making it easier to browse through the questions.
-Enhance readability on mobile devices and smaller screens where space is more limited.

Problem It Would Solve:
When a user opens the FAQ section, they are met with all questions and answers displayed at once, which can overwhelm them with information. By allowing users to toggle individual answers, we ensure a more focused and streamlined user experience.

Feature Description in Problem-Solution Format:
When a user visits the FAQ section, I want them to be able to click on a "+" sign next to a question to expand and view the answer. Clicking the "-" sign will collapse the answer again, allowing the user to explore only the questions they are interested in, while keeping the rest of the section clean and hidden.
![Screenshot 2024-10-04 005100](https://github.com/user-attachments/assets/c2254adb-7e66-4218-a47e-3544e5b7f16f)

### Acceptance criteria

- The FAQ questions should be displayed with a "+" sign next to each.
- When a user clicks on a "+" sign, the corresponding answer should be revealed, and the "+" sign should change to a "-" sign.
- When a user clicks the "-" sign, the answer should collapse, hiding the content and reverting the "-" sign back to a "+".
- Only one answer should be expanded at a time (optional, depending on user preference).
- The design should be responsive, ensuring that the accordion works on both desktop and mobile devices.
- The accordion transition should be smooth and animated to enhance user experience.
- All FAQs should initially appear collapsed when the page is loaded.

### Additional Comments

Hello! This is my first time participating in Hacktoberfest, and I’ve already successfully contributed to another project. I’m excited to contribute to your repository as well. I’m keen to bring my skills and enthusiasm to help improve the project in any way I can.

Looking forward to collaborating!

**Comment by KevinMulhern** [comment]
Thanks for the suggestion @achintyasrivastav, our site [FAQ page](https://www.theodinproject.com/faq) already uses an accordion. But I'm not sure if the [support us](https://www.theodinproject.com/support_us) page should too. 

There is a lot less information on that page and all the questions are related to each other, they kind of tell a story when read from top to bottom. I get the feeling that hiding the answers could make it feel less open, something we definitely don't want on a donations page, and negatively impact the UX instead of making it better.
