### ISSUE TITLE
Redesign: Clean up layout (Curriculum page)

### ISSUE THREAD

**Issue by adachiu** [TheOdinProject/theodinproject#483]
Tagging @arun1595 because you're already working on adding the background

- Remove text under Curriculum title
- Add background to bottom of page
- Badge padding to match course-card padding (currently badge is bleeding through course-card padding
- Add padding (10px) between card title and lesson number
- Remove subtitle for course cards

**Comment by adachiu** [comment]
@arun1595 I've updated this mock up to reflect the rest of the design review notes for this curriculum page https://zpl.io/G5zhP 

- Removed right column (Learn and Projects). Added CTA button to link to course
- Sizing of card is resized
- Card shadow updated
- Refer to spacing on Zeplin

**Comment by KevinMulhern** [comment]
@adachiu that looks lit :fire

**Comment by arun1595** [comment]
Closed by https://github.com/TheOdinProject/theodinproject/pull/508
