### ISSUE TITLE
Bug: Very minor typo in JavaScript section and lesson title (Organizing Your Javascript Code)

### ISSUE THREAD

**Issue by kysch13** [TheOdinProject/theodinproject#4849]
### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] The title of this issue follows the `Bug: brief description of bug` format, e.g. `Bug: Lesson complete button does not update on click`
- [X] Would you like to work on this issue?

### Bug description

**Very** minor typo - In the full stack JavaScript course (in both Ruby and JS paths) the section title 'Organizing Your Javascript Code' and lesson title 'Organizing Your Javascript Code Introduction' should have a capital 'S' in the word 'Javascript'. 

### How to reproduce

Section and Lesson Titles can be found here - 
https://www.theodinproject.com/paths/full-stack-javascript/courses/javascript#organizing-your-javascript-code
https://www.theodinproject.com/paths/full-stack-ruby-on-rails/courses/javascript#organizing-your-javascript-code

### Expected behavior

1. 'Organizing Your Javascript Code' should be 'Organizing Your JavaScript Code'
2. 'Organizing Your Javascript Code Introduction' should be 'Organizing Your JavaScript Code Introduction'

### Additional Comments

My apologies if this is not the right template/place to submit this typo.

**Comment by rlmoser99** [comment]
I will assign you this issue. You'll need to update the lesson files in `db/fixtures/lessons`.
