### ISSUE TITLE
Chore: Consolidate multiple get routes into a single resources declaration for static pages

### ISSUE THREAD

**Issue by Tongxin-Sun** [TheOdinProject/theodinproject#4855]
### Checks

- [X] I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
- [X] The title of this issue follows the `Chore: brief description of chore` format, e.g. `Chore: Lesson complete button does not update on click`
- [X] Would you like to work on this issue?

### Chore description

Currently, the routes for static pages like `home`, `about`, `faq`, `team`, `contributing`, `support_us`, `terms_of_use`, `privacy-policy`, and `success_stories` are declared individually using separate `get` statements in the `routes.rb file`. This approach can become cumbersome as the application grows and additional static pages are added. Refactoring these routes to use a single resources or scope declaration for the `static_pages` controller will streamline the routing configuration, improve readability, and make it easier to manage.

<img width="466" alt="image" src="https://github.com/user-attachments/assets/b342a116-c2a4-4bf7-b10e-5111bb08b014">

### Acceptance criteria

- [ ] Replace individual `get` routes for static pages (`home`, `about`, `faq`, `team`, `contributing`, `support_us`, `terms_of_use`, `privacy-policy`, and `success_stories`) with a single scope declaration for `static_pages`.
- [ ] Ensure that all route paths and actions remain functional after refactoring.
- [ ] Update all corresponding links and path helpers in the views to use the new resourceful routes (e.g., static_pages_path instead of individual page routes)
- [ ] Test to confirm that all static pages render correctly and the paths are resolved as expected.

**Comment by KevinMulhern** [comment]
Thanks for the suggestion @Tongxin-Sun. How would we get individual paths, for example the faq path, using `static_pages_path`?

**Comment by Tongxin-Sun** [comment]
> Thanks for the suggestion @Tongxin-Sun. How would we get individual paths, for example the faq path, using `static_pages_path`?

Thank you for your response! If we organize all the routes under a single resources declaration like the following, the individual path names would change—for example, faq_path would become faq_static_pages_path.
```ruby
resources :static_pages, only: [] do
  collection do
    get :home
    get :about
    get :faq
    get :team
    get :contributing
    get :support_us
    get :terms_of_use
    get 'privacy-policy', action: :privacy_policy
    get :success_stories
  end
end
 ```

While this method consolidates the routes, it requires updating all references to these paths in the codebase, which could involve significant effort depending on the scope of usage.

Alternatively, we could use a scope declaration, as shown below:
```ruby
  scope controller: :static_pages do
    get 'home'
    get 'about'
    get 'faq'
    get 'team'
    get 'contributing'
    get 'support_us'
    get 'terms_of_use'
    get 'privacy-policy'
    get 'success_stories'
  end
```

This approach reduces redundancy by eliminating repeated mentions of static_pages, while preserving the current path names (e.g., faq_path remains unchanged). It strikes a balance between simplifying the routing logic and maintaining compatibility with the existing code.

Please let me know your thoughts. Would you prefer consolidating these routes under a resources or scope declaration for better organization? Or do you think it's better to retain the original get statements for simplicity?
