### ISSUE TITLE
Redesign: Create a card class that can be used for all cards

### ISSUE THREAD

**Issue by KevinMulhern** [TheOdinProject/theodinproject#490]
Currently there are some inconsistencies with the cards in different pages, creating one card class that can be applied all cards on the site would be beneficial. 

The card styles on the [curriculum page](https://staging-odin-project.herokuapp.com/courses?ref=homenav) are what all cards should look like. Whoever picks this up should use those styles for this new generic card class. Don't forget about mobile view 😉 

Other pages which currently contain cards:
[success stories](https://staging-odin-project.herokuapp.com/success_stories)
[Contributing](https://staging-odin-project.herokuapp.com/contributing)

- [x] If you want to work on this task, please claim it by commenting below   
- [x] Branch off the redesign branch                                                                 
- [x] When you are submitting your pull request for this task please ensure the base branch you want to merge into is the redesign branch

**Comment by aneta-bielska** [comment]
Hi. Can I grab this one?

**Comment by arun1595** [comment]
@aneta-bielska It is yours. Let us know if you have any questions in the [Contributing](https://gitter.im/TheOdinProject/Contributing) channel

**Comment by codyloyd** [comment]
go for it 😸 
hit us up in the chatroom if you need help getting set up
