### ISSUE TITLE
Redesign: Contributing page tweaks

### ISSUE THREAD

**Issue by KevinMulhern** [TheOdinProject/theodinproject#491]
- Remove the instructions and notes text under the cards

**Why you Should get Involved section**
- Change “Why you should get involved” to “Benefits of Contributing” and section needs background color (light grey)
- Add padding between SVG and the text 30px, and padding between title and text 20px

**Hall of Fame section**
- Mobile view: Reduce margin for “Hall of Fame” bottom text 

---

- [ ] If you want to work on this task, please claim it by commenting below   
- [ ] Branch off the redesign branch                                                                 
- [ ] When you are submitting your pull request for this task please ensure the base branch you want to merge into is the redesign branch

**Comment by lehcsirk** [comment]
I would like to work on this task.

**Comment by KevinMulhern** [comment]
Its all yours @lehcsirk 😄, let us know if you have any questions

**Comment by KevinMulhern** [comment]
Hey @lehcsirk, did you get a chance to work on this?

**Comment by KevinMulhern** [comment]
Two weeks of no communication for such a small ticket, I have to assume this has been abandoned. Please do not pick things up if you do not intend to work on them @lehcsirk. Someone else could have done this in the mean time.
