### ISSUE TITLE
Redesign: Bug with floating gitter chat window

### ISSUE THREAD

**Issue by KevinMulhern** [TheOdinProject/theodinproject#506]
The button icons at the top of the window are un-clickable and the menu items on the navbar are overlaying the window.

This problem seems to be caused by the z-index of the navbar.

**Screen shot of the top of the window**
<img width="661" alt="screen shot 2017-05-04 at 23 40 22" src="https://cloud.githubusercontent.com/assets/7963776/25727781/13db90de-3123-11e7-9ccf-84b41c768aa2.png">

**Comment by codyloyd** [comment]
fixed
