### ISSUE TITLE
Redesign: Lesson page

### ISSUE THREAD

**Issue by KevinMulhern** [TheOdinProject/theodinproject#509]
This task is to implement a redesigned lesson page as shown in the mock up images below. For reference this is our current lesson page http://www.theodinproject.com/courses/ruby-on-rails/lessons/sinatra-basics

**Important**
Please ignore the solutions component at the bottom of the mock up. We will create another issue for implementing that feature when we merge in the backend work for it in the next few weeks.

### Working on this task

- [ ] If you want to work on this task, please claim it by commenting below   
- [ ] Branch off the redesign branch                                                                 
- [ ] Check out our [styleguide](https://staging-odin-project.herokuapp.com/styleguide)
- [ ] When you are submitting your pull request for this task please ensure the base branch you want to merge into is the redesign branch  

If you have any questions or need clarification about anything related to this task please contact the maintainers in our [contributing channel on Gitter](https://gitter.im/TheOdinProject/Contributing)

### Redesigned lesson page mock up
![lesson-detail-1](https://cloud.githubusercontent.com/assets/7963776/24772136/10e44ee2-1b08-11e7-869b-cd111b387484.png)

**Comment by ifiguer** [comment]
I'd like to help with this

**Comment by KevinMulhern** [comment]
Hi @ifiguer, its all yours. If you have any questions about it, please don't hesitate to let us know 😄

**Comment by ifiguer** [comment]
How should the headers be styled. I'm asking because all headers look the same in the mockup but actual lessons have h1, h2, h3 and so on.

**Comment by KevinMulhern** [comment]
Hi @ifiguer, good question 😄 

The lesson content is using all different types of headings. We will need to go through them all and make them consistent.

Using the mock up as an example:

The course name "Ruby on Rails" should be a h1
The lesson name "Sinatra Basics" should be a h2
all the headings within the lessons should be h3's eg "overview", "Points to Ponder etc"

**Comment by KevinMulhern** [comment]
I'll change [this lesson](https://www.theodinproject.com/courses/web-development-101/lessons/how-does-the-web-work) today to follow that format to give you a lesson to work with.

I'll comment again when thats done.

**Comment by KevinMulhern** [comment]
Hi @ifiguer, I updated that lesson 😄 you just need to run the curriculum update rake task to pull in the latest changes for the lesson content for it to display on your local machine. Let me know if you need anything else.

**Comment by KevinMulhern** [comment]
Hi @ifiguer, any updates on this? sorry I really don't mean to put pressure on you. But this page is blocking several other things at the moment. Thats why it has been labeled with priority.

**Comment by ifiguer** [comment]
Yeah, sorry, didn't mean to take so long. Thanks for the reminder. I just made the pull request. One thing that is missing is the navigation on the left... I can keep trying but I don't think I'm getting anywhere, maybe someone else wants to give it a shot?
