### ISSUE TITLE
Redesign: Dashboard

### ISSUE THREAD

**Issue by KevinMulhern** [TheOdinProject/theodinproject#510]
This task is to implement a dashboard page as shown in the mock up images below. You can use the users show controller action and view for this page.

**Important**
Please ignore the solutions component at the bottom of the mock up. We will create another issue for implementing that feature when we merge in the backend work for it in the next few weeks.

### Working on this task

- [ ] If you want to work on this task, please claim it by commenting below   
- [ ] Branch off the redesign branch                                                                 
- [ ] Check out our [styleguide](https://staging-odin-project.herokuapp.com/styleguide)
- [ ] When you are submitting your pull request for this task please ensure the base branch you want to merge into is the redesign branch  

If you have any questions or need clarification about anything related to this task please contact the maintainers in our [contributing channel on Gitter](https://gitter.im/TheOdinProject/Contributing)

### Redesigned lesson page mock up
![dashboard-complete](https://cloud.githubusercontent.com/assets/7963776/25784381/c3d9cef0-3363-11e7-8c8d-15c4f2616b84.png)

**Comment by arun1595** [comment]
I'm working on this.

**Comment by codyloyd** [comment]
I was using the users show controller and view for the user settings page..........
