### ISSUE TITLE
Add option to sign-up/sign-in through a Google account

### ISSUE THREAD

**Issue by faraazahmad** [TheOdinProject/theodinproject#512]
There's hardly any person to find without a Google account. Also, most newcomers may not have a Github account already. Signing-up the old fashioned way is mundane. So, if there was a way to sign-up using a Google account, it would arguably be the path of least resistance, and hence more people will actually sign-up.

There's a ruby gem for authentication with Google. [This](https://github.com/google/google-auth-library-ruby) may be a possible solution.

**Comment by codyloyd** [comment]
this is a good idea and would be relatively simple to implement.  I approve.

if we're in agreement here then @adachiu will want to build in the google sign in button to the mockups....

**Comment by adachiu** [comment]
That's a nice to have @faraazahmad ! We'll need to finish with our main priorities first, but we'll definitely get back to this.

**Comment by arun1595** [comment]
Agree with @adachiu.

@faraazahmad Thanks!

**Comment by faraazahmad** [comment]
Great👍
