### ISSUE TITLE
Redesign: Create a user avatar and drop down on the navbar for logged in users

### ISSUE THREAD

**Issue by KevinMulhern** [TheOdinProject/theodinproject#519]
When a user is logged in the right hand side of the nav links should contain a clickable user avatar. When the avatar is clicked it should display a drop down menu as shown in the screen shot below.

### Working on this task

- [ ] If you want to work on this task, please claim it by commenting below   
- [ ] Branch off the redesign branch                                                                 
- [ ] Check out our [styleguide](https://staging-odin-project.herokuapp.com/styleguide)
- [ ] When you are submitting your pull request for this task please ensure the base branch you want to merge into is the redesign branch  

If you have any questions or need clarification about anything related to this task please contact the maintainers in our [contributing channel on Gitter](https://gitter.im/TheOdinProject/Contributing)
<img width="463" alt="screen shot 2017-05-13 at 11 23 08" src="https://cloud.githubusercontent.com/assets/7963776/26024706/e80747a2-37ce-11e7-8393-ff22ea2ce178.png">

**Comment by SalMac86** [comment]
I'll work on this.

**Comment by arun1595** [comment]
@SalMac86 It is yours. Let us know if you need any help with the issue. Thanks!

**Comment by arun1595** [comment]
@KevinMulhern 

> When the avatar is clicked it should display a drop down menu as shown in the screen shot below.

How about displaying the dropdown on hovering the avatar?

**Comment by adachiu** [comment]
@arun1595 That is a good idea. Hover to display the dropdown under avatar.

**Comment by SalMac86** [comment]
I'll look at both. Are there any known cases of hover failing where a
contingency click would be advisable?

On May 19, 2017 9:41 PM, "Ada Chiu" <notifications@github.com> wrote:

@arun1595 <https://github.com/arun1595> That is a good idea. Hover to
display the dropdown under avatar.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/TheOdinProject/theodinproject/issues/519#issuecomment-302850335>,
or mute the thread

**Comment by KevinMulhern** [comment]
@SalMac86 yeah on mobile 😄, it will have to be a click to make it work on touch screens. Thank you for picking this one up.

**Comment by KevinMulhern** [comment]
Hi @SalMac86, just checking in 😄 have you made any progress on this one?

**Comment by SalMac86** [comment]
So far, I've been focused on getting my device environment up and running.
I'm using Google Cloud Platform, at least trying to!

I was able to make a P.o.C. work locally, just need to get all the moving
pieces working in concert!

**Comment by KevinMulhern** [comment]
Hey @SalMac86, its been another week 😄 so I'm checking in again. Have you made any progress? need any help with anything?

**Comment by KevinMulhern** [comment]
Putting this in for help wanted again.
