### ISSUE TITLE
Redesign: Contribution page tweaks

### ISSUE THREAD

**Issue by KevinMulhern** [TheOdinProject/theodinproject#521]
- Remove the instructions and notes text under the cards

**Why you Should get Involved section**
- Change “Why you should get involved” to “Benefits of Contributing” and section needs background color (light grey)
- Add padding between SVG and the text 30px, and padding between title and text 20px

**Hall of Fame section**
- Mobile view: Reduce margin for “Hall of Fame” bottom text 

---

- [x] If you want to work on this task, please claim it by commenting below   
- [ ] Branch off the redesign branch                                                                 
- [ ] When you are submitting your pull request for this task please ensure the base branch you want to merge into is the redesign branch

**Comment by mindovermiles262** [comment]
I can do this

**Comment by KevinMulhern** [comment]
Thanks @mindovermiles262, its all yours 😄 if you have any questions, don't hesitate to let us know.

**Comment by mindovermiles262** [comment]
> and section needs background color (light grey)

There is a gradient that starts at "Why You Should Get Involved" that runs through "Got Questions?"

**Comment by KevinMulhern** [comment]
Hey @mindovermiles262, yeah its pretty much the same as the about page. Heres a screen shot of the mock up. Sorry I should have included this in the description
![contribution](https://cloud.githubusercontent.com/assets/7963776/26243244/123f0984-3c83-11e7-9e58-9b92dc133ba8.png)

**Comment by mindovermiles262** [comment]
#523
