### ISSUE TITLE
Redesign: all submissions page

### ISSUE THREAD

**Issue by KevinMulhern** [TheOdinProject/theodinproject#525]
This task is to implement an all projects submissions for a project page as shown in the mock up images below. 

**Important**
* Please ignore the pagination at the bottom of the page, just display all submissions in the list on one page. We will be implementing lazy loading later.

* The backend needs to be implemented for the vote functionality. Just hard code a vote count for now.

### Working on this task

- [ ] If you want to work on this task, please claim it by commenting below   
- [ ] Branch off the redesign branch                                                                 
- [ ] Check out our [styleguide](https://staging-odin-project.herokuapp.com/styleguide)
- [ ] When you are submitting your pull request for this task please ensure the base branch you want to merge into is the redesign branch  

### Mock up for all projects page
![lesson-all-solutions](https://cloud.githubusercontent.com/assets/7963776/26278475/5f32e1aa-3d93-11e7-9b99-0624bf66b0ed.png)

**Comment by codyloyd** [comment]
on it.
