### ISSUE TITLE
Redesign: Add badge for Web Development 101 on Curriculum page 

### ISSUE THREAD

**Issue by adachiu** [TheOdinProject/theodinproject#529]
This task is to update the badge for the "Web Development 101" card on the curriculum page.

[badge-webdev101.svg.zip](https://github.com/TheOdinProject/theodinproject/files/1016618/badge-webdev101.svg.zip)

### Working on this task

- [ ] If you want to work on this task, please claim it by commenting below   
- [ ] Branch off the redesign branch                                                                 
- [ ] Check out our [styleguide](https://staging-odin-project.herokuapp.com/styleguide)
- [ ] When you are submitting your pull request for this task please ensure the base branch you want to merge into is the redesign branch

**Comment by 105ron** [comment]
I'll do this @adachiu.

**Comment by codyloyd** [comment]
nice work Rhys.

closing the issue
