### ISSUE TITLE
README.md links to 404 page

### ISSUE THREAD

**Issue by brianhays** [TheOdinProject/theodinproject#533]
Line 13 of the README currently links to a 404 page

Details:
The link in the following sends you to https://github.com/TheOdinProject/theodinproject/blob/master/theodinproject.com (instead of theodinproject.com)

> This repo contains the main app for the Odin Project which can be found online at theodinproject.com.

**Comment by brianhays** [comment]
submitted PR to fix the link

**Comment by codyloyd** [comment]
thanks! 🎉
