### ISSUE TITLE
Create 'Contributors' file

### ISSUE THREAD

**Issue by codyloyd** [TheOdinProject/theodinproject#539]
Edit the CONTRIBUTORS.md file to include the names of all significant contributors to the project listed in categories (Ruby on Rails, main site backend, etc. etc. etc.)

The file itself is being created in a separate PR, what we need is for someone to fill it out.

Do we have any criteria for making the contribution list?  How are we going to maintain it?

**Comment by KevinMulhern** [comment]
I suppose the best criteria for now is any past and present mods as well as outside contributors who helped significantly. Maintaining it shouldn't be too difficult. There will probably be a few names to go it every so often.

**Comment by codyloyd** [comment]
this is the file: https://github.com/TheOdinProject/theodinproject/blob/redesign/CONTRIBUTORS.md
