### ISSUE TITLE
Rethink Terms of service

### ISSUE THREAD

**Issue by KevinMulhern** [TheOdinProject/theodinproject#542]
Currently we require the user to click a terms of service checkbox when they sign up. This is fine with normal email and password sign up but gets complicated when the user signs up with github omniauth. To get around this at the moment we redirect the user to an extra verification page when they sign up using github. This is a convoluted and not a very user friendly experience though.

After doing a bit of [research](http://danashultz.com/blog/2010/03/01/online-terms-can-be-binding-even-if-you-dont-have-to-click/) we don't have to get the user to click a checkbox to agree to terms of service as long as they are reasonably aware of the terms.

**Proposal**
The solution I propose for this is two fold:

- [x]  adding a link above the sign up buttons which links to the terms and conditions and page states "By registering your account you agree to the terms of service"
- [x]  Adding a "legal" link to the footer which will link to the terms and conditions page

**Comment by KevinMulhern** [comment]
@adachiu @codyloyd @arun1595 @105ron do you guys have any thoughts on this?

**Comment by codyloyd** [comment]
I think that sounds like a good solution.

**Comment by 105ron** [comment]
I missed this. Sounds like a good plan...
