### ISSUE TITLE
Redesign: Update the course descriptions

### ISSUE THREAD

**Issue by KevinMulhern** [TheOdinProject/theodinproject#545]
This task is to update the descriptions of the courses on the [course index page](https://staging-odin-project.herokuapp.com/courses?ref=homenav) 

The descriptions are currently quite long winded and don't look very good on mobile. It would be better if the descriptions were shorter, ideally limited to 2 - 3 lines. 

The descriptions are in the `db/seed.rb` file so will need to be updated from there.

### Working on this task

- [ ] If you want to work on this task, please claim it by commenting below   
- [ ] Branch off the redesign branch                                                                 
- [ ] Check out our [styleguide](https://staging-odin-project.herokuapp.com/styleguide)
- [ ] When you are submitting your pull request for this task please ensure the base branch you want to merge into is the redesign branch

**Comment by Demo318** [comment]
Hi Kevin,

I'd like to take this on.

**Comment by KevinMulhern** [comment]
@Demo318 its all yours man 😄 thank you so much for helping us.

**Comment by Demo318** [comment]
Hi @KevinMulhern I've submitted a PR with these updates. #560

**Comment by KevinMulhern** [comment]
Thanks for all your work on this @Demo318 🎉
