### ISSUE TITLE
Redesign: Success stories tweaks

### ISSUE THREAD

**Issue by KevinMulhern** [TheOdinProject/theodinproject#546]
There are a bunch of small issues with the [success stories page](https://staging-odin-project.herokuapp.com/success_stories), this task is to fix them:

* Remove completed course text from the success stories card
* Bold the persons name in the success stories card
* Include job title beside name, not bold
* 10px for margin bottom for the name section
* On Mobile view, avatar at top and centered and all text centered

### Working on this task

- [ ] If you want to work on this task, please claim it by commenting below   
- [ ] Branch off the redesign branch                                                                 
- [ ] Check out our [styleguide](https://staging-odin-project.herokuapp.com/styleguide)
- [ ] When you are submitting your pull request for this task please ensure the base branch you want to merge into is the redesign branch

**Comment by darienh** [comment]
I would like to work on this!

**Comment by KevinMulhern** [comment]
Its all yours @darienh, thank you for helping us.

**Comment by KevinMulhern** [comment]
Hey @darienh, just doing a weekly checkin. How are you getting on with this?

**Comment by KevinMulhern** [comment]
No communication, So putting this back in for someone else to pick it up 👍
