### ISSUE TITLE
Redesign: Make flash messages visible again

### ISSUE THREAD

**Issue by KevinMulhern** [TheOdinProject/theodinproject#548]
Currently on the sign up page and sign in page the flash messages are invisible. This makes working with them a pain.

This task is to make them visible again, if you inspect the page after trying to sign up/in you can see they are there. I suspect that they just need styling. 

We haven't designed how these will look with the new aesthetics of the site so style them in what ever way you think is best. We just want them to visible again so makes it easier to work with logging in and signing up in the mean time.

### Working on this task

- [x] If you want to work on this task, please claim it by commenting below   
- [ ] Branch off the redesign branch                                                                 
- [ ] Check out our [styleguide](https://staging-odin-project.herokuapp.com/styleguide)
- [ ] When you are submitting your pull request for this task please ensure the base branch you want to merge into is the redesign branch

**Comment by hd719** [comment]
Hello @KevinMulhern can I work on this?

**Comment by KevinMulhern** [comment]
Hi @hd719, its all yours man 😄 thank you for helping us.

**Comment by hd719** [comment]
Hey @KevinMulhern is it okay if I name this branch fix/Redesign-Flash-Messages? 

-Thank you.

**Comment by KevinMulhern** [comment]
Hey @hd719, yeah thats great branch naming right there 😄 

You should be able to fork either or and switch to the redesign branch if your on master.

**Comment by hd719** [comment]
@KevinMulhern Yeah I think I got it 

```
Hamels-MacBook-Air:theodinproject HD$ git checkout redesign
Branch redesign set up to track remote branch redesign from origin.
Switched to a new branch 'redesign'
Hamels-MacBook-Air:theodinproject HD$ git branch
  master
* redesign
```

**Comment by KevinMulhern** [comment]
No problem @hd719, thanks 👍

**Comment by KevinMulhern** [comment]
Hey @hd719, just doing a weekly check in. How are you getting on with this?

**Comment by hd719** [comment]
Hey @KevinMulhern I am doing fine I'll be creating a PR for you to check later this week. 

-Thank you.

**Comment by KevinMulhern** [comment]
No problem, thanks 😄

**Comment by hd719** [comment]
Hey @KevinMulhern sorry for the bother, but I am having a real hard time finding html for the `Sign Up Page` that is repsonsible for displaying the following errors. If you can point me in the right direction that would be awesome. 

`is invalid` and `too short (minimum 6 characters)`

![screen shot 2017-06-01 at 10 12 44 am](https://cloud.githubusercontent.com/assets/20329318/26683808/1167016c-46b3-11e7-86f8-17ddd883bc8c.png)

- Thank you.

**Comment by KevinMulhern** [comment]
Hey @hd719, those are generated by simple form. They are a bit out of scope of this ticket thought. I would leave those for now. I'm not even sure if we will be keeping them. We might generate the errors in javascript instead.

Just make the the flash messages which appear above the h1 visible, that will make these pages easier to work with until we design the user interactions and error validations.

Don't spend a lot of time styling them either, as they will likely be changed when our designer gets to them.

**Comment by hd719** [comment]
Hey @KevinMulhern I am sorry for the bother, but for the sign up page I cannot find any flash messages. 

I enter in the information that is needed in the forms and click submit, but the only errors that seem to show up are in the errors in the picture (below). 

![screen shot 2017-06-01 at 8 35 52 pm](https://cloud.githubusercontent.com/assets/20329318/26706265/f577ffd6-4709-11e7-8110-3ffc52dda435.png)
![screen shot 2017-06-01 at 8 35 30 pm](https://cloud.githubusercontent.com/assets/20329318/26706266/f5794f1c-4709-11e7-91c2-81b777b7c8ce.png)

-Thank you.

**Comment by KevinMulhern** [comment]
ah yeah I see @hd719, sorry about that I thought there were flash messages on that page as well. Can you just target the error messages and make them red on that page then please?

**Comment by hd719** [comment]
Hey @KevinMulhern just an update I will be aiming to fix this issue by this week, sorry for the delay. 

-Thank you.

**Comment by KevinMulhern** [comment]
No worries @hd719, thanks for the update 😄

**Comment by KevinMulhern** [comment]
I think we should let someone else pick this up @hd719, thanks for your interest anyway.

**Comment by hd719** [comment]
Hey sorry for the delay, but I am almost finished with this.

**Comment by KevinMulhern** [comment]
Sorry @hd719, its already been done. Working with the auth pages was getting unbearable in development without them. We couldn't wait any longer.
