### ISSUE TITLE
Redesign: Add a link to the terms of use page in the footer menu

### ISSUE THREAD

**Issue by KevinMulhern** [TheOdinProject/theodinproject#550]
This task is to add a link to the [terms page](https://www.theodinproject.com/tou) on the footer menu.

### Working on this task

- [ ] If you want to work on this task, please claim it by commenting below   
- [ ] Branch off the redesign branch                                                                 
- [ ] When you are submitting your pull request for this task please ensure the base branch you want to merge into is the redesign branch  

This is the menu on the footer it should be added to:
<img width="343" alt="screen shot 2017-05-24 at 18 50 38" src="https://cloud.githubusercontent.com/assets/7963776/26417746/f529f556-40b1-11e7-94ae-9ee6c7d0429e.png">

**Comment by lqze** [comment]
No problem, will take.

**Comment by lqze** [comment]
Submitted pull request

**Comment by KevinMulhern** [comment]
Thanks @lqze 😄
