### ISSUE TITLE
Redesign: Remove path text from the homepage

### ISSUE THREAD

**Issue by KevinMulhern** [TheOdinProject/theodinproject#553]
Currently we have text on the courses section of the [homepage](https://staging-odin-project.herokuapp.com/) which implies we have different learning paths to choose from. We will eventually have different learning paths, but not right now. 

This task is to do the following:
* Change the title from **"Choose to learn from a path"** to **"Learn everything you need to know to become a web developer"**
* Remove the paths text "Full Stack, Front End, Back End" and associated styles.
* Remove the text under the paths "Or selectively learn from the following courses"

### Working on this task

- [ ] If you want to work on this task, please claim it by commenting below   
- [ ] Branch off the redesign branch                                                                 
- [ ] Check out our [styleguide](https://staging-odin-project.herokuapp.com/styleguide)
- [ ] When you are submitting your pull request for this task please ensure the base branch you want to merge into is the redesign branch  

**Note**
* Please use the [contributing guide](https://github.com/TheOdinProject/theodinproject/wiki/Contributing-Guide) to get the app running on your local machine if you haven't already.
* Please ignore the failing tests, all of the UI changes have broken many of the tests. We will be fixing these later.

This is a screen shot of all the text in question
<img width="537" alt="screen shot 2017-05-24 at 23 52 03" src="https://cloud.githubusercontent.com/assets/7963776/26429149/5350eb3c-40dd-11e7-9e7a-528bd90bbd11.png">

**Comment by cheukyin699** [comment]
I'll do this @KevinMulhern

**Comment by KevinMulhern** [comment]
Thanks @cheukyin699 😄

**Comment by KevinMulhern** [comment]
Thank you for completing this @cheukyin699 🎉
