### ISSUE TITLE
Redesign: Styling remember me checkbox on the sign in page

### ISSUE THREAD

**Issue by KevinMulhern** [TheOdinProject/theodinproject#554]
This task is to style the remember me checkbox on the [sign in page](https://staging-odin-project.herokuapp.com/login?ref=homenav) of the site so it looks like the checkbox in the mock up below.

### Working on this task

- [ ] If you want to work on this task, please claim it by commenting below   
- [ ] Branch off the redesign branch                                                                 
- [ ] Check out our [styleguide](https://staging-odin-project.herokuapp.com/styleguide)
- [ ] When you are submitting your pull request for this task please ensure the base branch you want to merge into is the redesign branch  

**Note**
* Please use the [contributing guide](https://github.com/TheOdinProject/theodinproject/wiki/Contributing-Guide) to get the app running on your local machine if you haven't already.
* Please ignore the failing tests, all of the UI changes have broken many of the tests. We will be fixing these later.

Mock up of the checkbox:
<img width="496" alt="screen shot 2017-05-25 at 00 07 52" src="https://cloud.githubusercontent.com/assets/7963776/26429488/05342994-40df-11e7-8591-9b34b39f8f9b.png">

**Comment by ayushkamadji** [comment]
Hi Kevin, I'd like to take this

**Comment by KevinMulhern** [comment]
Hi @ayushkamadji its all yours, thanks for helping us 😄

**Comment by KevinMulhern** [comment]
Thanks for your work on this @ayushkamadji 🎉
