### ISSUE TITLE
Redesign: Tweak styling on the sign up and sign in pages input boxes

### ISSUE THREAD

**Issue by KevinMulhern** [TheOdinProject/theodinproject#555]
There are a couple of minor styling tweaks we need to do to the [sign up](https://staging-odin-project.herokuapp.com/sign_up?ref=homenav) and [sign in](https://staging-odin-project.herokuapp.com/login?ref=homenav) pages

Tasks:
* Change the color of the h1 to the same color as the rest of h1's on the site
* Remove the space between "Log" and "in" in the h1
* Increase the font size in the input boxes to `1.125em`
* The placeholder and input text color seem to be in reverse. The placeholder text should be light grey and the input text should be the normal font color used in most p tags throughout the site.
* Remove the ugly yellow color chrome uses to highlight autofilled text boxes (this is shown in the screenshot below)

### Working on this task

- [ ] If you want to work on this task, please claim it by commenting below   
- [ ] Branch off the redesign branch                                                                 
- [ ] Check out our [styleguide](https://staging-odin-project.herokuapp.com/styleguide)
- [ ] When you are submitting your pull request for this task please ensure the base branch you want to merge into is the redesign branch  

**Note**
* Please use the [contributing guide](https://github.com/TheOdinProject/theodinproject/wiki/Contributing-Guide) to get the app running on your local machine if you haven't already.
* Please ignore the failing tests, all of the UI changes have broken many of the tests. We will be fixing these later.

Chrome autofill yellow highlight 😷 
<img width="513" alt="screen shot 2017-05-25 at 00 33 00" src="https://cloud.githubusercontent.com/assets/7963776/26429915/d3443318-40e1-11e7-926e-20b2c595948a.png">

**Comment by theXodus** [comment]
I would like to work on this please!

**Comment by KevinMulhern** [comment]
Hey @theXodus, its all yours 😄 thank you for helping us.

**Comment by KevinMulhern** [comment]
Hey @theXodus, just doing a check in 😄 
how have you been getting on with this? do you need any help with anything?

**Comment by theXodus** [comment]
My bad, I recently got a job and haven't been able to work on anything... you can take me off this since I won't have the time to complete. Sorry about that.

**Comment by KevinMulhern** [comment]
No problem, thanks for letting us know

**Comment by arcanck** [comment]
Hi!
I want to work on it.

**Comment by arun1595** [comment]
@arcanck It is yours. Thanks for picking it up :smile:
