### ISSUE TITLE
Redesign: Make the course cards on the curriculum page clickable

### ISSUE THREAD

**Issue by KevinMulhern** [TheOdinProject/theodinproject#556]
To make the [curriculum page](https://staging-odin-project.herokuapp.com/courses?ref=homenav) a bit more user friendly we want to make clicking anywhere on a course card take the user to the course that card represents.

Task:
* Wrap each course card in a link that will take the user to the specific course for that card when clicked.

### Working on this task

- [x] If you want to work on this task, please claim it by commenting below   
- [x] Branch off the redesign branch                                                                 
- [x] Check out our [styleguide](https://staging-odin-project.herokuapp.com/styleguide)
- [x] When you are submitting your pull request for this task please ensure the base branch you want to merge into is the redesign branch  

**Note**
* Please use the [contributing guide](https://github.com/TheOdinProject/theodinproject/wiki/Contributing-Guide) to get the app running on your local machine if you haven't already.
* Please ignore the failing tests, all of the UI changes have broken many of the tests. We will be fixing these later.

**Comment by mlendale** [comment]
Hi,
Is it ok that I take this one ?

**Comment by KevinMulhern** [comment]
Hi @mlendale Its all yours 😄, thanks for helping us.

**Comment by mlendale** [comment]
Just to be sure. When you say everywhere, you mean title and description right?

**Comment by KevinMulhern** [comment]
@mlendale yeah, wrapping the entire card in a link tag should do the trick.

**Comment by mlendale** [comment]
@KevinMulhern hmm actually, it doesn't. When doing that, only the title is. But, I'll find a workaround.

**Comment by KevinMulhern** [comment]
It doesn't work with wrapping the card in a link? thats strange.

Just to clarify when the user hovers over any part of a course card it should be clickable and redirect them to the specific course page when they click it.

**Comment by mlendale** [comment]
It works great without an inner anchor. But here there is the 'Open course' button.

**Comment by KevinMulhern** [comment]
ah, of course 😄 thats whats messing with it.

Ok, lets scale this back a bit in that case. Lets just make the title on the card clickable for now.

**Comment by mlendale** [comment]
Oh ok. Otherwise, I have just switched the inner anchor to a "fake button" with a span element...

**Comment by KevinMulhern** [comment]
We might get rid of the button some time in the near future, we need to talk about this with @adachiu our designer to see if clicking on the title of the card is more intuitive to users.

For now, I think its best to keep the button there as it was and just make the title a link.

**Comment by mlendale** [comment]
ok!

**Comment by mysteryihs** [comment]
I managed to make the the title, button, and text clickable, but not the entire card. Do you think that's enough?

**Comment by KevinMulhern** [comment]
Hi @mysteryihs, @mlendale has already submitted a PR which has been merged for this. Thanks anyway though 😄

**Comment by KevinMulhern** [comment]
Solved with https://github.com/TheOdinProject/theodinproject/pull/559
