### ISSUE TITLE
Redesign: Signup CTA button should only be displayed if the user is not logged in

### ISSUE THREAD

**Issue by arun1595** [TheOdinProject/theodinproject#567]
Currently the Sign up CTA button is showed even if a user is logged in. There's another signup CTA at the bottom of the homepage. This task is aimed at displaying the CTAs only if a guest user is viewing the page.

![image](https://cloud.githubusercontent.com/assets/7039523/26607921/6c5ac2fa-45b6-11e7-9538-7e3d4da886a0.png)

### Working on this task

- [ ] If you want to work on this task, please claim it by commenting below   
- [ ] Branch off the redesign branch                                              
- [ ] Check out our [styleguide](https://staging-odin-project.herokuapp.com/styleguide)
- [ ] When you are submitting your pull request for this task please ensure the base branch you want to merge into is the redesign branch

**Comment by mysteryihs** [comment]
I'll take this one Arun

**Comment by arun1595** [comment]
@mysteryihs It is yours :smile:
