### ISSUE TITLE
Redesign: vertical alignment of course badge content on home page

### ISSUE THREAD

**Issue by KevinMulhern** [TheOdinProject/theodinproject#573]
When on the [home page](https://staging-odin-project.herokuapp.com/) and on a mobile screen size, the course badge and name sit beside each other in the course tiles. Because some of the course names are quite long, this doesn't look right for some of the course tiles. The screen shot below shows this.

The task is to display the course name under the course badge in the course tiles. And to align both the badge and the course name centrally on mobile screen sizes.

### Working on this task

- [ ] If you want to work on this task, please claim it by commenting below   
- [ ] Branch off the redesign branch                                                                 
- [ ] Check out our [styleguide](https://staging-odin-project.herokuapp.com/styleguide)
- [ ] When you are submitting your pull request for this task please ensure the base branch you want to merge into is the redesign branch  

**Note**
* Please use the [contributing guide](https://github.com/TheOdinProject/theodinproject/wiki/Contributing-Guide) to get the app running on your local machine if you haven't already.
* Please ignore the failing tests, all of the UI changes have broken many of the tests. We will be fixing these later.

<img width="384" alt="screen shot 2017-06-01 at 08 22 59" src="https://cloud.githubusercontent.com/assets/7963776/26669081/64017808-46a4-11e7-91cf-dacb0323cc41.png">

**Comment by davidchappy** [comment]
I can take this.

**Comment by KevinMulhern** [comment]
Its all yours @davidchappy, thank you for picking this up 😄
