### ISSUE TITLE
Redesign: Gitter icon on footer takes the user to the wrong gitter room

### ISSUE THREAD

**Issue by KevinMulhern** [TheOdinProject/theodinproject#574]
The gitter icon on the footer of the site currently takes the user to this gitter room: https://gitter.im/TheOdinProject

It should take the user to this room instead: https://gitter.im/TheOdinProject/theodinproject

This task is to change the url to the correct one.

### Working on this task

- [x] If you want to work on this task, please claim it by commenting below   
- [ ] Branch off the redesign branch                                                                 
- [ ] Check out our [styleguide](https://staging-odin-project.herokuapp.com/styleguide)
- [ ] When you are submitting your pull request for this task please ensure the base branch you want to merge into is the redesign branch  

**Note**
* Please use the [contributing guide](https://github.com/TheOdinProject/theodinproject/wiki/Contributing-Guide) to get the app running on your local machine if you haven't already.
* Please ignore the failing tests, all of the UI changes have broken many of the tests. We will be fixing these later.

**Comment by arcanck** [comment]
I want to work on this, please.

**Comment by KevinMulhern** [comment]
Sure @arcanck, its all yours 😄 thanks for helping out.

**Comment by arun1595** [comment]
Closed via #582
