### ISSUE TITLE
Redesign: Success stories tweaks

### ISSUE THREAD

**Issue by KevinMulhern** [TheOdinProject/theodinproject#577]
There are a bunch of small issues with the [success stories page](https://staging-odin-project.herokuapp.com/success_stories), this task is to fix them:

* Remove completed course text from the success stories card
* Bold the persons name in the success stories card
* Include job title beside name, not bold
* 10px for margin bottom for the name section
* On Mobile view, avatar at top and centered and all text centered

### Working on this task

- [x] If you want to work on this task, please claim it by commenting below   
- [x] Branch off the redesign branch                                                                 
- [x] Check out our [styleguide](https://staging-odin-project.herokuapp.com/styleguide)
- [x] When you are submitting your pull request for this task please ensure the base branch you want to merge into is the redesign branch

**Comment by leosoaivan** [comment]
You know what, I'm gonna jump on this. Worst thing that could happen is I learn something :).

**Comment by leosoaivan** [comment]
For the mobile view, are we looking to have the elements stack vertically within each card?

**Comment by KevinMulhern** [comment]
Yeah I think so @leosoaivan

**Comment by leosoaivan** [comment]
I'm messing around Bootstrap for the stacking. Another question, though: 

> Include **job title** beside name, not bold

What does that refer to?

**Comment by KevinMulhern** [comment]
These success stories will probably mostly come from people who have gotten jobs after Odin. so where the name is no, we will have something like this:

> Leo - CTO
