### ISSUE TITLE
Redesign: Remove the padding from FAQ accordion 

### ISSUE THREAD

**Issue by KevinMulhern** [TheOdinProject/theodinproject#579]
This task is to remove the 6em of padding from the Accordion on the [faq](https://staging-odin-project.herokuapp.com/faq?ref=homenav) page

### Working on this task

- [x] If you want to work on this task, please claim it by commenting below   
- [ ] Branch off the redesign branch                                                                 
- [ ] Check out our [styleguide](https://staging-odin-project.herokuapp.com/styleguide)
- [ ] When you are submitting your pull request for this task please ensure the base branch you want to merge into is the redesign branch  

**Note**
* Please use the [contributing guide](https://github.com/TheOdinProject/theodinproject/wiki/Contributing-Guide) to get the app running on your local machine if you haven't already.
* Please ignore the failing tests, all of the UI changes have broken many of the tests. We will be fixing these later.

**Comment by buoyantair** [comment]
I would like to try this, I'm not good at it but it doesn't hurt to try and learn. :)

**Comment by buoyantair** [comment]
I think I worked it out, https://github.com/TheOdinProject/theodinproject/pull/580

**Comment by arun1595** [comment]
Fixed in #584
