### ISSUE TITLE
Redesign: Help us come up with a new slogan for the home page

### ISSUE THREAD

**Issue by KevinMulhern** [TheOdinProject/theodinproject#588]
Under the heading on the homepage we have the following text: 

"Stop wasting time...  Here's what you need to know."

This is a bit 💩 so we want to replace it with something better. @davidchappy has spent sometime putting a few together. These are are in the comments below. Please vote on the heading you like best by reacting to it with a 👍

**Comment by davidchappy** [comment]
Headline: Become a Web Developer for Free
Subheading: Join the world's only open source full stack training program.

**Comment by davidchappy** [comment]
Headline: Want to Become a Web Developer? 
Subheading: This is your complete free path for learning all you need to know.

**Comment by davidchappy** [comment]
Headline: Ready to Become a Web Developer?
Subheading: Our free curriculum gives you a complete learning path. Our open source community will help you complete it.

**Comment by davidchappy** [comment]
Headline: Your Career in Web Development is now (OR "starts here")
Subheading: Our full stack curriculum is free and supported by a passionate open source community. What are you waiting for?

**Comment by UnkyKong** [comment]
Headline: Ready to Become a Web Developer?
Subheading: Our free curriculum gives you a complete learning path. Our open source community will help you complete it.👍🏻

**Comment by davidchappy** [comment]
@UnkyKong thanks for the vote! Can you react with a thumbs up on my comment above instead of adding a new comment? Thanks.

**Comment by hosghf** [comment]
don't wast your time, become a fullstack web developer for free.
