### ISSUE TITLE
Redesign: Create a user avatar and drop down on the navbar for logged in users 

### ISSUE THREAD

**Issue by KevinMulhern** [TheOdinProject/theodinproject#590]
When a user is logged in the right hand side of the nav links should contain a clickable user avatar. When the avatar is clicked it should display a drop down menu as shown in the screen shot below.

**Important**
This isn't a beginner issue, only pick it up if you think you can do it please.

### Working on this task

- [ ] If you want to work on this task, please claim it by commenting below   
- [ ] Branch off the redesign branch                                                                 
- [ ] Check out our [styleguide](https://staging-odin-project.herokuapp.com/styleguide)
- [ ] When you are submitting your pull request for this task please ensure the base branch you want to merge into is the redesign branch  

**Note**
* Please use the [contributing guide](https://github.com/TheOdinProject/theodinproject/wiki/Contributing-Guide) to get the app running on your local machine if you haven't already.
* Please ignore the failing tests, all of the UI changes have broken many of the tests. We will be fixing these later.

If you have any questions or need clarification about anything related to this task please contact the maintainers in our [contributing channel on Gitter](https://gitter.im/TheOdinProject/Contributing)

Mock up of the navbar
<img width="463" alt="screen shot 2017-05-13 at 11 23 08" src="https://cloud.githubusercontent.com/assets/7963776/26024706/e80747a2-37ce-11e7-8393-ff22ea2ce178.png">

**Comment by 105ron** [comment]
Has PR? 😶

**Comment by KevinMulhern** [comment]
I removed that label lol, I selected by accident 🙈

**Comment by 105ron** [comment]
I could take this if no one else wants it. Is the mobile version any different?

**Comment by KevinMulhern** [comment]
We haven't really designed the mobile version yet, this is something we will have to bring up at the next review. For now lets collapse the items in the drop down into the mobile drop down when its on mobile.

**Comment by KevinMulhern** [comment]
Thanks for taking this one on @105ron 🎉
