### ISSUE TITLE
Redesign: Remove text from course page

### ISSUE THREAD

**Issue by KevinMulhern** [TheOdinProject/theodinproject#592]
This small task is to remove the text "Lessons" from the [course page](https://staging-odin-project.herokuapp.com/courses/web-development-101). This text is located right above the first section card in the course page as shown in the screenshot below.

### Working on this task

- [ ] If you want to work on this task, please claim it by commenting below   
- [ ] Branch off the redesign branch                                                                 
- [ ] Check out our [styleguide](https://staging-odin-project.herokuapp.com/styleguide)
- [ ] When you are submitting your pull request for this task please ensure the base branch you want to merge into is the redesign branch  

**Note**
* Please use the [contributing guide](https://github.com/TheOdinProject/theodinproject/wiki/Contributing-Guide) to get the app running on your local machine if you haven't already.
* Please ignore the failing tests, all of the UI changes have broken many of the tests. We will be fixing these later.

If you have any questions or need clarification about anything related to this task please contact the maintainers in our [contributing channel on Gitter](https://gitter.im/TheOdinProject/Contributing)

<img width="1136" alt="screen shot 2017-06-06 at 21 37 09" src="https://user-images.githubusercontent.com/7963776/26850782-a56e8654-4b00-11e7-8892-0bb70bd194b4.png">

**Comment by arcanck** [comment]
Hi!
I want to work on it.
