### ISSUE TITLE
Redesign: Add contact email to the contact us section of the about page

### ISSUE THREAD

**Issue by KevinMulhern** [TheOdinProject/theodinproject#594]
This task is to add the following to the text in the contact us section on the [about page](https://staging-odin-project.herokuapp.com/about?ref=homenav)

This is what the text should look like when you're finished with this issue:
"Connect with our friendly community on gitter, a chat and networking platform or send us an email contact@theodinproject.com"

### Working on this task

- [ ] If you want to work on this task, please claim it by commenting below   
- [ ] Branch off the redesign branch                                                                 
- [ ] Check out our [styleguide](https://staging-odin-project.herokuapp.com/styleguide)
- [ ] When you are submitting your pull request for this task please ensure the base branch you want to merge into is the redesign branch  

**Note**
* Please use the [contributing guide](https://github.com/TheOdinProject/theodinproject/wiki/Contributing-Guide) to get the app running on your local machine if you haven't already.
* Please ignore the failing tests, all of the UI changes have broken many of the tests. We will be fixing these later.

If you have any questions or need clarification about anything related to this task please contact the maintainers in our [contributing channel on Gitter](https://gitter.im/TheOdinProject/Contributing)

This is the section of the page where the text is located, for reference.
<img width="1164" alt="screen shot 2017-06-07 at 19 17 30" src="https://user-images.githubusercontent.com/7963776/26894342-02edfde0-4bb6-11e7-8b4c-d35b45f5e190.png">

**Comment by Rena-Ryumae** [comment]
Hi, @KevinMulhern 

I have never been a part of an open source project before and I would like to get involved!

Can I take this??
Thanks!

**Comment by KevinMulhern** [comment]
Hey @Rena-Ryumae, its all yours 😄 thank you for helping us.

**Comment by KevinMulhern** [comment]
Hey @Rena-Ryumae, just checking in 😄 how are you getting on with this? need any help?

**Comment by KevinMulhern** [comment]
:|

**Comment by KevinMulhern** [comment]
This has been done https://github.com/TheOdinProject/theodinproject/pull/609

Thanks for replying @Rena-Ryumae :|
