### ISSUE TITLE
Redesign: FAQ page tweaks

### ISSUE THREAD

**Issue by KevinMulhern** [TheOdinProject/theodinproject#595]
This task is to change the text and remove some unneeded elements from the FAQ accordion on our [FAQ page](https://staging-odin-project.herokuapp.com/faq?ref=homenav)

Tasks
* Remove the first paragraph on the "What technologies does The Odin Project teach?" accordion item. The paragraph about the Intro to Web Development course.
* Change the last sentence of the "Is The Odin Project free" accordion item to "To find out how you can help us, please visit our how to contribute page" make the "contribute page" a link to our contributing page.
* Remove the "When do I pay" accordion item
* Remove the how will TOP become sustainable item 
* Replace the contact us page link in the last accordion item with our contact email address: contact@theodinproject.com

### Working on this task

- [ ] If you want to work on this task, please claim it by commenting below   
- [ ] Branch off the redesign branch                                                                 
- [ ] Check out our [styleguide](https://staging-odin-project.herokuapp.com/styleguide)
- [ ] When you are submitting your pull request for this task please ensure the base branch you want to merge into is the redesign branch  

**Note**
* Please use the [contributing guide](https://github.com/TheOdinProject/theodinproject/wiki/Contributing-Guide) to get the app running on your local machine if you haven't already.
* Please ignore the failing tests, all of the UI changes have broken many of the tests. We will be fixing these later.

If you have any questions or need clarification about anything related to this task please contact the maintainers in our [contributing channel on Gitter](https://gitter.im/TheOdinProject/Contributing)

**Comment by mysteryihs** [comment]
Hey Kevin, I'll take this one, thanks!

**Comment by KevinMulhern** [comment]
Thanks @mysteryihs 😄

**Comment by codyloyd** [comment]
@KevinMulhern I didn't look to see if @mysteryihs's PR finished off this issue, so I'll leave you to close it if it did.
