### ISSUE TITLE
Redesign: Add a terms of use link above the sign up buttons

### ISSUE THREAD

**Issue by KevinMulhern** [TheOdinProject/theodinproject#596]
We need to protect ourselves by ensuring that users are aware that we have a standard terms of use that they agree to by signing up to the site.

This task is to add the following text above the sign up buttons on our [sign up page](https://staging-odin-project.herokuapp.com/sign_up?ref=homenav)

"By signing up, you agree to our terms of use"

Make this text a link to our terms of use page https://staging-odin-project.herokuapp.com/tou

### Working on this task

- [ ] If you want to work on this task, please claim it by commenting below   
- [ ] Branch off the redesign branch                                                                 
- [ ] Check out our [styleguide](https://staging-odin-project.herokuapp.com/styleguide)
- [ ] When you are submitting your pull request for this task please ensure the base branch you want to merge into is the redesign branch  

**Note**
* Please use the [contributing guide](https://github.com/TheOdinProject/theodinproject/wiki/Contributing-Guide) to get the app running on your local machine if you haven't already.
* Please ignore the failing tests, all of the UI changes have broken many of the tests. We will be fixing these later.

If you have any questions or need clarification about anything related to this task please contact the maintainers in our [contributing channel on Gitter](https://gitter.im/TheOdinProject/Contributing)

Screen shot of the buttons the link should be above:
<img width="564" alt="screen shot 2017-06-07 at 19 35 36" src="https://user-images.githubusercontent.com/7963776/26895142-8206c2e0-4bb8-11e7-987e-516058d24c4e.png">

**Comment by arcanck** [comment]
I want to work on it.

**Comment by KevinMulhern** [comment]
Its all yours @arcanck, thank you 😄
