### ISSUE TITLE
Redesign: change styles of dropdown menu on avatar of logged in users

### ISSUE THREAD

**Issue by KevinMulhern** [TheOdinProject/theodinproject#615]
This task is to change the styles of the dropdown menu that appears when you click the users avatar in the navbar.

Currently it is using the default bootstrap styles, we would like it to look like the cards we use throughout the site. See [the course cards on the curriculum page](https://staging-odin-project.herokuapp.com/courses?ref=homenav) for an idea of what the drop down should look like.

This is not just a matter of applying the current `.card-main` class we use everywhere else to the dropdown as that seems to mess up the positioning in the navbar. Creating a new class for the drop down is probably required.

### Working on this task

- [ ] If you want to work on this task, please claim it by commenting below   
- [ ] Branch off the redesign branch                                                                 
- [ ] Check out our [styleguide](https://staging-odin-project.herokuapp.com/styleguide)
- [ ] When you are submitting your pull request for this task please ensure the base branch you want to merge into is the redesign branch  

**Note**
* Please use the [contributing guide](https://github.com/TheOdinProject/theodinproject/wiki/Contributing-Guide) to get the app running on your local machine if you haven't already.
* Please ignore the failing tests, all of the UI changes have broken many of the tests. We will be fixing these later.

If you have any questions or need clarification about anything related to this task please contact the maintainers in our [contributing channel on Gitter](https://gitter.im/TheOdinProject/Contributing)

Screen shot of the dropdown currently
<img width="239" alt="screen shot 2017-06-29 at 18 45 52" src="https://user-images.githubusercontent.com/7963776/27702453-0e2671ea-5cfc-11e7-85f3-ec9ed03148d9.png">

**Comment by jcgalbano** [comment]
Greetings! Dibs on this issue. I'll start working on it asap

**Comment by KevinMulhern** [comment]
Thanks @jcgalbano, looking forward to your pull request 😄

**Comment by jcgalbano** [comment]
Hello I would just like to hear your opinion about this before i make a pull request. Is this all right? Or did I misunderstood/overlooked something?

<img width="397" alt="screen shot 2017-07-05 at 8 55 48 am" src="https://user-images.githubusercontent.com/15366277/27845235-cf0c6d58-615f-11e7-9b9a-1d7a8fea8ea2.png">

**Comment by CouchofTomato** [comment]
Hi @jcgalbano,

It'll be easier to review if you create the pull request. You can then commit any further changes afterwards.

**Comment by KevinMulhern** [comment]
@jcgalbano I agree with @CouchofTomato it would be easier to review with a pull request. From the screen shot you've provided, it doesn't look quite right though. The outer edges of the card should be the same as what we've got for the course cards on [this page](https://staging-odin-project.herokuapp.com/courses?ref=homenav)

**Comment by jcgalbano** [comment]
I see that's what you meant. I made a recent pull request and changed the outer edges of the dropdown, thanks!
