### ISSUE TITLE
Redesign: Terms of use page tweaks

### ISSUE THREAD

**Issue by KevinMulhern** [TheOdinProject/theodinproject#616]
There are a couple of finishing touches we need to make to the [terms of use page](https://staging-odin-project.herokuapp.com/terms_of_use) on the site

* Apply `color: $primary;` to all headings on the site
* Remove the `StaticPagesController` class from the top level div and replace it with the `gradient` class instead.

### Working on this task

- [ ] If you want to work on this task, please claim it by commenting below   
- [ ] Branch off the redesign branch                                                                 
- [ ] Check out our [styleguide](https://staging-odin-project.herokuapp.com/styleguide)
- [ ] When you are submitting your pull request for this task please ensure the base branch you want to merge into is the redesign branch  

**Note**
* Please use the [contributing guide](https://github.com/TheOdinProject/theodinproject/wiki/Contributing-Guide) to get the app running on your local machine if you haven't already.
* Please ignore the failing tests, all of the UI changes have broken many of the tests. We will be fixing these later.

If you have any questions or need clarification about anything related to this task please contact the maintainers in our [contributing channel on Gitter](https://gitter.im/TheOdinProject/Contributing)

**Comment by mindovermiles262** [comment]
I got this

**Comment by KevinMulhern** [comment]
Thanks @mindovermiles262 😄
