### ISSUE TITLE
Redesign: Dashboard tweaks

### ISSUE THREAD

**Issue by KevinMulhern** [TheOdinProject/theodinproject#617]
Tweaks for the dashboard page, you need to be logged in to access the page. You will be redirected to it as soon as you login.

Tasks include:

* Change the avatar on the page to use the same one thats in the avatar on the navbar
* Make the avatar a circle
* Make the users name go on the line below "welcome back"
* Link to the settings page instead of displaying "Not specified" when a user doesn't have a learning goal set.
* Change the "Start now" buttons in the courses list to use the green color we use for other call to action buttons throughout the site.

### Working on this task

- [ ] If you want to work on this task, please claim it by commenting below   
- [ ] Branch off the redesign branch                                                                 
- [ ] Check out our [styleguide](https://staging-odin-project.herokuapp.com/styleguide)
- [ ] When you are submitting your pull request for this task please ensure the base branch you want to merge into is the redesign branch  

**Note**
* Please use the [contributing guide](https://github.com/TheOdinProject/theodinproject/wiki/Contributing-Guide) to get the app running on your local machine if you haven't already.
* Please ignore the failing tests, all of the UI changes have broken many of the tests. We will be fixing these later.

If you have any questions or need clarification about anything related to this task please contact the maintainers in our [contributing channel on Gitter](https://gitter.im/TheOdinProject/Contributing)

**Comment by renziver** [comment]
I want to work on this issue

**Comment by arun1595** [comment]
@renziver Cool, it is all yours. Thanks for taking up the issue :smile:

**Comment by renziver** [comment]
<img width="1263" alt="screen shot 2017-07-04 at 7 27 03 am" src="https://user-images.githubusercontent.com/13497174/27810361-d302f032-608b-11e7-89a8-3e15b14d8a7a.png">

can anyone help me out why am I getting these errors whenever I click a link on the different steps in short courses?

**Comment by KevinMulhern** [comment]
Hi @renziver, the lesson content needs to be imported from git.

1. First you have the set up a github api token, thats described [here](https://github.com/TheOdinProject/theodinproject/wiki/Linux-Installation-Guide) under the section titled "Get a Github API Token"

2. Next you have to import the lesson content with this command from your command line `rake curriculum:update_content`
