### ISSUE TITLE
Redesign: Success Stories Page Tweaks

### ISSUE THREAD

**Issue by KevinMulhern** [TheOdinProject/theodinproject#645]
This ticket involves a slight restructuring of the success story cards on the [success stories page](https://staging-odin-project.herokuapp.com/success_stories)

Essentially we now want each card to have two rows, the top row will contain the persons image, name and occupation. The second row will contain the main text of the success story.

To achieve this:

- [x] Divide the card into two rows
- [x] Reduce the size of the persons image
- [x] Ensure the main text is flush under the avatar.

Additional fixes
- [x] on mobile put the persons occupation under their name (change the span that contains thier occupation to `display: block`)

---
### Working on this task

- [ ] If you want to work on this task, please claim it by commenting below   
- [ ] Branch off the redesign branch                                                                 
- [ ] Check out our [styleguide](https://staging-odin-project.herokuapp.com/styleguide)
- [ ] When you are submitting your pull request for this task please ensure the base branch you want to merge into is the redesign branch  

**Note**
* Please use the [contributing guide](https://github.com/TheOdinProject/theodinproject/wiki/Contributing-Guide) to get the app running on your local machine if you haven't already.
* Please ignore the failing tests, all of the UI changes have broken many of the tests. We will be fixing these later.

If you have any questions or need clarification about anything related to this task please contact the maintainers in our [contributing channel on Gitter](https://gitter.im/TheOdinProject/Contributing)

**Comment by leosoaivan** [comment]
I think I can handle this!

**Comment by KevinMulhern** [comment]
Thanks @leosoaivan 😄

**Comment by KevinMulhern** [comment]
Hey @leosoaivan, just checking in 😄 any updated on this?
