### ISSUE TITLE
Redesign: Dashboard Page Tweaks

### ISSUE THREAD

**Issue by KevinMulhern** [TheOdinProject/theodinproject#646]
Tweaks for the [dashboard](https://staging-odin-project.herokuapp.com/dashboard)

We want to restructure the profile card at the top of the dashboard page to reduce its height. To do this we will align everything on the profile card horizontally.

- [x] remove the text "Welcome Back"
- [x] horizontally align the users name with the their avatar 
- [x] remove the "Learning Goal" title
- [x] horizontally align the text "Set a learning goal in your settings." with the users avatar and name

Having a mock up of this would be more ideal than describing it, if you have any trouble understanding what way the profile card should be structured please reach out to us in our [contributing room on Gitter](https://gitter.im/TheOdinProject/Contributing)

---
### Working on this task

- [ ] If you want to work on this task, please claim it by commenting below   
- [ ] Branch off the redesign branch                                                                 
- [ ] Check out our [styleguide](https://staging-odin-project.herokuapp.com/styleguide)
- [ ] When you are submitting your pull request for this task please ensure the base branch you want to merge into is the redesign branch  

**Note**
* Please use the [contributing guide](https://github.com/TheOdinProject/theodinproject/wiki/Contributing-Guide) to get the app running on your local machine if you haven't already.
* Please ignore the failing tests, all of the UI changes have broken many of the tests. We will be fixing these later.

If you have any questions or need clarification about anything related to this task please contact the maintainers in our [contributing channel on Gitter](https://gitter.im/TheOdinProject/Contributing)

**Comment by davidchappy** [comment]
I can do this @KevinMulhern.

**Comment by KevinMulhern** [comment]
Thanks @davidchappy 🎉

**Comment by davidchappy** [comment]
You can check the changes here: https://limitless-headland-70035.herokuapp.com/dashboard

**Comment by KevinMulhern** [comment]
That looks perfect @davidchappy 😍
