### ISSUE TITLE
Redesign: Google Oauth

### ISSUE THREAD

**Issue by KevinMulhern** [TheOdinProject/theodinproject#656]
We need to do some more leg work to integrate google oauth fully

**Questions that need answered**
- [x] Find out if @adachiu is happy with the design and color
- [x] Investigate if its worth adding [this functionality](https://github.com/omniauth/omniauth/wiki/Managing-Multiple-Providers) for multiple oauth providers.

Development tasks
- [x] Refactor the omniauth callbacks controller to extract the duplication between the two omniauth methods and combine them into one method

Misc Tasks
- [x] Set up google api credentials on the production server
- [ ] Add google omniauth as optional task in the set up wiki guides
- [x] We need a 120 x 120 Odin logo image to go in the credentials screen when a user is redirected to google to verify they want to sign up to Odin with oauth.

**Comment by BryanSingh** [comment]
Who is working on this?

**Comment by KevinMulhern** [comment]
Hey @BryanSingh 👋 

It's all mostly been done, we just need to add an optional step to the [installation guides](https://github.com/TheOdinProject/theodinproject/wiki) to set it up locally. Thats up for grabs if you'd like to work on it?

**Comment by BryanSingh** [comment]
@KevinMulhern 

You mean to write the docs for setting up the Google OAuth locally, or setting up the entire application locally? (I am open to both, just wanted to clarify which one you meant!)

**Comment by KevinMulhern** [comment]
No worries @BryanSingh, just setting up Google OAuth locally. We have instructions for the everything else already in the guides 😄

**Comment by Deetss** [comment]
I'd like to take over the Google OAuth task

**Comment by KevinMulhern** [comment]
Hey @Deetss, thanks for offering to take this on 😄   

Theres not much left to do on this issue. The only thing left to close this issue is documentation on the installation guides for the app.

**Comment by mindovermiles262** [comment]
9 months later - has anyone written this in the guides yet?

**Comment by KevinMulhern** [comment]
@mindovermiles262 nope 😅

**Comment by morrowdavidson** [comment]
Updated OSX install wiki, let me know if this looks good and I'll update the other.

**Comment by KevinMulhern** [comment]
@morrowdavidson looks good to me 😄

**Comment by morrowdavidson** [comment]
Just a few months later...  Done! :) https://github.com/TheOdinProject/theodinproject/wiki/Linux-Installation-Guide#setting-up-google-oauth-optional

**Comment by KevinMulhern** [comment]
Thanks @morrowdavidson, very much appreciated
