### ISSUE TITLE
Redesign: Lesson page Nav

### ISSUE THREAD

**Issue by KevinMulhern** [TheOdinProject/theodinproject#662]
This task is to implement a nav on the [lesson page](https://staging-odin-project.herokuapp.com/courses/web-development-101/lessons/how-this-course-will-work) as shown in the mock ups below.

The nav items should be populated with all the lesson content titles, which are all `h3` elements. You may need to look into making the `h3` titles anchors as well for the nav to work. If you have any trouble with this part let us know.

---
### Working on this task

- [ ] If you want to work on this task, please claim it by commenting below   
- [ ] Branch off the redesign branch                                                                 
- [ ] Check out our [styleguide](https://staging-odin-project.herokuapp.com/styleguide)
- [ ] When you are submitting your pull request for this task please ensure the base branch you want to merge into is the redesign branch  

**Note**
* Please use the [contributing guide](https://github.com/TheOdinProject/theodinproject/wiki/Contributing-Guide) to get the app running on your local machine if you haven't already.

If you have any questions or need clarification about anything related to this task please contact the maintainers in our [contributing channel on Gitter](https://gitter.im/TheOdinProject/Contributing)

**Close up of the lesson nav**
![nav-sub](https://user-images.githubusercontent.com/7963776/28942616-f2195b9e-7893-11e7-9f4a-395d054f12b1.png)

**Lesson nav in a lesson page**
![lesson-detail-1](https://user-images.githubusercontent.com/7963776/28942631-022329de-7894-11e7-9b2a-f23aab22a93c.png)

**Comment by KevinMulhern** [comment]
Hey @arun1595, any progress on this?

**Comment by arun1595** [comment]
@KevinMulhern Yeah, I am on it. I'll try to make some progress today. Will keep you posted :smile:

**Comment by arun1595** [comment]
@KevinMulhern Ah, it has been a while since I made any progress on this issue. Just letting you know, I am on it :)

**Comment by AkshayRameshAppDEV** [comment]
@KevinMulhern  Hey Kevin Mulhern. I would like to work on implementing the Lesson Page Nav, can I work on it ?
Thank You!
