### ISSUE TITLE
Redesign: Footer Social Links Hover State

### ISSUE THREAD

**Issue by KevinMulhern** [TheOdinProject/theodinproject#663]
This task is to implement a black hover state on the social links in the footer as shown in the mock up below.

This will be trivial for most of the icons as they come from font awesome and are therefore a font. The gitter icon on the other hand is an svg as font awesome doesn't have a gitter icon.

Svg's can have hover states which change its color though.

---
### Working on this task

- [x] If you want to work on this task, please claim it by commenting below   
- [x] Branch off the redesign branch                                                                 
- [x] Check out our [styleguide](https://staging-odin-project.herokuapp.com/styleguide)
- [x] When you are submitting your pull request for this task please ensure the base branch you want to merge into is the redesign branch  

**Note**
* Please use the [contributing guide](https://github.com/TheOdinProject/theodinproject/wiki/Contributing-Guide) to get the app running on your local machine if you haven't already.

If you have any questions or need clarification about anything related to this task please contact the maintainers in our [contributing channel on Gitter](https://gitter.im/TheOdinProject/Contributing)

**Mock Up**
![tablet-footer-hover](https://user-images.githubusercontent.com/7963776/28942829-a3bc1634-7894-11e7-9eda-01cfc14bd425.png)

**Comment by mindovermiles262** [comment]
I will complete this one too while I'm at it
