### ISSUE TITLE
Redesign: Hover State for User Drop Down in the Navbar

### ISSUE THREAD

**Issue by KevinMulhern** [TheOdinProject/theodinproject#664]
This task is to implement a black hover state on the links in the user drop down on the navbar as shown in the mock up below. This includes both the text and the icon in each link.

The icons are svgs which makes it a little tricker to apply a hover state on them.

---
### Working on this task

- [x] If you want to work on this task, please claim it by commenting below   
- [x] Branch off the redesign branch                                                                 
- [x] Check out our [styleguide](https://staging-odin-project.herokuapp.com/styleguide)
- [x] When you are submitting your pull request for this task please ensure the base branch you want to merge into is the redesign branch  

**Note**
* Please use the [contributing guide](https://github.com/TheOdinProject/theodinproject/wiki/Contributing-Guide) to get the app running on your local machine if you haven't already.

If you have any questions or need clarification about anything related to this task please contact the maintainers in our [contributing channel on Gitter](https://gitter.im/TheOdinProject/Contributing)

**Mock Up**
![nav-dropdown-hover](https://user-images.githubusercontent.com/7963776/28942998-24ebdb22-7895-11e7-9d08-af592a0d562f.png)

**Comment by mindovermiles262** [comment]
I will cover this one with #668
