### ISSUE TITLE
Redesign: Dashboard tweaks

### ISSUE THREAD

**Issue by KevinMulhern** [TheOdinProject/theodinproject#667]
This task is to fix some issues raised at the last review:

- Title “dashboard” should be capitalized "Dashboard"
- When the learning goal is too long it is overflowing from the profile card, contain it within the card
- Set a validation on the learning goal in the user model to ensure it doesn't go over 100 characters

---
### Working on this task

- [x] If you want to work on this task, please claim it by commenting below   
- [x] Branch off the redesign branch                                                                 
- [x] Check out our [styleguide](https://staging-odin-project.herokuapp.com/styleguide)
- [x] When you are submitting your pull request for this task please ensure the base branch you want to merge into is the redesign branch  

**Note**
* Please use the [contributing guide](https://github.com/TheOdinProject/theodinproject/wiki/Contributing-Guide) to get the app running on your local machine if you haven't already.

If you have any questions or need clarification about anything related to this task please contact the maintainers in our [contributing channel on Gitter](https://gitter.im/TheOdinProject/Contributing)

**Comment by davidchappy** [comment]
I can do this @KevinMulhern.

**Comment by KevinMulhern** [comment]
Thanks @davidchappy 😄
