### ISSUE TITLE
Redesign: Button tweaks

### ISSUE THREAD

**Issue by KevinMulhern** [TheOdinProject/theodinproject#668]
This task is to fix some issues raised at the last review with buttons on the site

- The cursor is not changing when you hover over a button, change this to a pointer on a button hover state.
- Convert omniauth buttons on the sign in and sign up page to use button component

---
### Working on this task

- [x] If you want to work on this task, please claim it by commenting below   
- [x] Branch off the redesign branch                                                                 
- [x] Check out our [styleguide](https://staging-odin-project.herokuapp.com/styleguide)
- [x] When you are submitting your pull request for this task please ensure the base branch you want to merge into is the redesign branch  

**Note**
* Please use the [contributing guide](https://github.com/TheOdinProject/theodinproject/wiki/Contributing-Guide) to get the app running on your local machine if you haven't already.

If you have any questions or need clarification about anything related to this task please contact the maintainers in our [contributing channel on Gitter](https://gitter.im/TheOdinProject/Contributing)

**Comment by mindovermiles262** [comment]
I can do this

**Comment by KevinMulhern** [comment]
🎉 Thanks @mindovermiles262
