### ISSUE TITLE
Redesign: Help us find problems with lesson content

### ISSUE THREAD

**Issue by KevinMulhern** [TheOdinProject/theodinproject#671]
We have a lot of different kinds of lesson content throughout the site, We need help to find problems due to the amount of content we have. 

I'm going to use this issue as a catch all for issues with lesson content that exists at the moment. If you find any issues with lesson content can you please comment about them on this issue, please include a screen shot of the problem as well 😄 

**Issues to fix**
- [ ] Format h4's
- [x] multiline code blocks need styled - use prism?

**Questions that need answered**
* should we underline links on hover state?
* should we restyle italic text?

**Comment by davidchappy** [comment]
@KevinMulhern Here's the process I'm following for proofing lesson content if anyone wants to do something similar:
1. Claim a section (I've got [Rails](https://staging-odin-project.herokuapp.com/courses/ruby-on-rails)).
2. Have a [spell checker](https://chrome.google.com/webstore/detail/spell-checker-for-chrome/jfpdnkkdgghlpdgldicfgnnnkhdfhocg?hl=en) on.
3. Skim content, focusing on grammar/spelling issues (Odin uses a casual English style so many can be ignored). 
4. Check every link. 
5. Make changes in your forked curriculum and send a PR.

**Comment by KevinMulhern** [comment]
I'm on Web Development 101

**Comment by JonathanYiv** [comment]
I got Introduction to Web Development.
One question: What is seeds.rb?

**Comment by KevinMulhern** [comment]
Hey @JonathanYiv, intro to web dev won't be included in the re-designed site. We decided it was best to get users into the thick of the action sooner in web dev 101.

`Seeds.rb` is where the courses, sections and lessons are created in the db. After running the seed file the content for lessons are imported from github.

**Comment by JonathanYiv** [comment]
Ah, I see, so he was referring to that to ensure the description also is free of error. Thanks.

and wow, a whole section gone

**Comment by JonathanYiv** [comment]
Also got HTML5 and CSS3

**Comment by JonathanYiv** [comment]
The Javascript section had links that were dead since 2015.. yikes

**Comment by JonathanYiv** [comment]
Would you like me to parse WD101 to help reduce your load?

**Comment by KevinMulhern** [comment]
Hey @JonathanYiv, If you don't mind I would be very grateful 😄

**Comment by JonathanYiv** [comment]
Done. What do you mean by "Format h4s?"

**Comment by KevinMulhern** [comment]
ahh don't worry about that part, we need a proper plan for what we are going to do with the lesson content typography and hierarchy. @adachiu is working on that. Just do what you did with the javascript course 😄

**Comment by KevinMulhern** [comment]
I'm going to close this and make a more appropriate issue for it the typography.
