### ISSUE TITLE
Redesign: Sign up Form Validations

### ISSUE THREAD

**Issue by KevinMulhern** [TheOdinProject/theodinproject#675]
We already have error message that appear when the user submits the form and there are problems with one or more of the fields. 

It would be awesome to have more helpful validations on the [sign up form]() though, so users can know if they have made a mistake before submitting the form.

This Task is to add the following validations to the sign up form:

- [ ] username must be a minimum of 4 characters and a maximum of 20 characters
- [ ] validate the format of the email
- [ ] password must be at least 6 characters long
- [ ] validate the password and password confirmation match

We already have some basic styles in place for errors on this page, so please use those. As for placement of the error messages, please see the screen shot below:

**Error Message Placement**
<img width="866" alt="screen shot 2017-08-06 at 17 51 24" src="https://user-images.githubusercontent.com/7963776/29005305-12aebc08-7ad0-11e7-93c3-fae182990b91.png">

---
### Working on this task

- [ ] If you want to work on this task, please claim it by commenting below   
- [ ] Branch off the redesign branch                                                                 
- [ ] Check out our [styleguide](https://staging-odin-project.herokuapp.com/styleguide)
- [ ] When you are submitting your pull request for this task please ensure the base branch you want to merge into is the redesign branch  

**Note**
* Please use the [contributing guide](https://github.com/TheOdinProject/theodinproject/wiki/Contributing-Guide) to get the app running on your local machine if you haven't already.

If you have any questions or need clarification about anything related to this task please contact the maintainers in our [contributing channel on Gitter](https://gitter.im/TheOdinProject/Contributing)

**Comment by CouchofTomato** [comment]
Stand back. I got this
