### ISSUE TITLE
Redesign: Fix javascript error with the user dropdown menu

### ISSUE THREAD

**Issue by KevinMulhern** [TheOdinProject/theodinproject#679]
If you open the js console on the redesign branch or on [staging](https://staging-odin-project.herokuapp.com/) you will see a js error. This error seems to come from the user dropdown menu not being found when it isn't open.

The task for this issue is to fix this bug.

---
### Working on this task

- [ ] If you want to work on this task, please claim it by commenting below   
- [ ] Branch off the redesign branch                                                                 
- [ ] Check out our [styleguide](https://staging-odin-project.herokuapp.com/styleguide)
- [ ] When you are submitting your pull request for this task please ensure the base branch you want to merge into is the redesign branch  

**Note**
* Please use the [contributing guide](https://github.com/TheOdinProject/theodinproject/wiki/Contributing-Guide) to get the app running on your local machine if you haven't already.

If you have any questions or need clarification about anything related to this task please contact the maintainers in our [contributing channel on Gitter](https://gitter.im/TheOdinProject/Contributing)

**Comment by CouchofTomato** [comment]
The error comes from the navbar.js file when var userDropdown = document.querySelector('.dropdown') returns null. I had a look and can't find the dropdown selector anywhere. Was it required in a previous iteration of the user dropdown before it was refactored perhaps?

I tried commenting out the offending line and the dropdown still seems to work but just wondered if you had any idea what that dropdown class is for before I remove and submit a pull request?

**Comment by KevinMulhern** [comment]
Thanks for taking a look at this one @CouchofTomato, @mindovermiles262 was working in this area recently so he might have a better idea. I'll take a look at it tonight. If you can't find the class after doing a global search for it, it's probably safe to remove though.

**Comment by KevinMulhern** [comment]
I've had a look at this, its only happening when the user is logged out. The dropdown isn't in the navbar when the user is logged out so it can't find it. I think wrapping the event listeners in a conditional statement to only run when the dropdown is not null should fix it.

**Comment by CouchofTomato** [comment]
Bah, I should have read this first after debugging the issue this morning.

I've done a fix and will create a pull request
