### ISSUE TITLE
Redesign: Validation On the Forgot Password Page

### ISSUE THREAD

**Issue by KevinMulhern** [TheOdinProject/theodinproject#692]
Currently when you enter an email address that does not exist in our database on the [forgot password page](https://staging-odin-project.herokuapp.com/users/password) the page will just reload with no error displayed.

We want an error message to display in this scenario. This should be a quick and easy change to implement. We do the same thing on the sign up form, take a look at the view for the sign up form to see how we are implementing errors returned by rails.

---
### Working on this task

- [ ] If you want to work on this task, please claim it by commenting below   
- [ ] Branch off the redesign branch                                                                 
- [ ] Check out our [styleguide](https://staging-odin-project.herokuapp.com/styleguide)
- [ ] When you are submitting your pull request for this task please ensure the base branch you want to merge into is the redesign branch  

**Note**
* Please use the [contributing guide](https://github.com/TheOdinProject/theodinproject/wiki/Contributing-Guide) to get the app running on your local machine if you haven't already.

If you have any questions or need clarification about anything related to this task please contact the maintainers in our [contributing channel on Gitter](https://gitter.im/TheOdinProject/Contributing)

**Comment by mindovermiles262** [comment]
I'll work on this

**Comment by KevinMulhern** [comment]
Thanks @mindovermiles262 🎉
