### ISSUE TITLE
Redesign: Stop Users being able to Submit a Form if Errors Exist

### ISSUE THREAD

**Issue by KevinMulhern** [TheOdinProject/theodinproject#693]
A User can still submit a form even if there are errors, this task is to disable the submit button of a form in our `form_validation.js` file if errors exist. We use [validatejs](https://validatejs.org/) for our javascript rendered errors so please check out the documentation for that first as it will probably outline how to do this in there somewhere.

---
### Working on this task

- [ ] If you want to work on this task, please claim it by commenting below   
- [ ] Branch off the redesign branch                                                                 
- [ ] Check out our [styleguide](https://staging-odin-project.herokuapp.com/styleguide)
- [ ] When you are submitting your pull request for this task please ensure the base branch you want to merge into is the redesign branch  

**Note**
* Please use the [contributing guide](https://github.com/TheOdinProject/theodinproject/wiki/Contributing-Guide) to get the app running on your local machine if you haven't already.

If you have any questions or need clarification about anything related to this task please contact the maintainers in our [contributing channel on Gitter](https://gitter.im/TheOdinProject/Contributing)

**Comment by CouchofTomato** [comment]
If anyone wants to work on this some good resources are

https://validatejs.org/ for the documentation
https://validatejs.org/examples.html an example of the form in action
https://github.com/ansman/validate.js/blob/master/examples.html the html and javascript (which is inline in the same file) for the example above. It shows how to cancel the submit and the steps you have to go through. It should point you in the right direction.

**Comment by chari407** [comment]
I am working on this...

**Comment by KevinMulhern** [comment]
Hi @chari407, a majority of the work was done for this one. Sorry I should have updated this issue.

Theres a problem with the user settings form submitting though, would you like to take a look at that?

**Comment by chari407** [comment]
Hi @KevinMulhern , I shall surely get back to you on this. I shall check and will let you know for sure.

**Comment by KevinMulhern** [comment]
Thanks @chari407 😄

**Comment by KevinMulhern** [comment]
I'm going to open a new issue for this @CouchofTomato @chari407
