### ISSUE TITLE
Redesign: Bug with Submitting User Settings Forms

### ISSUE THREAD

**Issue by KevinMulhern** [TheOdinProject/theodinproject#701]
There is currently a problem on the user settings page when the user tries to submit a form. It redirects to the dashboard without updating the user. This is unexpected behaviour as it should not redirect at all.

This bug arose after [this pull request](https://github.com/TheOdinProject/theodinproject/pull/695) which disables the submit button if errors exist on form.

---
### Working on this task

- [ ] If you want to work on this task, please claim it by commenting below   
- [ ] Branch off the redesign branch                                                                 
- [ ] Check out our [styleguide](https://staging-odin-project.herokuapp.com/styleguide)
- [ ] When you are submitting your pull request for this task please ensure the base branch you want to merge into is the redesign branch  

**Note**
* Please use the [contributing guide](https://github.com/TheOdinProject/theodinproject/wiki/Contributing-Guide) to get the app running on your local machine if you haven't already.

If you have any questions or need clarification about anything related to this task please contact the maintainers in our [contributing channel on Gitter](https://gitter.im/TheOdinProject/Contributing)

**Comment by mindovermiles262** [comment]
I can work on this this week
