### ISSUE TITLE
Redesign: Dashboard badge spacing

### ISSUE THREAD

**Issue by adachiu** [TheOdinProject/theodinproject#727]
The title is too close to the badge. Let's use the same layout as this [page](https://staging-odin-project.herokuapp.com/courses) where the lesson number is right underneath the title. This would save horizontal space between the badge and the cta button.

**Issues to fix**
- [ ] Move lesson number to right under the title
- [ ] Add vertical spacing between title and lesson 10px

**Comment by vaughnanton** [comment]
Working on it
