### ISSUE TITLE
Redesign: Title spacing on Course detail page

### ISSUE THREAD

**Issue by adachiu** [TheOdinProject/theodinproject#728]
On course detail pages like this [one](https://staging-odin-project.herokuapp.com/courses/web-development-101), the h1 title is too close to the badge. Let's space it out with margin top 20px. Also update same spacing on media queries for this title under a badge.

**Issues to fix**
- [ ] Add margin top 20px to title
- [ ] Change margin bottom to 4rem
- [ ] Make sure media queries of the title maintain a consistent spacing in relation to the badge

**Comment by vaughnanton** [comment]
On it

**Comment by KevinMulhern** [comment]
I've got this

**Comment by 105ron** [comment]
@KevinMulhern how are you going with this?

**Comment by KevinMulhern** [comment]
@105ron yeah I just did in this one https://github.com/TheOdinProject/theodinproject/pull/748
