### ISSUE TITLE
Redesign: Make Section Headings Anchor Links

### ISSUE THREAD

**Issue by KevinMulhern** [TheOdinProject/theodinproject#731]
This task is to turn the headings of sections on the [course page]() anchor links. This will allow us to link to specific sections in lesson content and beyond.

---
### Working on this task

- [ ] If you want to work on this task, please claim it by commenting below   
- [ ] Branch off the redesign branch                                                                 
- [ ] Check out our [styleguide](https://staging-odin-project.herokuapp.com/styleguide)
- [ ] When you are submitting your pull request for this task please ensure the base branch you want to merge into is the redesign branch  

**Note**
* Please use the [contributing guide](https://github.com/TheOdinProject/theodinproject/wiki/Contributing-Guide) to get the app running on your local machine if you haven't already.

If you have any questions or need clarification about anything related to this task please contact the maintainers in our [contributing channel on Gitter](https://gitter.im/TheOdinProject/Contributing)

**Comment by mindovermiles262** [comment]
I'll do this.

@KevinMulhern  > The link is broken but I assume this is just adding ID tags to the section headings inside each course? So that we can use url searching for the course sections

**Comment by KevinMulhern** [comment]
I think @davidchappy might have picked this up @mindovermiles262

**Comment by davidchappy** [comment]
@mindovermiles262 can take it, no problem, thanks @KevinMulhern

**Comment by KevinMulhern** [comment]
Thanks @davidchappy

**Comment by morrowdavidson** [comment]
I'm working on adding internal links like [MDN docs](https://developer.mozilla.org/en-US/docs/Learn/JavaScript/Building_blocks/Looping_code#Keep_me_in_the_loop) So you can click the heading and it will redirect you to a hash url. Let me know if you think this is worth developing...
![internallink](https://user-images.githubusercontent.com/44884803/52782708-93d93980-3004-11e9-89b0-6781ff45bc11.jpg)
