### ISSUE TITLE
CodeCademy Learn Ruby Broken

### ISSUE THREAD

**Issue by I3uckwheat** [TheOdinProject/theodinproject#732]
It works alright until the "Re-factor Factory" portion. At this point it becomes impossible to solve. Codecademy will not allow correct code to pass and a person has to run it multiple times to see the solution. Sometimes the solution is the same as what was already typed.

**Comment by KevinMulhern** [comment]
Thanks for reporting this @I3uckwheat. Lets wait and see if more people get the same problem before we take any further action.

**Comment by KevinMulhern** [comment]
No other reports on this, but I'll keep an eye on it. Thanks again for reporting it @I3uckwheat
