### ISSUE TITLE
Redesign: Help us to decide how we should show a course has been completed

### ISSUE THREAD

**Issue by KevinMulhern** [TheOdinProject/theodinproject#744]
We thought we would do a bit of a/b testing on this feature. We have two different designs for this at the moment, these are shown in the comments below. 

Vote on the one you like best by reacting to the comment that contains it with a 👍

**Comment by KevinMulhern** [comment]
<img width="734" alt="screen-shot-2017-09-14-at-3 21 58-pm" src="https://user-images.githubusercontent.com/7963776/30504028-875a96ae-9a64-11e7-8f6c-87b1d7cf0414.png">

**Comment by KevinMulhern** [comment]
<img width="882" alt="screen shot 2017-09-15 at 22 19 32" src="https://user-images.githubusercontent.com/7963776/30504036-8d52c068-9a64-11e7-8256-c97ed0d0ab74.png">

**Comment by JonathanYiv** [comment]
The first one by far

**Comment by Deetss** [comment]
The first one looks way better

**Comment by KevinMulhern** [comment]
@JonathanYiv @Deetss can you react to it with a 👍 please 😄

**Comment by AchillesTurtle** [comment]
First one :+1:

**Comment by I3uckwheat** [comment]
I concurr, the first one is much more attractive

**Comment by KevinMulhern** [comment]
Thanks everyone, this was pretty conclusive 😄
