### ISSUE TITLE
Redesign: Badge update

### ISSUE THREAD

**Issue by adachiu** [TheOdinProject/theodinproject#754]
On the dashboard, curriculum and lesson pages, the hover state of the badge shows the interior circle badge. We want to replace that svg with a borderless circle badge.

Keep in mind that we want to maintain the current badge style if the course has not been started yet. In other words, if the course has no progress indicator, then the badge will look the way it is now, like this:
<img width="237" alt="screen shot 2017-09-21 at 11 48 58 pm" src="https://user-images.githubusercontent.com/13413986/30732455-7dcd3322-9f27-11e7-97ba-4ee666fddc80.png">

When there is progress, it currently looks like this:
<img width="135" alt="screen shot 2017-09-21 at 11 36 24 pm" src="https://user-images.githubusercontent.com/13413986/30732152-0283dd84-9f26-11e7-986c-0f5e67d4a463.png">

We want to update that hover state and have the interior show up like this instead.
<img width="312" alt="screen shot 2017-09-21 at 11 42 44 pm" src="https://user-images.githubusercontent.com/13413986/30732293-ae6255ea-9f26-11e7-8f97-bc8c631c3116.png">

All SVG assets could be found here: https://zpl.io/aXY3Kwg
Or download here: [badge-borderless.zip](https://github.com/TheOdinProject/theodinproject/files/1323661/badge-borderless.zip)

---
### Working on this task

- [ ] If you want to work on this task, please claim it by commenting below   
- [ ] Branch off the redesign branch                                                                 
- [ ] Check out our [styleguide](https://staging-odin-project.herokuapp.com/styleguide)
- [ ] When you are submitting your pull request for this task please ensure the base branch you want to merge into is the redesign branch

**Comment by KevinMulhern** [comment]
I've got this
