### ISSUE TITLE
Redesign: Style Welcome Email

### ISSUE THREAD

**Issue by KevinMulhern** [TheOdinProject/theodinproject#767]
The welcome email hasn't gotten any attention during the redesign. It could use a spruce up with styling so it fits in more with the new design of the site. We don't have any mock ups for this at the moment so use your best judgment when styling it, as long as it fits in with the design of the site it will be fine.

---
### Working on this task

- [ ] If you want to work on this task, please claim it by commenting below   
- [ ] Branch off the redesign branch                                                                 
- [ ] Check out our [styleguide](https://staging-odin-project.herokuapp.com/styleguide)
- [ ] When you are submitting your pull request for this task please ensure the base branch you want to merge into is the redesign branch  

**Note**
* Please use the [contributing guide](https://github.com/TheOdinProject/theodinproject/wiki/Contributing-Guide) to get the app running on your local machine if you haven't already.

If you have any questions or need clarification about anything related to this task please contact the maintainers in our [contributing channel on Gitter](https://gitter.im/TheOdinProject/Contributing)

**Comment by 105ron** [comment]
I will take this.

**Comment by KevinMulhern** [comment]
🎉 Thanks @105ron

**Comment by mindovermiles262** [comment]
https://foundation.zurb.com/emails.html
