### ISSUE TITLE
Chat Icon: Click to close

### ISSUE THREAD

**Issue by mindovermiles262** [TheOdinProject/theodinproject#772]
Expected chat icon in lower right corner to toggle chat window. Currently, the icon does not close the chat window if open

**Comment by KevinMulhern** [comment]
Nice spot @mindovermiles262 😄

**Comment by CouchofTomato** [comment]
There is an x in the top right corner that closes it. Do we want to also add the toggle feature?

**Comment by CouchofTomato** [comment]
I believe this issue is now fixed
