### ISSUE TITLE
Login page has incorrect title

### ISSUE THREAD

**Issue by 105ron** [TheOdinProject/theodinproject#780]
On the staging [site](https://staging-odin-project.herokuapp.com/login?ref=homenav) the login page directs you to the U-auth provides with a `Sign up with` instead of `Log in with`.

**Comment by JonathanYiv** [comment]
I would like to battle this issue

**Comment by KevinMulhern** [comment]
Thanks @JonathanYiv 😄

**Comment by merlin2049er** [comment]
Hmm, can I fix this?

**Comment by mindovermiles262** [comment]
@merlin2049er it looks like @JonathanYiv has already claimed this issue

**Comment by JonathanYiv** [comment]
Sorry I took so long. I will try to do this right now.
