### ISSUE TITLE
Course emblem popping out of location

### ISSUE THREAD

**Issue by ayushkamadji** [TheOdinProject/theodinproject#782]
The course emblem is displaced when using a mobile size window. It will go back to normal position after hovering into the element.

![image](https://user-images.githubusercontent.com/8255357/31886889-67950b2c-b820-11e7-8494-abb5c38e1bc0.png)

Reproduce:
1. Open a mobile wide browser window
2. Login to account
3. Go to curriculum page

Broswer build:
Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:56.0) Gecko/20100101 Firefox/56.0
*happens on my android phone as well (also firefox, I can't find the build)

**Comment by ayushkamadji** [comment]
@KevinMulhern I tried this in chrome and it seems to work as intended. I think the issue here is having a position: absolute element inside a flex-box. The flexbox layout spec seemed to have a back and forth on this issue. I can see how some browsers may implement things differently. 

I'll play around but I'm not sure if I can fix this. I'll make a PR if I manage to.

**Comment by KevinMulhern** [comment]
No problem @ayushkamadji, thanks for looking into this one 😄

**Comment by mindovermiles262** [comment]
https://github.com/TheOdinProject/theodinproject/pull/828
