### ISSUE TITLE
error 404 for links on Web Development 101 Project: HTML/CSS

### ISSUE THREAD

**Issue by DuncanSage** [TheOdinProject/theodinproject#792]
Links in this lesson that lead to other Odin project lessons take you instead to the 'are you lost page?'.
<a href="https://www.theodinproject.com/lessons/html-css">https://www.theodinproject.com/lessons/html-css</a>

**Comment by mindovermiles262** [comment]
Thanks for letting us know, @DuncanSage 👍

**Comment by JonathanYiv** [comment]
@mindovermiles262 just made a PR a second ago so you don't waste your time
