### ISSUE TITLE
Remove unique validation on Username field on User model

### ISSUE THREAD

**Issue by KevinMulhern** [TheOdinProject/theodinproject#796]
We are getting quite a few New Relic errors about this. We don't really need this to be unique though so removing this validation would be a good idea.

You will need to remove the unique validation for username on the user model and remove the unique constraint in the username index on the database as well.

---
### Working on this task

- [ ] If you want to work on this task, please claim it by commenting below   
- [ ] Branch off the redesign branch                                                                 
- [ ] Check out our [styleguide](https://staging-odin-project.herokuapp.com/styleguide)
- [ ] When you are submitting your pull request for this task please ensure the base branch you want to merge into is the redesign branch  

**Note**
* Please use the [contributing guide](https://github.com/TheOdinProject/theodinproject/wiki/Contributing-Guide) to get the app running on your local machine if you haven't already.

If you have any questions or need clarification about anything related to this task please contact the maintainers in our [contributing channel on Gitter](https://gitter.im/TheOdinProject/Contributing)

**Comment by JonathanYiv** [comment]
What are New Relic errors?

**Comment by KevinMulhern** [comment]
New relic is an application monitoring service. I can give you access if you like. Its a really good thing to know about.

**Comment by code-io** [comment]
Hi! I would like to solve this issue. Can I claim it?

**Comment by KevinMulhern** [comment]
Yeah its all yours @code-io, thank you
