### ISSUE TITLE
Clean up resume course logic

### ISSUE THREAD

**Issue by KevinMulhern** [TheOdinProject/theodinproject#798]

**Comment by KevinMulhern** [comment]
on it

**Comment by merlin2049er** [comment]
what does clean up mean?

**Comment by KevinMulhern** [comment]
Hey @merlin2049er, good question. I should have put more detail on this. 

We have a class for finding the next lesson on a course the user can complete https://github.com/TheOdinProject/theodinproject/blob/master/app/services/next_lesson.rb

It's a bit hard to understand and not all that efficient. I want to refactor it to a better design.

**Comment by zachmmeyer** [comment]
@KevinMulhern Does this issue need to stay open?
