### ISSUE TITLE
Code of Conduct

### ISSUE THREAD

**Issue by mindovermiles262** [TheOdinProject/theodinproject#803]
As TOP grows we should implement some code of conduct. Something that outlines our views for the project and what we will not tolerate.

**Comment by leosoaivan** [comment]
Agreed, had a similar thought yesterday after an interesting incident in the Gitter chat. I pulled the following from various sources:

> # The Odin Project Code of Conduct

> The Odin Project's Gitter chats are intended to be informative and relaxing spaces, where Odinites can find answers to their programming questions or simply hang out. Since we aim to be an inclusive and friendly community, we kindly request that all Odinites using our chatrooms follow the guidelines laid out on this Code of Conduct. Following these guidelines will ensure that all our Odinites have a positive learning and social experience:

> 1. Please be polite. Inappropriate conduct or harassment towards chat participants will not be tolerated and may result in a ban.
> 2. No racist remarks, sexually oriented remarks, or religious persecution will be tolerated; any such remarks may result in a ban.
> 3. Actions that seem specifically designed to test the limits of what is not offensive and to serve no other purpose (aka, trolling) will not be tolerated and such sessions will be immediately terminated.
> 4. Do not post someone's personal information, or post links to personal information.

Just something to kick this off.

**Comment by mindovermiles262** [comment]
> The Odin Project and it's core members reserve the right to ban or otherwise disable the account(s) of a user or users in defiance of this code of conduct or for any other reason they see fit.

🔨

**Comment by mindovermiles262** [comment]
I didn't even look before making this Issue :see_no_evil: 

There is already a code of conduct in both the main repo and the curriculum repo

**Comment by KevinMulhern** [comment]
I seen this as more chat oriented code of conduct, I think its something we should make a page for on the site like the terms of use. We could then direct users who violate it towards it as a warning.

**Comment by codyloyd** [comment]
we should also link it in the /help command on the bot

**Comment by mindovermiles262** [comment]
Is this worth adding to the footer of the main site? or just in the FAQ?

**Comment by KevinMulhern** [comment]
The Faq would be the easiest and quickest way of getting it on the site, it gets my vote 👍

**Comment by mindovermiles262** [comment]
I'll knock this out

**Comment by mindovermiles262** [comment]
#810
