### ISSUE TITLE
Make section title clickable

### ISSUE THREAD

**Issue by OmarMoataz** [TheOdinProject/theodinproject#806]
can you guys make Ruby Programming clickable like the old site

![image](https://user-images.githubusercontent.com/12211990/32249749-c70d55e6-be92-11e7-89d0-49083e738dcc.png)
I would like to be able to click on Ruby Programming to get to the entire lessons list

**Comment by KevinMulhern** [comment]
Thanks for raising this issue @OmarMoataz, agreed that this would be useful.
