### ISSUE TITLE
Fix broken Google analytics event trackers

### ISSUE THREAD

**Issue by KevinMulhern** [TheOdinProject/theodinproject#808]
With a lot of selectors changed in the redesign a lot of the google analytics event trackers are no longer working.

It would be good to get these functioning again so we can monitor things properly. 

The code for the event triggers is here https://github.com/TheOdinProject/theodinproject/blob/master/app/assets/javascripts/analytics.js.erb

The task here will be to cross reference the selectors used in each trigger with what selectors are actually being used and updating the event with the new selector if it has changed.

**Comment by 105ron** [comment]
@KevinMulhern can we close this now?

**Comment by KevinMulhern** [comment]
@105ron oops, yeah this can be closed.
