### ISSUE TITLE
Make check marks on course page clickable

### ISSUE THREAD

**Issue by Deetss** [TheOdinProject/theodinproject#811]
Just as a quality of life addition, i would personally like to be able to click on the check circle on the course page and change the state from incomplete to complete or vice versa.

**Comment by JonathanYiv** [comment]
I got this!

**Comment by JonathanYiv** [comment]
Thanks for pointing this out. Lemme know if there's more QoL changes you miss. One thing I personally miss is the little navigation bar at the top of each lesson that you can jump from lesson to lesson with

**Comment by KevinMulhern** [comment]
We had this in the old design, after tracking it with google analytics we discovered that it wasn't used that all often compared to the complete button on the lesson page. So we deemed it not worth the development time during the redesign with so much other things to do.

But it wouldn't hurt to include that feature again 😄 

@JonathanYiv we should talk about the breadcrumbs bar, a few people have asked about it. We will need to talk to @adachiu about the design first if we do include it again.

**Comment by JonathanYiv** [comment]
Sounds good!
I'm trying to familiarize myself with the code base anyway so things like this are helpful for me.

**Comment by Deetss** [comment]
I tried to do it myself last night but it it seems like it would take too much of my time

**Comment by JonathanYiv** [comment]
Is this more of a JS thing than Rails? If so, it might take me a little while to get to it while I learn JS

**Comment by KevinMulhern** [comment]
It can be done in rails with minimal js. It would be good to have a look at how we do it on individual lesson pages for an idea of how to do it.
