### ISSUE TITLE
Remove contact route

### ISSUE THREAD

**Issue by arun1595** [TheOdinProject/theodinproject#812]
Error report from New Relic:

**Action and Type:**

`ErrorsController#not_found AbstractController::ActionNotFound`

**Message:**

`AbstractController::ActionNotFound | The action 'contact' could not be found for StaticPagesController`

We've removed `contact` action and view in https://github.com/TheOdinProject/theodinproject/commit/59ed19957abc3751ee64274ee50da7f4a52927a2 but missed to remove the contact route from `routes.rb`

**Comment by KevinMulhern** [comment]
I remember removing all the unused routes in a pr recently 😖 I'm not sure what happened to them.
