### ISSUE TITLE
Fix undefined local variable or method `title' for nil:CourseDecorator

### ISSUE THREAD

**Issue by arun1595** [TheOdinProject/theodinproject#815]
**URL**

`/courses/introduction-to-web-development/lessons/web-development-jobs-and-careers`

**Comment by arun1595** [comment]
The issue is because we removed the **Introduction to Web Development** course. We'll have to update the course ids of the lessons which don't belong to a course currently. 

```ruby
lessons_without_courses = Lesson.all.select { |l| l.course == nil  }.pluck(:slug)
#=> ["getting-hired-as-a-web-developer", "the-best-web-developers", "web-development-jobs-and-careers", "tools-of-the-trade", "conclusion"]
```

**Comment by KevinMulhern** [comment]
This could also be happening due to outside referral links, I think the quickest and best solution to this would be creating a route that redirects users trying to access the Intro to Web Development course to Web Development 101.

**Comment by mftaff** [comment]
@KevinMulhern I am new-ish to open source contributing. May I have a go at this?

**Comment by KevinMulhern** [comment]
Hey @mftaff, yeah it looks like this one has been solved. It isn't showing up in newrelic anymore. Thank you for wanting to contribute to the project. I have a bunch of other issues that I'll be putting up soon.
