### ISSUE TITLE
When not logged in, logo link to "home" is broken.

### ISSUE THREAD

**Issue by ChadKreutzer** [TheOdinProject/theodinproject#821]
When you are not logged in, the Odin Project logo in the top left hand corner links to https://www.theodinproject.com/home which does not work (I've tried on all the main browsers) I'm looking at it to fix, but it has been a long time since I've played with Rails. :)
we either need to fix it to point to https://www.theodinproject.com or make https://www.theodinproject.com/home point to something.

**Comment by ChadKreutzer** [comment]
hmm. looks like it wants to be '/' or 'root'?

**Comment by leosoaivan** [comment]
Looking into it!

**Comment by KevinMulhern** [comment]
This might be due to the split test thats running. We will be turning it off this week.

**Comment by JonathanYiv** [comment]
Closed because test is complete!
