### ISSUE TITLE
Ruby Programming - A Deeper Look at Git

### ISSUE THREAD

**Issue by OmarMoataz** [TheOdinProject/theodinproject#824]
![image](https://user-images.githubusercontent.com/12211990/32793439-974f120e-c96e-11e7-88ca-48aeb7308974.png)

"this section" doesn't go anywhere, it takes me to the "You're lost odinite" page. I am not sure where it should or whether or not it should be a link in the first place.

Thanks in advance.

**Comment by JonathanYiv** [comment]
When we redesigned Odin, we also changed the way course and lesson paths are structured, so it broke a lot of links. This is one of those cases.
For reference, it was just linking to the next lesson: "Using Git in the Real World."

**Comment by OmarMoataz** [comment]
Yeah, I figured that had something to do with it. Thanks, Jonathan.

**Comment by JonathanYiv** [comment]
Thank you for pointing it out!

**Comment by KevinMulhern** [comment]
We should move this to the ruby course.

**Comment by KevinMulhern** [comment]
oops, it already has.
Thanks for fixing this @JonathanYiv
