### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by bishisht** [TheOdinProject/theodinproject#830]
In https://www.theodinproject.com/courses/ruby-programming/lessons/introduction-to-rspec page I am trying to follow link to Web Dev 101 rspec  intro ( which is in assignment section ) I clicked the link ( https://www.theodinproject.com/courses/ruby-programming/lessons/introduction-to-rspec ) and I got 404. Thanks. Please fix this asap.

**Comment by mindovermiles262** [comment]
Fixed https://github.com/TheOdinProject/ruby_course/commit/e33d62c3e515dc29ab66fa319880f3c83b5aef97

**Comment by mindovermiles262** [comment]
Thanks for bringing this up, @bishisht :+1:

**Comment by bishisht** [comment]
Thanks man :)
