### ISSUE TITLE
W3Schools course database might have changed

### ISSUE THREAD

**Issue by OmarMoataz** [TheOdinProject/theodinproject#844]
![image](https://user-images.githubusercontent.com/12211990/34467176-247f681a-eef2-11e7-933d-b5cc10d49688.png)

This is part of the [Databases and SQL](https://goo.gl/UNXcsW) course. 

![image](https://user-images.githubusercontent.com/12211990/34467183-9b94e650-eef2-11e7-9dec-f8261c3eca22.png)

This screenshot shows that there isn't a NumberOfOrders Column.

I might be doing something wrong. Feel free to correct me.

**Comment by KevinMulhern** [comment]
Hey @OmarMoataz, sorry it took so long to have a look at this. 

You are indeed correct. It looks like w3 have changed that example.

This will need fixed.

This repo is not the place for this issue though. It belongs in this repo https://github.com/TheOdinProject/mini_courses

I'll make an issue for it over there.

Thanks for reporting this
