### ISSUE TITLE
Community Hover Action

### ISSUE THREAD

**Issue by mindovermiles262** [TheOdinProject/theodinproject#856]
With the roll-out of the Forum, we should add a JS hover event for the "Community" button, similar to the Odin log when logged in

**Comment by chrislabarge** [comment]
https://drive.google.com/file/d/181zt5mJGFyD9NBd0ABc4t0FshjSx1l8L/view?usp=sharing duplicate the dropdown on hover?

**Comment by KevinMulhern** [comment]
Hey @chrislabarge, yeah duplicating the behaviour and style of the user dropdown on the community dropdown.

**Comment by chrislabarge** [comment]
@KevinMulhern ok awesome. I can work on this if no one else is.

**Comment by leosoaivan** [comment]
Closing. Resolved with #860
