### ISSUE TITLE
Potential Scam Email 

### ISSUE THREAD

**Issue by James-N-M** [TheOdinProject/theodinproject#857]
Hi I got an email from http://www.microverse.org/#faq you guys should look into this potential scam. to avoid potential students from falling into this and losing potentially thousands of dollars they could spend on school or anything..... seems like a scam maybe it isn't I dunno sorry In advance just looking out for the fellow students like me. http://www.microverse.org/#faq

**Comment by KevinMulhern** [comment]
Hi @James-N-M thanks for opening this issue. I don't quite understand though, how does this have anything to do with Odin?

**Comment by James-N-M** [comment]
I’ll close the issue and pr you the emails

**Comment by KevinMulhern** [comment]
No problem, thanks @James-N-M
