### ISSUE TITLE
Change "Learning Outcomes" to "Points to Ponder" in the Ruby Lessons

### ISSUE THREAD

**Issue by talihomz** [TheOdinProject/theodinproject#859]
In the "Test Yourself" section of [Ruby Building Blocks](https://www.theodinproject.com/courses/ruby-programming/lessons/ruby-building-blocks), there is an instruction to "look at all the questions from the “Points to Ponder” section" which doesn't seem to exist.

This is also happens at the [Advanced Ruby Building Blocks] lesson (https://www.theodinproject.com/courses/ruby-programming/lessons/advanced-ruby-building-blocks)

Was this intentional, or does it refer to the "Learning Outcomes" section?

**Comment by codyloyd** [comment]
this refers to "Learning Outcomes"  we have been changing the wording across the site from Points to Ponder to Learning Outcomes.... and must have missed this reference.

**Comment by talihomz** [comment]
Is this issue available for me to resolve? 
I'm learning about contributing to open source, and would like to use this to make my first PR if its agreeable.

**Comment by codyloyd** [comment]
@talihomz DO IT.

may the force be with you.

**Comment by talihomz** [comment]
Thanks @codyloy. I'm working on this.

**Comment by talihomz** [comment]
I've gone through the codebase and cant find "Learning Outcomes" in any markup file on the project. Is this being populated from a database?

**Comment by KevinMulhern** [comment]
Hey @talihomz, yeah the lesson content is pulled in from this repo https://github.com/TheOdinProject/curriculum

We've also been splitting out some of the courses to individual repos
Javascript - https://github.com/TheOdinProject/javascript_curriculum
Ruby - https://github.com/TheOdinProject/ruby_course
Rails - https://github.com/TheOdinProject/rails_course

**Comment by talihomz** [comment]
Ok @KevinMulhern. I'l will look for files where changes are needed in the ruby course repo.

**Comment by leosoaivan** [comment]
Closed. Resolved with TheOdinProject/ruby_course/pull/148
