### ISSUE TITLE
Wrong # in link  for RoR lesson: getting your feet wet

### ISSUE THREAD

**Issue by nidalaa** [TheOdinProject/theodinproject#865]
If you go to assigments of this lesson (https://www.theodinproject.com/courses/ruby-on-rails/lessons/getting-your-feet-wet#assignment) and click _Web Development Frameworks section._ link in point 3 you will be get to https://www.theodinproject.com/courses/web-development-101/#section-web-development-frameworks and element with `section-web-development-frameworks` does not exist on the page.

**Comment by talihomz** [comment]
Hmmm, I tried it out @nidalaa, and saw the issue.

The link targets `section-web-development-frameworks` but should target `web-development-frameworks`.  If no one is working on this already, I can go ahead and submit a PR with the fix.

**Comment by mindovermiles262** [comment]
All yours, @talihomz

**Comment by talihomz** [comment]
Thanks @mindovermiles262 😉.

I've made a [PR for this](https://github.com/TheOdinProject/rails_course/pull/68) that fixes the issue.
