### ISSUE TITLE
Linux Installation Guide - change order of instructions

### ISSUE THREAD

**Issue by PolarisTLX** [TheOdinProject/theodinproject#868]
On this link:
https://github.com/TheOdinProject/theodinproject/wiki/Linux-Installation-Guide

This instruction:

"If you encounter an error, could not connect to server or PG::ConnectionBad, you will need to start the PG server:
`sudo service postgresql start`"

Should go above:

"Next we need to create our role. Run the following:
`$ sudo -u postgres createuser yourusername -s
$ sudo -i -u postgres psql`"

There is also probably no need to mention an error if the instruction to start the server first. Could just re-write it as: 
"Next we need to start the postgreSQL server by typing the following command:
`sudo service postgresql start`

<br/>

![odin project instructions order switch](https://user-images.githubusercontent.com/26701119/37116744-24a7bc6c-221d-11e8-9959-0f7ada90e6fc.jpg)

Paul ( @PolarisTLX) and Kyle  (@jklemon17)

**Comment by KevinMulhern** [comment]
Nice spot @PolarisTLX, thanks for your detailed issue report. This would be a good issue for a first timer.

**Comment by PolarisTLX** [comment]
Is it just a matter of editing that text file right in its Github page?  If so then I went ahead and did so. If there is anything else required I'm happy to give that a shot as well.

**Comment by KevinMulhern** [comment]
Brilliant, thanks a lot for contributing @PolarisTLX 😄
