### ISSUE TITLE
Convert Create Project Controller Action to an API Endpoint

### ISSUE THREAD

**Issue by KevinMulhern** [TheOdinProject/theodinproject#878]
Currently the create project controller action and create.js are heavily coupled this makes both more complicated. 

Converting the create action into a simple API endpoint and moving the frontend logic for the create project feature to ajax functions in the assets folder will make the code leaner and much simpler.

**Comment by KevinMulhern** [comment]
@arun1595 I don't suppose you want this one?

**Comment by arun1595** [comment]
@KevinMulhern I'll work on it :)
