### ISSUE TITLE
Stories page shows Sign-Up button even when user is signed in.

### ISSUE THREAD

**Issue by GauravDhanuka** [TheOdinProject/theodinproject#879]

**Comment by goliveira-dev** [comment]
Newbie here!
The file is https://github.com/TheOdinProject/theodinproject/blob/master/app/views/static_pages/success_stories.html.erb

Needs to make an IF Check about user session.

**Comment by KevinMulhern** [comment]
Thanks for reporting this @GauravDhanuka and thank you for linking to the file @goliveira-dev.

The sign_up_button helper call just needs to be replaced with a call to [this helper](https://github.com/TheOdinProject/theodinproject/blob/master/app/helpers/application_helper.rb#L185) to fix this issue 😄
