### ISSUE TITLE
Javascript not Loading on Lesson Pages

### ISSUE THREAD

**Issue by KevinMulhern** [TheOdinProject/theodinproject#880]
There is a bug on lesson pages where the Javascript isn't working.

### To Recreate

1 Refresh a lesson page
2. Access a lesson page through an external link such as this one: https://www.theodinproject.com/courses/ruby-programming/lessons/advanced-ruby-building-blocks

### Notes
There doesn't seem to be any Javascript errors in the dev tools console, I suspect this is a issue with turbo links.

**Comment by Deetss** [comment]
I want to take care of this instead lol

**Comment by KevinMulhern** [comment]
aha no worries @Deetss

**Comment by Deetss** [comment]
@KevinMulhern I'm having a hard time recreating the bug here, the only thing i'm noticing is that the lesson is'nt centered after the refresh

**Comment by Deetss** [comment]
Addressed in #884

**Comment by KevinMulhern** [comment]
Hey @Deetss it still seems to be there unfortunately 😞 If you go to a lesson page and refresh the navigation on the left side disappears.

**Comment by tomdracz** [comment]
@Deetss @KevinMulhern Seen something similar recently, could be related to this https://github.com/turbolinks/turbolinks/issues/28

**Comment by KevinMulhern** [comment]
Thanks @tomdracz, that looks like our problem. I put an `async: true` option in the `javascript_include_tag` around the time this all started happening 🙈

**Comment by tomdracz** [comment]
@KevinMulhern Possibly also fixed in https://github.com/turbolinks/turbolinks/pull/274 which is in Turbolinks 5.1 but your mileage may vary. Still running bundle on the repo to try it myself!

**Comment by KevinMulhern** [comment]
Interesting, I didn't know this was an issue 😄 

I don't think we got that much of performance gain from deferring the scripts being loaded anyway. If the easiest fix is to get rid of the `async` I won't raise any objections.

**Comment by Deetss** [comment]
@KevinMulhern Oh wow, thats interesting.
