### ISSUE TITLE
White characters on white background in Active Record Queries lesson

### ISSUE THREAD

**Issue by OmarMoataz** [TheOdinProject/theodinproject#883]
Hey, the characters here are very hard to read.

<img width="868" alt="image" src="https://user-images.githubusercontent.com/12211990/37587246-7624ea44-2b67-11e8-8e46-804e85f4f4e5.png">

Link: https://www.theodinproject.com/courses/ruby-on-rails/lessons/active-record-queries

This might be browser specific. if so, I'm using Firefox.

**Comment by KevinMulhern** [comment]
Hey @OmarMoataz, thanks for the report. I think this is might be due to the async attribute on the javascript include tag here: https://github.com/TheOdinProject/theodinproject/blob/master/app/views/shared/_head.html.erb#L35

Removing that to see if it fixes the problem would be worth a shot.

**Comment by mindovermiles262** [comment]
Have we figured out how to reproduce this issue?

**Comment by OmarMoataz** [comment]
I tried it on chrome, the problem is that it doesn't render the black background on Firefox. I suspect you guys have already figured that out but I thought I should point it out anyway.

**Comment by OmarMoataz** [comment]
I'm gonna close this for now because it seems to be working correctly on Firefox (without changing anything on my side). I can not reproduce the issue. Thanks!
