### ISSUE TITLE
Facebook URL preview

### ISSUE THREAD

**Issue by Demo318** [TheOdinProject/theodinproject#886]
<img width="475" alt="screen shot 2018-04-07 at 10 33 53 pm" src="https://user-images.githubusercontent.com/18633311/38462925-f1aa81dc-3ab3-11e8-8f21-865631c6c82c.png">
Here's how Facebook previews the website's homepage every time I post the URL.

Is there anything that can be done to put the epic TOP logo there instead?

**Comment by KevinMulhern** [comment]
I've noticed this too, I'm not sure how @RobPando feels about being the face of TOP 😂 

It looks like we just need to add a meta tag in the head of the site https://www.adhesion.co.nz/blog/how-to-change-website-thumbnail-in-facebook-post/

**Comment by tomdracz** [comment]
Had a go at this one but Facebook preview does not accept .svg files. If there's a jpg/png logo that can be linked, this can be sorted quickly

**Comment by KevinMulhern** [comment]
We've got some png's in the public folder that might be suitable.

**Comment by mindovermiles262** [comment]
https://github.com/TheOdinProject/theodinproject/blob/master/public/apple-touch-icon-152x152.png

This is the largest icon in the `public` directory

**Comment by KevinMulhern** [comment]
I _think_, that should be big enough. I might be able to get a bigger one from @adachiu if she's available.

**Comment by loudmouse** [comment]
Hey all. Will either of these work?
![the_odin_project_1200x630_v2](https://user-images.githubusercontent.com/16002468/39258544-d93e0852-4879-11e8-95a0-478eb37670a3.png)
![the_odin_project_1200x630](https://user-images.githubusercontent.com/16002468/39258545-d9526aa4-4879-11e8-8a2b-9089bdde5c6d.png)

**Comment by tomdracz** [comment]
@loudmouse Yup, the top one should do it, probably better if you hit some centre cropping. Will push a PR later and we'll see how it goes

**Comment by loudmouse** [comment]
@tomdracz no problem. Here's one with a 1:1 aspect ratio.

![the_odin_project_850x850](https://user-images.githubusercontent.com/16002468/39259639-8e00f180-487c-11e8-90db-ef2b8bb4d9b8.png)
