### ISSUE TITLE
Dead Link: Web Development 101 PROJECT: PRACTICING GIT BASICS

### ISSUE THREAD

**Issue by Anthonyntilelli** [TheOdinProject/theodinproject#901]
There is a link on the web page that leads to a 404 in the Odin lesson.

Web Page: https://www.theodinproject.com/courses/web-development-101/lessons/practicing-git-basics
Dead Link: https://www.theodinproject.com/web-development-101/installations

The line on the web page is: "Create your repository on Github
You should have created a GitHub account in the `installations` project. If you haven’t done that yet you can sign up here."  and the link is the "installations" word

**Comment by KevinMulhern** [comment]
Thanks for reporting this @Anthonyntilelli 

Dead link needs to be changed to: https://www.theodinproject.com/courses/web-development-101/lessons/installations

**Comment by Anthonyntilelli** [comment]
I have created a merge request for it: https://github.com/TheOdinProject/curriculum/pull/7949

**Comment by KevinMulhern** [comment]
Thanks so much for fixing that @Anthonyntilelli 🙂
