### ISSUE TITLE
DEAD LINK: Web Development 101: HTML AND CSS BASICS

### ISSUE THREAD

**Issue by Anthonyntilelli** [TheOdinProject/theodinproject#902]
There is a link on the web page that leads to a 404 in the Odin lesson.
PAGE: https://www.theodinproject.com/courses/web-development-101/lessons/html-and-css-basics
DEAD LINK: https://skillcrush.com/2012/06/24/html-2/

Line: ( At top of page):

As you’ve hopefully `learned before,` HTML is the markup that contains all the actual stuff that a web page has. All the text on this page you’re reading right now lives inside HTML tags that tell your browser how to order the content on the page. Go on, right click any element on the page and choose “Inspect Element” to open up your browser’s Developer Tools and it will show you the structure of the page.

Please let me know the intended replacement link and I will make the correction.

**Comment by Anthonyntilelli** [comment]
Correction made, I have made the merge request at:
https://github.com/TheOdinProject/curriculum/pull/7958

**Comment by KevinMulhern** [comment]
Thanks again for fixing that @Anthonyntilelli
