### ISSUE TITLE
Bug: Section side bar highlighting not working as intended

### ISSUE THREAD

**Issue by OkuboTV** [TheOdinProject/theodinproject#903]
**The side bar for each section has a section which fails to embolden.**

**The section in particular is the Intermediate Array Magic Section**

 

![selection_014](https://user-images.githubusercontent.com/27530602/40561167-383662ec-602a-11e8-947a-d3a6c6dc18a6.png)

**The section also, when clicked, stays bold even when in other sections.**

![selection_015](https://user-images.githubusercontent.com/27530602/40561172-3d030b5e-602a-11e8-9b41-af7ccba81730.png)

**Comment by cheukyin699** [comment]
This looks like an issue with parsing headers in Markdown vs parsing them in Javascript - in particular, the function `kebabCase` in `lesson.js`.

I can help with this.
