### ISSUE TITLE
Design: Dark theme

### ISSUE THREAD

**Issue by adachiu** [TheOdinProject/theodinproject#908]
I've created the dark theme for the lesson page. Since most of the reading is on the lesson pages, I think we can have the dark theme implemented on lesson pages first. The component underneath consisting of "view course" and "next lesson" may or may not need a dark theme. Let's have a discussion around this.

*Edit*
Will have a mock for another lesson page with more page variety. Ie. code blocks, Assignment block, etc.

![dark-lesson-detail-1](https://user-images.githubusercontent.com/13413986/41238182-e6b0981a-6dc7-11e8-94d8-140781c114d4.jpg)

**Comment by Deetss** [comment]
:+1:

**Comment by CouchofTomato** [comment]
@adachiu It looks amazing and will definitely be a nice choice to give users. Thanks for putting this together.

**Comment by mindovermiles262** [comment]
Hey @adachiu this looks really good. Thanks for putting it together :smiley: 

A few suggestions from the peanut gallery over here:

- The top SVG round icon for "ruby on rails" looks very out of place. I don't know much about SVG graphics but if it's simple to replace the colors it may be worth looking into - something closer to the dark gray of the background so it's not so flashy.

- The very light gray background in the student solutions area is a little bright for a dark theme.  Maybe we can darken it a bit to match the dark theme above.

**Comment by adachiu** [comment]
Thanks for the input @mindovermiles262 !

- There are pros and cons for the badge (top SVG icon) to have a different color. The con would be that the dark theme badge may be confusing from the original set of badges. The pro would be the whole page aligning more to the dark theme if the badge was darker. Or we can try to keep the original badge and adjust the top to allow a smooth transition into the dark theme.

- The bottom solutions part has a dark theme in this newest upload 😄 

![dark-lesson-detail-1 2](https://user-images.githubusercontent.com/13413986/41295892-353af50e-6e8e-11e8-9766-aaf968f705e6.jpg)

**Comment by CouchofTomato** [comment]
I think that looks awesome @adachiu 

Thanks for putting this together.

**Comment by KevinMulhern** [comment]
This looks fantastic @adachiu, great work 🎉

**Comment by kashura** [comment]
Wow this would be awesome!

**Comment by LE-HU** [comment]
Guys just to let you know what i've been using so far when coding @ night. These examples might provide you with some example and ideas in further development of in-app dark mode. Both are mozilla add-ons.
1. Custom TOP dark theme created solely for this website, unfortunatelly I dont know who's the creator. This add-on worked quite well but I've spot some issues like not seeing comments properly or code highlighting, so I've switched to 2.
https://addons.mozilla.org/en-US/firefox/addon/the-odin-project-dark-theme/
2. All purpose Dark-Reader for firefox, works very well, and i use it every time i code during nighttime - worth giving a shot to see how it looks.
https://addons.mozilla.org/en-US/firefox/addon/darkreader/

Thanks!

**Comment by mindovermiles262** [comment]
Hey thanks @LE-HU ! I'm the creator of the dark mode plugins for firefox.

There is also one available for chrome: https://chrome.google.com/webstore/detail/the-odin-project-dark-the/omiecnmmajomefpodcdjkebeonieonef

**Comment by thebluedev** [comment]
@LE-HU  The dark reader extension is Extremely good! I have been using it for quite a few years now , it makes any site go into dark mode seamlessly!

also would like to point out that Dark reader is available on all browsers and not only mozilla Firefox

**Comment by I3uckwheat** [comment]
Hey guys, this is for adding an actual dark mode to the Odin site itself, not to discuss dark reader.

**Comment by brooksquil** [comment]
I would love to take a whack at this!

**Comment by KevinMulhern** [comment]
Hey @brooksquil, this could potentially be a big piece of work. Are you in our discord? it would be worth having a chat about the approach.

**Comment by brooksquil** [comment]
I just got on discord. I know it's a big chunk of work but I have done a
lot of react component styling on a project at my first consulting firm and
on contract with the same client after I went to work on a Ruby app. I have
also done research on how to go about this and while it looks challenging,
it also looks like this ticket has been sitting around for a while so I
have no need to rush through it. Are there Sketch files to get the styes
and everything from?

**Comment by KevinMulhern** [comment]
Hey @brooksquil, hopefully you haven't done too much with this. We recently decided to convert the site to use Tailwind. We're starting to look at converting everything over. We're putting this story on hold until thats done.

**Comment by brooksquil** [comment]
Thanks for letting me know

**Comment by twalton83** [comment]
A beta was released that differs from the final designs seen above in #2202.

**Comment by qazip** [comment]
The dark mode implemented in the TOP site is not really eye-friendly, in my opinion. The contrast is too big. The white too white, the dark too dark. I have sensitive eyes, and it gets tiring very fast. I would suggest changing the white to some off-white color.

**Comment by ChargrilledChook** [comment]
Closing as will be resolved soon by #3385 :tada:
