### ISSUE TITLE
Page Consistency

### ISSUE THREAD

**Issue by adachiu** [TheOdinProject/theodinproject#909]
1. This page is not following the current Odin UI for the "Assignment" section
https://www.theodinproject.com/courses/web-development-101/lessons/clean-code
It should look like this page
https://www.theodinproject.com/courses/web-development-101/lessons/html-and-css-basics

2. Side navigation for "Assignment" also needs to be consistent throughout all the pages. Let's just keep "Assignment" instead of "Your Assignment"

Note: There may be more pages with inconsistencies. I haven't looked at every page yet.

**Comment by lujanfernaud** [comment]
I can work on this.

**Comment by AREEBAISHTIAQ** [comment]
Can I help you ? @adachiu
