### ISSUE TITLE
Drop-downs on installations should have a more heading type style

### ISSUE THREAD

**Issue by I3uckwheat** [TheOdinProject/theodinproject#920]
Currently the drop-downs on [this](https://www.theodinproject.com/courses/web-development-101/lessons/prerequisites) page are styled like they are part of normal text. They should stand out a bit more like a heading.

Attached is an image of the problem areas. A possible solution would be to add a class to the `<summary>` html tag and edit the CSS to make them more heading-like. Below are the sections that would need to be edited.

[Prerequisites](https://github.com/TheOdinProject/curriculum/blob/master/web_development_101/installfest_prerequisites.md)

[First Rails App](https://github.com/TheOdinProject/curriculum/blob/master/web_development_101/installfest_first_rails_app.md)

![image](https://user-images.githubusercontent.com/4411701/42606742-d6343002-8544-11e8-9276-9317608ace83.png)

Comment here if you'd like to take this task on!

**Comment by IrritatedEllipses** [comment]
I'd be more than happy to take a crack at this.

**Comment by I3uckwheat** [comment]
@IrritatedEllipses Great! I'll self assign this so nobody else takes it!

**Comment by I3uckwheat** [comment]
@adachiu Might have some valuable input here as well.
