### ISSUE TITLE
Redirection issues: Bug

### ISSUE THREAD

**Issue by BonfaceKilz** [TheOdinProject/theodinproject#930]
Someone should redirect https://theodinproject.com/ to point to https://www.theodinproject.com/

https://theodinproject.com/ currently points nowhere.

**Comment by mindovermiles262** [comment]
@KevinMulhern do you know who manages the DNS for the site? The fix would just be a new DNS A record.

**Comment by KevinMulhern** [comment]
@mindovermiles262 yeah Thinkful handles the DNS stuff. 

@adamelevenson would it be possible for you guys to do as @mindovermiles262 suggested to fix this issue please?

**Comment by mindovermiles262** [comment]
Pinging @adamelevenson 

Is it possible for one of TOP maintainers to manage theodinproject domain?

**Comment by nearmint** [comment]
Sad that the Thinkful guys don't react. @adamelevenson doesn't seem to be very active on Github. Maybe send them an email?

**Comment by KevinMulhern** [comment]
This has been resolved 🎉
