### ISSUE TITLE
odin page display issues

### ISSUE THREAD

**Issue by chgedlxk** [TheOdinProject/theodinproject#939]
I am currently using I3wm when the screen is splitted 50|50, the odin page look like this.
![selection_001](https://user-images.githubusercontent.com/42925146/46359786-f6263480-c637-11e8-8015-d9bea67bc9f1.png)

when the screen is splitted 50%+2px|50%-2px, The odin page looks fine.
![selection_002](https://user-images.githubusercontent.com/42925146/46359305-f70a9680-c636-11e8-8861-7a6e8c31a739.png).

Also when the screen is splitted 50%-10px|50%+10px, the page is fine too. 
![selection_003](https://user-images.githubusercontent.com/42925146/46359612-9596f780-c637-11e8-9748-bdef905ddf00.png)

It happens both in chromium and firefox. Don't know about the browsers.

**Comment by codyloyd** [comment]
pretty sure I know what's going on here... testing a fix right now
