### ISSUE TITLE
email confirmation link 404

### ISSUE THREAD

**Issue by eriktrautman** [TheOdinProject/theodinproject#95]
Looks like if you're on a specific lesson page and click the "resend confirmation email" link (or whatever it's called) it 404's because it tries to generate the /confirm_email link gets appended to the course name, e.g. `http://theodinproject.com/ruby-on-rails/confirm_email` and there's a routing error.

**Comment by KevinMulhern** [comment]
@eriktrautman has this been fixed or is it still an issue?

**Comment by AbbyJonesDev** [comment]
It is fixed!

**Comment by KevinMulhern** [comment]
Hi @AbbyJonesDev, thanks you :)
