### ISSUE TITLE
Allow users to see start date and end date for sections (ex. Web Development 101) or individual lessons

### ISSUE THREAD

**Issue by CrispyCB** [TheOdinProject/theodinproject#958]
Motivation: I'd like to be able to see when I started and when I finished sections or lessons in order to chart personal learning goals (ex. it took me 6 months to do Web Development 101, but only 3 months to JavaScript, etc) but it would also be good to use in place of certificates or similar for those that need to put _something_ on a resume.

Definition of done: I can either go into a user view and see the course listings and when I started/completed them, or see them from the curriculum screen when I log in.

**Comment by I3uckwheat** [comment]
Thanks for the suggestion, this could be part of this feature. 

https://github.com/TheOdinProject/theodinproject/issues/1116
