### ISSUE TITLE
Navbar out of alignment

### ISSUE THREAD

**Issue by mindovermiles262** [TheOdinProject/theodinproject#960]
While browsing the site with my screen split, the navbar is out of alignment:

![screenshot_2019-01-07 dashboard the odin project](https://user-images.githubusercontent.com/14863257/50800411-f10afe00-1294-11e9-839b-b3b39d94e4ee.png)

Also effects users that are not logged in.

Browser Resolution: 952x932
Effects: Chrome, FireFox (Not tested on others)
OS: Linux

**Comment by dos077** [comment]
I found the issue in css. The ::after element in .dropdown-toggle class uses vertical-align: 0.255em to align itself. That throws off the padding calculation of <a.nav-link> in tablet mode. Testing in chrome using position:relative and top: -0.255em seems to fix the issue by isolation the vertical offset to only the ::after element. I cannot find the css file in the odinproject repo though.

**Comment by dos077** [comment]
Pull request sent. I am in the middle of the "Using Git in the Real World" section. I tried to follow all the steps, hopefully there's no screw up.
