### ISSUE TITLE
Sign up bug

### ISSUE THREAD

**Issue by jcwimer** [TheOdinProject/theodinproject#963]
When signing up, I was redirected to an error page. I received an email and was able to sign in successfully. Seems to be an issue with the sign up redirection.

I signed up with email and password.

**Comment by JMikeW** [comment]
I tried by signing up through github - same results.

**Comment by KevinMulhern** [comment]
Thanks for reporting @jcwimer, we'll get this fixed asap.

@JMikeW your's is a different problem, your github name "JM" is failing our validations, we have a minimum of 4 characters for the name field in our system.

**Comment by KevinMulhern** [comment]
@jcwimer that should be fixed now.
