### ISSUE TITLE
Project: Restaurant - add info about debugging with webpack

### ISSUE THREAD

**Issue by morrowdavidson** [TheOdinProject/theodinproject#973]
concerning: [https://www.theodinproject.com/courses/javascript/lessons/restaurant-page](https://www.theodinproject.com/courses/javascript/lessons/restaurant-page)

I struggled using webpack at first because I couldn't debug my javascript with Firefox Developer Tools. 

Adding: **mode: 'development'** and **devtool: 'eval-source-map'** to my webpack.config.js helped me get through my project. Maybe instructions about adding these lines to your webpack.config.js could be included in the [Project: Restaurant Assignment](https://www.theodinproject.com/courses/javascript/lessons/restaurant-page)?

My webpack.config.js : 

```javascript
const path = require('path');

module.exports = {
  watch: true,
  mode: 'development',
  devtool: 'eval-source-map',
  entry: './src/index.js',
  output: {
    filename: 'main.js',
    path: path.resolve(__dirname, 'dist')
  }
};
```

**Comment by codyloyd** [comment]
why is this an issue instead of a pull request? 😝 

this is indeed very helpful.. add it to the lesson!

**Comment by morrowdavidson** [comment]
thanks @codyloyd for the response. I definitely put this in the wrong area. Still trying to figure out GitHub :)
