### ISSUE TITLE
Feature request: lesson completion tracker

### ISSUE THREAD

**Issue by morrowdavidson** [TheOdinProject/theodinproject#981]
![git_hub_contributions](https://user-images.githubusercontent.com/44884803/52911440-9d5adf80-3258-11e9-9d79-34a8c050996a.png)

I set a goal to try and commit something every day to github, I only do this because of the contribution tracker. I think a similar feature for lesson completion for TOP would be a neat gamifying feature.

**Comment by KevinMulhern** [comment]
I think something like this would be useful too, I don't know if lesson completions is the best metric for it though as some lessons can take more than one day to complete, especially projects. Maybe we could integrate this with the proposed points system we want to include on the site in the future.

Helping on chat will be one of the ways a user will be able to get a point so that could be a way to keep a streak going whilst they are working through a long lesson/project.

**Comment by morrowdavidson** [comment]
Cool. Yeah, I think lessons would be the wrong thing to track too. I wonder if an honor system would work, maybe you could just check-in if you haven't completed a lesson that day. 

I'm going to mock something up for fun.

**Comment by morrowdavidson** [comment]
@KevinMulhern Do you know what the average time someone spends on odin, in months? When working on the mock-up I felt a year might be too long to show in a tracker.

**Comment by KevinMulhern** [comment]
@morrowdavidson we used to have a quip on the faq that it would take 6 months full time study or a year or over of part time study. 

It varies widely though.

**Comment by tfantina** [comment]
Anyone working on this? I  could take a stab at it.

**Comment by tfantina** [comment]
I'm going to open a PR for this in a few days if I can learn enough SVG to effectively copy what GitHub does.

**Comment by tfantina** [comment]
@KevinMulhern && @morrowdavidson I've mocked up a version of this: [fork'd here](https://github.com/tfantina/theodinproject-1/tree/feature/daily-calendar
).  It has some issues (see the commit message) which I am aware of but I'm wondering what your thoughts are on this.  I created the heatmap with vanilla JS but I've seen some interesting libraries out there, would you be opposed to using one of them?

**Comment by I3uckwheat** [comment]
@tfantina Thank you for taking a look at this, but I think we're going to go a different direction where we re-design the dashboard entirely. Please see the issue below.

https://github.com/TheOdinProject/theodinproject/issues/1116
