### ISSUE TITLE
Upgrade to FontAwesome 5

### ISSUE THREAD

**Issue by morrowdavidson** [TheOdinProject/theodinproject#986]
Font Awesome 5 has some neat new features but upgrading seems like [a bit of work](https://fontawesome.com/how-to-use/on-the-web/setup/upgrading-from-version-4). If there is interest I could try to work on it.

**Comment by KevinMulhern** [comment]
I'm not opposed to upgrading, looks like there isn't a gem so that would be one less gem to bundle.

**Comment by morrowdavidson** [comment]
@KevinMulhern So would putting the Font Awesome's CDN in `_head.html.erb` work?
```html
 <%= stylesheet_link_tag 'application', media: 'all'%>
  <link href='https://fonts.googleapis.com/css?family=Open+Sans+Condensed:300,700,300italic|Open+Sans:300,300italic,400,700' rel='stylesheet' type='text/css'>
  **<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">**
```

**Comment by KevinMulhern** [comment]
It should do, it will need to come before the application stylesheet though. Just so we can use fontawesome within our css.
