### ISSUE TITLE
Broken link to codeacademy Ruby courses in the Ruby Programming How this Course Will Work section 

### ISSUE THREAD

**Issue by TheBrianGuy** [TheOdinProject/theodinproject#991]
In the Ruby Programming [How this Course Will Work section](https://www.theodinproject.com/courses/ruby-programming/lessons/how-this-course-will-work-ruby-programming) there is a header for "**Our Primary Textbooks**". The first list item has a broken codeacademy link to http://www.codecademy.com/tracks/ruby.

The new link should be to https://www.codecademy.com/catalog/language/ruby.

**Comment by KevinMulhern** [comment]
Thanks for reporting this @TheBrianGuy, @jamhog has fixes this:
https://github.com/TheOdinProject/curriculum/pull/9767
